"""Comprehensive Qt unit tests for ChatInputWidget.

Tests cover:
  - Widget construction and initialization
  - Text input field exists and accepts text
  - Enter key triggers send signal
  - Send button click triggers send signal
  - Mic button exists and toggles recording state
  - Empty text does not send (validation)
  - Very long text handling
  - Special characters in input
  - Disabled/processing state
  - Clear input after send
  - Signal emissions (send_clicked, mic_pressed, mic_released)
  - Mic visibility and enabled toggles
  - set_text() pre-fill
"""

from __future__ import annotations

from unittest.mock import patch

import pytest
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication, QPushButton, QWidget

# =============================================================================
# Helpers
# =============================================================================

# The placeholder is generated by t("copilot.input.placeholder", …)
# which falls back to the default English string when no translation is loaded.
EXPECTED_PLACEHOLDER = "Ask me anything about your fleet..."


def _find_child(widget: QWidget, klass: type, object_name: str | None = None) -> QWidget:
    """Find a single child widget of a given class, optionally matching objectName."""
    children = widget.findChildren(klass)
    if object_name:
        candidates = [c for c in children if c.objectName() == object_name]
        if candidates:
            return candidates[0]
    return children[0] if children else None


# =============================================================================
# Construction & Initialization
# =============================================================================


class TestConstruction:
    """Verify the widget is built correctly with expected defaults."""

    def test_construction_defaults(self, qt_widget):
        """Widget is a QFrame with transparent background and expanding policy."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w is not None
        # Size policy
        policy = w.sizePolicy()
        assert policy.horizontalPolicy().name == "Expanding"
        assert policy.verticalPolicy().name == "Fixed"
        # Stylesheet is transparent
        assert "transparent" in w.styleSheet()

    def test_construction_no_parent(self, qt_widget):
        """Can construct with no parent."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(parent=None)
        assert w is not None

    def test_input_widget_exists(self, qt_widget):
        """Text input QLineEdit exists with correct placeholder."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._input is not None
        assert EXPECTED_PLACEHOLDER in w._input.placeholderText()

    def test_send_button_exists(self, qt_widget):
        """Send button exists and has correct text."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._send_btn is not None
        assert w._send_btn.text() == "Send"

    def test_mic_button_exists(self, qt_widget):
        """Microphone button exists and shows mic emoji."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._mic_btn is not None
        assert "🎤" in w._mic_btn.text()

    def test_mic_button_idle_by_default(self, qt_widget):
        """Mic button starts in idle state."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert "transparent" in w._mic_btn.styleSheet() or "COLOR_BORDER_SUBTLE" or "1px solid" in w._mic_btn.styleSheet()


# =============================================================================
# Text Input
# =============================================================================


class TestTextInput:
    """Text input field behavior."""

    def test_input_accepts_text(self, qt_widget):
        """Line edit accepts and returns text."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w._input.setText("Hello world")
        assert w._input.text() == "Hello world"

    def test_set_text_prefills(self, qt_widget):
        """set_text() pre-fills the input without sending."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_text("Prefilled text")
        assert w._input.text() == "Prefilled text"

    def test_input_clear(self, qt_widget):
        """Input can be cleared programmatically."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w._input.setText("Some text")
        w._input.clear()
        assert w._input.text() == ""


# =============================================================================
# Send Signal — Enter Key & Button Click
# =============================================================================


class TestSendSignal:
    """Verify send signals are emitted at the right times."""

    def test_enter_key_triggers_send(self, qt_widget, qtbot):
        """Pressing Enter on the input emits send_clicked with the text."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)
        w._input.setText("test message")
        w._input.returnPressed.emit()
        assert received == ["test message"]

    def test_send_button_click_triggers_send(self, qt_widget, qtbot):
        """Clicking the Send button emits send_clicked with the text."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)
        w._input.setText("click to send")
        w._send_btn.click()
        assert received == ["click to send"]

    def test_empty_text_does_not_send(self, qt_widget, qtbot):
        """Empty or whitespace-only text does NOT emit send_clicked."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)

        # Empty string
        w._input.setText("")
        w._send_btn.click()
        assert received == []

        # Whitespace only
        w._input.setText("   \t  \n  ")
        w._send_btn.click()
        assert received == []

    def test_input_cleared_after_send(self, qt_widget, qtbot):
        """Input text is cleared after a successful send."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        w._input.setText("will be cleared")
        w._send_btn.click()
        assert w._input.text() == ""

    def test_multiple_sends_work(self, qt_widget, qtbot):
        """Multiple sends in sequence work correctly."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)

        w._input.setText("first")
        w._send_btn.click()
        w._input.setText("second")
        w._send_btn.click()
        w._input.setText("third")
        w._send_btn.click()

        assert received == ["first", "second", "third"]

    def test_whitespace_stripped_before_send(self, qt_widget, qtbot):
        """Leading/trailing whitespace is stripped before sending."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)
        w._input.setText("  spaced out  ")
        w._send_btn.click()
        assert received == ["spaced out"]


# =============================================================================
# Long Text & Special Characters
# =============================================================================


class TestEdgeCaseInputs:
    """Edge cases: long text, special characters, unicode."""

    def test_very_long_text_sends(self, qt_widget, qtbot):
        """A very long message (10K chars) is sent correctly."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        long_text = "A" * 10_000
        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)
        w._input.setText(long_text)
        w._send_btn.click()
        assert received == [long_text]
        assert len(received[0]) == 10_000

    def test_extremely_long_text_does_not_crash(self, qt_widget, qtbot):
        """Near-limit text (30K characters) does not crash.
        QLineEdit has a platform-dependent max length (default ~32767);
        we test with a large but safe value."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        huge_text = "X" * 30_000
        w._input.setText(huge_text)
        # Should not crash
        assert len(w._input.text()) == 30_000

    def test_unicode_and_special_characters(self, qt_widget, qtbot):
        """Unicode, emoji, and special characters are sent correctly."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        special = "Hello café 日本 你好 🚚 $100 <test> & \"quote\" 'single'"
        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)
        w._input.setText(special)
        w._send_btn.click()
        assert received == [special]

    def test_html_tags_preserved(self, qt_widget, qtbot):
        """HTML-like content is sent as literal text (no rendering)."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        html_text = "<script>alert('xss')</script>"
        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)
        w._input.setText(html_text)
        w._send_btn.click()
        assert received == [html_text]

    def test_newlines_in_text(self, qt_widget, qtbot):
        """Newlines in the input are preserved."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        multiline = "line one\nline two\nline three"
        received = []

        def on_send(text: str):
            received.append(text)

        w.send_clicked.connect(on_send)
        w._input.setText(multiline)
        w._send_btn.click()
        assert received == [multiline]


# =============================================================================
# Disabled / Processing State
# =============================================================================


class TestProcessingState:
    """Input disabled while processing."""

    def test_set_processing_disables_input(self, qt_widget):
        """set_processing(True) disables input and send button."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_processing(True)
        assert w._input.isEnabled() is False
        assert w._send_btn.isEnabled() is False

    def test_set_processing_reenables_input(self, qt_widget):
        """set_processing(False) re-enables input and send button."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_processing(True)
        w.set_processing(False)
        assert w._input.isEnabled() is True
        assert w._send_btn.isEnabled() is True

    def test_processing_does_not_disable_mic(self, qt_widget):
        """Mic button is NOT disabled during processing (voice can interrupt)."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._mic_btn.isEnabled() is True
        w.set_processing(True)
        # Mic should remain enabled
        assert w._mic_btn.isEnabled() is True

    def test_send_does_not_fire_when_disabled(self, qt_widget, qtbot):
        """When processing is True, the input field is disabled and the user
        cannot type or press Enter to send."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        w.set_processing(True)
        assert w._input.isEnabled() is False
        assert w._send_btn.isEnabled() is False

        # Direct _on_send signal is still callable internally (it reads input),
        # but the real guard is that the input is disabled so the user
        # cannot press Enter. Verify input is effectively blocked.
        w._input.setText("should not send")
        # Simulate what happens when Enter is pressed on a disabled field:
        # returnPressed is NOT emitted by Qt when the widget is disabled.
        # We verify the disabled state is correct.
        assert w._input.isEnabled() is False


# =============================================================================
# Mic Button — State & Signals
# =============================================================================


class TestMicButton:
    """Microphone button state management and signals."""

    def test_mic_pressed_signal(self, qt_widget, qtbot):
        """Pressing the mic button emits mic_pressed."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []
        w.mic_pressed.connect(lambda: received.append(True))
        w._mic_btn.pressed.emit()
        assert received == [True]

    def test_mic_released_signal(self, qt_widget, qtbot):
        """Releasing the mic button emits mic_released."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []
        w.mic_released.connect(lambda: received.append(True))
        w._mic_btn.released.emit()
        assert received == [True]

    def test_mic_state_idle_stylesheet(self, qt_widget):
        """Setting mic state to 'idle' applies the idle style."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_mic_state("idle")
        ss = w._mic_btn.styleSheet()
        assert "transparent" in ss or "border-radius" in ss

    def test_mic_state_listening_stylesheet(self, qt_widget):
        """Setting mic state to 'listening' applies the listening style."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_mic_state("listening")
        ss = w._mic_btn.styleSheet()
        assert "COLOR_ERROR_DEFAULT" in ss or "background-color" in ss

    def test_mic_state_processing_stylesheet(self, qt_widget):
        """Setting mic state to 'processing' applies the processing style."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_mic_state("processing")
        ss = w._mic_btn.styleSheet()
        assert "COLOR_WARNING_DEFAULT" in ss or "background-color" in ss

    def test_mic_state_unknown_falls_back_to_idle(self, qt_widget):
        """Unknown state falls back to idle style."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_mic_state("nonexistent")
        ss = w._mic_btn.styleSheet()
        assert "transparent" in ss or "border-radius" in ss

    def test_mic_visible_toggle(self, qt_widget, qtbot):
        """set_mic_visible shows/hides the mic button."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)
        qt_widget.show()
        w.show()

        w.set_mic_visible(False)
        assert w._mic_btn.isVisible() is False
        w.set_mic_visible(True)
        assert w._mic_btn.isVisible() is True

    def test_mic_enabled_toggle(self, qt_widget):
        """set_mic_enabled enables/disables the mic button."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._mic_btn.isEnabled() is True
        w.set_mic_enabled(False)
        assert w._mic_btn.isEnabled() is False
        w.set_mic_enabled(True)
        assert w._mic_btn.isEnabled() is True

    def test_mic_state_updates_tooltip(self, qt_widget):
        """Setting mic state changes the tooltip text."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        w.set_mic_state("listening")
        assert "Recording" in w._mic_btn.toolTip() or "release to send" in w._mic_btn.toolTip()
        w.set_mic_state("processing")
        assert "Processing" in w._mic_btn.toolTip()
        w.set_mic_state("idle")
        assert "Hold to record" in w._mic_btn.toolTip()

    def test_mic_button_cursor_is_pointing_hand(self, qt_widget):
        """Mic button has a pointing-hand cursor."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._mic_btn.cursor().shape() == Qt.PointingHandCursor


# =============================================================================
# Signal Emission — send_clicked
# =============================================================================


class TestSignalEmission:
    """Comprehensive signal emission tests."""

    def test_send_clicked_emitted_with_trimmed_text(self, qt_widget, qtbot):
        """send_clicked emits trimmed text."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []
        w.send_clicked.connect(received.append)
        w._input.setText("  hello  ")
        w._send_btn.click()
        assert received == ["hello"]

    def test_send_clicked_not_emitted_for_empty(self, qt_widget, qtbot):
        """send_clicked is NOT emitted for empty input."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        received = []
        w.send_clicked.connect(received.append)

        # Empty
        w._on_send()
        assert received == []

        # Whitespace only
        w._input.setText("   ")
        w._on_send()
        assert received == []

    def test_send_clicked_clears_input(self, qt_widget, qtbot):
        """After send_clicked, the input is cleared."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        w._input.setText("clear me")
        w._send_btn.click()
        assert w._input.text() == ""

    def test_mic_pressed_emitted_on_press(self, qt_widget, qtbot):
        """mic_pressed signal is emitted when mic button is pressed."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        pressed = []
        w.mic_pressed.connect(lambda: pressed.append(True))
        w._mic_btn.pressed.emit()
        assert pressed == [True]

    def test_mic_released_emitted_on_release(self, qt_widget, qtbot):
        """mic_released signal is emitted when mic button is released."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        qtbot.addWidget(w)

        released = []
        w.mic_released.connect(lambda: released.append(True))
        w._mic_btn.released.emit()
        assert released == [True]

    def test_send_clicked_signal_type_is_str(self, qt_widget):
        """send_clicked is a Signal that accepts a string."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        # Verify the signal exists and accepts str
        assert hasattr(w, "send_clicked")
        # Signal should accept a string argument
        from PySide6.QtCore import Signal
        assert isinstance(ChatInputWidget.send_clicked, Signal)

    def test_mic_signals_exist(self, qt_widget):
        """mic_pressed and mic_released signals exist on the class."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        from PySide6.QtCore import Signal
        assert isinstance(ChatInputWidget.mic_pressed, Signal)
        assert isinstance(ChatInputWidget.mic_released, Signal)


# =============================================================================
# Layout & Children
# =============================================================================


class TestLayout:
    """Verify the widget layout structure."""

    def test_has_layout(self, qt_widget):
        """Widget has a QHBoxLayout."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        from PySide6.QtWidgets import QHBoxLayout
        assert isinstance(w.layout(), QHBoxLayout)

    def test_children_order(self, qt_widget):
        """Children are present in the correct order: input, mic, send."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        items = [w.layout().itemAt(i) for i in range(w.layout().count())]
        widgets = [it.widget() for it in items if it.widget()]
        assert w._input in widgets
        assert w._mic_btn in widgets
        assert w._send_btn in widgets

    def test_input_stretch_factor(self, qt_widget):
        """Input field has stretch factor 1 (takes remaining space)."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        stretch = w.layout().stretch(0)
        assert stretch == 1

    def test_send_button_has_style(self, qt_widget):
        """Send button has styled stylesheet with accent colour."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._send_btn.styleSheet() != ""


# =============================================================================
# Constructor with i18n patching (defensive)
# =============================================================================


class TestI18NIntegration:
    """Widget uses t() for user-visible strings with sensible fallbacks."""

    def test_placeholder_uses_t_fallback(self, qt_widget):
        """Placeholder text comes from t() with fallback."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        # When no translation is loaded, t() returns the default
        assert "fleet" in w._input.placeholderText().lower()

    def test_send_button_text_uses_t_fallback(self, qt_widget):
        """Send button text comes from t() with fallback."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert w._send_btn.text() == "Send"

    def test_mic_tooltip_uses_t_fallback(self, qt_widget):
        """Mic tooltip comes from t() with fallback."""
        from ui.copilot.widgets.chat_input import ChatInputWidget
        w = ChatInputWidget(qt_widget)
        assert "record" in w._mic_btn.toolTip().lower()
