import json
import re

# Load source and target
with open('data/translations/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('data/translations/hr.json', 'r', encoding='utf-8') as f:
    hr = json.load(f)

ACRONYMS = {'ID', 'KM', 'VIN', 'EUR', 'N/A', 'CSV', 'PDF', 'OCR', 'GPS', 'API',
            'CMR', 'KPI', 'SMTP', 'DSO', 'SLA', 'SOC', 'GDPR', 'CUI', 'VAT',
            'ETA', 'SMS', 'GBP', 'USD', 'RON', 'JSON', 'BOM', 'UTF-8'}

# Croatian translations dictionary for all English strings found in the app
TRANSLATIONS = {
    # nav section
    "Overview": "Pregled",
    "Calculator": "Kalkulator",
    "Dispatcher Board": "Dispečerska ploča",
    "Driver Manager": "Upravitelj vozača",
    "Maintenance Analytics": "Analitika održavanja",
    "Maintenance Control": "Kontrola održavanja",
    "Tachograph": "Tahograf",
    "Operations": "Operacije",
    "Finance": "Financije",
    "Live Tracking": "Praćenje uživo",
    "Maintenance": "Održavanje",
    "Route Planner": "Planer ruta",
    "Clients": "Klijenti",
    "Document Center": "Centar dokumenata",
    "Does Not Exist": "Ne postoji",
    "Team": "Tim",
    "Migration Center": "Centar migracije",
    "Tools": "Alati",
    "Administration": "Administracija",
    "Generators": "Generatori",

    # migration section
    "Import and export your data": "Uvoz i izvoz vaših podataka",
    "Import from Software": "Uvoz iz softvera",
    "Physical Archive": "Fizički arhiv",
    "Export Data": "Izvoz podataka",

    # team section
    "Team Management": "Upravljanje timom",
    "Add User": "Dodaj korisnika",
    "Invite a new team member": "Pozovite novog člana tima",
    "Team Members": "Članovi tima",
    "Manage existing users": "Upravljanje postojećim korisnicima",
    "EMAIL": "E-POŠTA",
    "PASSWORD": "LOZINKA",
    "ROLE": "ULOGA",
    "LINK DRIVER": "VEZA S VOZAČEM",
    "Dispatcher": "Dispečer",
    "Driver": "Vozač",
    "Role": "Uloga",
    "Created": "Kreirano",
    "Actions": "Radnje",
    "Deactivate": "Deaktiviraj",
    "Email is required.": "E-pošta je obavezna.",
    "Password is required.": "Lozinka je obavezna.",
    "User added successfully.": "Korisnik uspješno dodan.",
    "Failed to add user: {}": "Neuspješno dodavanje korisnika: {}",
    "Failed to deactivate user: {}": "Neuspješna deaktivacija korisnika: {}",
    "Are you sure you want to deactivate {email}?": "Jeste li sigurni da želite deaktivirati {email}?",
    "Deactivate User": "Deaktiviraj korisnika",
    "Validation": "Validacija",
    "Deactivate": "Deaktiviraj",
    "No API client or database available.": "Nije dostupan API klijent niti baza podataka.",
    "Success": "Uspjeh",
    "Failed to add user: {error}": "Neuspješno dodavanje korisnika: {error}",
    "Failed to deactivate user: {error}": "Neuspješna deaktivacija korisnika: {error}",

    # main section
    "Add VAT": "Dodaj PDV",
    "Price (before VAT):": "Cijena (bez PDV-a):",
    "Price (after VAT):": "Cijena (s PDV-om):",
    "CALCULATION RESULT": "REZULTAT IZRAČUNA",
    "Fill in the form to calculate profit": "Ispunite obrazac za izračun dobiti",
    "Enter trip data and press Calculate.": "Unesite podatke o turi i pritisnite Izračunaj.",
    "Gross Revenue": "Bruto prihod",
    "Total Cost": "Ukupni trošak",
    "Net Profit": "Neto dobit",
    "Rate / km": "Stopa / km",
    "Margin": "Marža",
    "{module}\n(Module not yet migrated)": "{module}\n(Modul još nije migriran)",
    "VAT %": "PDV %",

    # fleet section
    "Documents": "Dokumenti",
    "Select a truck first.": "Prvo odaberite kamion.",
    "General": "Općenito",
    "Unassigned": "Neraspoređeno",
    "Active": "Aktivno",
    "Unknown": "Nepoznato",
    "No engine data": "Nema podataka o motoru",
    "Open Alerts": "Otvorena upozorenja",
    "Cost/Month": "Trošak/mjesec",
    "Last Service": "Posljednji servis",
    "Next Due": "Sljedeći rok",
    "Odometer": "Brojač kilometara",
    "Maintenance": "Održavanje",
    "Maintenance History": "Povijest održavanja",
    "Open Maintenance": "Otvori održavanje",
    "Alerts": "Upozorenja",
    "Tracking Device ID": "ID uređaja za praćenje",
    "Truck {}": "Kamion {}",

    # history section
    "Cancel Status": "Otkaži status",
    "Confirm Status": "Potvrdi status",
    "No Engine": "Nema motora",
    "No Transitions": "Nema prijelaza",
    "Status Prompt": "Zahtjev statusa",
    "Transition Failed": "Prijelaz nije uspio",
    "Load More": "Učitaj više",
    "Date": "Datum",
    "Truck": "Kamion",
    "Client": "Klijent",
    "Distance (km)": "Udaljenost (km)",
    "€/km": "€/km",
    "Profit": "Dobit",
    "Emailed": "Poslano e-poštom",
    "Trip emailed successfully": "Tura uspješno poslana e-poštom",
    "Invoiced": "Fakturirano",
    "Invoice generated successfully": "Račun uspješno generiran",
    "Error": "Greška",
    "Search trips...": "Pretraži ture...",
    "Export PDF": "Izvezi PDF",
    "Export Excel": "Izvezi Excel",
    "Email Invoice": "Pošalji račun e-poštom",
    "Operations management and invoicing": "Upravljanje operacijama i fakturiranje",
    "Trip #{}": "Tura #{}",

    # analytics section
    "Invalid Date Format": "Neispravan format datuma",
    "Top Trucks by Revenue": "Najbolji kamioni po prihodu",
    "Revenue vs Expenses": "Prihod vs troškovi",
    "Driver Profit": "Dobit po vozaču",
    "Profit Margin": "Marža profita",
    "From": "Od",
    "To": "Do",
    "Apply": "Primijeni",
    "Revenue": "Prihod",
    "Expenses": "Troškovi",
    "Profit": "Dobit",
    "Chart Error": "Greška grafikona",
    "Invalid date range": "Neispravan raspon datuma",
    "Fleet performance analytics and KPIs": "Analitika učinkovitosti voznog parka i KPI",
    "Financial": "Financijski",
    "Fleet": "Vozni park",
    "Routes": "Rute",
    "Drivers": "Vozači",
    "Documents": "Dokumenti",
    "Revenue, profit, margin, and cash flow trends": "Trendovi prihoda, dobiti, marže i novčanog toka",
    "Truck utilization, fuel efficiency, and maintenance alerts": "Iskorištenost kamiona, učinkovitost goriva i upozorenja održavanja",
    "Route profitability and country corridor analysis": "Profitabilnost ruta i analiza koridora zemalja",
    "Client revenue, payment behavior, and growth": "Prihod klijenata, ponašanje plaćanja i rast",
    "Driver performance, efficiency, and compliance": "Učinak vozača, učinkovitost i usklađenost",
    "Document volume, trends, and expiration tracking": "Volumen dokumenata, trendovi i praćenje isteka",
    "Total Revenue": "Ukupni prihod",
    "Total Profit": "Ukupna dobit",
    "Current Margin": "Trenutna marža",
    "Top Client": "Najbolji klijent",
    "Active Trucks": "Aktivni kamioni",
    "Total KM": "Ukupno KM",
    "Avg Consumption": "Prosječna potrošnja",
    "Maint. Alerts": "Upozorenja održavanja",
    "Invoices": "Računi",
    "CMRs": "CMR-ovi",
    "Total Docs": "Ukupno dokumenata",
    "Expiring": "Istječe",
    "months": "mjeseci",
    "Truck Profitability": "Profitabilnost kamiona",
    "Fuel Efficiency (L/100km)": "Učinkovitost goriva (L/100km)",
    "Truck Utilization (Trips)": "Iskorištenost kamiona (ture)",
    "Revenue by Client": "Prihod po klijentu",
    "Profit by Client": "Dobit po klijentu",
    "Average Payment Delay (Days)": "Prosječno kašnjenje plaćanja (dani)",
    "Revenue Concentration": "Koncentracija prihoda",
    "Last quarter": "Prošli kvartal",
    "No data available": "Nema dostupnih podataka",
    "Rest": "Ostalo",
    "New Clients per Month": "Novi klijenti mjesečno",
    "Insight: {client} generates {rev_pct}% of revenue but only {profit_pct}% of profit.": "Uvid: {client} generira {rev_pct}% prihoda ali samo {profit_pct}% dobiti.",
    "Trips Completed": "Završene ture",
    "Profit per Driver": "Dobit po vozaču",
    "Efficiency (Profit/km)": "Učinkovitost (dobit/km)",
    "Tacho Violations (90 days)": "Tahografski prekršaji (90 dana)",
    "Most Profitable Routes": "Najprofitabilnije rute",
    "Profit per KM": "Dobit po KM",
    "Fuel Cost per KM": "Trošak goriva po KM",
    "Country Profit per KM": "Dobit po KM po zemlji",
    "Document Distribution": "Distribucija dokumenata",
    "Monthly Uploads": "Mjesečna učitavanja",
    "CMR Generation Trend": "Trend generiranja CMR-a",
    "Other": "Ostalo",
    "{count} documents expiring within 30 days:": "{count} dokumenata istječe u roku od 30 dana:",
    "Revenue by Country": "Prihod po zemlji",
    "Financial Trends": "Financijski trendovi",
    "Financial Performance": "Financijski učinak",
    "Client & Geographic": "Klijenti i geografija",
    "Volume & Cost": "Volumen i trošak",
    "Fleet Performance": "Učinkovitost voznog parka",
    "Fleet Composition": "Sastav voznog parka",
    "Cost & Maintenance": "Trošak i održavanje",
    "Volume & Efficiency": "Volumen i učinkovitost",
    "Compliance & Safety": "Usklađenost i sigurnost",
    "Distribution & Insights": "Distribucija i uvidi",
    "Trip Distance Distribution": "Distribucija udaljenosti tura",
    "Trips by Month x Driver": "Ture po mjesecu x vozaču",
    "Profit Breakdown (Top Driver)": "Raščlamba dobiti (najbolji vozač)",
    "Driving vs Rest Hours": "Sati vožnje vs odmora",
    "Driver Utilization Score": "Bod iskorištenosti vozača",
    "Avg Profit per Trip": "Prosječna dobit po turi",
    "Total costs": "Ukupni troškovi",
    "Top Route": "Najbolja ruta",
    "Avg Profit/km": "Prosječna dobit/km",
    "Total Routes": "Ukupno ruta",
    "Top Country": "Najbolja zemlja",
    "Route Performance": "Učinak rute",
    "Geographic Analysis": "Geografska analiza",
    "Correlation & Distribution": "Korelacija i distribucija",
    "Volume & Trends": "Volumen i trendovi",
    "Top Countries by Volume": "Najbolje zemlje po volumenu",
    "Top Countries by Profit": "Najbolje zemlje po dobiti",
    "Cost Breakdown": "Raščlamba troškova",
    "Distance (km)": "Udaljenost (km)",
    "Net Profit (€)": "Neto dobit (€)",
    "Distance Distribution": "Distribucija udaljenosti",
    "Route Length Trend": "Trend duljine rute",
    "Net Profit Trend": "Trend neto dobiti",
    "Monthly Trip Volume": "Mjesečni volumen tura",
    "Trucks": "Kamioni",
    "Idle": "Neaktivno",
    "Client Performance": "Učinak klijenta",
    "Client Composition": "Sastav klijenata",
    "Client Trends": "Trendovi klijenata",
    "Client Insights": "Uvidi o klijentima",
    "Document Overview": "Pregled dokumenata",
    "Document Breakdown": "Raščlamba dokumenata",
    "Expiry & Aging": "Istek i starenje",
    "Growth & Trends": "Rast i trendovi",
    "Document Type Breakdown": "Raščlamba vrsta dokumenata",
    "Category Distribution": "Distribucija kategorija",
    "Upload by Quarter": "Učitavanje po kvartalu",
    "Expiry Timeline": "Vremenska crta isteka",
    "Document Aging": "Starenje dokumenata",
    "Expiring by Type": "Istječe po vrsti",
    "Document Growth": "Rast dokumenata",
    "Volume vs Revenue": "Volumen vs prihod",
    "Total Documents Trend": "Trend ukupnih dokumenata",
    "Revenue per Client Trend": "Trend prihoda po klijentu",
    "Trip Count Trend": "Trend broja tura",
    "Profit Margin per Client": "Marža dobiti po klijentu",
    "Revenue vs Profit": "Prihod vs dobit",
    "Active Clients Trend": "Trend aktivnih klijenata",
    "Total Clients": "Ukupno klijenata",
    "Avg Payment Delay": "Prosječno kašnjenje plaćanja",
    "Concentration": "Koncentracija",
    "Safety Score": "Bod sigurnosti",
    "Active vs Inactive": "Aktivno vs neaktivno",
    "Distance (km)": "Udaljenost (km)",
    "Net Profit (€)": "Neto dobit (€)",
    "Fuel": "Gorivo",
    "Toll": "Cestarina",
    "Salary": "Plaća",
    "Net": "Neto",
    "Total": "Ukupno",
    "Relevant": "Relevantno",
    "Top 3": "Top 3",
    "Others": "Ostali",
    "Trips": "Ture",
    "Period": "Razdoblje",
    "Last 30 days": "Zadnjih 30 dana",
    "Last 90 days": "Zadnjih 90 dana",
    "Last 6 months": "Zadnjih 6 mjeseci",
    "Last year": "Prošla godina",
    "All time": "Sve vrijeme",
    "Daily Activity": "Dnevna aktivnost",
    "Year": "Godina",
    "Client Retention": "Zadržavanje klijenata",
    "Cost Per Truck": "Trošak po kamionu",
    "Country Corridors": "Koridori zemalja",
    "Driver Distance": "Udaljenost vozača",
    "Driver Driving Hours": "Sati vožnje vozača",
    "Driver Ranking": "Rangiranje vozača",
    "Driver Rest Hours": "Sati odmora vozača",
    "Efficiency Trend": "Trend učinkovitosti",
    "Extra Costs": "Dodatni troškovi",
    "Fuel Cost Trend": "Trend troškova goriva",
    "Fuel Efficiency Trend": "Trend učinkovitosti goriva",
    "Idle Vs Active": "Neaktivno vs aktivno",
    "Inactive": "Neaktivno",
    "Invoiced Vs Paid": "Fakturirano vs plaćeno",
    "Kpi Avg Trips": "Prosječne ture",
    "Kpi Top Driver": "Najbolji vozač",
    "Kpi Total Drivers": "Ukupno vozača",
    "Kpi Total Violations": "Ukupno prekršaja",
    "Maintenance Cost": "Trošak održavanja",
    "Mileage Ranking": "Rangiranje po kilometraži",
    "Paid": "Plaćeno",
    "Profit Vs Distance": "Dobit vs udaljenost",
    "Quarterly Revenue": "Kvartalni prihod",
    "Revenue Per Client Trend": "Trend prihoda po klijentu",
    "Revenue Vs Profit Scatter": "Rasipanje prihoda vs dobiti",
    "Section Driver Metrics": "Metrike vozača",
    "Section Driver Performance": "Učinak vozača",
    "Section Volume Safety": "Volumen i sigurnost",
    "Total Distance": "Ukupna udaljenost",
    "Trip Status Distribution": "Distribucija statusa tura",
    "Truck Age Distribution": "Distribucija starosti kamiona",
    "31-60 days": "31-60 dana",
    "61-90 days": "61-90 dana",
    "Current (0-30d)": "Trenutno (0-30d)",
    "90+ days": "90+ dana",
    "All Countries": "Sve zemlje",
    "Profit/KM": "Dobit/KM",
    "Route": "Ruta",
    "Actual Uploads": "Stvarna učitavanja",
    "Expected (Trips)": "Očekivano (ture)",
    "No documents expiring within 30 days": "Nema dokumenata koji istječu u roku od 30 dana",
    "See all ({count})": "Vidi sve ({count})",
    "Document Uploads vs Expected": "Učitavanja dokumenata vs očekivano",
    "{count} trips without assigned driver (excluded)": "{count} tura bez dodijeljenog vozača (isključeno)",
    "Insufficient data for chart — add more trips": "Nedovoljno podataka za grafikon — dodajte više tura",
    "Outstanding Invoices by Age": "Nenaplaćeni računi po starosti",
    "Active Drivers": "Aktivni vozači",
    "Avg Profit/Driver": "Prosječna dobit/vozač",
    "Avg Profit/Route": "Prosječna dobit/ruta",
    "Avg Trips/Driver": "Prosječne ture/vozač",
    "Avg Cost/km": "Prosječni trošak/km",
    "Avg collection period": "Prosječno razdoblje naplate",
    "DSO (Days)": "DSO (dani)",
    "Most Frequent": "Najčešće",
    "New Clients": "Novi klijenti",
    "Unassigned Trips": "Neraspoređene ture",
    "Unique Routes": "Jedinstvene rute",
    "No assigned driver data for this period.": "Nema podataka o dodijeljenom vozaču za ovo razdoblje.",
    "Outstanding": "Nenaplaćeno",
    "Target 30d": "Cilj 30d",
    "Refresh data": "Osvježi podatke",
    "Revenue vs Profit Trend": "Trend prihoda vs dobiti",
    "Revenue by Country": "Prihod po zemlji",
    "Route Frequency": "Učestalost ruta",
    "Driver Activity Timeline": "Vremenska crta aktivnosti vozača",
    "Invoice Aging": "Starenje računa",
    "Payment Behavior": "Ponašanje plaćanja",
    "Revenue & Profit Trend": "Trend prihoda i dobiti",
    "No revenue data yet": "Još nema podataka o prihodu",
    "Expires": "Istječe",

    # invoice section
    "Button Email": "Gumb e-pošta",
    "Default Client": "Zadani klijent",
    "Email Body": "Tijelo e-pošte",
    "Email Failed": "E-pošta nije uspjela",
    "Email Subject": "Predmet e-pošte",
    "Email Success": "E-pošta uspješna",
    "Smtp Not Configured": "SMTP nije konfiguriran",
    "Field {Key}": "Polje {Key}",

    # settings section
    "EMAIL & SMTP": "E-POŠTA I SMTP",
    "MAINTENANCE THRESHOLDS": "GRANICE ODRŽAVANJA",
    "Save": "Spremi",
    "Reset": "Poništi",
    "Application Settings": "Postavke aplikacije",
    "SMTP Server:": "SMTP poslužitelj:",
    "SMTP Port:": "SMTP port:",
    "SMTP User:": "SMTP korisnik:",
    "SMTP Password:": "SMTP lozinka:",
    "Alert Email Recipients:": "Primatelji upozorenja e-poštom:",
    "Alert Days Ahead:": "Dani unaprijed za upozorenja:",
    "Tacho Warning Days:": "Dani upozorenja tahografa:",
    "Tacho Critical Days:": "Kritični dani tahografa:",
    "Test Connection": "Testiraj vezu",
    "Email Logs": "Zapisnici e-pošte",
    "Connection successful": "Veza uspješna",
    "Test failed: {}": "Test neuspješan: {}",
    "BRANDING": "BREndiranje",
    "Company Logo:": "Logotip tvrtke:",
    "Color": "Boja",
    "Signature Image:": "Slika potpisa:",
    "Stamp Image:": "Slika pečata:",
    "Dark": "Tamno",
    "Light": "Svijetlo",
    "Field Ai Vision": "Polje AI vida",
    "Body template:": "Predložak tijela:",
    "Field Email Importer": "Polje uvoznika e-pošte",
    "Field Folder Watcher": "Polje praćenja mape",
    "PaddleOCR advanced settings:": "Napredne postavke PaddleOCR:",
    "Cloud OCR credentials:": "Vjerodajnice cloud OCR-a:",
    "Field Ocr Gpu": "Polje OCR GPU",
    "Set at least one provider": "Postavite barem jednog pružatelja",
    " seconds": " sekundi",

    # edit_trip section
    "Completed": "Završeno",
    "Overdue": "Prekoračeno",

    # route section
    "Calculate a route to see details.": "Izračunajte rutu za prikaz detalja.",
    "Add to Dispatch": "Dodaj na dispečing",
    "Send to Calculator": "Pošalji u kalkulator",
    "Client Name": "Ime klijenta",
    "No saved route ID": "Nema spremljenog ID rute",
    "Select Driver": "Odaberi vozača",
    "Start Date": "Datum početka",
    "Destination": "Odredište",
    "Stop {n}": "Stajalište {n}",
    "Start": "Početak",
    "Trip Created": "Tura kreirana",
    "Recommended": "Preporučeno",
    "Fastest": "Najbrže",
    "Cheapest": "Najjeftinije",
    "Safest": "Najsigurnije",
    "Shortest": "Najkraće",
    "Click map to add stop": "Kliknite na kartu za dodavanje stajališta",
    "Route loaded": "Ruta učitana",
    "Route Options": "Opcije rute",
    "Plan multi-stop routes with cost estimation": "Planirajte rute s više stajališta s procjenom troškova",
    "Route Planner": "Planer ruta",
    "SMART ROUTE": "PAMETNA RUTA",
    "OPTIONS": "OPCIJE",
    "EXCLUDED COUNTRIES": "ISKLJUČENE ZEMLJE",
    "ROUTE RESULT": "REZULTAT RUTE",
    "Add Country": "Dodaj zemlju",
    "Share Route": "Podijeli rutu",
    "Share this route with others so they can load it in Operion.": "Podijelite ovu rutu s drugima kako bi je mogli učitati u Operion.",
    "Share link": "Poveznica za dijeljenje",
    "Copy": "Kopiraj",
    "Export File": "Izvezi datoteku",
    "Google Maps": "Google karte",
    "Save & Open Folder": "Spremi i otvori mapu",
    "Copied!": "Kopirano!",
    "Clipboard unavailable": "Međuspremnik nedostupan",
    "Saved: {path}": "Spremljeno: {path}",
    "Calculate Route": "Izračunaj rutu",
    "Distance": "Udaljenost",
    "Duration": "Trajanje",

    # route_history section
    "Route #{a} vs #{b}\nDistance delta: {d_dist:+.1f} km\nDuration delta: {d_dur}\nProfiles: {p_a} / {p_b}": "Ruta #{a} vs #{b}\nRazlika udaljenosti: {d_dist:+.1f} km\nRazlika trajanja: {d_dur}\nProfili: {p_a} / {p_b}",
    "Page {current} of {total} ({count} routes)": "Stranica {current} od {total} ({count} ruta)",
    "None": "Ništa",
    "Total routes: {count}\nTotal distance: {dist:.1f} km\nTop destinations: {dests}": "Ukupno ruta: {count}\nUkupna udaljenost: {dist:.1f} km\nNajbolja odredišta: {dests}",
    "Recalculate": "Ponovno izračunaj",
    "Archive": "Arhiviraj",
    "Export JSON": "Izvezi JSON",
    "Export CSV": "Izvezi CSV",
    "Delete": "Izbriši",
    "Compare": "Usporedi",
    "Loading map...": "Učitavanje karte...",
    "Search...": "Pretraži...",
    "Filter by truck": "Filtriraj po kamionu",
    "Filter by Truck": "Filtriraj po kamionu",
    "Confirm Archive": "Potvrdi arhiviranje",
    "Archive these routes?": "Arhivirati ove rute?",
    "Confirm Delete": "Potvrdi brisanje",
    "Delete these routes?": "Izbrisati ove rute?",
    "Exported": "Izvoz",
    "Routes exported successfully.": "Rute uspješno izvezene.",
    "Recalculated": "Ponovno izračunato",
    "Routes recalculated successfully.": "Rute uspješno ponovno izračunate.",
    "Search routes...": "Pretraži rute...",
    "Select truck...": "Odaberi kamion...",
    "Review and manage saved routes": "Pregledajte i upravljajte spremljenim rutama",
    "Route History": "Povijest ruta",
    "Total:": "Ukupno:",
    "Active:": "Aktivno:",
    "Archived:": "Arhivirano:",
    "Date:": "Datum:",
    "Truck:": "Kamion:",
    "Distance:": "Udaljenost:",
    "Duration:": "Trajanje:",

    # result section
    "day": "dan",
    "hour": "sat",
    "minute": "minuta",
    "Routing server is off. Check that GraphHopper is running.": "Poslužitelj usmjeravanja je isključen. Provjerite radi li GraphHopper.",

    # email section
    "Documents for Trip #{}": "Dokumenti za turu #{}",
    "Trip #{}": "Tura #{}",

    # tracking section
    "Fleet Tracking": "Praćenje voznog parka",
    "Configure fleet tracking credentials in Settings.": "Konfigurirajte vjerodajnice za praćenje u Postavkama.",
    "Tracking Platform": "Platforma za praćenje",
    "Platform not configured": "Platforma nije konfigurirana",
    "API Token": "API token",
    "Server URL": "URL poslužitelja",
    "Username": "Korisničko ime",
    "Password": "Lozinka",
    "Test Connection": "Testiraj vezu",
    "Connection test incomplete": "Test veze nije dovršen",
    "Connection test failed": "Test veze nije uspio",
    "No vehicles tracked": "Nema praćenih vozila",
    "Not Configured": "Nije konfigurirano",
    "Settings": "Postavke",
    "Speed": "Brzina",
    "Last Updated": "Zadnje ažuriranje",
    "Address": "Adresa",
    "Fleet Details": "Detalji voznog parka",
    "Stopped": "Zaustavljeno",
    "Account / Subdomain": "Račun / poddomena",
    "ID Field": "ID polje",
    "Latitude Field": "Polje širine",
    "Longitude Field": "Polje dužine",
    "Positions JSON Path": "PUT JSON pozicija",

    # email_logs section
    "Recipient": "Primatelj",
    "Subject": "Predmet",
    "Sent": "Poslano",
    "No logs found": "Nema pronađenih zapisnika",

    # alerts section
    "Critical": "Kritično",
    "Warning": "Upozorenje",
    "Info": "Informacija",

    # status section
    "Planned": "Planirano",
    "Loading": "Utovar",
    "In Transit": "U tranzitu",
    "Delivered": "Isporučeno",
    "Cancelled": "Otkazano",
    "planned": "planirano",
    "loading": "utovar",
    "in_transit": "u tranzitu",
    "delivered": "isporučeno",
    "cancelled": "otkazano",
    "invoiced": "fakturirano",
    "paid": "plaćeno",
    "Invoiced": "Fakturirano",
    "Paid": "Plaćeno",
    "Archived": "Arhivirano",

    # common section
    "Search...": "Pretraži...",
    "Confirm": "Potvrdi",
    "Warning": "Upozorenje",
    "Error": "Greška",
    "Schedule": "Raspored",
    "No activity recorded": "Nema zabilježene aktivnosti",
    "No revenue data yet": "Još nema podataka o prihodu",
    "Ops not available": "Operacije nisu dostupne",
    "No signature": "Nema potpisa",
    "Signature accepted": "Potpis prihvaćen",
    "Cleaned up": "Očišćeno",
    "Select Signature Image": "Odaberite sliku potpisa",
    "Open calendar": "Otvori kalendar",
    "Select date": "Odaberi datum",
    "Show alerts": "Prikaži upozorenja",
    "Cancel": "Odustani",
    "↓ Down": "↓ Dolje",
    "Refresh": "Osvježi",
    "↑ Up": "↑ Gore",
    "Truck": "Kamion",
    "Schedule": "Raspored",

    # dispatch_board section
    "Board": "Ploča",
    "Resources": "Resursi",
    "Alerts & Ops": "Upozorenja i operacije",
    "Timeline": "Vremenska crta",
    "Search trips...": "Pretraži ture...",
    "Clear": "Očisti",
    "Filter by status": "Filtriraj po statusu",
    "No matching trips": "Nema odgovarajućih tura",
    "Driver Availability": "Dostupnost vozača",
    "Truck Availability": "Dostupnost kamiona",
    "Available": "Dostupno",
    "Returning": "Povratak",
    "On Trip": "Na turi",
    "Blocked": "Blokirano",
    "No active drivers": "Nema aktivnih vozača",
    "No active trucks": "Nema aktivnih kamiona",
    "License Expired": "Dozvola istekla",
    "Medical Expired": "Liječnički istekao",
    "Hours Exceeded": "Prekoračeni sati",
    "Maint. Due": "Održavanje dospjelo",
    "Insurance Expired": "Osiguranje isteklo",
    "Inspection Expired": "Inspekcija istekla",
    "In Service": "U servisu",
    "Trip": "Tura",
    "ETA": "ETA",
    "Next free": "Sljedeći slobodan",
    "Operational Alerts": "Operativna upozorenja",
    "No active alerts": "Nema aktivnih upozorenja",
    "All alerts have been resolved": "Sva upozorenja su riješena",
    "Unassigned Trips": "Neraspoređene ture",
    "All trips assigned": "Sve ture raspoređene",
    "All trips are fully assigned": "Sve ture su u potpunosti raspoređene",
    "No Truck": "Nema kamiona",
    "No Driver": "Nema vozača",
    "No Truck or Driver": "Nema kamiona ili vozača",
    "Quick Assign": "Brzo dodjeljivanje",
    "Assignment Summary": "Sažetak dodjeljivanja",
    "Total Active": "Ukupno aktivno",
    "Fully Assigned": "U potpunosti dodijeljeno",
    "Partial": "Djelomično",
    "Unassigned": "Neraspoređeno",
    "Resolve All": "Riješi sve",
    "Trip Details": "Detalji ture",
    "Edit Trip": "Uredi turu",
    "Save": "Spremi",
    "Cancel": "Odustani",
    "Close": "Zatvori",
    "Trip ID": "ID ture",
    "Status": "Status",
    "Truck": "Kamion",
    "Driver": "Vozač",
    "Client": "Klijent",
    "Route": "Ruta",
    "Departure": "Polazak",
    "ETA": "ETA",
    "Distance": "Udaljenost",
    "Price": "Cijena",
    "Net Profit": "Neto dobit",
    "Currency": "Valuta",
    "Notes": "Bilješke",
    "Alerts": "Upozorenja",
    "No alerts for this trip": "Nema upozorenja za ovu turu",
    "Resource Conflict": "Sukob resursa",
    "The following conflicts were detected:": "Otkriveni su sljedeći sukobi:",
    "Drivers Free": "Slobodni vozači",
    "Trucks Free": "Slobodni kamioni",
    "Schedule Timeline": "Vremenska crta rasporeda",
    "No scheduled trips to display": "Nema zakazanih tura za prikaz",
    "No trips scheduled for the selected period": "Nema zakazanih tura za odabrano razdoblje",
    "Plan a Trip": "Planiraj turu",
    "NOW": "SADA",
    "Assign Truck + Driver": "Dodijeli kamion + vozača",
    "Quick Assign Truck & Driver": "Brzo dodijeli kamion i vozača",
    "Truck blocked: {reason}": "Kamion blokiran: {reason}",
    "Driver blocked: {reason}": "Vozač blokiran: {reason}",
    "Cancelled": "Otkazano",
    "Cancel Trip": "Otkaži turu",
    "Are you sure you want to cancel trip {trip_id}?": "Jeste li sigurni da želite otkazati turu {trip_id}?",
    "Cancelled": "Otkazano",
    "Today's Brief": "Današnji sažetak",
    "Departing Today": "Polazi danas",
    "Arriving Today": "Dolazi danas",
    "Needs Attention": "Treba pažnju",
    "{n} trips selected": "{n} tura odabrano",
    "Assign Truck": "Dodijeli kamion",
    "Assign Driver": "Dodijeli vozača",
    "Clear": "Očisti",
    "Assigned to {count} trips": "Dodijeljeno {count} tura",
    "Assigned to {ok} trips ({failed} blocked)": "Dodijeljeno {ok} tura ({failed} blokirano)",
    "Assign Truck & Driver": "Dodijeli kamion i vozača",
    "Select Truck": "Odaberi kamion",
    "Select Driver": "Odaberi vozača",
    "Assign Both": "Dodijeli oboje",
    "Assign Truck Only": "Dodijeli samo kamion",
    "Assign Driver Only": "Dodijeli samo vozača",
    "Suggested pair: {driver} ↔ {truck}": "Predloženi par: {driver} ↔ {truck}",
    "CSV": "CSV",
    "PDF": "PDF",
    "Exported to {path}": "Izvoz u {path}",
    "Export failed: {error}": "Izvoz nije uspio: {error}",
    "Undone: {trip_id} {new_status} → {old_status}": "Vraćeno: {trip_id} {new_status} → {old_status}",
    "Redone: {trip_id} {old_status} → {new_status}": "Ponovljeno: {trip_id} {old_status} → {new_status}",
    "Nothing to undo": "Ništa za vratiti",
    "Nothing to redo": "Ništa za ponoviti",
    "Showing {} of {} trips": "Prikazano {} od {} tura",
    "{} trips": "{} tura",
    "No trips found": "Nema pronađenih tura",
    "Try adjusting your search or filter criteria": "Pokušajte prilagoditi kriterije pretraživanja ili filtriranja",

    # driver_manager section
    "Select a driver first.": "Prvo odaberite vozača.",
    "Drivers imported": "Vozači uvezeni",
    "Driver {}": "Vozač {}",

    # fleet_dashboard section
    "Past 30 Days": "Proteklih 30 dana",
    "more": "više",

    # fuel section
    "Fuel prices updated {minutes} ago": "Cijene goriva ažurirane prije {minutes} min",

    # maint section
    "Next due at {km} km": "Sljedeći rok na {km} km",
    "{km} km remaining": "{km} km preostalo",
    "Action Maint": "Akcija održavanja",
    "Action Remind": "Akcija podsjetnika",
    "Action Resolve": "Akcija rješavanja",
    "Action Trip": "Akcija ture",
    "Action Truck": "Akcija kamiona",
    "Add Record": "Dodaj zapis",
    "Alert Plural": "Upozorenja (mn.)",
    "Alert S": "Upozorenje (jd.)",
    "Cancel": "Odustani",
    "Close": "Zatvori",
    "Col Cost": "Trošak",
    "Col Date": "Datum",
    "Col Km": "KM",
    "Col Notes": "Bilješke",
    "Col Provider": "Dobavljač",
    "Col Type": "Vrsta",
    "Confirm Delete Msg": "Potvrdi poruku brisanja",
    "Confirm Delete Title": "Potvrdi naslov brisanja",
    "Critical Count": "Kritični broj",
    "Critical Health": "Kritično zdravlje",
    "Days Left": "Preostalo dana",
    "Delete": "Izbriši",
    "Due By Date": "Rok do datuma",
    "Edit": "Uredi",
    "Error Generic": "Opća greška",
    "Excellent": "Izvrsno",
    "Export": "Izvezi",
    "Export Success": "Izvoz uspješan",
    "Export Title": "Naslov izvoza",
    "Fair": "Dobro",
    "Filter Label": "Oznaka filtera",
    "Flash Maint Scheduled": "Održavanje zakazano",
    "Flash Reminder": "Podsjetnik",
    "Flash Trip Copied": "Tura kopirana",
    "Flash Truck Copied": "Kamion kopiran",
    "Form Cost": "Trošak",
    "Form Date": "Datum",
    "Form Km": "KM",
    "Notes": "Bilješke",
    "Service Provider": "Dobavljač usluge",
    "Quick select:": "Brzi odabir:",
    "Add Record": "Dodaj zapis",
    "Edit Record": "Uredi zapis",
    "Type:": "Vrsta:",
    "Attachment:": "Privitak:",
    "No file selected": "Nije odabrana datoteka",
    "Choose File": "Odaberi datoteku",
    "Header": "Zaglavlje",
    "Info Count": "Broj informacija",
    "Km Remaining": "Preostalo KM",
    "Label Trip": "Oznaka ture",
    "Label Truck": "Oznaka kamiona",
    "Metric Compliance": "Metrika usklađenosti",
    "Metric Downtime": "Metrika zastoja",
    "Metric Overdue": "Metrika prekoračenja",
    "Metric Recurring": "Metrika ponavljanja",
    "Metric Score": "Metrika rezultata",
    "Next": "Dalje",
    "No Alerts": "Nema upozorenja",
    "No Records": "Nema zapisa",
    "No Schedule": "Nema rasporeda",
    "No Schedules": "Nema rasporeda",
    "Page Info": "Informacije o stranici",
    "Predictions": "Predviđanja",
    "Predictions Header": "Zaglavlje predviđanja",
    "Predictions Title": "Naslov predviđanja",
    "Prev": "Natrag",
    "Refresh": "Osvježi",
    "Refresh Score": "Osvježi rezultat",
    "Save": "Spremi",
    "Schedule Add": "Dodaj raspored",
    "Schedule Delete Confirm": "Potvrdi brisanje rasporeda",
    "Schedule Delete Prompt": "Uputa za brisanje rasporeda",
    "Schedule Delete Title": "Naslov brisanja rasporeda",
    "Schedule Due By": "Rok rasporeda do",
    "Schedule Every Km": "Raspored svakih KM",
    "Schedule Every Months": "Raspored svakih mjeseci",
    "Schedule Expires": "Raspored istječe",
    "Schedule Form Expiry": "Obrazac isteka rasporeda",
    "Schedule Form Interval Km": "Obrazac intervala KM",
    "Schedule Form Interval Months": "Obrazac intervala mjeseci",
    "Schedule Form Last Date": "Obrazac zadnjeg datuma",
    "Schedule Form Last Km": "Obrazac zadnjeg KM",
    "Schedule Form Title Add": "Obrazac naslova dodavanja",
    "Schedule Form Title Edit": "Obrazac naslova uređivanja",
    "Schedule Last Date": "Zadnji datum rasporeda",
    "Schedule Last Km": "Zadnji KM rasporeda",
    "Status Due Soon": "Status uskoro dospijeva",
    "Status Ok": "Status OK",
    "Tab Health": "Zdravlje",
    "Tab History": "Povijest",
    "Tab Schedules": "Rasporedi",
    "Target Km": "Ciljni KM",
    "Title": "Naslov",
    "Updated": "Ažurirano",
    "Warning Count": "Broj upozorenja",
    "Filter by Severity": "Filtriraj po ozbiljnosti",
    "Filter Trip": "Filtriraj turu",
    "Filter Truck": "Filtriraj kamion",
    "Filter Type": "Filtriraj vrstu",
    "Show Resolved": "Prikaži riješeno",
    "Critical": "Kritično",
    "Warning": "Upozorenje",
    "Info": "Informacija",
    "Due by Km": "Dospijeva po KM",
    "Alerts": "Upozorenja",
    "Overall Health": "Opće zdravlje",
    "Compliance": "Usklađenost",
    "Overdue": "Prekoračeno",
    "Recurring Issues": "Ponavljajući problemi",
    "Description": "Opis",
    "Interval (days)": "Interval (dani)",
    "Interval (km)": "Interval (km)",
    "Mileage": "Kilometraža",
    "Next Date": "Sljedeći datum",
    "Next Mileage": "Sljedeća kilometraža",
    "Downtime": "Zastoj",
    "No health data available": "Nema dostupnih podataka o zdravlju",
    "All systems nominal": "Svi sustavi nominalni",
    "Maintenance schedules and health monitoring": "Rasporedi održavanja i praćenje zdravlja",
    "Filter...": "Filter...",
    " km": " km",
    " months": " mjeseci",

    # tacho section
    "Unknown error": "Nepoznata greška",
    "Import successful": "Uvoz uspješan",
    "{label}: {value}": "{label}: {value}",
    "Found {count} violation(s) flagged": "Pronađeno {count} prekršaja",
    "Driver": "Vozač",
    "Plate": "Tablica",
    "Calibration": "Kalibracija",
    "Days": "Dani",
    "Odometer": "Brojač km",
    "Date": "Datum",
    "File": "Datoteka",
    "Records": "Zapisi",
    "Status": "Status",
    "Type": "Vrsta",
    "Error": "Greška",
    "OK": "OK",
    "Partial": "Djelomično",
    "Drop files here or click to select": "Ispustite datoteke ovdje ili kliknite za odabir",
    "DDD / TGD / other tachograph files": "DDD / TGD / ostale tahograf datoteke",
    "Select tachograph file": "Odaberite tahograf datoteku",
    "No imports yet": "Još nema uvoza",
    "Import a tachograph file to see the history": "Uvezite tahograf datoteku za prikaz povijesti",

    # maint_analytics section
    "Fleet maintenance costs and trends": "Troškovi održavanja i trendovi",
    "Maintenance Analytics": "Analitika održavanja",
    "Cost per Month": "Trošak mjesečno",
    "Cost per Year": "Trošak godišnje",
    "Total Cost": "Ukupni trošak",
    "All": "Sve",
    "Truck": "Kamion",

    # maint_timeline section
    "Maintenance Timeline": "Vremenska crta održavanja",
    "Add Entry": "Dodaj unos",
    "Date": "Datum",
    "KM": "KM",
    "Type": "Vrsta",
    "Cost": "Trošak",
    "Description": "Opis",
    "No Entries": "Nema unosa",

    # client section
    "Billed": "Fakturirano",
    "Paid": "Plaćeno",
    "Unpaid": "Neplaćeno",
    "Overdue": "Prekoračeno",
    "Name": "Ime",
    "Contact Person": "Kontakt osoba",
    "Phone": "Telefon",
    "Email": "E-pošta",
    "Trips": "Ture",
    "Revenue": "Prihod",
    "Outstanding": "Nenaplaćeno",
    "Invoice #": "Račun #",
    "Amount": "Iznos",
    "Due Date": "Datum dospijeća",
    "Client Name *": "Ime klijenta *",
    "Contact Person": "Kontakt osoba",
    "Phone": "Telefon",
    "Email": "E-pošta",
    "Address": "Adresa",
    "VAT Number": "PDV broj",
    "Notes": "Bilješke",
    "Clients": "Klijenti",
    "New Client": "Novi klijent",
    "Edit": "Uredi",
    "Deactivate": "Deaktiviraj",
    "Deactivate '{name}'?": "Deaktivirati '{name}'?",
    "\n({count} trip(s) linked — trips will be preserved)": "\n({count} povezanih tura — ture će biti sačuvane)",
    "Edit Client": "Uredi klijenta",
    "New Client": "Novi klijent",
    "Save": "Spremi",
    "Name is required.": "Ime je obavezno.",
    "Client '{name}' already exists.": "Klijent '{name}' već postoji.",
    "Select a client to view details": "Odaberite klijenta za prikaz detalja",
    "Show All": "Prikaži sve",
    "Recent Trips": "Nedavne ture",
    "Outstanding Invoices": "Nenaplaćeni računi",
    "No trips found for this client.": "Nema pronađenih tura za ovog klijenta.",
    "No outstanding invoices for this client.": "Nema nenaplaćenih računa za ovog klijenta.",
    "Total Revenue": "Ukupni prihod",
    "Total Trips": "Ukupno tura",
    "Total Distance": "Ukupna udaljenost",
    "Trips (30d)": "Ture (30d)",
    "Total Profit": "Ukupna dobit",
    "Avg Profit/Trip": "Prosječna dobit/tura",
    "Outstanding": "Nenaplaćeno",
    "Last Trip": "Zadnja tura",
    "Contacts": "Kontakti",
    "Tags": "Oznake",
    "Revenue Trend": "Trend prihoda",
    "Activity Timeline": "Vremenska crta aktivnosti",
    "Payment Summary": "Sažetak plaćanja",
    "Client Type": "Vrsta klijenta",
    "Payment Terms (days)": "Uvjeti plaćanja (dani)",
    "Credit Limit (EUR)": "Kreditni limit (EUR)",
    "Default Rate/km": "Zadana stopa/km",
    "Rating (1-5)": "Ocjena (1-5)",
    "Full Name *": "Puno ime *",
    "Job Title": "Naziv radnog mjesta",
    "Contact Type": "Vrsta kontakta",
    "Add tag...": "Dodaj oznaku...",
    "No tags assigned.": "Nema dodijeljenih oznaka.",
    "No client data to export.": "Nema podataka o klijentima za izvoz.",
    "Clients exported successfully.": "Klijenti uspješno izvezeni.",
    "Export CSV": "Izvezi CSV",
    "Merge": "Spoji",
    "Merge Clients": "Spoji klijente",
    "Merge from: {name}": "Spoji iz: {name}",
    "Into target client:": "U ciljnog klijenta:",
    "All trips, invoices, contacts and tags will be moved to the target client. The source client will be deactivated. This cannot be undone.": "Sve ture, računi, kontakti i oznake bit će premješteni na ciljnog klijenta. Izvorni klijent bit će deaktiviran. Ovo se ne može poništiti.",
    "Merge all data from '{source}' into '{target}'?": "Spojiti sve podatke iz '{source}' u '{target}'?",
    "Execute Merge": "Izvrši spajanje",
    "New Contact": "Novi kontakt",
    "Edit Contact": "Uredi kontakt",
    "Delete this contact?": "Izbrisati ovaj kontakt?",
    "Add Contact": "Dodaj kontakt",
    "KPIs": "KPI",
    "Details": "Detalji",
    "Trips": "Ture",
    "Invoices": "Računi",
    "Revenue": "Prihod",
    "VAT:": "PDV:",
    "Terms: {} days": "Uvjeti: {} dana",
    "Limit: €{:,}": "Limit: €{:,}",
    "Trip: {} — {} / {} — {} km": "Tura: {} — {} / {} — {} km",
    "Invoice: {} — {} — {} EUR ({})": "Račun: {} — {} — {} EUR ({})",

    # docs section
    "DOCUMENT CENTER": "CENTAR DOKUMENATA",
    "UPLOAD": "UČITAJ",
    "Select files to upload": "Odaberite datoteke za učitavanje",
    "View": "Pregled",
    "Delete": "Izbriši",
    "Delete Document": "Izbriši dokument",
    "Delete '{name}'?\nThis will remove the file and all its links.": "Izbrisati '{name}'?\nOvo će ukloniti datoteku i sve njezine veze.",
    "Search documents...": "Pretraži dokumente...",
    "Select a document to see details": "Odaberite dokument za prikaz detalja",
    "No documents found": "Nema pronađenih dokumenata",
    "<": "<",
    ">": ">",
    "All": "Sve",
    "Maintenance": "Održavanje",
    "Invoices": "Računi",
    "Other": "Ostalo",
    "Newest first": "Najnovije prvo",
    "Oldest first": "Najstarije prvo",
    "Name A-Z": "Naziv A-Z",
    "Name Z-A": "Naziv Z-A",
    "Largest first": "Najveće prvo",
    "Smallest first": "Najmanje prvo",
    "Filters": "Filteri",
    "Apply Filters": "Primijeni filtere",
    "Clear Filters": "Očisti filtere",
    "Entity type:": "Vrsta entiteta:",
    "From date:": "Od datuma:",
    "To date:": "Do datuma:",
    "File type:": "Vrsta datoteke:",
    "Details": "Detalji",
    "Tags:": "Oznake:",
    "Add tag...": "Dodaj oznaku...",
    "Linked to:": "Povezano s:",
    "Email": "E-pošta",
    "Send document via email": "Pošalji dokument e-poštom",
    "Recipient email address:": "Adresa e-pošte primatelja:",
    "Email sent successfully.": "E-pošta uspješno poslana.",
    "Download as ZIP": "Preuzmi kao ZIP",
    "Archive": "Arhiviraj",
    "Unlink": "Odveži",
    "Delete Selected": "Izbriši odabrano",
    "Select All": "Odaberi sve",
    "Expiry date:": "Datum isteka:",
    "Set": "Postavi",
    "Versions:": "Verzije:",
    "Restore": "Vrati",
    "Upload new version": "Učitaj novu verziju",
    "Restore Version": "Vrati verziju",
    "Restore version {v}? Current version will be replaced.": "Vratiti verziju {v}? Trenutna verzija bit će zamijenjena.",
    "Create Contract": "Kreiraj ugovor",
    "Contract type:": "Vrsta ugovora:",
    "Generate CMR": "Generiraj CMR",
    "Expiry date saved": "Datum isteka spremljen",
    "Comment": "Komentar",
    "Version error": "Greška verzije",
    "Version uploaded": "Verzija učitana",
    "Date range:": "Raspon datuma:",
    "Invalid document data.": "Neispravni podaci dokumenta.",
    "Link to trip…": "Poveži s turom...",
    "Document linked to trip.": "Dokument povezan s turom.",
    "Already linked.": "Već povezano.",
    "Extracted": "Izdvojeno",
    "Last run": "Zadnje pokretanje",
    "OCR has not been run on this document yet.": "OCR još nije pokrenut na ovom dokumentu.",
    "OCR": "OCR",
    "No trips match your filter.": "Nema tura koje odgovaraju vašem filteru.",
    "Type to filter…": "Upišite za filtriranje...",
    "Search:": "Pretraži:",
    "Pick a trip": "Odaberi turu",
    "Re-run OCR": "Ponovno pokreni OCR",
    "OCR complete": "OCR dovršen",
    "OCR started…": "OCR pokrenut...",
    "Select": "Odaberi",
    "Documents": "Dokumenti",
    "Proforma": "Profaktura",
    "Proformas": "Profakture",
    "Receipts": "Potvrde",
    "Documents — {title}": "Dokumenti — {title}",
    "Entity Documents": "Dokumenti entiteta",

    # generators section
    "Document Generators": "Generatori dokumenata",
    "Create invoices and international CMR waybills for your trips.": "Kreirajte račune i međunarodne CMR teretnice za vaše ture.",
    "Trip:": "Tura:",
    "Invoice": "Račun",
    "Generate a professional PDF invoice for the selected trip.": "Generirajte profesionalni PDF račun za odabranu turu.",
    "CMR Waybill": "CMR teretnica",
    "Generate an international road consignment note (CMR) with all 4 copies.": "Generirajte međunarodni CMR teretni list sa svim 4 kopije.",
    "Invoice": "Račun",
    "CMR": "CMR",
    "Generate CMR Waybill": "Generiraj CMR teretnicu",
    "Create an international CMR waybill for a selected trip.": "Kreirajte međunarodnu CMR teretnicu za odabranu turu.",
    "1. Select Trip:": "1. Odaberite turu:",
    "2. Optional Overrides:": "2. Opcionalna preglasavanja:",
    "Loading Address:": "Adresa utovara:",
    "Unloading Address:": "Adresa istovara:",
    "Driver Name:": "Ime vozača:",
    "Generate CMR": "Generiraj CMR",
    "Open PDF": "Otvori PDF",
    "CMR generated: {path}": "CMR generiran: {path}",
    "All copies generated: {path}": "Sve kopije generirane: {path}",
    "Please select a trip first.": "Prvo odaberite turu.",
    "CMR generation failed: {error}": "Generiranje CMR-a nije uspjelo: {error}",
    "Primary Language": "Primarni jezik",
    "Secondary Language": "Sekundarni jezik",
    "Consignment Parties": "Stranke pošiljke",
    "Transport Details": "Detalji prijevoza",
    "Cargo Details": "Detalji tereta",
    "Instructions & Reservations": "Upute i rezervacije",
    "ADR Dangerous Goods": "ADR opasni tereti",
    "Successive Carriers": "Uzastopni prijevoznici",
    "Signature & Stamp": "Potpis i pečat",
    "Generate All 4 Copies": "Generiraj sve 4 kopije",
    "Generate Single Copy": "Generiraj jednu kopiju",
    "Sender Copy": "Kopija pošiljatelja",
    "Consignee Copy": "Kopija primatelja",
    "Carrier Copy": "Kopija prijevoznika",
    "Administrative Copy": "Administrativna kopija",
    "not generated": "nije generirano",
    "Generated Copies": "Generirane kopije",
    "Options": "Opcije",
    "Actions": "Radnje",
    "Ready to generate.": "Spremno za generiranje.",
    "Generating 4 copies...": "Generiranje 4 kopije...",
    "Open": "Otvori",
    "generated": "generirano",
    "CMR Trip #{}": "CMR tura #{}",
    "CMR Trip #{} - {} COPY": "CMR tura #{} - {} KOPIJA",
    "Receipt": "Potvrda",

    # invoice_editor section
    "Client:": "Klijent:",
    "Trip:": "Tura:",
    "Auto-Fill": "Automatsko popunjavanje",
    "From": "Od",
    "Bill To": "Primatelj računa",
    "Invoice #": "Račun #",
    "Issue Date": "Datum izdavanja",
    "Due Date": "Datum dospijeća",
    "Payment Terms": "Uvjeti plaćanja",
    "Description": "Opis",
    "Amount": "Iznos",
    "Qty": "Kol.",
    "Unit Price": "Jedinična cijena",
    "Tax Rate": "Porezna stopa",
    "Tax%": "Porez%",
    "Total": "Ukupno",
    "Add Row": "Dodaj red",
    "Remove": "Ukloni",
    "Duplicate": "Dupliciraj",
    "Move Up": "Pomakni gore",
    "Move Down": "Pomakni dolje",
    "Notes": "Bilješke",
    "Subtotal": "Podzbroj",
    "Tax": "Porez",
    "Discount": "Popust",
    "Grand Total": "Sveukupno",
    "Financial Controls": "Financijske kontrole",
    "Tax Preset": "Predložak poreza",
    "Discount Type": "Vrsta popusta",
    "Discount Value": "Vrijednost popusta",
    "Currency": "Valuta",
    "Branding": "Brendiranje",
    "Logo": "Logotip",
    "Color": "Boja",
    "Signature": "Potpis",
    "Stamp": "Pečat",
    "Upload": "Učitaj",
    "Pick": "Odaberi",
    "Choose Company Color": "Odaberi boju tvrtke",
    "Preview": "Pregled",
    "Generate PDF": "Generiraj PDF",
    "Print": "Ispis",
    "Email": "E-pošta",
    "Save Draft": "Spremi nacrt",
    "Load Draft": "Učitaj nacrt",
    "Cancel": "Odustani",
    "Percentage": "Postotak",
    "Fixed": "Fiksno",
    "Net 30": "Neto 30",
    "Net 15": "Neto 15",
    "Net 60": "Neto 60",
    "Due on Receipt": "Plaćanje po primitku",
    "Select Logo Image": "Odaberite sliku logotipa",
    "Select Signature Image": "Odaberite sliku potpisa",
    "Select Stamp Image": "Odaberite sliku pečata",
    "Invoice generated: {}": "Račun generiran: {}",
    "Draft Saved": "Nacrt spremljen",
    "Draft '{}' saved successfully.": "Nacrt '{}' uspješno spremljen.",
    "Draft Loaded": "Nacrt učitana",
    "Draft '{}' loaded successfully.": "Nacrt '{}' uspješno učitana.",
    "No drafts found.": "Nema pronađenih nacrta.",
    "Enter a name for this draft:": "Unesite naziv za ovaj nacrt:",
    "Transport services": "Usluge prijevoza",
    "Recipient Email": "E-pošta primatelja",
    "Enter recipient email address:": "Unesite adresu e-pošte primatelja:",
    "Trip Details": "Detalji ture",
    "Loading Stops": "Stajališta utovara",
    "Unloading Stops": "Stajališta istovara",
    "Loading": "Utovar",
    "Unloading": "Istovar",
    "Add Loading Stop": "Dodaj stajalište utovara",
    "Add Unloading Stop": "Dodaj stajalište istovara",
    "Distance": "Udaljenost",
    "Truck Plate": "Registarska oznaka",
    "Driver": "Vozač",
    "Browse": "Pretraži",
    "Invoice Editor": "Uređivač računa",
    "Totals": "Zbrojevi",
    "Line Items": "Stavke",
    "Notes": "Bilješke",
    "Invoice Details": "Detalji računa",
    "Invoice Metadata": "Metapodaci računa",
    "Client Info": "Informacije o klijentu",
    "Create and edit professional invoices": "Kreirajte i uređujte profesionalne račune",
    "Export JSON": "Izvezi JSON",
    "Branch / Office": "Podružnica / Ured",
    "Number Format": "Format broja",

    # proforma_editor section
    "Proforma Invoice Editor": "Uređivač profakture",
    "Create and manage proforma invoices": "Kreirajte i upravljajte profakturama",
    "Client:": "Klijent:",
    "Client Mode": "Način rada za klijenta",
    "Internal Mode": "Interni način rada",
    "Proforma Details": "Detalji profakture",
    "Proforma #": "Profaktura #",
    "Issue Date": "Datum izdavanja",
    "Valid Until": "Vrijedi do",
    "Payment Terms": "Uvjeti plaćanja",
    "Client Info": "Informacije o klijentu",
    "From": "Od",
    "Bill To": "Primatelj računa",
    "Description": "Opis",
    "Line Items": "Stavke",
    "Add Row": "Dodaj red",
    "Qty": "Kol.",
    "Unit Price": "Jedinična cijena",
    "Total": "Ukupno",
    "Tax Rate": "Porezna stopa",
    "Discount": "Popust",
    "Percentage": "Postotak",
    "Fixed": "Fiksno",
    "Currency": "Valuta",
    "Subtotal": "Podzbroj",
    "Tax": "Porez",
    "Grand Total": "Sveukupno",
    "Financial Controls": "Financijske kontrole",
    "Branding": "Brendiranje",
    "Logo": "Logotip",
    "Color": "Boja",
    "Signature": "Potpis",
    "Stamp": "Pečat",
    "Browse": "Pretraži",
    "Pick": "Odaberi",
    "Choose Company Color": "Odaberi boju tvrtke",
    "Notes": "Bilješke",
    "Linked Documents": "Povezani dokumenti",
    "Link Document": "Poveži dokument",
    "Unlink": "Odveži",
    "Select Document": "Odaberi dokument",
    "Select": "Odaberi",
    "Cancel": "Odustani",
    "Save": "Spremi",
    "Auto-Fill from Doc": "Automatsko popunjavanje iz dokumenta",
    "No extractable text in the selected document.": "Nema teksta za izdvajanje u odabranom dokumentu.",
    "Fields auto-filled from linked document.": "Polja automatski popunjena iz povezanog dokumenta.",
    "Linked document has text but no structured data. Manual entry required.": "Povezani dokument ima tekst, ali nema strukturiranih podataka. Potreban je ručni unos.",
    "No documents available to link.": "Nema dostupnih dokumenata za povezivanje.",
    "Please add at least one line item.": "Dodajte barem jednu stavku.",
    "Preview": "Pregled",
    "Generate PDF": "Generiraj PDF",
    "Print": "Ispis",
    "Email": "E-pošta",
    "Recipient Email": "E-pošta primatelja",
    "Enter recipient email address:": "Unesite adresu e-pošte primatelja:",
    "Send proforma via email?": "Poslati profakturu e-poštom?",
    "Include linked CMRs and invoices": "Uključi povezane CMR-ove i račune",
    "Email sent successfully.": "E-pošta uspješno poslana.",
    "Failed to send email.": "Slanje e-pošte nije uspjelo.",
    "Save Draft": "Spremi nacrt",
    "Load Draft": "Učitaj nacrt",
    "Enter a name for this draft:": "Unesite naziv za ovaj nacrt:",
    "Draft Saved": "Nacrt spremljen",
    "Draft '{}' saved successfully.": "Nacrt '{}' uspješno spremljen.",
    "Failed to save draft.": "Spremanje nacrta nije uspjelo.",
    "No drafts found.": "Nema pronađenih nacrta.",
    "Load": "Učitaj",
    "Success": "Uspjeh",
    "Error": "Greška",
    "Proforma generated: {}": "Profaktura generirana: {}",
    "Edit Company Info": "Uredi podatke tvrtke",
    "Net 30": "Neto 30",
    "Net 15": "Neto 15",
    "Net 60": "Neto 60",
    "Due on Receipt": "Plaćanje po primitku",
    "Select Logo Image": "Odaberite sliku logotipa",
    "Select Signature Image": "Odaberite sliku potpisa",
    "Select Stamp Image": "Odaberite sliku pečata",
    "Export JSON": "Izvezi JSON",
    "Number Format": "Format broja",

    # receipt section
    # ... many receipt keys, but most are already using labels. Let me focus on the ones that match English
    "Customer": "Klijent",
    "Vehicle": "Vozilo",
    "Trailer": "Prikolica",

    # dashboard period options
    "All history": "Sva povijest",
    "Last week": "Prošli tjedan",
    "Current month": "Trenutni mjesec",
    "Specific year": "Određena godina",
    "Custom": "Prilagođeno",

    # format strings
    "[{type}] {msg}": "[{type}] {msg}",
    "#{id} {truck_number} — {client_name} [{created_at}]": "#{id} {truck_number} — {client_name} [{created_at}]",
    "tkintermapview not installed.\nRun: pip install tkintermapview": "tkintermapview nije instaliran.\nPokrenite: pip install tkintermapview",
    "{hours:.1f}h/{max_h}h": "{hours:.1f}h/{max_h}h",
    "Weekly hours exceeded ({hours:.1f}h/{max_h}h)": "Tjedni sati prekoračeni ({hours:.1f}h/{max_h}h)",
    "{n} documents deleted": "{n} dokumenata izbrisano",
    "Document deleted": "Dokument izbrisan",
    "Downloaded as ZIP": "Preuzeto kao ZIP",
    "Document emailed": "Dokument poslan e-poštom",
    "New version added": "Nova verzija dodana",
    "Version restored": "Verzija vraćena",
    "All Files": "Sve datoteke",
    "Images": "Slike",
    "Upload Error": "Greška pri učitavanju",
    "Extracted Fields": "Izdvojena polja",
    "File too large": "Datoteka je prevelika",
    "Maximum upload size is 50 MB.": "Maksimalna veličina učitavanja je 50 MB.",
    "Uploading...": "Učitavanje...",
    "Upload complete. Document #{id}": "Učitavanje dovršeno. Dokument #{id}",
    "Fetching OCR results...": "Dohvaćanje OCR rezultata...",
    "OCR complete.": "OCR dovršen.",

    # home/features section
    "Intelligent Route Planning": "Inteligentno planiranje ruta",
    "Optimize routes in seconds with advanced algorithms that consider distance, traffic, fuel costs, and delivery windows.": "Optimizirajte rute u sekundama naprednim algoritmima koji uzimaju u obzir udaljenost, promet, troškove goriva i vremenske prozore isporuke.",
    "Real-Time Fleet Tracking": "Praćenje voznog parka u stvarnom vremenu",
    "Monitor every vehicle in your fleet with live GPS tracking, geofencing, and instant alerts.": "Nadzirite svako vozilo u vašem voznom parku GPS praćenjem uživo, geofencingom i trenutnim upozorenjima.",
    "Smart Dispatch": "Pametni dispečing",
    "Assign jobs automatically based on driver availability, truck status, and proximity.": "Automatski dodjeljujte poslove na temelju dostupnosti vozača, statusa kamiona i blizine.",
    "OCR Document Processing": "OCR obrada dokumenata",
    "Scan and digitize invoices, CMRs, and receipts with AI-powered OCR.": "Skenirajte i digitalizirajte račune, CMR-ove i potvrde OCR-om pokretanim umjetnom inteligencijom.",
    "Advanced Analytics": "Napredna analitika",
    "Gain actionable insights with dashboards, KPIs, and customizable reports.": "Dobijte korisne uvide putem nadzornih ploča, KPI-jeva i prilagodljivih izvješća.",
    "Driver Management": "Upravljanje vozačima",
    "Manage driver profiles, licenses, medical certificates, and performance.": "Upravljajte profilima vozača, dozvolama, liječničkim potvrdama i učinkom.",
    "Reduce Operational Costs": "Smanjite operativne troškove",
    "Cut fuel consumption by up to 20%% with optimized routing, reduce idle time, and minimize maintenance costs.": "Smanjite potrošnju goriva do 20%% optimiziranim rutama, smanjite vrijeme mirovanja i minimizirajte troškove održavanja.",
    "Increase Delivery Speed": "Povećajte brzinu isporuke",
    "Complete more deliveries per day with intelligent route optimization and real-time traffic avoidance.": "Ostvarite više isporuka dnevno inteligentnom optimizacijom ruta i izbjegavanjem prometa u stvarnom vremenu.",
    "Eliminate Paperwork": "Eliminirajte papirologiju",
    "Digitize all documents with OCR, automate invoicing, and go fully paperless.": "Digitalizirajte sve dokumente OCR-om, automatizirajte fakturiranje i postanite potpuno bez papira.",
    "Scale With Confidence": "Rastite s povjerenjem",
    "From 5 vehicles to 500, our platform grows with your business without missing a beat.": "Od 5 do 500 vozila, naša platforma raste s vašim poslovanjem bez zastoja.",
    "Operion transformed our operations. We cut route planning time by 80%% and fuel costs by 15%% in the first quarter.": "Operion je transformirao naše poslovanje. Smanjili smo vrijeme planiranja ruta za 80%% i troškove goriva za 15%% u prvom kvartalu.",
    "Mihai Popescu": "Mihai Popescu",
    "Fleet Manager, TransLogistic": "Voditelj voznog parka, TransLogistic",
    "Having real-time visibility into our fleet has been a game-changer. Our customers love the accurate ETAs.": "Vidljivost našeg voznog parka u stvarnom vremenu promijenila je pravila igre. Naši klijenti obožavaju točne ETA-e.",
    "Sarah Müller": "Sarah Müller",
    "Operations Director, EuroFreight": "Direktor operacija, EuroFreight",
    "We scaled from 10 to 50 vehicles without adding a single dispatcher. Operion's automation is incredible.": "Povećali smo se s 10 na 50 vozila bez dodavanja ijednog dispečera. Operionova automatizacija je nevjerojatna.",
    "John Smith": "John Smith",
    "CEO, Smith Logistics": "CEO, Smith Logistics",
    "Operion ERP — Enterprise Logistics, Simplified": "Operion ERP — Korporativna logistika, pojednostavljena",
    "Enterprise Logistics, Simplified": "Korporativna logistika, pojednostavljena",
    "Operion ERP gives your fleet the power to plan smarter, dispatch faster, and grow bigger.": "Operion ERP daje vašem voznom parku moć pametnijeg planiranja, bržeg dispečinga i većeg rasta.",
    "Start Free Trial": "Započnite besplatno probno razdoblje",
    "See How It Works": "Pogledajte kako radi",
    "Everything you need to run your fleet": "Sve što vam treba za upravljanje voznim parkom",
    "Powerful tools that work together to streamline every aspect of your logistics operations.": "Snažni alati koji zajedno rade na pojednostavljenju svakog aspekta vaših logističkih operacija.",
    "Built for real logistics results": "Izgrađeno za stvarne logističke rezultate",
    "Every feature is designed to solve a real problem our customers faced.": "Svaka značajka dizajnirana je za rješavanje stvarnog problema s kojim su se suočili naši klijenti.",
    "Trusted by logistics leaders": "Povjerenje logističkih lidera",
    "See how Operion is helping companies transform their logistics operations.": "Pogledajte kako Operion pomaže tvrtkama transformirati njihove logističke operacije.",
    "Our Mission": "Naša misija",
    "Our mission is to make enterprise logistics software accessible, powerful, and easy to use.": "Naša misija je učiniti korporativni logistički softver dostupnim, moćnim i jednostavnim za korištenje.",
    "Ready to Transform Your Logistics?": "Spremni za transformaciju vaše logistike?",
    "Join hundreds of companies that trust Operion to run their fleet operations.": "Pridružite se stotinama tvrtki koje vjeruju Operionu za upravljanje njihovim voznim parkom.",
    "Talk to Sales": "Razgovarajte s prodajom",

    # maint section
    "Due for Service": "Dospjelo za servis",
    "Cost (30d)": "Trošak (30d)",
    "Filter...": "Filter...",
    " km": " km",

    # tacho section
    "1. Driver inserts card into USB reader\n2. Export .DDD file using card reader software\n3. Import the .DDD file here": "1. Vozač umeće karticu u USB čitač\n2. Izvezite .DDD datoteku pomoću softvera čitača kartica\n3. Uvezite .DDD datoteku ovdje",
    "{label}: {value}": "{label}: {value}",

    # client section
    "Vehicles": "Vozila",

    # admin section
    "Admin Panel": "Admin ploča",
    "Admin authentication required": "Potrebna admin autentifikacija",
    "Admin Login": "Admin prijava",
    "Login": "Prijava",
    "Invalid email or password.": "Neispravna e-pošta ili lozinka.",
    "Cancel": "Odustani",
    "Email": "E-pošta",
    "Password": "Lozinka",
    "Email and password are required.": "E-pošta i lozinka su obavezni.",
    "Enter your email": "Unesite vašu e-poštu",
    "Please enter your email address.": "Molimo unesite vašu adresu e-pošte.",
    "Please enter a valid email address.": "Molimo unesite važeću adresu e-pošte.",
    "Please enter your password.": "Molimo unesite vašu lozinku.",
    "Next": "Dalje",
    "Back": "Natrag",
    "Diagnostics": "Dijagnostika",
    "Database Inspector": "Inspektor baze podataka",
    "Document Statistics": "Statistika dokumenata",
    "System Info": "Informacije o sustavu",
    "Health": "Zdravlje",
    "Latency": "Kašnjenje",
    "{value} ms": "{value} ms",
    "Celery Status": "Status Celeryja",
    "Redis Status": "Status Redisa",
    "Configuration": "Konfiguracija",
    "Active Tasks": "Aktivni zadaci",
    "Scheduled": "Zakazano",
    "Queue Size": "Veličina reda",
    "Workers Online": "Radnici na mreži",
    "Memory Used": "Iskorištena memorija",
    "Keys": "Ključevi",
    "Hit Rate": "Stopa pogodaka",
    "Unavailable": "Nedostupno",
    "Select table": "Odaberi tablicu",
    "Execute": "Izvrši",
    "Refresh": "Osvježi",
    "Clear Cache": "Očisti cache",
    "Cache cleared": "Cache očišćen",
    "{count} rows": "{count} redaka",
    "No data": "Nema podataka",
    "SELECT * FROM table LIMIT 100": "SELECT * FROM table LIMIT 100",
    "Server unreachable": "Poslužitelj nedostupan",
    "Total Documents": "Ukupno dokumenata",
    "Storage Used": "Iskorišteni prostor",
    "OCR Coverage": "OCR pokrivenost",
    "Orphan Documents": "Dokumenti bez veze",
    "Invalid query": "Neispravan upit",
    "Query error": "Greška upita",
    "Access denied": "Pristup odbijen",
    "Connected:": "Povezano:",
    "DB Engine:": "DB motor:",
    "Environment:": "Okruženje:",
    "API Version:": "API verzija:",
    "Debug Mode:": "Debug način:",
    "Python Version": "Python verzija",
    "DB Path": "PUT baze podataka",
    "Platform": "Platforma",
    "admin@example.com": "admin@primjer.com",
    "············": "············",

    # features section
    "Features - Operion ERP": "Značajke - Operion ERP",
    "Powerful Features for Modern Logistics": "Snažne značajke za modernu logistiku",
    "Everything you need to run your fleet efficiently, from route planning to analytics.": "Sve što vam je potrebno za učinkovito upravljanje voznim parkom, od planiranja ruta do analitike.",

    # about section
    "About - Operion ERP": "O nama - Operion ERP",
    "About Operion": "O Operionu",
    "We're building the future of enterprise logistics software.": "Gradimo budućnost korporativnog logističkog softvera.",
    "Our Story": "Naša priča",
    "Operion was founded in 2024 with a clear mission: make enterprise-grade logistics software accessible to fleets of all sizes.": "Operion je osnovan 2024. s jasnom misijom: učiniti korporativni logistički softver dostupnim voznim parkovima svih veličina.",
    "Our team combines decades of experience in logistics, software engineering, and AI to build tools that solve real-world problems.": "Naš tim kombinira desetljeća iskustva u logistici, softverskom inženjerstvu i AI-u za izgradnju alata koji rješavaju stvarne probleme.",
}


CRO_CHARS = set('čćšžđČĆŠŽĐ')

def is_croatian_text(val):
    """Detect if a string is already in Croatian."""
    if not isinstance(val, str):
        return False
    if not val.strip():
        return False
    # Contains Croatian-specific characters
    if CRO_CHARS & set(val):
        return True
    v = val.lower().strip(':,.()[]!?%')
    # Split into words, clean them
    words = [w.strip('.:(),{}[]%""\'"" ') for w in v.split()]
    # Croatian common words (comprehensive list)
    cro_words = {
        'iznos', 'kategorija', 'aktivan', 'model', 'godina', 'inspekcija',
        'osiguranje', 'klijent', 'dobit', 'kamion', 'vozač', 'bruto', 'status',
        'izvezi', 'spremljen', 'napomene', 'telefon', 'limit', 'stajalište',
        'udaljenost', 'trajanje', 'prihod', 'trošak', 'ruta', 'plaća', 'gorivo',
        'cestarina', 'marža', 'ukupno', 'greška', 'upozorenje', 'potvrda',
        'pregled', 'dodaj', 'uredi', 'izbriši', 'spremi', 'odustani', 'poništi',
        'pretraga', 'vozilo', 'datum', 'opis', 'stajališta', 'neto', 'održavanje',
        'povijest', 'postavke', 'jezik', 'flota', 'tablica', 'oznaka', 'valuta',
        'dnevno', 'dodatni', 'planiranje', 'početka', 'izračunaj', 'unesite',
        'analize', 'podatke', 'stopa', 'goriva', 'sigurnost', 'upravljanje',
        'podacima', 'uvezeno', 'zapisa', 'automatske', 'sigurnosne', 'kopije',
        'poslovna', 'inteligencija', 'razdoblje', 'analize', 'osvježi',
        'mjesečni', 'prosječna', 'neplaćeni', 'aktivne', 'financijski', 'učinak',
        'najbolji', 'mjesec', 'centar', 'nema', 'evolucija', 'registarska',
        'kamiona', 'odustani', 'poništi', 'pronađi', 'brzo', 'spremi', 'trošak',
        'grafikoni', 'dodavanje', 'pretraga', 'odaberite', 'dodan', 'nije',
        'pronađen', 'detalji', 'obavezna', 'mora', 'biti', 'cijeli', 'broj',
        'neispravna', 'vrijednosti', 'brisanje', 'dodaj', 'izvozu',
        'upravljanje', 'voznim', 'parkom', 'dodaj', 'održavanje', 'vrsta',
        'podaci', 'ažurirani', 'operativno', 'fakturiranje', 'e-pošta',
        'brisanje', 'prikaži', 'rutu', 'povezanu', 'nema', 'odaberite',
        'unutar', 'aplikacije', 'dostupnih', 'sustavu', 'generiranje',
        'vizualne', 'analitike', 'omjer', 'prikazivanju', 'grafikona',
        'financijskih', 'nedovoljno', 'dodajte', 'više', 'prilagođeno',
        'pokušajte', 'kriterije', 'jedinstvene', 'nepoznata',
        'uspješan', 'uvoz', 'usluge', 'odabir', 'dostupno', 'povratak',
        'blokirano', 'istekla', 'prekoračeni', 'servisu', 'dostupnosti',
        'otkazano', 'današnji', 'sažetak', 'polazi', 'dolazi', 'odabrano',
        'dodijeli', 'predloženi', 'vraćeno', 'ponovljeno', 'prikazano',
        'neraspoređene', 'potpisa', 'prihvaćen', 'očišćeno', 'odaberite',
        'otvori', 'kalendar', 'odaberi', 'prikaži', 'raspored',
        'planer', 'pametna', 'isključene', 'izračunavanje', 'obrada',
        'izračuna', 'metapodaci', 'izvezeni', 'očisti', 'odabrano',
        'ništa', 'nije', 'planirajte', 'procjenom', 'podijelite', 'drugima',
        'poveznica', 'kopiraj', 'datoteku', 'spremi', 'otvori', 'mapu',
        'kopirano', 'međuspremnik', 'nedostupan', 'udaljenost', 'trajanje',
        'stranica', 'preostalo', 'zaglavlje', 'bilješke', 'dobavljač',
        'izvrsno', 'dobro', 'zakazano', 'kopirana', 'kopiran',
        'predviđanja', 'dodavanja', 'uređivanja', 'zdravlje',
        'ponavljajući', 'problemi', 'interval', 'kilometraža',
        'sljedeći', 'zastoj', 'filter', 'mjeseci',
        'dnevni', 'prosjek', 'kalibracije', 'aktivnost', 'tahografa',
        'istječe', 'datoteka', 'povijest', 'sada', 'tijeku',
        'zadnjih', 'dana', 'podataka', 'registriranih',
        'nedavni', 'prekršaji', 'odaberi', 'karticu', 'jedinicu',
        'istekao', 'važeći', 'ukupno', 'sati', 'kartica',
        'jedinica', 'prekršaji', 'izradite', 'profakture',
        'upravljajte', 'način', 'rada', 'vrijedi', 'porezna',
        'klijenta', 'interni', 'profaktura', 'uključi',
        'kreirajte', 'uređujte', 'profesionalne', 'podružnica',
        'ured', 'formata', 'broja',
    }
    for w in words:
        w_clean = w.strip('.:(),{}[]%""\'"" ')
        if w_clean in cro_words:
            return True
    # Croatian suffixes
    cro_suffixes = ['čki', 'čka', 'čko', 'anje', 'enje', 'nje', 'ost', 'cija',
                    'ića', 'ač', 'ica', 'ilo', 'ana', 'eno', 'ovi', 'eva']
    for w in words:
        w_clean = w.strip('.:(),{}[]%""\'"" ')
        for sfx in cro_suffixes:
            if w_clean.endswith(sfx) and len(w_clean) > 3:
                return True
    return False

def should_translate(val):
    """Check if a string value should be translated (not an acronym-only string)."""
    if not isinstance(val, str):
        return False
    # Skip strings that are only acronyms
    words = val.split()
    if all(w.strip('.:(),{}[]%') in ACRONYMS for w in words if w.strip('.:(),{}[]%')):
        return False
    # Skip if already Croatian
    if is_croatian_text(val):
        return False
    return True


def translate_recursive(en_obj, hr_obj):
    """Recursively translate values in hr_obj where they match en_obj."""
    if isinstance(en_obj, dict) and isinstance(hr_obj, dict):
        result = {}
        for k in en_obj:
            if k in hr_obj:
                result[k] = translate_recursive(en_obj[k], hr_obj[k])
            else:
                result[k] = en_obj[k] if isinstance(en_obj[k], (dict, list)) else en_obj[k]
        # Add keys that are in hr_obj but not in en_obj (keep them)
        for k in hr_obj:
            if k not in en_obj:
                result[k] = hr_obj[k]
        return result
    elif isinstance(en_obj, list) and isinstance(hr_obj, list):
        return [translate_recursive(e, h) if isinstance(e, (dict, list)) and isinstance(h, (dict, list))
                else translate_value(e, h)
                for e, h in zip(en_obj, hr_obj)]
    elif isinstance(en_obj, str) and isinstance(hr_obj, str):
        if en_obj == hr_obj and should_translate(en_obj):
            tr = TRANSLATIONS.get(en_obj)
            if tr:
                return tr
            # Try case-insensitive match
            for eng, cro in TRANSLATIONS.items():
                if eng.lower() == en_obj.lower():
                    return cro
            # Return the English value unchanged if no translation found
            print(f"  MISSING TRANSLATION: '{en_obj}'")
            return en_obj
        return hr_obj
    else:
        return hr_obj


def translate_value(en_val, hr_val):
    """Translate a leaf-level value."""
    if isinstance(en_val, str) and isinstance(hr_val, str):
        if en_val == hr_val and should_translate(en_val):
            tr = TRANSLATIONS.get(en_val)
            if tr:
                return tr
            for eng, cro in TRANSLATIONS.items():
                if eng.lower() == en_val.lower():
                    return cro
            print(f"  MISSING TRANSLATION: '{en_val}'")
            return en_val
    return hr_val


# Walk and collect all missing translations first
def find_missing(en_obj, hr_obj, path=''):
    """Find all values that are identical between en and hr."""
    missing = []
    if isinstance(en_obj, dict) and isinstance(hr_obj, dict):
        for k in en_obj:
            new_path = f'{path}.{k}' if path else k
            if k in hr_obj:
                missing.extend(find_missing(en_obj[k], hr_obj[k], new_path))
    elif isinstance(en_obj, list) and isinstance(hr_obj, list) and len(en_obj) == len(hr_obj):
        for i, (e, h) in enumerate(zip(en_obj, hr_obj)):
            missing.extend(find_missing(e, h, f'{path}[{i}]'))
    elif isinstance(en_obj, str) and isinstance(hr_obj, str):
        if en_obj == hr_obj and should_translate(en_obj):
            missing.append((path, en_obj))
    return missing

import sys
sys.stdout.reconfigure(encoding='utf-8')

print("Finding untranslated values...")
missing = find_missing(en, hr)
print(f"Untranslated (identical) values: {len(missing)}")
untranslated = []
for path, val in missing:
    if val not in TRANSLATIONS:
        found = False
        for eng, cro in TRANSLATIONS.items():
            if eng.lower() == val.lower():
                found = True
                break
        if not found:
            untranslated.append((path, val))
            print(f"  NEEDS TRANSLATION: {path} = \"{val}\"")

if not untranslated:
    print("  (All untranslated values have translations in the dictionary)")

print("\n--- Translating hr.json ---")
new_hr = translate_recursive(en, hr)

# Count what changed
def count_changes(old, new, path=''):
    changes = 0
    if isinstance(old, dict) and isinstance(new, dict):
        for k in old:
            np = f'{path}.{k}' if path else k
            if k in new:
                changes += count_changes(old[k], new[k], np)
    elif isinstance(old, list) and isinstance(new, list) and len(old) == len(new):
        for i, (o, n) in enumerate(zip(old, new)):
            changes += count_changes(o, n, f'{path}[{i}]')
    elif old != new:
        changes = 1
    return changes

changes = count_changes(hr, new_hr)
print(f"Values changed: {changes}")

# Write back
with open('data/translations/hr.json', 'w', encoding='utf-8') as f:
    json.dump(new_hr, f, ensure_ascii=False, indent=2)
    f.write('\n')

print("Done! Written to hr.json")

# Validate
with open('data/translations/hr.json', 'r', encoding='utf-8') as f:
    validated = json.load(f)

def count_missing(en_obj, hr_obj):
    c = 0
    if isinstance(en_obj, dict) and isinstance(hr_obj, dict):
        for k in en_obj:
            if k in hr_obj:
                c += count_missing(en_obj[k], hr_obj[k])
            else:
                print(f"  Key missing in hr: {k}")
    elif isinstance(en_obj, list) and isinstance(hr_obj, list) and len(en_obj) == len(hr_obj):
        for e, h in zip(en_obj, hr_obj):
            c += count_missing(e, h)
    elif isinstance(en_obj, str) and isinstance(hr_obj, str):
        if en_obj == hr_obj and should_translate(en_obj):
            return 1
    return c

remaining = count_missing(en, validated)
print(f"\nRemaining untranslated values: {remaining}")
if remaining == 0:
    print("SUCCESS: All translatable values have been translated!")
else:
    print(f"WARNING: {remaining} values still untranslated")
