#!/usr/bin/env python3
"""Add remaining missing translations to _el_translations.json"""
from __future__ import annotations

import json
import os

BASE = os.path.dirname(os.path.abspath(__file__))
TR_PATH = os.path.join(BASE, "data", "translations", "_el_translations.json")
MI_PATH = os.path.join(BASE, "data", "translations", "_missing.json")

with open(TR_PATH, "r", encoding="utf-8") as f:
    translations = json.load(f)

# Additional translations from missing list
additional = {
    # Separators and special chars
    "───────────────────────────────────────────────────────────": "───────────────────────────────────────────────────────────",
    "[{type}] {msg}": "[{type}] {msg}",
    "km": "χλμ",
    
    # CMR section labels (Romanian headers - keep as-is)
    "Boxes 3-5": "Πλαίσια 3-5",
    "Boxes 13-17": "Πλαίσια 13-17",
    "Boxes 1-2": "Πλαίσια 1-2",
    "Boxes 21-24": "Πλαίσια 21-24",
    "Boxes 18-19": "Πλαίσια 18-19",
    "Boxes 8-14": "Πλαίσια 8-14",
    "Boxes 6-7": "Πλαίσια 6-7",
    "+ Add ADR Entry": "+ Προσθήκη Καταχώρησης ADR",
    "Truck plate": "Πινακίδα φορτηγού",
    
    # Email and password labels
    "PASSWORD": "PASSWORD",
    "EMAIL": "EMAIL",
    "Email": "Ηλεκτρονικό Ταχυδρομείο",
    "Excel": "Excel",
    
    # Units
    " seconds": " δευτερόλεπτα",
    
    # Upload section
    "Upload & OCR": "Μεταφόρτωση & OCR",
    "Browse...": "Περιήγηση...",
    "Upload & Run OCR": "Μεταφόρτωση & Εκτέλεση OCR",
    "File too large": "Το αρχείο είναι πολύ μεγάλο",
    "Maximum upload size is 50 MB.": "Το μέγιστο μέγεθος μεταφόρτωσης είναι 50 MB.",
    "Uploading...": "Μεταφόρτωση...",
    "Upload complete. Document #{id}": "Η μεταφόρτωση ολοκληρώθηκε. Έγγραφο #{id}",
    "Fetching OCR results...": "Λήψη αποτελεσμάτων OCR...",
    "OCR complete.": "Το OCR ολοκληρώθηκε.",
    "Upload Error": "Σφάλμα Μεταφόρτωσης",
    "Extracted Fields": "Εξαγόμενα Πεδία",
    "Select Document": "Επιλογή Εγγράφου",
    "LOGISTICS ERP": "LOGISTICS ERP",
    "ERP": "ERP",
    
    # Admin section
    "Admin Panel": "Πίνακας Διαχειριστή",
    "Admin authentication required": "Απαιτείται έλεγχος ταυτότητας διαχειριστή",
    "Admin Login": "Σύνδεση Διαχειριστή",
    "Login": "Σύνδεση",
    "Invalid email or password.": "Μη έγκυρο email ή κωδικός πρόσβασης.",
    "Email and password are required.": "Το email και ο κωδικός πρόσβασης είναι υποχρεωτικά.",
    "Enter your email": "Εισαγάγετε το email σας",
    "Please enter your email address.": "Παρακαλώ εισαγάγετε τη διεύθυνση email σας.",
    "Please enter a valid email address.": "Παρακαλώ εισαγάγετε μια έγκυρη διεύθυνση email.",
    "Please enter your password.": "Παρακαλώ εισαγάγετε τον κωδικό πρόσβασής σας.",
    "Next": "Επόμενο",
    "Back": "Πίσω",
    "Diagnostics": "Διαγνωστικά",
    "Database Inspector": "Επιθεώρηση Βάσης Δεδομένων",
    "Document Statistics": "Στατιστικά Εγγράφων",
    "System Info": "Πληροφορίες Συστήματος",
    "Health": "Υγεία",
    "Latency": "Καθυστέρηση",
    "Celery Status": "Κατάσταση Celery",
    "Redis Status": "Κατάσταση Redis",
    "Configuration": "Διαμόρφωση",
    "Active Tasks": "Ενεργές Εργασίες",
    "Scheduled": "Προγραμματισμένες",
    "Queue Size": "Μέγεθος Ουράς",
    "Workers Online": "Εργάτες Σε Σύνδεση",
    "Memory Used": "Μνήμη που Χρησιμοποιείται",
    "Keys": "Κλειδιά",
    "Hit Rate": "Ποσοστό Επιτυχιών",
    "Unavailable": "Μη Διαθέσιμο",
    "Select table": "Επιλογή πίνακα",
    "Execute": "Εκτέλεση",
    "Clear Cache": "Εκκαθάριση Προσωρινής Μνήμης",
    "Cache cleared": "Η προσωρινή μνήμη εκκαθαρίστηκε",
    "No data": "Χωρίς δεδομένα",
    "SELECT * FROM table LIMIT 100": "SELECT * FROM table LIMIT 100",
    "Server unreachable": "Ο διακομιστής δεν είναι προσβάσιμος",
    "Total Documents": "Σύνολο Εγγράφων",
    "Storage Used": "Χώρος που Χρησιμοποιείται",
    "OCR Coverage": "Κάλυψη OCR",
    "Orphan Documents": "Ορφανά Έγγραφα",
    "Invalid query": "Μη έγκυρο ερώτημα",
    "Query error": "Σφάλμα ερωτήματος",
    "Access denied": "Πρόσβαση απορρίφθηκε",
    "Connected:": "Συνδεδεμένο:",
    "DB Engine:": "Μηχανή ΒΔ:",
    "Environment:": "Περιβάλλον:",
    "API Version:": "Έκδοση API:",
    "Debug Mode:": "Λειτουργία Εντοπισμού Σφαλμάτων:",
    "Python Version": "Έκδοση Python",
    "DB Path": "Διαδρομή ΒΔ",
    "Platform": "Πλατφόρμα",
    "admin@example.com": "admin@example.com",
    "············": "············",
    "×": "×",
    
    # Auth section
    "Sign In — Operion ERP": "Σύνδεση — Operion ERP",
    "Back to home": "Επιστροφή στην αρχική",
    "Welcome back": "Καλώς ήρθατε ξανά",
    "Sign in to your Operion account": "Συνδεθείτε στον λογαριασμό σας Operion",
    "you@company.com": "you@company.com",
    "Forgot password?": "Ξεχάσατε τον κωδικό;",
    "Enter your password": "Εισαγάγετε τον κωδικό πρόσβασής σας",
    "Hide password": "Απόκρυψη κωδικού",
    "Show password": "Εμφάνιση κωδικού",
    "Signing in…": "Σύνδεση…",
    "Sign in": "Σύνδεση",
    "Don't have an account?": "Δεν έχετε λογαριασμό;",
    "Sign up": "Εγγραφή",
    "Signed in successfully!": "Επιτυχής σύνδεση!",
    "Failed to sign in": "Αποτυχία σύνδεσης",
    "Please enter a valid email": "Παρακαλώ εισαγάγετε ένα έγκυρο email",
    "Password is required": "Ο κωδικός πρόσβασης είναι υποχρεωτικός",
    "Password must be at most 72 characters": "Ο κωδικός πρόσβασης πρέπει να είναι το πολύ 72 χαρακτήρες",
    "Create Account — Operion ERP": "Δημιουργία Λογαριασμού — Operion ERP",
    "Create your account": "Δημιουργήστε τον λογαριασμό σας",
    "Start your 14-day free trial": "Ξεκινήστε τη δωρεάν δοκιμή 14 ημερών",
    "Full Name": "Πλήρες Όνομα",
    "John Doe": "John Doe",
    "Company Name (optional)": "Επωνυμία Εταιρείας (προαιρετικό)",
    "Acme Inc.": "Acme Inc.",
    "At least 8 characters": "Τουλάχιστον 8 χαρακτήρες",
    "Confirm Password": "Επιβεβαίωση Κωδικού",
    "Repeat your password": "Επαναλάβετε τον κωδικό πρόσβασής σας",
    "Creating account…": "Δημιουργία λογαριασμού…",
    "Create account": "Δημιουργία λογαριασμού",
    "Already have an account?": "Έχετε ήδη λογαριασμό;",
    "Sign in": "Σύνδεση",
    "Account created successfully!": "Ο λογαριασμός δημιουργήθηκε με επιτυχία!",
    "Failed to create account": "Αποτυχία δημιουργίας λογαριασμού",
    "Name must be at least 2 characters": "Το όνομα πρέπει να έχει τουλάχιστον 2 χαρακτήρες",
    "Password must be at least 8 characters": "Ο κωδικός πρόσβασης πρέπει να έχει τουλάχιστον 8 χαρακτήρες",
    "Passwords don't match": "Οι κωδικοί δεν ταιριάζουν",
    "admin@example.com": "admin@example.com",
    "Operion": "Operion",
    
    # Features section
    "Features - Operion ERP": "Λειτουργίες - Operion ERP",
    "Powerful Features for Modern Logistics": "Ισχυρές Λειτουργίες για Σύγχρονα Logistics",
    "Everything you need to run your fleet efficiently, from route planning to analytics.": "Όλα όσα χρειάζεστε για να διαχειριστείτε αποτελεσματικά τον στόλο σας, από τον σχεδιασμό διαδρομών έως τις αναλύσεις.",
    "Route Planning & Optimization": "Σχεδιασμός & Βελτιστοποίηση Διαδρομών",
    "Intelligent Route Planning": "Ευφυής Σχεδιασμός Διαδρομών",
    "Advanced algorithms optimize for time, distance, fuel, and toll costs across Europe.": "Προηγμένοι αλγόριθμοι βελτιστοποιούν χρόνο, απόσταση, καύσιμα και διόδια σε όλη την Ευρώπη.",
    "Multi-Stop Optimization": "Βελτιστοποίηση Πολλαπλών Στάσεων",
    "Plan complex multi-stop routes with up to 50 waypoints and automated sequencing.": "Σχεδιάστε πολύπλοκες διαδρομές με έως 50 σημεία και αυτόματη αλληλουχία.",
    "Real-Time Traffic Integration": "Ενσωμάτωση Κυκλοφορίας σε Πραγματικό Χρόνο",
    "Routes adjust dynamically based on live traffic conditions and road closures.": "Οι διαδρομές προσαρμόζονται δυναμικά βάσει κυκλοφορίας και κλεισίματος δρόμων.",
    "Fleet Management": "Διαχείριση Στόλου",
    "Real-Time GPS Tracking": "Παρακολούθηση GPS σε Πραγματικό Χρόνο",
    "Monitor every vehicle's location, speed, and status on an interactive map.": "Παρακολουθήστε την τοποθεσία, ταχύτητα και κατάσταση κάθε οχήματος σε διαδραστικό χάρτη.",
    "Vehicle Maintenance Tracking": "Παρακολούθηση Συντήρησης Οχημάτων",
    "Schedule and track maintenance with automated alerts for inspections, insurance, and services.": "Προγραμματίστε και παρακολουθήστε συντήρηση με αυτοματοποιημένες ειδοποιήσεις.",
    "Geofencing & Alerts": "Γεωπερίφραξη & Ειδοποιήσεις",
    "Set geographic boundaries and receive instant notifications when vehicles enter or leave zones.": "Ορίστε γεωγραφικά όρια και λάβετε άμεσες ειδοποιήσεις.",
    "Dispatch & Operations": "Διανομή & Λειτουργίες",
    "Automated Job Assignment": "Αυτοματοποιημένη Ανάθεση Εργασιών",
    "Match jobs to the best available drivers and trucks based on location, skills, and compliance.": "Αντιστοιχίστε εργασίες με τους καλύτερους διαθέσιμους οδηγούς και φορτηγά.",
    "Digital Proof of Delivery": "Ψηφιακή Απόδειξη Παράδοσης",
    "Capture signatures, photos, and timestamps at delivery for complete proof of delivery.": "Καταγράψτε υπογραφές, φωτογραφίες και χρονοσφραγίδες κατά την παράδοση.",
    "Real-Time Status Updates": "Ενημερώσεις Κατάστασης σε Πραγματικό Χρόνο",
    "Track every job from assignment to completion with live status updates.": "Παρακολουθήστε κάθε εργασία από την ανάθεση έως την ολοκλήρωση.",
    "Document Management": "Διαχείριση Εγγράφων",
    "AI-Powered OCR": "OCR με Τεχνητή Νοημοσύνη",
    "Scan and digitize invoices, CMRs, receipts, and contracts with AI-powered OCR.": "Σαρώστε και ψηφιοποιήστε τιμολόγια, CMR, αποδείξεις και συμβόλαια με OCR.",
    "Digital Archive": "Ψηφιακό Αρχείο",
    "Store and search all documents with version history, tags, and full-text search.": "Αποθηκεύστε και αναζητήστε έγγραφα με ιστορικό εκδόσεων, ετικέτες και πλήρη αναζήτηση.",
    "Automated Invoicing": "Αυτοματοποιημένη Τιμολόγηση",
    "Generate invoices from delivery data automatically and email them to clients.": "Δημιουργήστε αυτόματα τιμολόγια από δεδομένα παράδοσης και στείλτε τα με email.",
    "Analytics & Reporting": "Αναλύσεις & Αναφορές",
    "Custom Dashboards": "Προσαρμοσμένοι Πίνακες Ελέγχου",
    "Build personalized views with KPIs, charts, and real-time data.": "Δημιουργήστε εξατομικευμένες προβολές με KPIs, γραφήματα και δεδομένα πραγματικού χρόνου.",
    "KPI Tracking": "Παρακολούθηση KPI",
    "Monitor key performance indicators including profit per mile, fuel efficiency, and driver performance.": "Παρακολουθήστε βασικούς δείκτες απόδοσης.",
    "Export & Integration": "Εξαγωγή & Ενσωμάτωση",
    "Export reports in multiple formats and integrate with your existing ERP and accounting software.": "Εξάγετε αναφορές σε πολλές μορφές και ενσωματώστε με ERP και λογιστικό λογισμικό.",
    "Driver Management": "Διαχείριση Οδηγών",
    "Driver Profiles": "Προφίλ Οδηγών",
    "Complete driver database with licenses, medical certificates, contracts, and documents.": "Πλήρης βάση δεδομένων οδηγών με άδειες, ιατρικά πιστοποιητικά, συμβόλαια και έγγραφα.",
    "Performance Tracking": "Παρακολούθηση Απόδοσης",
    "Monitor driver efficiency, safety scores, tachograph compliance, and driving hours.": "Παρακολουθήστε απόδοση οδηγού, βαθμολογίες ασφάλειας, συμμόρφωση ταχογράφου και ώρες οδήγησης.",
    "Schedule Management": "Διαχείριση Προγράμματος",
    "Plan driver shifts, manage availability, and track working hours.": "Προγραμματίστε βάρδιες οδηγών, διαχειριστείτε διαθεσιμότητα και παρακολουθήστε ώρες εργασίας.",
    
    # About section
    "About - Operion ERP": "Σχετικά - Operion ERP",
    "About Operion": "Σχετικά με το Operion",
    "We're building the future of enterprise logistics software.": "Χτίζουμε το μέλλον του λογισμικού εταιρικών logistics.",
    "Our Story": "Η Ιστορία Μας",
    "Operion was founded in 2024 with a clear mission: make enterprise-grade logistics software accessible to fleets of all sizes.": "Το Operion ιδρύθηκε το 2024 με ξεκάθαρη αποστολή: να κάνει λογισμικό logistics επιχειρηματικού επιπέδου προσβάσιμο σε στόλους όλων των μεγεθών.",
    "Our team combines decades of experience in logistics, software engineering, and AI to build tools that solve real-world problems.": "Η ομάδα μας συνδυάζει δεκαετίες εμπειρίας σε logistics, μηχανική λογισμικού και AI.",
    "Today, Operion powers fleets across Europe, helping them plan smarter, dispatch faster, and grow bigger.": "Σήμερα, το Operion υποστηρίζει στόλους σε όλη την Ευρώπη.",
    "Our Values": "Οι Αξίες Μας",
    "The principles that guide every decision we make.": "Οι αρχές που καθοδηγούν κάθε απόφασή μας.",
    "Customer First": "Ο Πελάτης Πρώτα",
    "Every feature we build starts with real customer needs and feedback.": "Κάθε λειτουργία ξεκινά από πραγματικές ανάγκες και σχόλια πελατών.",
    "Reliability": "Αξιοπιστία",
    "Your operations depend on our software. We take that responsibility seriously.": "Οι λειτουργίες σας εξαρτώνται από το λογισμικό μας. Παίρνουμε αυτή την ευθύνη στα σοβαρά.",
    "Innovation": "Καινοτομία",
    "We invest heavily in R&D to bring cutting-edge AI and optimization to logistics.": "Επενδύουμε σε Ε&Α για να φέρουμε αιχμής AI και βελτιστοποίηση στα logistics.",
    "Transparency": "Διαφάνεια",
    "Clear pricing, honest communication, and no hidden fees.": "Σαφής τιμολόγηση, ειλικρινής επικοινωνία και χωρίς κρυφά τέλη.",
    "Security": "Ασφάλεια",
    "Enterprise-grade encryption, GDPR compliance, and regular security audits.": "Κρυπτογράφηση επιχειρηματικού επιπέδου, συμμόρφωση GDPR και τακτικοί έλεγχοι ασφάλειας.",
    "Partnership": "Συνεργασία",
    "We don't just sell software. We partner with our customers for their success.": "Δεν πουλάμε απλώς λογισμικό. Συνεργαζόμαστε με τους πελάτες μας για την επιτυχία τους.",
    "Our Team": "Η Ομάδα Μας",
    
    # Home section
    "Past 30 Days": "Τελευταίες 30 Ημέρες",
    "Everything you need to run your fleet": "Όλα όσα χρειάζεστε για τον στόλο σας",
    "Powerful tools that work together to streamline every aspect of your logistics operations.": "Ισχυρά εργαλεία που συνεργάζονται για να βελτιστοποιήσουν κάθε πτυχή των logistics σας.",
    "Built for real logistics results": "Σχεδιασμένο για πραγματικά αποτελέσματα logistics",
    "Every feature is designed to solve a real problem our customers faced.": "Κάθε λειτουργία σχεδιάστηκε για να λύσει ένα πραγματικό πρόβλημα των πελατών μας.",
    "Trusted by logistics leaders": "Εμπιστεύονται ηγέτες των logistics",
    "See how Operion is helping companies transform their logistics operations.": "Δείτε πώς το Operion βοηθά εταιρείες να μετασχηματίσουν τις λειτουργίες logistics τους.",
    "Our Mission": "Η Αποστολή Μας",
    "Our mission is to make enterprise logistics software accessible, powerful, and easy to use.": "Η αποστολή μας είναι να κάνουμε το λογισμικό logistics προσιτό, ισχυρό και εύχρηστο.",
    "Ready to Transform Your Logistics?": "Έτοιμοι να Μεταμορφώσετε τα Logistics σας;",
    "Join hundreds of companies that trust Operion to run their fleet operations.": "Γίνετε μέλος εκατοντάδων εταιρειών που εμπιστεύονται το Operion.",
    "Operion ERP — Enterprise Logistics, Simplified": "Operion ERP — Enterprise Logistics, Απλοποιημένα",
    "Enterprise Logistics, Simplified": "Enterprise Logistics, Απλοποιημένα",
    "Operion ERP gives your fleet the power to plan smarter, dispatch faster, and grow bigger.": "Το Operion ERP δίνει στον στόλο σας τη δύναμη να σχεδιάζει πιο έξυπνα, να διανέμει ταχύτερα και να αναπτύσσεται περισσότερο.",
    "Start Free Trial": "Ξεκινήστε Δωρεάν Δοκιμή",
    "See How It Works": "Δείτε Πώς Λειτουργεί",
    "Talk to Sales": "Μιλήστε με Πωλήσεις",
    "Reduce Operational Costs": "Μειώστε τα Λειτουργικά Κόστη",
    "Cut fuel consumption by up to 20%% with optimized routing, reduce idle time, and minimize maintenance costs.": "Μειώστε την κατανάλωση καυσίμου έως 20%% με βελτιστοποιημένες διαδρομές.",
    "Increase Delivery Speed": "Αυξήστε την Ταχύτητα Παράδοσης",
    "Complete more deliveries per day with intelligent route optimization and real-time traffic avoidance.": "Ολοκληρώστε περισσότερες παραδόσεις ανά ημέρα με έξυπνη βελτιστοποίηση διαδρομών.",
    "Eliminate Paperwork": "Εξαλείψτε τη Γραφειοκρατία",
    "Digitize all documents with OCR, automate invoicing, and go fully paperless.": "Ψηφιοποιήστε όλα τα έγγραφα με OCR, αυτοματοποιήστε την τιμολόγηση και γίνετε εντελώς χωρίς χαρτί.",
    "Scale With Confidence": "Αναπτυχθείτε με Αυτοπεποίθηση",
    "From 5 vehicles to 500, our platform grows with your business without missing a beat.": "Από 5 έως 500 οχήματα, η πλατφόρμα μας αναπτύσσεται με την επιχείρησή σας.",
    "Operion transformed our operations. We cut route planning time by 80%% and fuel costs by 15%% in the first quarter.": "Το Operion μεταμόρφωσε τις λειτουργίες μας. Μειώσαμε τον χρόνο σχεδιασμού διαδρομών κατά 80%%.",
    "Mihai Popescu": "Mihai Popescu",
    "Fleet Manager, TransLogistic": "Διαχειριστής Στόλου, TransLogistic",
    "Having real-time visibility into our fleet has been a game-changer. Our customers love the accurate ETAs.": "Η παρακολούθηση σε πραγματικό χρόνο άλλαξε το παιχνίδι. Οι πελάτες μας λατρεύουν τις ακριβείς ΕΤΑ.",
    "Sarah Müller": "Sarah Müller",
    "Operations Director, EuroFreight": "Διευθύντρια Λειτουργιών, EuroFreight",
    "We scaled from 10 to 50 vehicles without adding a single dispatcher. Operion's automation is incredible.": "Αναπτυχθήκαμε από 10 σε 50 οχήματα χωρίς να προσθέσουμε ούτε έναν διακομιστή.",
    "John Smith": "John Smith",
    "CEO, Smith Logistics": "Διευθύνων Σύμβουλος, Smith Logistics",
    
    # Failed/success format strings
    "Failed to add user: {error}": "Αποτυχία προσθήκης χρήστη: {error}",
    "Failed to deactivate user: {error}": "Αποτυχία απενεργοποίησης χρήστη: {error}",
    "Fuel prices updated {minutes} ago": "Οι τιμές καυσίμων ενημερώθηκαν πριν από {minutes} λεπτά",
    
    # Misc
    "Net Profit (€)": "Καθαρό Κέρδος (€)",
    "Net": "Καθαρό",
    "Outstanding": "Εκκρεμεί",
    "CMRs": "CMRs",
    "Stamp": "Σφραγίδα",
    "Select Stamp Image": "Επιλογή Εικόνας Σφραγίδας",
    "Details": "Λεπτομέρειες",
    "Trips": "Διαδρομές",
    "Vehicles": "Οχήματα",
    "Resources": "Πόροι",
    "LIVE": "ΖΩΝΤΑΝΑ",
    "Document": "Έγγραφο",
    "<": "<",
    ">": ">",
    "Maintenance Timeline": "Χρονολόγιο Συντήρησης",
    "Next due at {km} km": "Επόμενη λήξη στα {km} χλμ",
    "0.00": "0.00",
    "{count} trip(s) linked — trips will be preserved": "{count} συνδεδεμένες διαδρομές — οι διαδρομές θα διατηρηθούν",
    "Clients exported successfully.": "Οι πελάτες εξήχθησαν με επιτυχία.",
    "Image files (*.png *.jpg *.jpeg *.bmp);;All files (*.*)": "Αρχεία εικόνας (*.png *.jpg *.jpeg *.bmp);;Όλα τα αρχεία (*.*)",
    "This is a test notification from the Operations Engine.": "Αυτή είναι μια δοκιμαστική ειδοποίηση από τη Μηχανή Λειτουργιών.",
    "#{id} {truck_number} — {client_name} [{created_at}]": "#{id} {truck_number} — {client_name} [{created_at}]",
    "Email": "Email",
    "EMAIL & SMTP": "EMAIL & SMTP",
    "07xx xxx xxx": "07xx xxx xxx",
    "J40/123/2023": "J40/123/2023",
    "contact@firma.ro": "contact@firma.ro",
    "RO12345678": "RO12345678",
    "CMR Trip #{}": "CMR Διαδρομή #{}",
    "CMR Trip #{} - {} COPY": "CMR Διαδρομή #{} - {} ΑΝΤΙΓΡΑΦΟ",
    "CMR Trip #{}": "CMR Διαδρομή #{}",
    "cmr_trip_title": "CMR Διαδρομή #{}",
    "cmr_copy_title": "CMR Διαδρομή #{} - {} ΑΝΤΙΓΡΑΦΟ",
    "Trip: {} — {} / {} — {} km": "Διαδρομή: {} — {} / {} — {} χλμ",
    "Invoice: {} — {} — {} EUR ({})": "Τιμολόγιο: {} — {} — {} EUR ({})",
    "📞": "📞",
    "✉": "✉",
    "🗑 Delete": "🗑 Διαγραφή",
    "Delete '{name}'?\nThis will remove the file and all its links.": "Διαγραφή '{name}';\nΑυτό θα αφαιρέσει το αρχείο και όλες τις συνδέσεις του.",
    "Weekly hours exceeded ({hours:.1f}h/{max_h}h)": "Υπέρβαση εβδομαδιαίων ωρών ({hours:.1f}ώ/{max_h}ώ)",
    "Select a driver first.": "Επιλέξτε πρώτα έναν οδηγό.",
    "Imported {} ({} bytes)": "Εισήχθη {} ({} bytes)",
    "Package saved to:\n{path}": "Πακέτο αποθηκεύτηκε στο:\n{path}",
    "Route #{a} vs #{b}\nDistance delta: {d_dist:+.1f} km\nDuration delta: {d_dur}\nProfiles: {p_a} / {p_b}": "Διαδρομή #{a} vs #{b}\nΔιαφορά απόστασης: {d_dist:+.1f} χλμ\nΔιαφορά διάρκειας: {d_dur}\nΠροφίλ: {p_a} / {p_b}",
    "Total routes: {count}\nTotal distance: {dist:.1f} km\nTop destinations: {dests}": "Σύνολο διαδρομών: {count}\nΣυνολική απόσταση: {dist:.1f} χλμ\nΚορυφαίοι προορισμοί: {dests}",
    "Page {current} of {total} ({count} routes)": "Σελίδα {current} από {total} ({count} διαδρομές)",
    "Route History": "Ιστορικό Διαδρομών",
    "1. Driver inserts card into USB reader\n2. Export .DDD file using card reader software\n3. Import the .DDD file here": "1. Ο οδηγός εισάγει την κάρτα στο USB\n2. Εξαγωγή αρχείου .DDD\n3. Εισαγωγή του αρχείου .DDD εδώ",
}

# Merge and save
translations.update(additional)
with open(TR_PATH, "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print(f"Added {len(additional)} translations. Total: {len(translations)}")
