uk = {
    "alerts.none_active": "Немає Активних",
    "alerts.panel_title": "Панель Сповіщень",
    "common.all": "Всі",
    "common.csv_filter": "CSV Фільтр",
    "common.currency_eur": "EUR",
    "common.from_date": "Від Дати",
    "common.id": "ID",
    "common.na": "Н/Д",
    "common.no": "Ні",
    "common.no_data": "Немає Даних",
    "common.status": "Статус",
    "common.to_date": "До Дати",
    "common.unknown": "Невідомо",
    "common.yes": "Так",
    "dispatch_board.alerts": "Сповіщення",
    "dispatch_board.assign_driver": "Призначити Водія",
    "dispatch_board.assign_truck": "Призначити Вантажівку",
    "dispatch_board.available_from": "Доступно з {next_slot}",
    "dispatch_board.confirm_backward": "Підтвердити переміщення поїздки #{trip_id} назад з {old_status} до {new_status}?",
    "dispatch_board.confirm_title": "Підтвердити Перехід",
    "dispatch_board.conflict_warning_title": "Попередження Конфлікту",
    "dispatch_board.delay_alert_message": "Поїздка #{trip_id} ({client}) затримується більш ніж на {hours} год.",
    "dispatch_board.delay_alert_title": "Затримка Поїздки #{trip_id}",
    "dispatch_board.delayed": "Затримано",
    "dispatch_board.driver_not_found": "Водія не знайдено.",
    "dispatch_board.hours_overdue": "{hours} год прострочено",
    "dispatch_board.load_error": "Помилка Завантаження",
    "dispatch_board.load_older": "Завантажити Старіші",
    "dispatch_board.loading": "Завантаження...",
    "dispatch_board.loading_options": "Завантаження опцій...",
    "dispatch_board.minutes_overdue": "{minutes} хв прострочено",
    "dispatch_board.no_options": "Немає Доступних Опцій",
    "dispatch_board.refresh": "Оновити",
    "dispatch_board.retry": "Повторити",
    "dispatch_board.select_driver": "Вибрати Водія",
    "dispatch_board.select_truck": "Вибрати Вантажівку",
    "dispatch_board.subtitle": "Панель Диспетчера",
    "dispatch_board.title": "Панель Диспетчера",
    "dispatch_board.transition_error": "Помилка переходу з {old_status} до {new_status}.",
    "dispatch_board.transition_success": "Успішно переміщено до статусу {new_status}.",
    "dispatch_board.trip_id_prefix": "#",
    "dispatch_board.truck_not_found": "Вантажівку не знайдено.",
    "dispatch_board.unavailable_overlap": "Недоступно: перекривається з поїздкою {trip_ref}",
    "dispatch_board.col_delivered": "Доставлено",
    "dispatch_board.col_in_transit": "В Дорозі",
    "dispatch_board.col_loading": "Завантаження",
    "dispatch_board.col_planned": "Заплановано",
    "driver_manager.add_driver": "Додати Водія",
    "driver_manager.cancel": "Скасувати",
    "driver_manager.col_active": "Активний",
    "driver_manager.col_hire_date": "Дата Найму",
    "driver_manager.col_id": "ID",
    "driver_manager.col_license": "Посвідчення",
    "driver_manager.col_license_expiry": "Термін Дії Посвідчення",
    "driver_manager.col_medical_expiry": "Термін Дії Медогляду",
    "driver_manager.col_name": "Ім'я",
    "driver_manager.col_phone": "Телефон",
    "driver_manager.col_salary": "Зарплата",
    "driver_manager.col_truck": "Вантажівка",
    "driver_manager.confirm_delete": "Ви впевнені, що хочете видалити цього водія?",
    "driver_manager.delete_driver": "Видалити Водія",
    "driver_manager.edit_driver": "Редагувати Водія",
    "driver_manager.export_csv": "Експорт CSV",
    "driver_manager.export_success": "Експорт виконано успішно.",
    "driver_manager.field_active": "Активний",
    "driver_manager.field_email": "Email",
    "driver_manager.field_hire_date": "Дата Найму",
    "driver_manager.field_license_category": "Категорія Посвідчення",
    "driver_manager.field_license_expiry": "Термін Дії Посвідчення",
    "driver_manager.field_license_number": "Номер Посвідчення",
    "driver_manager.field_medical_expiry": "Термін Дії Медогляду",
    "driver_manager.field_monthly_salary": "Місячна Зарплата",
    "driver_manager.field_name": "Ім'я",
    "driver_manager.field_notes": "Примітки",
    "driver_manager.field_phone": "Телефон",
    "driver_manager.kpi_expiring": "Закінчуються",
    "driver_manager.kpi_on_trip": "В Поїздці",
    "driver_manager.kpi_total": "Всього Водіїв",
    "driver_manager.kpi_unassigned": "Не Призначені",
    "driver_manager.no_driver_selected": "Виберіть водія",
    "driver_manager.save": "Зберегти",
    "driver_manager.search_placeholder": "Пошук...",
    "driver_manager.title": "Менеджер Водіїв",
    "driver_manager.toggle_active": "Перемкнути Активність",
    "driver_manager.unassigned": "Не Призначений",
    "fleet_dashboard.activity_title": "Активність Автопарку",
    "fleet_dashboard.activity_view_all": "Переглянути Все",
    "fleet_dashboard.card_avg_profit": "Середній Прибуток",
    "fleet_dashboard.card_best_driver": "Найкращий Водій",
    "fleet_dashboard.card_best_truck": "Найкраща Вантажівка",
    "fleet_dashboard.card_consumption": "Витрата Палива",
    "fleet_dashboard.card_fuel_cost": "Вартість Палива",
    "fleet_dashboard.card_highest_fuel": "Найбільша Витрата Палива",
    "fleet_dashboard.card_revenue": "Дохід",
    "fleet_dashboard.card_trips": "Поїздки",
    "fleet_dashboard.chart_fleet_status": "Статус Автопарку",
    "fleet_dashboard.chart_trip_activity": "Активність Поїздок",
    "fleet_dashboard.charts_unavailable": "Графіки Недоступні",
    "fleet_dashboard.date": "Дата",
    "fleet_dashboard.error_msg": "Помилка завантаження даних.",
    "fleet_dashboard.error_title": "Помилка",
    "fleet_dashboard.last_refreshed": "Останнє Оновлення",
    "fleet_dashboard.no_data": "Немає Даних",
    "fleet_dashboard.no_driver_data": "Немає Даних про Водіїв",
    "fleet_dashboard.refresh": "Оновити",
    "fleet_dashboard.status_active": "Активна",
    "fleet_dashboard.status_cancelled": "Скасовано",
    "fleet_dashboard.status_completed": "Завершено",
    "fleet_dashboard.status_idle": "Простоює",
    "fleet_dashboard.status_in_progress": "В Процесі",
    "fleet_dashboard.status_inactive": "Неактивна",
    "fleet_dashboard.status_maintenance": "На ТО",
    "fleet_dashboard.title": "Панель Автопарку",
    "fleet_dashboard.trips": "Поїздки",
    "fuel.age_hours": "{n} год тому",
    "fuel.age_minutes": "{n} хв тому",
    "fuel.age_seconds": "{n} сек тому",
    "fuel.no_data": "Немає Даних",
    "fuel.not_fetched": "Ще Не Отримано",
    "fuel.section_title": "Ціни на Паливо",
    "fuel.updated_status": "Оновлено: {ts} ({age})",
    "home.active_alerts": "Активні Сповіщення",
    "home.active_trips": "Активні Поїздки",
    "home.no_active_trips": "Немає Активних Поїздок",
    "home.no_alerts": "Немає Сповіщень",
    "home.profit_chart_title": "Прибуток за Минулий Місяць",
    "home.profit_data_source": "Дані автоматично імпортовано з Аналітики",
    "home.profit_day_label": "День",
    "home.profit_no_data": "Дані про прибуток ще недоступні.",
    "home.recent_activity": "Нещодавня Активність",
    "home.top_trucks": "Найкращі Вантажівки Цього Місяця",
    "form.duration": "Тривалість",
    "form.start_date": "Дата Початку",
    "form.status": "Статус",
    "form.truck": "Вантажівка",
    "tacho.avg_daily": "Сер. Щоденно",
    "tacho.calibration_date": "Дата Калібрування",
    "tacho.driver_activity_title": "Активність Тахографа",
    "tacho.expiry": "Закінчення",
    "tacho.how_it_works": "Виберіть файл .ddd нижче, щоб імпортувати дані картки водія або блоку автомобіля.",
    "tacho.import_card_title": "Імпорт Файлів",
    "tacho.import_driver_card": "Імпорт Картки Водія",
    "tacho.import_history": "Історія Імпорту",
    "tacho.import_now": "Імпортувати Зараз",
    "tacho.import_vehicle_unit": "Імпорт Блоку Автомобіля",
    "tacho.importing": "Імпортується...",
    "tacho.last_14_days": "Останні 14 Днів",
    "tacho.last_import": "Останній Імпорт",
    "tacho.no_activity": "Немає активності тахографа для цього водія",
    "tacho.no_data": "Немає даних тахографа",
    "tacho.no_history": "Ще немає імпортів.",
    "tacho.no_trucks": "Немає зареєстрованих вантажівок",
    "tacho.recent_violations": "Нещодавні Порушення",
    "tacho.section_status_title": "Статус Тахографа",
    "tacho.select_driver_card": "Вибрати Картку Водія (DDD)",
    "tacho.select_vehicle_unit": "Вибрати Блок Автомобіля (DDD)",
    "tacho.status_expired": "Закінчився",
    "tacho.status_no_data": "Немає Даних",
    "tacho.status_valid": "Дійсний",
    "tacho.subtitle": "Імпорт файлів картки водія (DDD) та блоку автомобіля (DDD)",
    "tacho.title": "Тахограф",
    "tacho.total_hours": "Всього Годин",
    "tacho.type_driver": "Картка Водія",
    "tacho.type_vehicle": "Блок Автомобіля",
    "tacho.violations": "Порушення",
    "time.days_ago": "{n} дн. тому",
    "time.hours_ago": "{n} год. тому",
    "time.just_now": "Щойно",
    "time.minutes_ago": "{n} хв. тому",
    "tracking.section_title": "Відстеження Автопарку",
    "tracking.setup_hint": "Налаштуйте платформу відстеження для активації позицій вантажівок у реальному часі.",
    "tracking.platform": "Платформа Відстеження",
    "tracking.platform_not_configured": "Не налаштовано",
    "tracking.token": "API Токен",
    "tracking.host": "URL Сервера",
    "tracking.username": "Користувач",
    "tracking.password": "Пароль",
    "tracking.btn_test": "Перевірити З'єднання",
    "tracking.test_incomplete": "Неповна інформація",
    "tracking.test_incorrect": "Некоректна інформація",
    "tracking.panel_title": "Автопарк",
    "tracking.no_vehicles": "Транспортних засобів не знайдено",
    "tracking.not_configured_title": "Відстеження Не Налаштовано",
    "tracking.not_configured_hint": "Налаштуйте платформу відстеження в Налаштуваннях, щоб бачити позиції вантажівок у реальному часі.",
    "tracking.go_to_settings": "Перейти до Налаштувань",
    "tracking.d_status": "Статус",
    "tracking.d_speed": "Швидкість",
    "tracking.d_updated": "Оновлено",
    "tracking.d_odometer": "Одометр",
    "tracking.d_address": "Локація",
    "tracking.btn_fleet_detail": "Переглянути в Менеджері Автопарку →",
    "tracking.account": "Акаунт / Субдомен",
    "tracking.id_field": "Поле ID",
    "tracking.lat_field": "Поле Широти",
    "tracking.lng_field": "Поле Довготи",
    "tracking.positions_path": "Шлях JSON Позицій",
    "tracking.not_configured": "Не Налаштовано",
    "maint.control_panel_title": "Панель Контролю ТО",
    "maint.schedule_next_due_km": "Наступне ТО через КМ",
    "maint.status_overdue": "Прострочено",
    "maint.status_remaining": "Залишилось",
    "maint.action_maint": "Дія ТО",
    "maint.action_remind": "Дія Нагадати",
    "maint.action_resolve": "Дія Вирішити",
    "maint.action_trip": "Дія Поїздка",
    "maint.action_truck": "Дія Вантажівка",
    "maint.add_record": "Додати Запис",
    "maint.alert_plural": "Сповіщення",
    "maint.alert_s": "Сповіщення",
    "maint.cancel": "Скасувати",
    "maint.close": "Закрити",
    "maint.col_cost": "Вартість",
    "maint.col_date": "Дата",
    "maint.col_km": "КМ",
    "maint.col_notes": "Примітки",
    "maint.col_provider": "Постачальник",
    "maint.col_type": "Тип",
    "maint.confirm_delete_msg": "Ви впевнені, що хочете видалити цей запис?",
    "maint.confirm_delete_title": "Підтвердити Видалення",
    "maint.critical_count": "Критичних",
    "maint.critical_health": "Критичний Стан",
    "maint.days_left": "Залишилось Днів",
    "maint.delete": "Видалити",
    "maint.due_by_date": "Термін до Дати",
    "maint.edit": "Редагувати",
    "maint.error_generic": "Сталася Помилка",
    "maint.excellent": "Відмінно",
    "maint.export": "Експорт",
    "maint.export_success": "Експорт Виконано",
    "maint.export_title": "Експорт",
    "maint.fair": "Задовільно",
    "maint.filter_label": "Фільтр",
    "maint.flash_maint_scheduled": "ТО Заплановано",
    "maint.flash_reminder": "Нагадування",
    "maint.flash_trip_copied": "Поїздку Скопійовано",
    "maint.flash_truck_copied": "Вантажівку Скопійовано",
    "maint.form_cost": "Вартість",
    "maint.form_date": "Дата",
    "maint.form_km": "КМ",
    "maint.form_notes": "Примітки",
    "maint.form_provider": "Постачальник",
    "maint.form_quick": "Швидка Форма",
    "maint.form_title_add": "Додати Запис ТО",
    "maint.form_title_edit": "Редагувати Запис ТО",
    "maint.form_type": "Тип",
    "maint.header": "Заголовок",
    "maint.info_count": "Кількість",
    "maint.km_remaining": "Залишилось КМ",
    "maint.label_trip": "Поїздка",
    "maint.label_truck": "Вантажівка",
    "maint.metric_compliance": "Відповідність",
    "maint.metric_downtime": "Час Простою",
    "maint.metric_overdue": "Прострочено",
    "maint.metric_recurring": "Повторювані",
    "maint.metric_score": "Оцінка Стану",
    "maint.next": "Далі",
    "maint.no_alerts_filter": "Немає Сповіщень",
    "maint.no_records": "Немає Записів",
    "maint.no_schedule": "Немає Графіку",
    "maint.no_schedules": "Немає Графіків",
    "maint.page_info": "Інформація Сторінки",
    "maint.predictions": "Прогнози",
    "maint.predictions_header": "Прогнозування ТО",
    "maint.predictions_title": "Прогнози ТО",
    "maint.prev": "Назад",
    "maint.refresh": "Оновити",
    "maint.refresh_score": "Оновити Оцінку",
    "maint.save": "Зберегти",
    "maint.schedule_add": "Додати Графік",
    "maint.schedule_delete_confirm": "Ви впевнені, що хочете видалити цей графік?",
    "maint.schedule_delete_prompt": "Видалити графік ТО?",
    "maint.schedule_delete_title": "Видалити Графік",
    "maint.schedule_due_by": "Термін до",
    "maint.schedule_every_km": "Кожні КМ",
    "maint.schedule_every_months": "Кожні Місяці",
    "maint.schedule_expires": "Закінчується",
    "maint.schedule_form_expiry": "Термін Дії",
    "maint.schedule_form_interval_km": "Інтервал КМ",
    "maint.schedule_form_interval_months": "Інтервал Місяці",
    "maint.schedule_form_last_date": "Остання Дата",
    "maint.schedule_form_last_km": "Останні КМ",
    "maint.schedule_form_title_add": "Додати Графік ТО",
    "maint.schedule_form_title_edit": "Редагувати Графік ТО",
    "maint.schedule_last_date": "Остання Дата",
    "maint.schedule_last_km": "Останні КМ",
    "maint.status_due_soon": "Скоро Термін",
    "maint.status_ok": "Все Гаразд",
    "maint.tab_health": "Стан",
    "maint.tab_history": "Історія",
    "maint.tab_schedules": "Графіки",
    "maint.target_km": "Цільові КМ",
    "maint.title": "Техобслуговування",
    "maint.updated": "Оновлено",
    "maint.warning_count": "Попереджень",
    "maint.filter_severity": "Фільтр за Серйозністю",
    "maint.filter_trip": "Фільтр Поїздка",
    "maint.filter_truck": "Фільтр Вантажівка",
    "maint.filter_type": "Фільтр Тип",
    "maint.show_resolved": "Показати Вирішені",
    "maint_analytics.chart_cost_per_truck": "Вартість на Вантажівку",
    "maint_analytics.chart_fleet_trend": "Тренд Автопарку",
    "maint_analytics.cost_label": "Вартість",
    "maint_analytics.no_data": "Немає Даних",
    "maint_analytics.no_data_12mo": "Немає Даних за 12 Міс.",
    "maint_analytics.no_records": "Немає Записів",
    "maint_analytics.title": "Аналітика Техобслуговування",
    "maint_analytics.total_cost_label": "Загальна Вартість",
    "maint_analytics.truck_fallback": "Вантажівка",
    "maint_analytics.cost_month": "Вартість за Місяць",
    "maint_analytics.cost_total": "Загальна Вартість",
    "maint_analytics.cost_year": "Вартість за Рік",
    "maint_analytics.filter_all": "Всі",
    "maint_analytics.filter_truck": "Вантажівка",
    "maint_analytics.section_title": "Аналітика ТО",
    "maint_analytics.type": "Тип",
    "maint_timeline.detail_title": "Деталі Запису ТО",
    "maint_timeline.field_cost": "Вартість",
    "maint_timeline.field_date": "Дата",
    "maint_timeline.field_km": "КМ",
    "maint_timeline.field_notes": "Примітки",
    "maint_timeline.field_provider": "Постачальник",
    "maint_timeline.field_type": "Тип",
    "maint_timeline.title": "Хронологія ТО",
    "maint_timeline.add_entry": "Додати Запис",
    "maint_timeline.cost": "Вартість",
    "maint_timeline.date": "Дата",
    "maint_timeline.description": "Опис",
    "maint_timeline.km": "КМ",
    "maint_timeline.no_entries": "Немає Записів",
    "maint_timeline.section_title": "Хронологія Техобслуговування",
    "maint_timeline.type": "Тип",
    "analytics.title": "Аналітика Бізнес-Аналізу",
    "analytics.header": "РОЗШИРЕНИЙ АНАЛІЗ ЕФЕКТИВНОСТІ АВТОПАРКУ",
    "analytics.empty_state": "Недостатньо даних у системі для створення візуальної аналітики.
Введіть поїздки в історію.",
    "analytics.chart_top_trucks": "Топ 10 Вантажівок (Чистий Прибуток)",
    "analytics.legend_revenue": "Дохід",
    "analytics.legend_expenses": "Витрати",
    "analytics.chart_revenue_vs_expenses": "Дохід проти Витрат (Останні 6 Місяців)",
    "analytics.chart_profit_per_driver": "Прибуток на Водія",
    "analytics.pie_profit": "Прибуток",
    "analytics.pie_expenses": "Витрати",
    "analytics.no_financial_data": "Немає фінансових даних",
    "analytics.chart_profit_expenses_ratio": "Співвідношення Прибуток / Витрати (Всього)",
    "analytics.render_error": "Помилка відображення графіків: {}",
    "analytics.invalid_date_format": "Некоректний Формат Дати",
    "compliance.traversed": "Пройдено: {}",
    "compliance.toll_countries": "Країни з платними дорогами: {}",
    "compliance.excluded_avoided": "Уникнено виключених: {}",
    "compliance.border_crossings": "Перетинів кордону: {}",
    "compliance.extra_distance": "Додаткова дистанція: {:.1f} км",
    "compliance.why_chosen": "Чому вибрано: {}. {}",
    "dashboard.title": "Панель Бізнес-Аналітики",
    "dashboard.period_label": "ПЕРІОД АНАЛІЗУ:",
    "dashboard.refresh_button": "ОНОВИТИ",
    "dashboard.error_title": "Помилка Даних",
    "dashboard.error_msg": "Не вдалося обробити дані: {}",
    "dashboard.kpi_monthly_revenue": "Місячний Дохід",
    "dashboard.kpi_monthly_profit": "Місячний Прибуток",
    "dashboard.kpi_avg_profit_per_km": "Сер. Прибуток / КМ",
    "dashboard.kpi_unpaid_invoices": "Неоплачені Рахунки",
    "dashboard.kpi_active_trips": "Активні Поїздки",
    "dashboard.section_financial": "ФІНАНСОВА ЕФЕКТИВНІСТЬ",
    "dashboard.card_net_profit": "Чистий Прибуток",
    "dashboard.card_gross_revenue": "Валовий Дохід",
    "dashboard.card_avg_gross_rate": "Сер. Валова Ставка",
    "dashboard.card_avg_net_rate": "Сер. Чиста Ставка",
    "dashboard.card_best_month": "Найкращий Місяць",
    "dashboard.card_top_truck": "Найкраща Вантажівка",
    "dashboard.card_top_driver": "Найкращий Водій",
    "dashboard.section_alerts": "ЦЕНТР СПОВІЩЕНЬ",
    "dashboard.no_alerts": "Немає сповіщень",
    "dashboard.total_overdue": "Загальна Прострочка: {:,.2f} €",
    "dashboard.chart_profit_evolution": "ЕВОЛЮЦІЯ ПРИБУТКУ",
    "edit_trip.title": "Редагувати Поїздку #{}",
    "edit_trip.field_truck": "Номер Вантажівки:",
    "edit_trip.field_driver": "Водій:",
    "edit_trip.field_client": "Клієнт:",
    "edit_trip.field_distance": "Дистанція КМ:",
    "edit_trip.field_profit": "Прибуток (Редагувати вручну):",
    "edit_trip.field_status": "Статус:",
    "edit_trip.save_button": "Зберегти Зміни",
    "edit_trip.error_title": "Помилка",
    "email.config_missing": "Відсутня SMTP конфігурація. Перейдіть в Налаштування.",
    "email.invoice_subject": "Рахунок {} - {}",
    "email.invoice_body": "Шановний(а) пане/пані,

Будь ласка, знайдіть у вкладенні рахунок {}.

Загальна сума: {:.2f} EUR
Термін оплати: {}

Дякуємо за співпрацю.

З повагою,
{}",
    "email.reminder_subject": "НАГАДУВАННЯ: Прострочений Платіж Рахунок {}",
    "email.reminder_body": "Шановний(а) пане/пані,

Це нагадування щодо рахунку {} на загальну суму {:.2f} EUR,
термін оплати {}.

Будь ласка, здійсніть оплату за першої можливості.

З повагою,
{}",
    "email.default_subject": "Сповіщення ERP Логістика",
    "email.default_body": "Шановний(а) пане/пані,

Ви маєте нове повідомлення від логістичної системи.

З повагою.",
    "fleet.title": "Управління Автопарком",
    "fleet.header": "Управління Автопарком",
    "fleet.export_csv": "Експорт CSV",
    "fleet.export_excel": "Експорт Excel",
    "fleet.export_pdf": "Експорт PDF",
    "fleet.kpi_total_trucks": "Всього Вантажівок",
    "fleet.kpi_active": "Активні",
    "fleet.kpi_service_due": "Потребують ТО",
    "fleet.kpi_monthly_rate": "Місячна Ставка (EUR)",
    "fleet.search_label": "Пошук:",
    "fleet.reset_button": "Скинути",
    "fleet.plate_label": "Номерний Знак:",
    "fleet.find_button": "Знайти",
    "fleet.table_id": "ID",
    "fleet.table_plate": "Номер",
    "fleet.table_model": "Модель",
    "fleet.table_manufacturer": "Виробник",
    "fleet.table_year": "Рік",
    "fleet.table_vin": "VIN",
    "fleet.table_km": "КМ",
    "fleet.table_consumption": "Л/100км",
    "fleet.table_rate": "Ставка EUR",
    "fleet.table_status": "Статус",
    "fleet.table_insurance": "Страхування",
    "fleet.table_inspection": "Техогляд",
    "fleet.table_service_km": "ТО КМ",
    "fleet.table_active": "Активна",
    "fleet.add_truck": "Додати Вантажівку",
    "fleet.edit_button": "Редагувати",
    "fleet.delete_button": "Видалити",
    "fleet.section_alerts": "Сповіщення",
    "fleet.section_charts": "Графіки Автопарку",
    "fleet.section_quick_add": "Швидке Додавання",
    "fleet.plate_quick": "Номерний Знак:",
    "fleet.model_quick": "Модель:",
    "fleet.rate_quick": "Місячна Ставка (EUR):",
    "fleet.save_quick": "Швидке Збереження",
    "fleet.error_load": "Не вдалося завантажити автопарк: {}",
    "fleet.alert_format": "[{type}] {msg}",
    "fleet.no_alerts": "Немає поточних сповіщень.",
    "fleet.alert_load_error": "Помилка завантаження сповіщень.",
    "fleet.no_data_chart": "Немає даних",
    "fleet.search_info_title": "Пошук",
    "fleet.search_info_msg": "Введіть номерний знак.",
    "fleet.search_not_found": "Вантажівку з номером {} не знайдено.",
    "fleet.select_first": "Спочатку виберіть вантажівку.",
    "fleet.truck_not_found": "Вантажівку не знайдено.",
    "fleet.truck_form_title": "Вантажівка",
    "fleet.form_plate": "Номерний Знак:",
    "fleet.form_model": "Модель:",
    "fleet.form_manufacturer": "Виробник:",
    "fleet.form_year": "Рік (РРРР):",
    "fleet.form_vin": "VIN:",
    "fleet.form_consumption": "Витрата (Л/100км):",
    "fleet.form_km": "КМ:",
    "fleet.form_rate": "Місячна Ставка (EUR):",
    "fleet.form_status": "Статус:",
    "fleet.form_insurance": "Страхування (дд/мм/РРРР):",
    "fleet.form_inspection": "Техогляд (дд/мм/РРРР):",
    "fleet.form_service_km": "ТО на (КМ):",
    "fleet.form_active": "Активна",
    "fleet.validation_plate_required": "Номерний знак обов'язковий.",
    "fleet.validation_year_invalid": "Рік має бути цілим числом.",
    "fleet.validation_consumption_invalid": "Некоректна витрата.",
    "fleet.validation_km_rate_service_invalid": "Некоректні значення КМ/Ставки/ТО.",
    "fleet.validation_rate_invalid": "Некоректна ставка.",
    "fleet.save_button": "Зберегти",
    "fleet.cancel_button": "Скасувати",
    "fleet.success_added": "Вантажівку додано.",
    "fleet.error_save": "Не вдалося зберегти: {}",
    "fleet.confirm_delete": "Ви впевнені, що хочете видалити цю вантажівку?",
    "fleet.error_delete": "Не вдалося видалити вантажівку: {}",
    "fleet.truck_detail_title": "Деталі Вантажівки - {}",
    "fleet.detail_manufacturer": "Виробник:",
    "fleet.detail_year": "Рік:",
    "fleet.detail_vin": "VIN:",
    "fleet.detail_km": "КМ:",
    "fleet.detail_rate": "Місячна Ставка:",
    "fleet.detail_edit_button": "Редагувати Вантажівку",
    "fleet.detail_export_button": "Експорт Деталей CSV",
    "fleet.tab_maintenance": "Техобслуговування",
    "fleet.tab_insurance": "Страхування/Техогляд",
    "fleet.tab_expenses": "Витрати",
    "fleet.maintenance_table_id": "ID",
    "fleet.maintenance_table_date": "Дата",
    "fleet.maintenance_table_type": "Тип",
    "fleet.maintenance_table_km": "КМ",
    "fleet.maintenance_table_cost": "Вартість",
    "fleet.maintenance_table_desc": "Опис",
    "fleet.add_maintenance": "Додати ТО",
    "fleet.validation_km_cost_invalid": "Некоректні КМ або Вартість.",
    "fleet.error_save_maintenance": "Не вдалося зберегти ТО: {}",
    "fleet.save_maintenance": "Зберегти ТО",
    "fleet.insurance_label": "Страхування (дд/мм/РРРР):",
    "fleet.inspection_label": "Техогляд (дд/мм/РРРР):",
    "fleet.success_updated": "Дані оновлено.",
    "fleet.expenses_table_id": "ID",
    "fleet.expenses_table_date": "Дата",
    "fleet.expenses_table_category": "Категорія",
    "fleet.expenses_table_amount": "Сума",
    "fleet.expenses_table_desc": "Опис",
    "fleet.add_expense": "Додати Витрату",
    "fleet.validation_amount_invalid": "Некоректна сума.",
    "fleet.error_save_expense": "Не вдалося зберегти витрату: {}",
    "fleet.save_expense": "Зберегти Витрату",
    "fleet.save_csv_title": "Зберегти CSV",
    "fleet.export_csv_success": "CSV збережено: {}",
    "fleet.export_csv_error": "Помилка експорту CSV: {}",
    "fleet.export_excel_success": "Excel збережено: {}",
    "fleet.export_excel_error": "Помилка експорту Excel: {}",
    "fleet.export_pdf_success": "PDF збережено: {}",
    "fleet.export_pdf_error": "Помилка експорту PDF: {}",
    "fleet.save_truck_csv_title": "Зберегти CSV Вантажівки",
    "fleet.export_truck_csv_success": "CSV вантажівки збережено: {}",
    "fleet.export_truck_csv_error": "Помилка експорту CSV вантажівки: {}",
    "fleet.expense_default_category": "Категорія Витрат За Замовчуванням",
    "fleet.form_tracking_device_id": "ID Пристрою Відстеження",
    "fleet.kpi_alerts": "Сповіщення",
    "fleet.maint_history_desc": "Історія Техобслуговування",
    "fleet.maint_kpi_alerts": "Сповіщення ТО",
    "fleet.maint_kpi_cost_month": "Витрати на ТО за Місяць",
    "fleet.maint_kpi_last_service": "Останнє ТО",
    "fleet.maint_kpi_next_due": "Наступне ТО",
    "fleet.maint_kpi_odometer": "Одометр",
    "fleet.maint_kpi_tacho": "Тахограф",
    "fleet.maint_kpi_title": "Показники ТО",
    "fleet.no_engine": "Немає Даних Двигуна",
    "fleet.open_maintenance_manager": "Відкрити Менеджер ТО",
    "fleet.status_active": "Активна",
    "fleet.status_unknown": "Невідомо",
    "fleet.table_driver": "Водій",
    "fleet.table_driver_unassigned": "Водій (Не Призначений)",
    "fleet.unit_km": "км",
    "history.title": "Операційне Управління та Виставлення Рахунків",
    "history.search_label": "Пошук:",
    "history.reset_button": "Скинути",
    "history.table_id": "ID",
    "history.table_date": "Дата",
    "history.table_truck": "Вантажівка",
    "history.table_driver": "Водій",
    "history.table_client": "Клієнт",
    "history.table_km": "КМ",
    "history.table_gross_per_km": "Валовий/км",
    "history.table_profit": "Прибуток",
    "history.table_status": "Статус",
    "history.button_status": "Статус",
    "history.button_edit": "Редагувати",
    "history.button_invoice": "Рахунок",
    "history.button_email": "Email",
    "history.button_pdf": "PDF",
    "history.button_excel": "Excel",
    "history.button_delete": "Видалити",
    "history.update_status_title": "Оновити Статус",
    "history.error_title": "Помилка",
    "history.warning_title": "Увага",
    "history.no_export_data": "Немає даних для експорту!",
    "history.error_pdf": "Помилка PDF",
    "history.error_excel": "Помилка Excel",
    "history.select_trip_first": "Виберіть поїздку з таблиці!",
    "history.email_recipient_title": "Отримувач",
    "history.email_recipient_msg": "Введіть email клієнта:",
    "history.email_success": "Email успішно надіслано: {}",
    "history.email_error": "Помилка надсилання email: {}",
    "history.confirm_delete_title": "Видалити",
    "history.confirm_delete_msg": "Ви впевнені, що хочете видалити цей запис?",
    "history.button_view_route": "Переглянути Маршрут",
    "history.no_route_linked": "Ця поїздка не має пов'язаного маршруту.",
    "history.route_not_found": "Пов'язаний маршрут не знайдено.",
    "history.cancel_status": "Скасувати Статус",
    "history.confirm_status": "Підтвердити Статус",
    "history.email_deprecated": "Email Застарілий",
    "history.no_engine": "Немає Даних Двигуна",
    "history.no_transitions": "Немає Переходів",
    "history.status_prompt": "Запит Статусу",
    "history.transition_failed": "Перехід Не Вдався",
    "invoice.section_company": "Дані Вашої Компанії (Відправник)",
    "invoice.field_company_name": "Назва Компанії:",
    "invoice.field_cui": "CUI / Номер ПДВ:",
    "invoice.field_reg_number": "Реєстр. Номер Торг. Реєстру:",
    "invoice.field_address": "Юридична Адреса:",
    "invoice.field_phone": "Номер Телефону:",
    "invoice.field_email": "Email Адреса:",
    "invoice.save_company": "Зберегти Дані Компанії",
    "invoice.section_generator": "Генератор Документів",
    "invoice.select_trip": "1. Виберіть Поїздку з Історії:",
    "invoice.doc_type_label": "2. Тип Документу:",
    "invoice.radio_client_invoice": "Рахунок Клієнту (Лише загальна ціна)",
    "invoice.radio_internal_invoice": "Внутрішній Розрахунок (Деталі прибутку та витрат)",
    "invoice.generate_button": "ЗГЕНЕРУВАТИ PDF ТА ВІДКРИТИ",
    "invoice.warning_fields_title": "Обов'язкові Поля",
    "invoice.warning_fields_msg": "Назва компанії та CUI обов'язкові.",
    "invoice.success_save_company": "Дані компанії збережено та буде використано в нових рахунках.",
    "invoice.warning_select_trip": "Будь ласка, виберіть поїздку зі списку.",
    "invoice.error_generate": "Помилка генерації: {}",
    "invoice.button_email": "Надіслати Email",
    "invoice.default_client": "Клієнт За Замовчуванням",
    "invoice.email_body": "Тіло Email",
    "invoice.email_failed": "Email Не Відправлено",
    "invoice.email_subject": "Тема Email",
    "invoice.email_success": "Email Відправлено",
    "invoice.smtp_not_configured": "SMTP Не Налаштовано",
    "invoice.trip_list_format": "Формат Списку Поїздок",
    "invoice.field_{key}": "Поле {key}",
    "invoice_pdf.title_client": "РАХУНОК КЛІЄНТУ",
    "invoice_pdf.title_internal": "ВНУТРІШНІЙ РОЗРАХУНОК",
    "invoice_pdf.serial": "Серія/№: {} | Дата: {}",
    "invoice_pdf.sender_header": "ВІДПРАВНИК:",
    "invoice_pdf.bill_to_header": "ОТРИМУВАЧ:",
    "invoice_pdf.trip_info": "ДЕТАЛІ ТРАНСПОРТУВАННЯ / ІНФО ПОЇЗДКИ",
    "invoice_pdf.truck": "Вантажівка",
    "invoice_pdf.driver": "Водій",
    "invoice_pdf.distance": "Дистанція",
    "invoice_pdf.start_date": "Дата Початку",
    "invoice_pdf.end_date": "Дата Завершення",
    "invoice_pdf.financials": "ВАРТІСТЬ ПОСЛУГ / ФІНАНСИ",
    "invoice_pdf.desc_header": "Опис",
    "invoice_pdf.amount_header": "Сума (EUR)",
    "invoice_pdf.line_gross": "Транспортний Збір (Валовий)",
    "invoice_pdf.line_fuel": "Вартість Палива",
    "invoice_pdf.line_tolls": "Дорожні Збори",
    "invoice_pdf.line_salary": "Зарплата Водія/Щоденно",
    "invoice_pdf.line_other": "Інші Витрати",
    "invoice_pdf.net_profit": "ЗАГАЛЬНИЙ ЧИСТИЙ ПРИБУТОК",
    "invoice_pdf.qty_header": "К-ть",
    "invoice_pdf.total_header": "Всього (EUR)",
    "invoice_pdf.service_desc": "Автомобільні вантажні перевезення ({} км)",
    "invoice_pdf.footer": "Дякуємо за довіру!
Згенеровано ERP Логістичною Системою",
    "invoice_pdf.default_company": "Назва Вашої Компанії",
    "invoice_pdf.default_cui": "RO12345678",
    "invoice_pdf.default_reg": "J40/123/2023",
    "invoice_pdf.default_address": "Повна Адреса",
    "invoice_pdf.default_phone": "07xx xxx xxx",
    "invoice_pdf.default_email": "contact@firma.ro",
    "main.section_identify": "ІДЕНТИФІКАЦІЯ",
    "main.truck_label": "Вантажівка:",
    "main.client_label": "Клієнт (Компанія):",
    "main.section_finance": "ФІНАНСИ ТА СПОЖИВАННЯ",
    "main.offer_price": "Ціна Пропозиції (Всього):",
    "main.currency_label": "Валюта:",
    "main.section_costs": "ВИТРАТИ (0 = АВТО)",
    "main.salary_label": "Зарплата/День (EUR):",
    "main.extra_costs_label": "Додаткові Витрати (EUR):",
    "main.section_planning": "ПЛАНУВАННЯ",
    "main.start_date_label": "Дата Початку (ДД/ММ/РРРР):",
    "main.duration_label": "Тривалість Поїздки (Дні):",
    "main.payment_term_label": "Термін Оплати (Дні):",
    "main.calculate_button": "РОЗРАХУВАТИ ТА ЗБЕРЕГТИ В БАЗУ",
    "main.placeholder_info": "Введіть дані для початку аналізу.",
    "main.net_profit": "ЧИСТИЙ ПРИБУТОК: {:.2f} EUR",
    "main.gross_rate": "ВАЛОВА СТАВКА: {:.2f} €/км | ЧИСТА СТАВКА: {:.2f} €/км",
    "main.margin": "МАРЖА: {}% | ОРІЄНТ. ІНКАСАЦІЯ: {}",
    "main.separator": "───────────────────────────────────────────────────────────",
    "main.cost_breakdown": "Паливо: {:.2f} € | Дорожні Збори: {:.2f} € | Зарплата: {:.2f} €",
    "main.warning_title": "Увага",
    "main.fields_required": "Дистанція та Ціна обов'язкові.",
    "main.save_success": "Поїздку успішно збережено!",
    "main.error_title": "Помилка",
    "main.check_data": "Перевірте дані: {}",
    "main.fuel_updated_at": "Оновлено: {}",
    "main.fuel_age": "Вік: {}",
    "main.fuel_offline": "Офлайн (використовується резерв)",
    "result.distance": "Дистанція: {:.2f} км",
    "result.duration": "Тривалість: {}",
    "result.stops": "Зупинки: {} зупинок",
    "result.fuel": "Паливо: {:.2f} Л",
    "result.fuel_cost": "Вартість палива: {:.2f} RON",
    "result.history_loaded": "Маршрут завантажено з історії",
    "result.days": "дні",
    "result.hours": "год",
    "result.minutes": "хв",
    "result.route_not_found_title": "Маршрут не знайдено",
    "result.route_not_found_msg": "Пункти можуть бути недосяжними.
Спробуйте додати проміжні зупинки.",
    "result.invalid_coords": "Некоректні координати",
    "result.connection_error": "Помилка з'єднання - Неможливо підключитися до сервера GraphHopper.
Переконайтеся, що сервер працює за адресою {}",
    "result.geocode_error": "Адресу не знайдено",
    "result.timeout_error": "Тайм-аут - Розрахунок маршруту зайняв занадто багато часу.
Спробуйте менше зупинок або перевірте сервер GraphHopper.",
    "result.generic_error": "{}:
{}",
    "result.need_2_stops": "Потрібно принаймні 2 зупинки.",
    "result.duplicate_stops": "Дублювання зупинок - Видаліть однакові локації.",
    "result.invalid_route_distance": "Некоректна дистанція маршруту.",
    "result.controller_select_truck": "Виберіть вантажівку.",
    "result.controller_invalid_truck": "Некоректна вантажівка.",
    "result.controller_empty_stop": "Зупинка #{} має порожню адресу.",
    "result.controller_need_2_stops": "Потрібно принаймні 2 зупинки.",
    "result.controller_calc_failed": "Не вдалося розрахувати маршрут.",
    "result.controller_invalid_distance": "Некоректна дистанція маршруту.",
    "result.controller_no_metadata": "Немає метаданих маршруту для експорту.",
    "route.planner_title": "Планувальник Маршрутів",
    "route.section_header": "РОЗУМНИЙ МАРШРУТ",
    "route.destinations_label": "Пункти Призначення:",
    "route.add_stop": "+ Додати Зупинку",
    "route.remove_stop": "- Видалити Зупинку",
    "route.highlight_avoided": "Виділити уникнені країни",
    "route.show_comparison": "Показати оригінальний vs кінцевий маршрут",
    "route.export_metadata": "Експортувати метадані маршруту",
    "route.select_truck": "Вибрати вантажівку:",
    "route.profile_label": "Профіль маршруту:",
    "route.calculate_button": "Розрахувати Маршрут",
    "route.info_placeholder": "Інформація про маршрут з'явиться тут.",
    "route.calculating": "Розрахунок...",
    "route.processing": "Обробка розрахунку маршруту...",
    "route.calc_failed": "Не вдалося розрахувати маршрут.",
    "route.export_success": "Метадані експортовано: {}",
    "route.exclusions_label": "Виключені Країни",
    "route.exclusions_clear": "Очистити все",
    "route.exclusions_selected": "{} вибрано",
    "route.exclusions_none": "Нічого не вибрано",
    "route.exclusions_empty": "Немає виключених країн",
    "route.add_to_dispatch": "Додати до Диспетчерської",
    "route.client_name": "Назва Клієнта",
    "route.no_saved_route_id": "Немає ID Збереженого Маршруту",
    "route.select_driver": "Вибрати Водія",
    "route.start_date": "Дата Початку",
    "route.stop_destination": "Пункт Призначення",
    "route.stop_n": "Зупинка {n}",
    "route.stop_start": "Початкова Зупинка",
    "route.trip_created": "Поїздку Створено",
    "route_history.title": "Історія Маршрутів",
    "route_history.header": "Історія Маршрутів",
    "route_history.refresh": "Оновити",
    "route_history.open_planner": "Відкрити Планувальник Маршрутів",
    "route_history.search_label": "Пошук",
    "route_history.profile_label": "Профіль",
    "route_history.truck_label": "Вантажівка",
    "route_history.archived_checkbox": "Архівовані",
    "route_history.apply_button": "Застосувати",
    "route_history.reset_button": "Скинути",
    "route_history.table_origin": "Початок",
    "route_history.table_destination": "Призначення",
    "route_history.table_datetime": "Дата / Час",
    "route_history.table_truck": "Вантажівка",
    "route_history.table_distance": "Дистанція",
    "route_history.table_duration": "Тривалість",
    "route_history.table_profile": "Профіль",
    "route_history.table_total_cost": "Загальна Вартість",
    "route_history.table_net_profit": "Чистий Прибуток",
    "route_history.loading_routes": "Завантаження маршрутів...",
    "route_history.next_button": "Далі",
    "route_history.prev_button": "Назад",
    "route_history.reopen_button": "Відкрити Знову",
    "route_history.recalculate_button": "Перерахувати",
    "route_history.duplicate_button": "Дублювати",
    "route_history.export_button": "Експорт",
    "route_history.archive_button": "Архівувати",
    "route_history.delete_button": "Видалити",
    "route_history.section_stats": "Статистика Маршруту",
    "route_history.loading_placeholder": "Завантаження...",
    "route_history.section_map": "Попередній Перегляд Мапи",
    "route_history.section_comparison": "Порівняння Маршрутів",
    "route_history.comparison_hint": "Виберіть два маршрути та натисніть Порівняти.",
    "route_history.compare_button": "Порівняти Вибрані",
    "route_history.warning_select_route": "Спочатку виберіть маршрут.",
    "route_history.error_not_found": "Маршрут не знайдено.",
    "route_history.warning_select_one": "Виберіть принаймні один маршрут.",
    "route_history.confirm_delete_title": "Видалити Маршрути",
    "route_history.confirm_delete_msg": "Видалити {} вибраних маршрутів?",
    "route_history.export_dialog": "Експорт маршруту",
    "route_history.export_success": "Маршрут експортовано:
{}",
    "route_history.comparison_error": "Виберіть рівно два маршрути для порівняння.",
    "route_history.truck_all": "Всі",
    "route_history.calculate_trip_button": "Розрахувати Поїздку",
    "route_history.comparison_result": "Результат Порівняння",
    "route_history.page_info": "Інформація Сторінки",
    "route_history.stats_none": "Немає Статистики",
    "route_history.stats_summary": "Підсумок Статистики",
    "safety.title": "Безпека Даних",
    "safety.management": "КЕРУВАННЯ ДАНИМИ",
    "safety.export_success": "Дані експортовано в JSON:
{}",
    "safety.import_confirm": "Імпортувати дані в поточну базу даних?",
    "safety.import_success": "Імпортовано {} записів.",
    "safety.export_button": "ЕКСПОРТУВАТИ ВСЕ (JSON)",
    "safety.import_button": "ІМПОРТУВАТИ З JSON",
    "safety.backup_info": "Автоматичні резервні копії (.db) знаходяться в:
data/backups/",
    "settings.title": "Налаштування ERP та Email",
    "settings.section_company": "ДАНІ КОМПАНІЇ (ВІДПРАВНИК)",
    "settings.field_company_name": "Назва Компанії:",
    "settings.field_cui": "CUI / ПДВ:",
    "settings.field_reg_number": "Реєстр. Номер Торг. Реєстру:",
    "settings.field_address": "Юридична Адреса:",
    "settings.field_phone": "Телефон:",
    "settings.field_email": "Контактний Email:",
    "settings.section_smtp": "НАЛАШТУВАННЯ EMAIL СЕРВЕРА",
    "settings.smtp_server": "SMTP Сервер (напр. smtp.gmail.com):",
    "settings.smtp_port": "Порт (напр. 587 або 465):",
    "settings.smtp_user": "Email (Користувач):",
    "settings.smtp_password": "Пароль Додатку:",
    "settings.save_all": "ЗБЕРЕГТИ ВСІ НАЛАШТУВАННЯ",
    "settings.success_save": "Всі налаштування збережено!",
    "settings.error_save_smtp": "Не вдалося зберегти налаштування SMTP: {}",
    "settings.section_smtp_legacy": "КОНФІГУРАЦІЯ SMTP (EMAIL)",
    "settings.smtp_port_legacy": "SMTP Порт (напр. 587):",
    "settings.smtp_user_legacy": "Користувач Email:",
    "settings.smtp_password_legacy": "Пароль Додатку:",
    "settings.save_smtp": "Зберегти Налаштування SMTP",
    "settings.success_smtp": "Налаштування email збережено!",
    "settings.section_preferences": "НАЛАШТУВАННЯ",
    "settings.language_label": "Мова:",
    "settings.currency_label": "Валюта За Замовчуванням:",
    "settings.section_email": "EMAIL ТА SMTP",
    "settings.section_maintenance": "ПОРОГИ ТЕХОБСЛУГОВУВАННЯ",
    "settings.save": "Зберегти",
    "settings.reset": "Скинути",
    "settings.subtitle": "Налаштуйте параметри ERP",
    "settings.field_smtp_server": "SMTP Сервер:",
    "settings.field_smtp_port": "SMTP Порт:",
    "settings.field_smtp_user": "SMTP Користувач:",
    "settings.field_smtp_password": "SMTP Пароль:",
    "settings.field_alert_recipients": "Email Отримувачів Сповіщень:",
    "settings.field_alert_days_ahead": "Днів Попередження:",
    "settings.field_tacho_warning": "Дні Попередження Тахо:",
    "settings.field_tacho_critical": "Критичні Дні Тахо:",
    "settings.test_connection": "Перевірити З'єднання",
    "settings.email_logs": "Логи Email",
    "settings.test_success": "Перевірка успішна!",
    "settings.test_failed": "Перевірка не вдалася: {}",
    "validation.positive_km_price": "КМ та Ціна мають бути додатними.",
    "validation.numeric_km_price": "КМ та Ціна мають бути числовими значеннями.",
    "nav.live_tracking": "Відстеження в Реальному Часі",
}