import json, os, sys

path = r"C:\Users\Bonjo\source\repos\Calculator logistica\data\translations"
with open(os.path.join(path, "en.json"), "r", encoding="utf-8") as f:
    en = json.load(f)

# ── ROMANIAN ──
ro = {
    "common.all":"Toate","common.csv_filter":"Filtru CSV","common.currency_eur":"EUR","common.from_date":"De la","common.id":"ID","common.na":"N/A","common.no":"Nu","common.no_data":"Fara date","common.status":"Status","common.to_date":"Pana la","common.unknown":"Necunoscut","common.yes":"Da",
    "nav.calculator":"Calculator","nav.dispatch_board":"Panou Dispecer","nav.driver_manager":"Manager Soferi","nav.group_finance":"Finante","nav.group_fleet":"Flota","nav.group_operations":"Operatiuni","nav.group_overview":"Prezentare Generala","nav.live_tracking":"Urmarire Live","nav.maintenance_analytics":"Analize Mentenanta","nav.maintenance_control":"Control Mentenanta","nav.overview":"Prezentare Generala","nav.tachograph":"Tahograf",
    "alerts.none_active":"Nicio alerta activa","alerts.panel_title":"Notificari",
    "home.active_alerts":"Alerte Active","home.active_trips":"Curse Active","home.no_active_trips":"Fara curse active","home.no_alerts":"Nu exista alerte active","home.profit_chart_title":"Profitul Lunii Precedente","home.profit_data_source":"Date importate automat din Analytics","home.profit_day_label":"Zi","home.profit_no_data":"Nu sunt disponibile date despre profit inca.","home.recent_activity":"Activitate Recenta","home.top_trucks":"Top Camioane Luna Aceasta",
    "time.days_ago":"acum {n}z","time.hours_ago":"acum {n}h","time.just_now":"acum","time.minutes_ago":"acum {n}m",
    "fuel.age_hours":"acum {n}h","fuel.age_minutes":"acum {n}m","fuel.age_seconds":"acum {n}s","fuel.no_data":"Nicio data disponibila","fuel.not_fetched":"Neactualizat inca","fuel.section_title":"Preturi Combustibil","fuel.updated_status":"Actualizat: {ts} ({age})",
    "tracking.account":"Cont / Subdomeniu","tracking.btn_fleet_detail":"Vezi in Manager Flota \u2192","tracking.btn_test":"Testeaza Conexiunea","tracking.d_address":"Locatie","tracking.d_odometer":"Odometru","tracking.d_speed":"Viteza","tracking.d_status":"Status","tracking.d_updated":"Actualizat","tracking.go_to_settings":"Mergi la Setari","tracking.host":"URL Server","tracking.id_field":"Camp ID","tracking.lat_field":"Camp Lat","tracking.lng_field":"Camp Lng","tracking.no_vehicles":"Niciun vehicul gasit","tracking.not_configured":"Neconfigurat","tracking.not_configured_hint":"Configurati platforma de urmarire in Setari pentru a vedea pozitiile camioanelor in timp real.","tracking.not_configured_title":"Urmarire Neconfigurata","tracking.panel_title":"Flota","tracking.password":"Parola","tracking.platform":"Platforma Urmarire","tracking.platform_not_configured":"Neconfigurat","tracking.positions_path":"Cale JSON pozitii","tracking.section_title":"Urmarire Flota","tracking.setup_hint":"Configurati platforma de urmarire pentru a activa pozitiile live ale camioanelor in Operion.","tracking.test_incorrect":"Informatii incorecte","tracking.test_incomplete":"Informatii incomplete","tracking.token":"Token API","tracking.username":"Utilizator",
    "tacho.avg_daily":"Medie Zilnica","tacho.calibration_date":"Data Calibrare","tacho.driver_activity_title":"Activitate Tahograf","tacho.expiry":"Expirare","tacho.how_it_works":"Selectati un fisier .ddd mai jos pentru a importa datele cardului sofer sau ale unitatii vehicul.","tacho.import_card_title":"Importa Fisiere","tacho.import_driver_card":"Importa Card Sofer","tacho.import_history":"Istoric Importuri","tacho.import_now":"Importa Acum","tacho.import_vehicle_unit":"Importa Unitate Vehicul","tacho.importing":"Se importa...","tacho.last_14_days":"Ultimele 14 Zile","tacho.last_import":"Ultimul Import","tacho.no_activity":"Nicio activitate tahograf pentru acest sofer","tacho.no_data":"Nicio data tahograf disponibila","tacho.no_history":"Niciun import inca.","tacho.no_trucks":"Niciun camion inregistrat","tacho.recent_violations":"Violatii Recente","tacho.section_status_title":"Status Tahograf","tacho.select_driver_card":"Selecteaza Card Sofer (DDD)","tacho.select_vehicle_unit":"Selecteaza Unitate Vehicul (DDD)","tacho.status_expired":"Expirat","tacho.status_no_data":"Fara Date","tacho.status_valid":"Valid","tacho.subtitle":"Importa fisiere card sofer (DDD) si unitate vehicul (DDD)","tacho.title":"Tahograf","tacho.total_hours":"Total Ore","tacho.type_driver":"Card Sofer","tacho.type_vehicle":"Unitate Vehicul","tacho.violations":"Violatii",
    "dispatch_board.alerts":"Alerte","dispatch_board.assign_driver":"Atribuie Sofer","dispatch_board.assign_truck":"Atribuie Camion","dispatch_board.available_from":"disponibil de la {next_slot}","dispatch_board.col_delivered":"Livrat","dispatch_board.col_in_transit":"In Tranzit","dispatch_board.col_loading":"Incarcare","dispatch_board.col_planned":"Planificat","dispatch_board.confirm_backward":"Confirmati mutarea cursei #{trip_id} inapoi de la {old_status} la {new_status}?","dispatch_board.confirm_title":"Confirma Tranzitia","dispatch_board.conflict_warning_title":"Atentie Conflict","dispatch_board.delay_alert_message":"Cursele #{trip_id} ({client}) sunt intarziate cu peste {hours} ore.","dispatch_board.delay_alert_title":"Intarziere Curse #{trip_id}","dispatch_board.delayed":"Intarziat","dispatch_board.driver_not_found":"Sofer negasit.","dispatch_board.hours_overdue":"{hours}h peste termen","dispatch_board.load_error":"Eroare incarcare","dispatch_board.load_older":"Incarca mai vechi","dispatch_board.loading":"Se incarca...","dispatch_board.loading_options":"Se incarca optiunile...","dispatch_board.minutes_overdue":"{minutes}m peste termen","dispatch_board.no_options":"Nicio optiune disponibila","dispatch_board.refresh":"Reimprospatare","dispatch_board.retry":"Reincercare","dispatch_board.select_driver":"Selecteaza Sofer","dispatch_board.select_truck":"Selecteaza Camion","dispatch_board.subtitle":"Panou Dispecer","dispatch_board.title":"Panou Dispecer","dispatch_board.transition_error":"Eroare la mutarea din {old_status} in {new_status}.","dispatch_board.transition_success":"Mutare realizata cu succes la statutul {new_status}.","dispatch_board.trip_id_prefix":"#","dispatch_board.truck_not_found":"Camion negasit.","dispatch_board.unavailable_overlap":"Indisponibil: se suprapune cu cursa {trip_ref}",
    "driver_manager.add_driver":"Adauga Sofer","driver_manager.cancel":"Anulare","driver_manager.col_active":"Activ","driver_manager.col_hire_date":"Data Angajarii","driver_manager.col_id":"ID","driver_manager.col_license":"Permis","driver_manager.col_license_expiry":"Expirare Permis","driver_manager.col_medical_expiry":"Expirare Medical","driver_manager.col_name":"Nume","driver_manager.col_phone":"Telefon","driver_manager.col_salary":"Salariu","driver_manager.col_truck":"Camion","driver_manager.confirm_delete":"Sigur doriti sa stergeti acest sofer?","driver_manager.delete_driver":"Sterge Soferul","driver_manager.edit_driver":"Editeaza Sofer","driver_manager.export_csv":"Exporta CSV","driver_manager.export_success":"Export realizat cu succes.","driver_manager.field_active":"Activ","driver_manager.field_email":"Email","driver_manager.field_hire_date":"Data Angajarii","driver_manager.field_license_category":"Categorie Permis","driver_manager.field_license_expiry":"Expirare Permis","driver_manager.field_license_number":"Numar Permis","driver_manager.field_medical_expiry":"Expirare Medical","driver_manager.field_monthly_salary":"Salariu Lunar","driver_manager.field_name":"Nume","driver_manager.field_notes":"Observatii","driver_manager.field_phone":"Telefon","driver_manager.kpi_expiring":"In Expirare","driver_manager.kpi_on_trip":"In Cursa","driver_manager.kpi_total":"Total Soferi","driver_manager.kpi_unassigned":"Nealocati","driver_manager.no_driver_selected":"Selectati un sofer","driver_manager.save":"Salvare","driver_manager.search_placeholder":"Cautare...","driver_manager.title":"Manager Soferi","driver_manager.toggle_active":"Comuta Activ","driver_manager.unassigned":"Nealocat",
    "form.duration":"Durata","form.start_date":"Data Inceput","form.status":"Status","form.truck":"Camion",
    "maint.control_panel_title":"Panou Control Mentenanta","maint.filter_severity":"Filtreaza dupa Severitate","maint.no_alerts_filter":"Fara Alerte","maint.refresh":"Reimprospatare",
    "fleet_dashboard.activity_title":"Activitate Flota","fleet_dashboard.activity_view_all":"Vezi Tot","fleet_dashboard.card_avg_profit":"Profit Mediu","fleet_dashboard.card_best_driver":"Cel Mai Bun Sofer","fleet_dashboard.card_best_truck":"Cel Mai Bun Camion","fleet_dashboard.card_consumption":"Consum","fleet_dashboard.card_fuel_cost":"Cost Combustibil","fleet_dashboard.card_highest_fuel":"Cel Mai Mare Consum","fleet_dashboard.card_revenue":"Venituri","fleet_dashboard.card_trips":"Curse","fleet_dashboard.chart_fleet_status":"Status Flota","fleet_dashboard.chart_trip_activity":"Activitate Curse","fleet_dashboard.charts_unavailable":"Grafice Indisponibile","fleet_dashboard.date":"Data","fleet_dashboard.error_msg":"Eroare la incarcarea datelor.","fleet_dashboard.error_title":"Eroare","fleet_dashboard.last_refreshed":"Ultima actualizare","fleet_dashboard.no_data":"Nicio data disponibila","fleet_dashboard.no_driver_data":"Nicio data despre soferi.","fleet_dashboard.refresh":"Reimprospatare","fleet_dashboard.status_active":"Activ","fleet_dashboard.status_cancelled":"Anulat","fleet_dashboard.status_completed":"Finalizat","fleet_dashboard.status_idle":"Inactiv","fleet_dashboard.status_in_progress":"In Desfasurare","fleet_dashboard.status_inactive":"Inactiv","fleet_dashboard.status_maintenance":"In Mentenanta","fleet_dashboard.title":"Dashboard Flota","fleet_dashboard.trips":"Curse",
    "maint_analytics.cost_month":"Cost Lunar","maint_analytics.cost_total":"Cost Total","maint_analytics.cost_year":"Cost Anual","maint_analytics.filter_all":"Toate","maint_analytics.filter_truck":"Camion","maint_analytics.no_data":"Fara date","maint_analytics.section_title":"Analize Mentenanta","maint_analytics.title":"Analize Mentenanta","maint_analytics.type":"Tip",
    "maint_timeline.add_entry":"Adauga Intrare","maint_timeline.cost":"Cost","maint_timeline.date":"Data","maint_timeline.description":"Descriere","maint_timeline.km":"KM","maint_timeline.no_entries":"Nicio intrare","maint_timeline.section_title":"Cronologie Mentenanta","maint_timeline.type":"Tip",
}

# ── Apply all 5 languages ──
# (rest of the translations omitted for brevity - will apply in batches)
all_maps = {"ro": ro}
# ... HU, DE, IT, FR will be added via separate scripts due to size

total = 0
for lang, xmap in all_maps.items():
    fp = os.path.join(path, f"{lang}.json")
    with open(fp, "r", encoding="utf-8") as f:
        d = json.load(f)
    applied = 0
    for fk, tv in xmap.items():
        parts = fk.split(".")
        t = d
        for p in parts[:-1]:
            if p not in t or not isinstance(t[p], dict):
                t[p] = {}
            t = t[p]
        last = parts[-1]
        if last in t:
            t[last] = tv
            applied += 1
    with open(fp, "w", encoding="utf-8") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"{lang}: {applied}")
    total += applied
print(f"Total: {total}")
