"""Shared PySide6 widget wrappers for the Operion ERP Qt branch.

These classes mirror the API of the CustomTkinter wrappers in ``ui/widgets`` so
that view migration is mostly a matter of changing imports. They intentionally do
**not** embed inline stylesheets; appearance is controlled by the global QSS
sheet generated by ``ui.theme_engine.QtTheme``.
"""

from __future__ import annotations

from typing import Callable

from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import (
    QAbstractItemView,
    QCheckBox,
    QComboBox,
    QFrame,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPlainTextEdit,
    QPushButton,
    QRadioButton,
    QScrollArea,
    QSizePolicy,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

from ui.design_tokens import (
    ACCENT,  # noqa: F401
    ACCENT_DIM,  # noqa: F401
    ACCENT_TEXT,  # noqa: F401
    BG_SURFACE,  # noqa: F401
    BORDER_DEFAULT,  # noqa: F401
    RADIUS,  # noqa: F401
    TEXT_MUTED,  # noqa: F401
    TEXT_PRIMARY,  # noqa: F401
)
from ui.design_tokens import SP as S
from ui.styles import Theme
from ui.theme import COLORS

# ──────────────────────────────────────────────────────────────────────────────
# Inputs
# ──────────────────────────────────────────────────────────────────────────────


class StyledLineEdit(QLineEdit):
    """Dark-themed single-line text input.

    Appearance is handled by the global QSS (``QLineEdit`` selector). This
    wrapper only adds convenient defaults and tk-style placeholder support.
    """

    def __init__(
        self,
        parent: QWidget | None = None,
        placeholder: str | None = None,
        height: int = 36,
        text: str = "",
        **kwargs,
    ):
        super().__init__(parent)
        if placeholder:
            self.setPlaceholderText(placeholder)
        if text:
            self.setText(text)
        self.setFixedHeight(height)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)


class StyledTextEdit(QPlainTextEdit):
    """Dark-themed multi-line text input."""

    def __init__(
        self,
        parent: QWidget | None = None,
        height: int | None = None,
        placeholder: str | None = None,
        text: str = "",
        **kwargs,
    ):
        super().__init__(parent)
        if placeholder:
            self.setPlaceholderText(placeholder)
        if text:
            self.setPlainText(text)
        if height:
            self.setFixedHeight(height)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)


class StyledComboBox(QComboBox):
    """Dark-themed dropdown."""

    def __init__(
        self,
        parent: QWidget | None = None,
        values: list[str] | None = None,
        state: str = "normal",
        variable=None,
        **kwargs,
    ):
        super().__init__(parent)
        if values:
            self.addItems(values)
        if state == "readonly":
            self.setEditable(False)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        # ``variable`` is accepted for API compatibility but not used here.
        # Views should connect to currentTextChanged/currentIndexChanged.


# ──────────────────────────────────────────────────────────────────────────────
# Buttons
# ──────────────────────────────────────────────────────────────────────────────


class ActionButton(QPushButton):
    """Styled push button with variants matching the old CTk ActionButton.

    Variants are resolved by the global QSS via the ``variant`` property:
    ``primary`` (default), ``secondary``, ``danger``, ``ghost``, ``success``.
    """

    def __init__(
        self,
        parent: QWidget | None,
        text: str,
        command: Callable | None = None,
        color: str | None = None,
        hover_color: str | None = None,
        width: int | None = None,
        variant: str = "primary",
        **kwargs,
    ):
        super().__init__(text, parent)
        self.setProperty("variant", self._resolve_variant(color, variant))
        if width is not None:
            self.setFixedWidth(width)
        if command:
            self.clicked.connect(command)
        # Explicit color override: only used when a variant cannot be inferred.
        if color and not self._variant_from_color(color):
            self.setStyleSheet(
                f"QPushButton {{ background-color: {color}; }}\n"
                f"QPushButton:hover {{ background-color: {hover_color or color}; }}"
            )

    @staticmethod
    def _variant_from_color(color: str) -> str | None:
        normalized = color.lower()
        if normalized in (COLORS["success"].lower(), Theme.ACCENT_SUCCESS.lower()):
            return "success"
        if normalized == COLORS["danger"].lower():
            return "danger"
        if normalized == COLORS["accent"].lower():
            return "primary"
        return None

    def _resolve_variant(self, color: str | None, variant: str) -> str:
        if color:
            inferred = self._variant_from_color(color)
            if inferred:
                return inferred
        return variant


# ──────────────────────────────────────────────────────────────────────────────
# Selection widgets
# ──────────────────────────────────────────────────────────────────────────────


class StyledCheckBox(QCheckBox):
    """Dark-themed checkbox."""

    toggled_value = Signal(object)

    def __init__(
        self,
        parent: QWidget | None = None,
        text: str = "",
        variable=None,
        onvalue=None,
        offvalue=None,
        **kwargs,
    ):
        super().__init__(text, parent)
        self._onvalue = onvalue
        self._offvalue = offvalue
        if variable is not None:
            # Tk-style variable compatibility: sync the Qt state to the variable.
            self.stateChanged.connect(self._emit_toggled_value)

    def _emit_toggled_value(self, state: int):
        if Qt.CheckState(state) == Qt.Checked:
            self.toggled_value.emit(self._onvalue)
        else:
            self.toggled_value.emit(self._offvalue)


class StyledRadioButton(QRadioButton):
    """Dark-themed radio button."""

    def __init__(self, parent: QWidget | None = None, text: str = "", **kwargs):
        super().__init__(text, parent)


# ──────────────────────────────────────────────────────────────────────────────
# Composite widgets
# ──────────────────────────────────────────────────────────────────────────────


class SectionHeader(QWidget):
    """Section title with an accent label and trailing divider line."""

    def __init__(self, parent: QWidget | None, text: str, _return: bool = False):
        super().__init__(parent)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(S["3"])

        self.label = QLabel(text)
        self.label.setProperty("role", "section-title")
        self.label.style().unpolish(self.label)
        self.label.style().polish(self.label)
        layout.addWidget(self.label)

        line = QFrame()
        line.setProperty("role", "section-line")
        line.setFrameShape(QFrame.HLine)
        line.setFrameShadow(QFrame.Plain)
        layout.addWidget(line, 1)

        if _return:
            # Match the old ``section_header(..., _return=True)`` behavior.
            self.label_returned = self.label


class KpiCard(QFrame):
    """Metric card showing a title and a large value."""

    def __init__(
        self,
        parent: QWidget | None,
        title: str,
        value: str,
    ):
        super().__init__(parent)
        self.setProperty("role", "kpi-card")
        self.setFrameShape(QFrame.StyledPanel)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(S["4"], S["3"], S["4"], S["3"])
        layout.setSpacing(S["1"])

        self.title_label = QLabel(title)
        self.title_label.setProperty("role", "kpi-label")
        self.title_label.style().unpolish(self.title_label)
        self.title_label.style().polish(self.title_label)
        layout.addWidget(self.title_label)

        self.value_label = QLabel(value)
        self.value_label.setProperty("role", "kpi-value")
        self.value_label.style().unpolish(self.value_label)
        self.value_label.style().polish(self.value_label)
        layout.addWidget(self.value_label)

    def set_title(self, text: str) -> None:
        self.title_label.setText(text)

    def set_value(self, text: str) -> None:
        self.value_label.setText(text)


class ScrollableFormContainer(QScrollArea):
    """Scrollable area with a constrained maximum form width.

    Add widgets/layouts to ``.content`` via ``add_widget()`` / ``add_layout()``.
    """

    def __init__(self, parent: QWidget | None = None, max_width: int = 740):
        super().__init__(parent)
        self.setWidgetResizable(True)
        self.setFrameShape(QFrame.NoFrame)

        self.content = QWidget()
        self.content.setMaximumWidth(max_width)
        self.content.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        self.layout = QVBoxLayout(self.content)
        self.layout.setContentsMargins(S["10"], S["6"], S["10"], S["10"])
        self.layout.setSpacing(S["6"])
        self.layout.setAlignment(Qt.AlignTop)

        self.setWidget(self.content)

    def add_widget(self, widget: QWidget, stretch: int = 0) -> None:
        self.layout.addWidget(widget, stretch)

    def add_layout(self, layout, stretch: int = 0) -> None:
        self.layout.addLayout(layout, stretch)

    def add_stretch(self, stretch: int = 1) -> None:
        self.layout.addStretch(stretch)


class TwoColRow(QWidget):
    """Horizontal row split into two equal-width columns."""

    def __init__(self, parent: QWidget | None = None):
        super().__init__(parent)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(S["3"])

        self.left = QWidget()
        self.left.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        self.right = QWidget()
        self.right.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)

        layout.addWidget(self.left, 1)
        layout.addWidget(self.right, 1)

    def left_layout(self) -> QVBoxLayout:
        if self.left.layout() is None:
            self.left.setLayout(QVBoxLayout())
            self.left.layout().setContentsMargins(0, 0, 0, 0)
            self.left.layout().setSpacing(0)
        return self.left.layout()

    def right_layout(self) -> QVBoxLayout:
        if self.right.layout() is None:
            self.right.setLayout(QVBoxLayout())
            self.right.layout().setContentsMargins(0, 0, 0, 0)
            self.right.layout().setSpacing(0)
        return self.right.layout()


# ──────────────────────────────────────────────────────────────────────────────
# Compatibility helpers
# ──────────────────────────────────────────────────────────────────────────────


def section_header(parent: QWidget, text: str, _return: bool = False):
    """Factory matching the old ``ui.widgets.section_header`` signature."""
    header = SectionHeader(parent, text, _return=_return)
    if _return:
        return header.label_returned
    return header


def kpi_card(parent: QWidget, title: str, value: str) -> KpiCard:
    """Factory matching the old ``ui.widgets.kpi_card`` signature."""
    return KpiCard(parent, title, value)


def themed_combobox(parent: QWidget, **kwargs) -> StyledComboBox:
    """Factory matching the old ``ui.widgets.themed_combobox`` signature."""
    return StyledComboBox(parent, **kwargs)


def field(
    parent: QWidget,
    label_text: str,
    widget: QWidget,
    helper_text: str = "",
) -> QWidget:
    """Form field helper: label + input widget + optional helper text.

    Returns a container widget so callers can add it directly to a layout.
    """
    container = QWidget(parent)
    layout = QVBoxLayout(container)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(S["1"])

    label = QLabel(label_text)
    label.setProperty("role", "field-label")
    label.style().unpolish(label)
    label.style().polish(label)
    layout.addWidget(label)

    layout.addWidget(widget)

    if helper_text:
        helper = QLabel(helper_text)
        helper.setProperty("role", "muted")
        helper.style().unpolish(helper)
        helper.style().polish(helper)
        layout.addWidget(helper)

    return container


# ──────────────────────────────────────────────────────────────────────────────
# Table
# ──────────────────────────────────────────────────────────────────────────────


class StyledTableWidget(QTableWidget):
    """Dark-themed read-only table with sort support and selection helpers.

    Columns are specified as ``(id, label, width)`` tuples. The last column
    stretches to fill remaining horizontal space.
    """

    rowSelected = Signal(dict)
    rowDoubleClicked = Signal(dict)
    headerClicked = Signal(int, str)

    def __init__(
        self,
        parent: QWidget | None = None,
        columns: list[tuple] | None = None,
        formatters: dict[str, Callable] | None = None,
    ):
        super().__init__(parent)
        self._columns: list[tuple] = columns or []
        self._column_ids: list[str] = []
        self._data: list[dict] = []
        self._formatters: dict[str, Callable] = formatters or {}
        self._alignments: dict[str, Qt.AlignmentFlag] = {}

        self.setAlternatingRowColors(True)
        self.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.setSelectionMode(QAbstractItemView.SingleSelection)
        self.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.setShowGrid(False)
        self.verticalHeader().setVisible(False)
        self.setSortingEnabled(False)
        # The first column is the implicit default sort.  When sorting is
        # enabled at the end of ``set_data`` without an explicit sort
        # indicator, Qt falls back to column 0 ascending.  Mirror that
        # here so ``_data`` and the visual rows line up from the start.
        if self._columns:
            header = self.horizontalHeader()
            header.setSortIndicator(0, Qt.AscendingOrder)
        # Keep the in-memory data list aligned with the visual row order
        # whenever the user (or code) changes the sort indicator.
        self.horizontalHeader().sortIndicatorChanged.connect(
            self._on_sort_indicator_changed
        )

        self.cellClicked.connect(self._emit_selection)
        self.cellDoubleClicked.connect(self._emit_double_click)
        self.horizontalHeader().sectionClicked.connect(self._on_section_clicked)

        if self._columns:
            self._apply_columns()

    def _apply_columns(self) -> None:
        self.setColumnCount(len(self._columns))
        self._column_ids = []
        labels = []
        for i, (cid, label, width) in enumerate(self._columns):
            self._column_ids.append(cid)
            labels.append(label)
            self.setColumnWidth(i, width)
        self.setHorizontalHeaderLabels(labels)
        if self._columns:
            self.horizontalHeader().setStretchLastSection(True)
            self.horizontalHeader().setSortIndicator(0, Qt.AscendingOrder)

    def _sort_key(self, cid: str):
        """Return a key function that orders ``None`` last and everything
        else by natural comparison.  Used for both ``set_data`` and
        ``_on_sort_indicator_changed``.
        """
        def key(row: dict):
            value = row.get(cid)
            if value is None:
                # Tuple ordering: ``(True, ...)`` sorts after ``(False, ...)``
                # in ascending order, so ``None`` always sinks to the
                # bottom regardless of direction.
                return (True, "")
            return (False, value)
        return key

    def _sort_rows(self, rows: list[dict]) -> list[dict]:
        """Return a copy of *rows* sorted by the table's current sort
        indicator.  Returns the input list unchanged if the indicator
        points past the last column.  This is independent of whether
        ``setSortingEnabled`` is currently true — the indicator is
        always consulted so callers can call us from ``set_data``
        before sorting is enabled.
        """
        if not rows:
            return rows
        header = self.horizontalHeader()
        section = header.sortIndicatorSection()
        order = header.sortIndicatorOrder()
        if section < 0 or section >= len(self._column_ids):
            return list(rows)
        cid = self._column_ids[section]
        reverse = order == Qt.DescendingOrder
        return sorted(rows, key=self._sort_key(cid), reverse=reverse)

    def _on_sort_indicator_changed(
        self, logical_index: int, order: Qt.SortOrder
    ) -> None:
        """Reorder ``self._data`` to match the new visual order whenever
        the sort indicator changes (programmatic or user-driven).  Then
        notify listeners of the *currently selected* row (if any) so
        views that cache a selection by row-index can re-validate.
        """
        if not self._data:
            return
        # Capture the data the user has actually selected *before* we
        # re-sort.  The user expects their selection to follow the
        # data item, not the visual row index.
        previous = self.current_row_data()
        self._data = self._sort_rows(self._data)
        # Qt's QTableWidget will re-position the selection to the same
        # data item on its own.  Re-emit ``rowSelected`` so views that
        # cached by data dict (e.g. ``_selected_id``) can re-fetch.
        if previous is not None:
            self.rowSelected.emit(previous)

    def _on_section_clicked(self, logical_index: int) -> None:
        """User clicked a header — Qt will flip the sort indicator.  We
        don't reorder ``_data`` here (the connected
        ``sortIndicatorChanged`` will fire and handle it), but we
        preserve selection across the visual re-sort so the user keeps
        the same logical row highlighted.
        """
        # No-op: ``sortIndicatorChanged`` does the re-order.
        return

    def set_data(self, rows: list[dict]) -> None:
        # ``setSortingEnabled(False)`` would also clear the sort
        # indicator, so we keep the current indicator and just suppress
        # intermediate sorts while populating.
        self.setSortingEnabled(False)
        self.setRowCount(0)
        self._data = self._sort_rows(rows)
        self.setRowCount(len(self._data))
        for r, row in enumerate(self._data):
            for c, cid in enumerate(self._column_ids):
                value = row.get(cid, "")
                fmt = self._formatters.get(cid)
                if fmt is not None and value != "":
                    display = fmt(value)
                else:
                    display = str(value) if value is not None else ""
                item = QTableWidgetItem(display)
                item.setData(Qt.UserRole, value)
                align = self._alignments.get(cid)
                if align is not None:
                    item.setTextAlignment(align)
                self.setItem(r, c, item)
        self.setSortingEnabled(True)

    def set_column_alignment(self, cid: str, alignment: Qt.AlignmentFlag) -> None:
        """Set text alignment for a specific column id."""
        self._alignments[cid] = alignment
        # Re-apply to existing items if data is already loaded
        if not self._data:
            return
        for r, _row in enumerate(self._data):
            if cid in self._column_ids:
                c = self._column_ids.index(cid)
                item = self.item(r, c)
                if item is not None:
                    item.setTextAlignment(alignment)

    def current_row_data(self) -> dict | None:
        row = self.currentRow()
        if 0 <= row < len(self._data):
            return self._data[row]
        return None

    def selected_row_data(self) -> dict | None:
        rows = set()
        for idx in self.selectedIndexes():
            rows.add(idx.row())
        for r in sorted(rows):
            if 0 <= r < len(self._data):
                return self._data[r]
        return None

    def _emit_selection(self, row: int, col: int) -> None:
        if 0 <= row < len(self._data):
            self.rowSelected.emit(self._data[row])

    def _emit_double_click(self, row: int, col: int) -> None:
        if 0 <= row < len(self._data):
            self.rowDoubleClicked.emit(self._data[row])


def styled_table(parent: QWidget, columns: list[tuple]) -> StyledTableWidget:
    """Factory matching ``StyledTableWidget(parent, columns)``."""
    return StyledTableWidget(parent, columns)
