"""Shared PySide6 widget wrappers for the Operion ERP Qt branch.

These classes mirror the API of the CustomTkinter wrappers in ``ui/widgets`` so
that view migration is mostly a matter of changing imports. They intentionally do
**not** embed inline stylesheets; appearance is controlled by the global QSS
sheet generated by ``ui.theme_engine.QtTheme``.
"""

from __future__ import annotations

from typing import Callable, List, Optional

from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import (
    QWidget,
    QFrame,
    QLabel,
    QLineEdit,
    QPushButton,
    QCheckBox,
    QRadioButton,
    QComboBox,
    QPlainTextEdit,
    QScrollArea,
    QVBoxLayout,
    QHBoxLayout,
    QSizePolicy,
    QTableWidget,
    QTableWidgetItem,
    QAbstractItemView,
)

from ui.theme import COLORS, S
from ui.styles import Theme


# ──────────────────────────────────────────────────────────────────────────────
# Inputs
# ──────────────────────────────────────────────────────────────────────────────


class StyledLineEdit(QLineEdit):
    """Dark-themed single-line text input.

    Appearance is handled by the global QSS (``QLineEdit`` selector). This
    wrapper only adds convenient defaults and tk-style placeholder support.
    """

    def __init__(
        self,
        parent: Optional[QWidget] = None,
        placeholder: Optional[str] = None,
        height: int = 38,
        text: str = "",
        **kwargs,
    ):
        super().__init__(parent)
        if placeholder:
            self.setPlaceholderText(placeholder)
        if text:
            self.setText(text)
        self.setFixedHeight(height)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)


class StyledTextEdit(QPlainTextEdit):
    """Dark-themed multi-line text input."""

    def __init__(
        self,
        parent: Optional[QWidget] = None,
        height: Optional[int] = None,
        placeholder: Optional[str] = None,
        text: str = "",
        **kwargs,
    ):
        super().__init__(parent)
        if placeholder:
            self.setPlaceholderText(placeholder)
        if text:
            self.setPlainText(text)
        if height:
            self.setFixedHeight(height)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)


class StyledComboBox(QComboBox):
    """Dark-themed dropdown."""

    def __init__(
        self,
        parent: Optional[QWidget] = None,
        values: Optional[List[str]] = None,
        state: str = "normal",
        variable=None,
        **kwargs,
    ):
        super().__init__(parent)
        if values:
            self.addItems(values)
        if state == "readonly":
            self.setEditable(False)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        # ``variable`` is accepted for API compatibility but not used here.
        # Views should connect to currentTextChanged/currentIndexChanged.


# ──────────────────────────────────────────────────────────────────────────────
# Buttons
# ──────────────────────────────────────────────────────────────────────────────


class ActionButton(QPushButton):
    """Styled push button with variants matching the old CTk ActionButton.

    Variants are resolved by the global QSS via the ``variant`` property:
    ``primary`` (default), ``secondary``, ``danger``, ``ghost``, ``success``.
    """

    def __init__(
        self,
        parent: Optional[QWidget],
        text: str,
        command: Optional[Callable] = None,
        color: Optional[str] = None,
        hover_color: Optional[str] = None,
        width: Optional[int] = None,
        variant: str = "primary",
        **kwargs,
    ):
        super().__init__(text, parent)
        self.setProperty("variant", self._resolve_variant(color, variant))
        if width is not None:
            self.setFixedWidth(width)
        if command:
            self.clicked.connect(command)
        # Explicit color override: only used when a variant cannot be inferred.
        if color and not self._variant_from_color(color):
            self.setStyleSheet(
                f"QPushButton {{ background-color: {color}; }}\n"
                f"QPushButton:hover {{ background-color: {hover_color or color}; }}"
            )

    @staticmethod
    def _variant_from_color(color: str) -> Optional[str]:
        normalized = color.lower()
        if normalized in (COLORS["success"].lower(), Theme.ACCENT_SUCCESS.lower()):
            return "success"
        if normalized == COLORS["danger"].lower():
            return "danger"
        if normalized == COLORS["accent"].lower():
            return "primary"
        return None

    def _resolve_variant(self, color: Optional[str], variant: str) -> str:
        if color:
            inferred = self._variant_from_color(color)
            if inferred:
                return inferred
        return variant


# ──────────────────────────────────────────────────────────────────────────────
# Selection widgets
# ──────────────────────────────────────────────────────────────────────────────


class StyledCheckBox(QCheckBox):
    """Dark-themed checkbox."""

    toggled_value = Signal(object)

    def __init__(
        self,
        parent: Optional[QWidget] = None,
        text: str = "",
        variable=None,
        onvalue=None,
        offvalue=None,
        **kwargs,
    ):
        super().__init__(text, parent)
        self._onvalue = onvalue
        self._offvalue = offvalue
        if variable is not None:
            # Tk-style variable compatibility: sync the Qt state to the variable.
            self.stateChanged.connect(self._emit_toggled_value)

    def _emit_toggled_value(self, state: int):
        if Qt.CheckState(state) == Qt.Checked:
            self.toggled_value.emit(self._onvalue)
        else:
            self.toggled_value.emit(self._offvalue)


class StyledRadioButton(QRadioButton):
    """Dark-themed radio button."""

    def __init__(self, parent: Optional[QWidget] = None, text: str = "", **kwargs):
        super().__init__(text, parent)


# ──────────────────────────────────────────────────────────────────────────────
# Composite widgets
# ──────────────────────────────────────────────────────────────────────────────


class SectionHeader(QWidget):
    """Section title with an accent label and trailing divider line."""

    def __init__(self, parent: Optional[QWidget], text: str, _return: bool = False):
        super().__init__(parent)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(S["3"])

        self.label = QLabel(text)
        self.label.setProperty("fontRole", "section")
        layout.addWidget(self.label)

        line = QFrame()
        line.setProperty("role", "section-line")
        line.setFrameShape(QFrame.HLine)
        line.setFrameShadow(QFrame.Plain)
        layout.addWidget(line, 1)

        if _return:
            # Match the old ``section_header(..., _return=True)`` behavior.
            self.label_returned = self.label


class KpiCard(QFrame):
    """Metric card showing a title and a large value."""

    def __init__(
        self,
        parent: Optional[QWidget],
        title: str,
        value: str,
    ):
        super().__init__(parent)
        self.setProperty("role", "kpi-card")
        self.setFrameShape(QFrame.StyledPanel)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(S["4"], S["3"], S["4"], S["3"])
        layout.setSpacing(S["1"])

        self.title_label = QLabel(title)
        self.title_label.setProperty("fontRole", "kpi-title")
        layout.addWidget(self.title_label)

        self.value_label = QLabel(value)
        self.value_label.setProperty("fontRole", "kpi-value")
        layout.addWidget(self.value_label)

    def set_title(self, text: str) -> None:
        self.title_label.setText(text)

    def set_value(self, text: str) -> None:
        self.value_label.setText(text)


class ScrollableFormContainer(QScrollArea):
    """Scrollable area with a constrained maximum form width.

    Add widgets/layouts to ``.content`` via ``add_widget()`` / ``add_layout()``.
    """

    def __init__(self, parent: Optional[QWidget] = None, max_width: int = 720):
        super().__init__(parent)
        self.setWidgetResizable(True)
        self.setFrameShape(QFrame.NoFrame)

        self.content = QWidget()
        self.content.setMaximumWidth(max_width)
        self.content.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        self.layout = QVBoxLayout(self.content)
        self.layout.setContentsMargins(S["5"], S["4"], S["5"], S["4"])
        self.layout.setSpacing(S["4"])
        self.layout.setAlignment(Qt.AlignTop)

        self.setWidget(self.content)

    def add_widget(self, widget: QWidget, stretch: int = 0) -> None:
        self.layout.addWidget(widget, stretch)

    def add_layout(self, layout, stretch: int = 0) -> None:
        self.layout.addLayout(layout, stretch)

    def add_stretch(self, stretch: int = 1) -> None:
        self.layout.addStretch(stretch)


class TwoColRow(QWidget):
    """Horizontal row split into two equal-width columns."""

    def __init__(self, parent: Optional[QWidget] = None):
        super().__init__(parent)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(S["3"])

        self.left = QWidget()
        self.left.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        self.right = QWidget()
        self.right.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)

        layout.addWidget(self.left, 1)
        layout.addWidget(self.right, 1)

    def left_layout(self) -> QVBoxLayout:
        if self.left.layout() is None:
            self.left.setLayout(QVBoxLayout())
            self.left.layout().setContentsMargins(0, 0, 0, 0)
            self.left.layout().setSpacing(0)
        return self.left.layout()

    def right_layout(self) -> QVBoxLayout:
        if self.right.layout() is None:
            self.right.setLayout(QVBoxLayout())
            self.right.layout().setContentsMargins(0, 0, 0, 0)
            self.right.layout().setSpacing(0)
        return self.right.layout()


# ──────────────────────────────────────────────────────────────────────────────
# Compatibility helpers
# ──────────────────────────────────────────────────────────────────────────────


def section_header(parent: QWidget, text: str, _return: bool = False):
    """Factory matching the old ``ui.widgets.section_header`` signature."""
    header = SectionHeader(parent, text, _return=_return)
    if _return:
        return header.label_returned
    return header


def kpi_card(parent: QWidget, title: str, value: str) -> KpiCard:
    """Factory matching the old ``ui.widgets.kpi_card`` signature."""
    return KpiCard(parent, title, value)


def themed_combobox(parent: QWidget, **kwargs) -> StyledComboBox:
    """Factory matching the old ``ui.widgets.themed_combobox`` signature."""
    return StyledComboBox(parent, **kwargs)


def field(
    parent: QWidget,
    label_text: str,
    widget: QWidget,
    helper_text: str = "",
) -> QWidget:
    """Form field helper: label + input widget + optional helper text.

    Returns a container widget so callers can add it directly to a layout.
    """
    container = QWidget(parent)
    layout = QVBoxLayout(container)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(S["1"])

    label = QLabel(label_text)
    label.setProperty("fontRole", "label")
    layout.addWidget(label)

    layout.addWidget(widget)

    if helper_text:
        helper = QLabel(helper_text)
        helper.setProperty("fontRole", "helper")
        layout.addWidget(helper)

    return container


# ──────────────────────────────────────────────────────────────────────────────
# Table
# ──────────────────────────────────────────────────────────────────────────────


class StyledTableWidget(QTableWidget):
    """Dark-themed read-only table with sort support and selection helpers.

    Columns are specified as ``(id, label, width)`` tuples. The last column
    stretches to fill remaining horizontal space.
    """

    rowSelected = Signal(dict)
    rowDoubleClicked = Signal(dict)
    headerClicked = Signal(int, str)

    def __init__(
        self,
        parent: Optional[QWidget] = None,
        columns: Optional[List[tuple]] = None,
    ):
        super().__init__(parent)
        self._columns: List[tuple] = columns or []
        self._column_ids: List[str] = []
        self._data: List[dict] = []

        self.setAlternatingRowColors(True)
        self.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.setSelectionMode(QAbstractItemView.SingleSelection)
        self.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.setShowGrid(False)
        self.verticalHeader().setVisible(False)
        self.setSortingEnabled(False)

        self.cellClicked.connect(self._emit_selection)
        self.cellDoubleClicked.connect(self._emit_double_click)

        if self._columns:
            self._apply_columns()

    def _apply_columns(self) -> None:
        self.setColumnCount(len(self._columns))
        self._column_ids = []
        labels = []
        for i, (cid, label, width) in enumerate(self._columns):
            self._column_ids.append(cid)
            labels.append(label)
            self.setColumnWidth(i, width)
        self.setHorizontalHeaderLabels(labels)
        if self._columns:
            self.horizontalHeader().setStretchLastSection(True)

    def set_data(self, rows: List[dict]) -> None:
        self._data = rows
        self.setSortingEnabled(False)
        self.setRowCount(0)
        self.setRowCount(len(rows))
        for r, row in enumerate(rows):
            for c, cid in enumerate(self._column_ids):
                value = row.get(cid, "")
                item = QTableWidgetItem(str(value) if value is not None else "")
                self.setItem(r, c, item)
        self.setSortingEnabled(True)

    def current_row_data(self) -> Optional[dict]:
        row = self.currentRow()
        if 0 <= row < len(self._data):
            return self._data[row]
        return None

    def selected_row_data(self) -> Optional[dict]:
        rows = set()
        for idx in self.selectedIndexes():
            rows.add(idx.row())
        for r in sorted(rows):
            if 0 <= r < len(self._data):
                return self._data[r]
        return None

    def _emit_selection(self, row: int, col: int) -> None:
        if 0 <= row < len(self._data):
            self.rowSelected.emit(self._data[row])

    def _emit_double_click(self, row: int, col: int) -> None:
        if 0 <= row < len(self._data):
            self.rowDoubleClicked.emit(self._data[row])


def styled_table(parent: QWidget, columns: List[tuple]) -> StyledTableWidget:
    """Factory matching ``StyledTableWidget(parent, columns)``."""
    return StyledTableWidget(parent, columns)
