"""MFA (TOTP two-factor) — users mfa columns + single-use backup codes.

Adds the ``users.mfa_enabled`` / ``users.mfa_secret`` columns (SQLite side
of the Gate-34 A3a schema; ``database/schema_pg.sql`` already carries them
in its ``users`` DDL) and creates the ``mfa_backup_codes`` table for the
bcrypt-hashed, atomically-claimed single-use recovery codes.

Idempotent by design (mirrors n7f8a9b0c1d4 / p1q2r3s4t5u7):
  - the column adds are guarded by ``_column_exists`` — ``schema_pg.sql``
    pre-creates both columns on the PostgreSQL deployment path BEFORE
    Alembic runs, so an unconditional ``op.add_column`` would abort the
    chain on a fresh PostgreSQL database;
  - the table create is guarded by ``_table_exists`` — ``schema_pg.sql``
    also pre-creates ``mfa_backup_codes`` (CREATE TABLE IF NOT EXISTS), so
    on the deployment path this migration is a no-op; on pure-Alembic
    databases it creates the table.

The SQLite test harness inspects the resulting schema only (no INSERTs), so
``sa.Identity()`` (compiled to ``BIGINT GENERATED BY DEFAULT AS IDENTITY``
on PostgreSQL and ``BIGINT PRIMARY KEY`` on SQLite) is safe.  Real SQLite
deployments get the table from ``database/schema.py``/``db_manager``
(``INTEGER PRIMARY KEY AUTOINCREMENT``).

Revision ID: q0r1s2t3u4v8
Revises: p1q2r3s4t5u7
Create Date: 2026-09-19
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "q0r1s2t3u4v8"
down_revision: Union[str, Sequence[str], None] = "p1q2r3s4t5u7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Helpers ────────────────────────────────────────────────────────────────


def _column_exists(table: str, column: str) -> bool:
    """True when *column* already exists on *table* (engine-agnostic)."""
    from sqlalchemy import inspect

    conn = op.get_bind()
    try:
        insp = inspect(conn)
        columns = [c["name"] for c in insp.get_columns(table)]
        return column in columns
    except Exception:
        return False


def _table_exists(table: str) -> bool:
    """True when *table* already exists in the database."""
    from sqlalchemy import inspect

    conn = op.get_bind()
    try:
        return table in inspect(conn).get_table_names()
    except Exception:
        return False


# ── Migration ──────────────────────────────────────────────────────────────


def upgrade() -> None:
    """Add MFA columns to users and create the backup-codes table."""
    # users.mfa_enabled / users.mfa_secret — added only when absent
    # (schema_pg.sql pre-creates them on the deployment path).
    if not _column_exists("users", "mfa_enabled"):
        op.add_column(
            "users",
            sa.Column("mfa_enabled", sa.Integer(), nullable=False, server_default="0"),
        )
    if not _column_exists("users", "mfa_secret"):
        op.add_column(
            "users",
            sa.Column("mfa_secret", sa.Text(), nullable=True),
        )

    # mfa_backup_codes — created only when absent (schema_pg.sql pre-creates
    # it on the deployment path).
    if _table_exists("mfa_backup_codes"):
        return
    op.create_table(
        "mfa_backup_codes",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index(
        "idx_mfa_backup_codes_user", "mfa_backup_codes", ["user_id"]
    )


def downgrade() -> None:
    """Drop the backup-codes table and the users MFA columns."""
    if _table_exists("mfa_backup_codes"):
        op.drop_index("idx_mfa_backup_codes_user", table_name="mfa_backup_codes")
        op.drop_table("mfa_backup_codes")
    if _column_exists("users", "mfa_secret"):
        op.drop_column("users", "mfa_secret")
    if _column_exists("users", "mfa_enabled"):
        op.drop_column("users", "mfa_enabled")