#!/usr/bin/env node
// Self-host script for the website's fonts (Inter + JetBrains Mono).
//
// Fetches the Google Fonts CSS with a modern browser User-Agent (required to
// get the subsetted woff2 URLs instead of full ttf), parses every @font-face
// block, downloads each woff2 into public/fonts/, and emits a local
// public/fonts/fonts.css that mirrors the upstream rules (font-family,
// font-style, font-weight, unicode-range, font-display: swap) but points at
// /fonts/... local files.
//
// Zero runtime deps — uses global fetch (Node >= 18) + node:fs.
// Idempotent: files that already exist as valid woff2 are skipped, and when the
// same upstream file is reused across weights (Google serves the variable font
// once per subset), it is copied to the per-weight filename instead of
// downloaded again.
//
// Usage:  node scripts/fetch-fonts.mjs
// Output: public/fonts/*.woff2  +  public/fonts/fonts.css

import { mkdirSync, writeFileSync, existsSync, readFileSync, copyFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const fontsDir = join(__dirname, "..", "public", "fonts")
const outCss = join(fontsDir, "fonts.css")

const FONTS_URL =
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap"

// Modern browser UA — Google serves ttf (full fonts) to curl/default UAs and
// woff2 (subsetted) to real browser UAs.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"

const WOFF2_MAGIC = Buffer.from([0x77, 0x4f, 0x46, 0x32]) // "wOF2"

function familySlug(family) {
  return family
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

async function main() {
  console.log(`Fetching font CSS: ${FONTS_URL}`)
  const res = await fetch(FONTS_URL, { headers: { "user-agent": UA } })
  if (!res.ok) throw new Error(`fonts.googleapis.com returned HTTP ${res.status}`)
  const css = await res.text()

  // Google prefixes every @font-face with a /* subset */ comment.
  const blockRe = /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*{([^}]*)}/g
  const blocks = []
  let m
  while ((m = blockRe.exec(css)) !== null) {
    const subset = m[1].trim()
    const body = m[2]
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1]
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1]
    const style = /font-style:\s*([^;]+)/.exec(body)?.[1]?.trim() ?? "normal"
    const unicodeRange = /unicode-range:\s*([^;]+)/.exec(body)?.[1]?.trim()
    const url = /src:\s*url\(([^)]+)\)/.exec(body)?.[1]
    if (!family || !weight || !url || !unicodeRange) {
      console.warn(`  skipping malformed @font-face (subset=${subset})`)
      continue
    }
    blocks.push({ subset, family, weight, style, unicodeRange, url })
  }
  if (blocks.length === 0) throw new Error("no @font-face blocks parsed from font CSS")
  console.log(`Parsed ${blocks.length} @font-face rules from Google Fonts CSS`)

  mkdirSync(fontsDir, { recursive: true })

  const downloaded = new Map() // url -> first local filename (dedupe across weights)
  let downloads = 0
  let copies = 0

  const fileNameFor = (b) => `${familySlug(b.family)}-${b.weight}-${b.subset}.woff2`

  for (const b of blocks) {
    const filename = fileNameFor(b)
    const localPath = join(fontsDir, filename)
    const valid =
      existsSync(localPath) && readFileSync(localPath).subarray(0, 4).equals(WOFF2_MAGIC)

    const prior = downloaded.get(b.url)
    if (prior && prior !== filename) {
      // Same upstream file (variable font) reused across weights for a subset.
      copyFileSync(join(fontsDir, prior), localPath)
      copies++
    } else if (!valid) {
      const data = Buffer.from(await (await fetch(b.url, { headers: { "user-agent": UA } })).arrayBuffer())
      if (data.length < 4 || !data.subarray(0, 4).equals(WOFF2_MAGIC)) {
        throw new Error(`downloaded file is not a woff2: ${filename} (${data.length} bytes)`)
      }
      writeFileSync(localPath, data)
      downloads++
      downloaded.set(b.url, filename)
    }
  }

  // Re-emit the stylesheet with local URLs.
  const rules = blocks.map((b) => {
    const filename = fileNameFor(b)
    return [
      `@font-face {`,
      `  font-family: '${b.family}';`,
      `  font-style: ${b.style};`,
      `  font-weight: ${b.weight};`,
      `  font-display: swap;`,
      `  src: url(/fonts/${filename}) format('woff2');`,
      `  unicode-range: ${b.unicodeRange};`,
      `}`,
    ].join("\n")
  })
  writeFileSync(outCss, `/* Generated by scripts/fetch-fonts.mjs — do not edit. */\n${rules.join("\n\n")}\n`, "utf8")

  console.log(
    `Wrote ${outCss} (${blocks.length} @font-face rules; ${downloads} files downloaded, ${copies} copied to per-weight names)`
  )
}

main().catch((err) => {
  console.error("fetch-fonts failed:", err.message)
  process.exit(1)
})
