#!/usr/bin/env python3
"""Translate all remaining untranslated keys in fr.json to French."""
from __future__ import annotations

import json, os

BASE = os.path.join(os.path.dirname(__file__), os.pardir, "data", "translations")
FR_PATH = os.path.join(BASE, "fr.json")
EN_PATH = os.path.join(BASE, "en.json")

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def flatten(d, prefix=""):
    items = {}
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            items.update(flatten(v, key))
        else:
            items[key] = v
    return items

def set_nested(d, key_parts, value):
    cur = d
    for p in key_parts[:-1]:
        cur = cur.setdefault(p, {})
    cur[key_parts[-1]] = value

fr_data = load_json(FR_PATH)
en_data = load_json(EN_PATH)
en_flat = flatten(en_data)
fr_flat = flatten(fr_data)

# Find untranslated keys (fr value == en value)
untranslated = {k for k in en_flat if k in fr_flat and isinstance(fr_flat[k], str) and fr_flat[k] == en_flat[k]}
print(f"Untranslated before mapping: {len(untranslated)}")

# ============================================================
# COMPREHENSIVE FRENCH TRANSLATION MAPPING
# ============================================================
EXPLICIT = {
    # ---- about ----
    "about.page_title": "À propos - Operion ERP",
    "about.page_header": "À propos d'Operion",
    "about.page_header_desc": "Nous construisons l'avenir du logiciel de logistique d'entreprise.",
    "about.story_title": "Notre histoire",
    "about.story_p1": "Operion a été fondée en 2024 avec une mission claire : rendre les logiciels de logistique de niveau entreprise accessibles aux flottes de toutes tailles.",
    "about.story_p2": "Notre équipe combine des décennies d'expérience en logistique, en génie logiciel et en IA pour construire des outils qui résolvent des problèmes concrets.",
    "about.story_p3": "Aujourd'hui, Operion alimente des flottes dans toute l'Europe, les aidant à planifier plus intelligemment, à répartir plus rapidement et à se développer davantage.",
    "about.values_title": "Nos valeurs",
    "about.values_desc": "Les principes qui guident chacune de nos décisions.",
    "about.value_customer_title": "Le client d'abord",
    "about.value_customer_desc": "Chaque fonctionnalité que nous construisons commence par les besoins réels et les retours des clients.",
    "about.value_reliability_title": "Fiabilité",
    "about.value_reliability_desc": "Vos opérations dépendent de notre logiciel. Nous prenons cette responsabilité très au sérieux.",
    "about.value_innovation_title": "Innovation",
    "about.value_innovation_desc": "Nous investissons massivement en R&D pour apporter une IA et une optimisation de pointe à la logistique.",
    "about.value_transparency_title": "Transparence",
    "about.value_transparency_desc": "Tarification claire, communication honnête et aucun frais caché.",
    "about.value_security_title": "Sécurité",
    "about.value_security_desc": "Chiffrement de niveau entreprise, conformité RGPD et audits de sécurité réguliers.",
    "about.value_partnership_title": "Partenariat",
    "about.value_partnership_desc": "Nous ne vendons pas seulement un logiciel. Nous nous associons à nos clients pour leur réussite.",
    "about.team_title": "Notre équipe",
    "about.team_desc": "Notre équipe combine des décennies d'expérience en logistique, en génie logiciel et en IA.",

    # ---- admin ----
    "admin.tab_title": "Panneau d'administration",
    "admin.login_required": "Authentification administrateur requise",
    "admin.login_title": "Connexion administrateur",
    "admin.login_button": "Connexion",
    "admin.login_failed": "Email ou mot de passe invalide.",
    "admin.cancel": "Annuler",
    "admin.email": "Email",
    "admin.password": "Mot de passe",
    "admin.required_fields": "L'email et le mot de passe sont requis.",
    "admin.email_prompt": "Entrez votre email",
    "admin.email_required": "Veuillez saisir votre adresse email.",
    "admin.email_invalid": "Veuillez saisir une adresse email valide.",
    "admin.password_required": "Veuillez saisir votre mot de passe.",
    "admin.next": "Suivant",
    "admin.back": "Retour",
    "admin.diagnostics": "Diagnostics",
    "admin.db_inspector": "Inspecteur de base de données",
    "admin.doc_stats": "Statistiques des documents",
    "admin.system_info": "Informations système",
    "admin.health": "Santé",
    "admin.latency": "Latence",
    "admin.latency_ms": "{value} ms",
    "admin.celery_status": "Statut Celery",
    "admin.redis_status": "Statut Redis",
    "admin.config_flags": "Configuration",
    "admin.active_tasks": "Tâches actives",
    "admin.scheduled_tasks": "Planifiées",
    "admin.queue_size": "Taille de la file d'attente",
    "admin.workers_online": "Travailleurs en ligne",
    "admin.memory_used": "Mémoire utilisée",
    "admin.keys_count": "Clés",
    "admin.hit_rate": "Taux de succès",
    "admin.unavailable": "Indisponible",
    "admin.table_selector": "Sélectionner une table",
    "admin.execute_query": "Exécuter",
    "admin.refresh": "Actualiser",
    "admin.clear_cache": "Vider le cache",
    "admin.cache_cleared": "Cache vidé",
    "admin.rows": "{count} lignes",
    "admin.no_data": "Aucune donnée",
    "admin.query_placeholder": "SELECT * FROM table LIMIT 100",
    "admin.offline": "Serveur inaccessible",
    "admin.total_docs": "Total documents",
    "admin.storage_used": "Stockage utilisé",
    "admin.ocr_coverage": "Couverture OCR",
    "admin.orphan_docs": "Documents orphelins",
    "admin.invalid_query": "Requête invalide",
    "admin.query_error": "Erreur de requête",
    "admin.forbidden": "Accès refusé",
    "admin.connected_label": "Connecté :",
    "admin.db_engine_label": "Moteur BD :",
    "admin.environment_label": "Environnement :",
    "admin.api_version_label": "Version API :",
    "admin.debug_mode_label": "Mode débogage :",
    "admin.python_version_label": "Version Python",
    "admin.db_path_label": "Chemin BD",
    "admin.platform_label": "Plateforme",
    "admin.email_placeholder": "admin@exemple.com",
    "admin.password_placeholder": "············",

    # ---- analytics ----
    "analytics.tab_client": "Clients",
    "analytics.tab_document": "Documents",
    "analytics.col_km": "KM",
    "analytics.group_total": "Total",
    "analytics.group_top3": "Top 3",
    "analytics.group_clients": "Clients",
    "analytics.waterfall_net": "Net",
    "analytics.distance_km": "Distance (km)",
    "analytics.distance_label": "Distance (km)",
    "analytics.kpi_revenue_concentration": "Concentration",

    # ---- app ----
    "app.subtitle": "ERP",

    # ---- auth ----
    "auth.login_title": "Connexion — Operion ERP",
    "auth.login_back": "Retour à l'accueil",
    "auth.login_brand": "Operion",
    "auth.login_welcome": "Bon retour",
    "auth.login_subtitle": "Connectez-vous à votre compte Operion",
    "auth.email_label": "Email",
    "auth.email_placeholder": "vous@entreprise.com",
    "auth.password_label": "Mot de passe",
    "auth.forgot_password": "Mot de passe oublié ?",
    "auth.password_placeholder": "Entrez votre mot de passe",
    "auth.hide_password": "Masquer le mot de passe",
    "auth.show_password": "Afficher le mot de passe",
    "auth.signing_in": "Connexion en cours…",
    "auth.sign_in": "Se connecter",
    "auth.no_account": "Vous n'avez pas de compte ?",
    "auth.sign_up_link": "S'inscrire",
    "auth.signed_in_success": "Connecté avec succès !",
    "auth.sign_in_failed": "Échec de la connexion",
    "auth.validation_invalid_email": "Veuillez saisir un email valide",
    "auth.validation_password_required": "Le mot de passe est requis",
    "auth.validation_password_max": "Le mot de passe doit faire au maximum 72 caractères",
    "auth.register_title": "Créer un compte — Operion ERP",
    "auth.register_back": "Retour à l'accueil",
    "auth.register_brand": "Operion",
    "auth.register_welcome": "Créez votre compte",
    "auth.register_subtitle": "Démarrez votre essai gratuit de 14 jours",
    "auth.name_label": "Nom complet",
    "auth.name_placeholder": "Jean Dupont",
    "auth.company_label": "Nom de l'entreprise (optionnel)",
    "auth.company_placeholder": "Acme SARL",
    "auth.password_min_hint": "Au moins 8 caractères",
    "auth.confirm_password_label": "Confirmer le mot de passe",
    "auth.confirm_password_placeholder": "Répétez votre mot de passe",
    "auth.creating_account": "Création du compte…",
    "auth.create_account": "Créer un compte",
    "auth.has_account": "Vous avez déjà un compte ?",
    "auth.sign_in_link": "Se connecter",
    "auth.account_created": "Compte créé avec succès !",
    "auth.create_account_failed": "Échec de la création du compte",
    "auth.validation_name_min": "Le nom doit contenir au moins 2 caractères",
    "auth.validation_password_min": "Le mot de passe doit contenir au moins 8 caractères",
    "auth.validation_passwords_match": "Les mots de passe ne correspondent pas",

    # ---- automation ----
    "automation.attachments_empty": "Pièces jointes vides",
    "automation.body_label": "Corps :",
    "automation.browse_title": "Parcourir",
    "automation.cancelled": "Annulé",
    "automation.confirm_delete_title": "Supprimer cette exécution et son fichier traité ?",
    "automation.continue_to_email": "Continuer vers l'email",
    "automation.copy_run": "Copier le chemin",
    "automation.delete_run": "🗑 Supprimer",
    "automation.detail_title": "Sélectionnez une exécution pour voir les détails",
    "automation.download_done": "Paquet sauvegardé dans :\n{path}",
    "automation.download_empty": "Aucun document à mettre en paquet.",
    "automation.download_pdf": "📄 Télécharger le PDF combiné",
    "automation.download_run": "📥 Télécharger",
    "automation.download_zip": "📦 Télécharger ZIP",
    "automation.draft_saved_title": "Brouillon sauvegardé",
    "automation.drop_title": "Déposez les images ou PDF ici",
    "automation.email_title": "Envoyer le paquet client",
    "automation.err_bad_to": "L'adresse email n'est pas valide.",
    "automation.err_no_to": "Veuillez saisir une adresse de destinataire.",
    "automation.mode_advanced": "Avancé",
    "automation.mode_label": "Mode :",
    "automation.mode_simple": "Simple",
    "automation.no_docs_msg": "Il n'y a aucun document à envoyer. Annulez et exécutez d'abord l'automatisation.",
    "automation.no_docs_title": "Aucun document",
    "automation.package_create_error": "Erreur interne : échec de la création de la ligne de paquet",
    "automation.package_empty": "(Aucun document lié à ce trajet pour l'instant)",
    "automation.package_subtitle": "Paquet pour {trip}",
    "automation.package_title": "Préparer le paquet client",
    "automation.prepare_package": "Préparer le paquet client",
    "automation.refresh": "Actualiser",
    "automation.related_docs": "Documents liés :",
    "automation.save_draft": "Sauvegarder le brouillon",
    "automation.save_pdf": "Enregistrer le document sous…",
    "automation.search_trips": "Rechercher tous les trajets…",
    "automation.select_trip": "Sélectionnez un trajet pour lier ce document :",
    "automation.send": "Envoyer",
    "automation.send_documents": "Envoyer les documents",
    "automation.sending": "Envoi en cours…",
    "automation.skip_package": "Ignorer — Créer un paquet",
    "automation.standalone_title": "Paquet autonome",
    "automation.subject_label": "Objet :",
    "automation.tab_title": "Automatisation",
    "automation.title": "Automatisation des documents",
    "automation.to_label": "À :",
    "automation.to_placeholder": "Saisissez l'adresse email…",
    "automation.trip_not_found": "Trajet introuvable",
    "automation.err_read_input": "Impossible de lire l'entrée : {}",
    "automation.err_database": "Erreur de base de données : {}",
    "automation.err_processing": "Échec du traitement : {}",
    "automation.err_ocr": "Échec OCR : {}",
    "automation.err_ocr_persist": "Échec de la persistance OCR",
    "automation.err_match_persist": "Échec de la persistance de correspondance",
    "automation.err_grouping": "Échec du regroupement : {}",
    "automation.err_grouping_no_doc": "Le regroupement n'a produit aucun document",
    "automation.no_match": "Aucun trajet correspondant — exécution terminée sans pièce jointe",
    "automation.imported": "Importé {} ({} octets)",
    "automation.processing_complete": "Amélioré → {} ({} pages, {} images)",
    "automation.ocr_complete": "OCR terminé : {} caractères, confiance={}%, moteur={}",
    "automation.match_found": "Correspondance : trajet #{} confiance={}% ({} candidats)",
    "automation.match_manual": "Correspondance nécessitant une sélection manuelle ({} candidats)",
    "automation.simple_done": "Mode simple : traitement terminé, en attente d'action utilisateur",
    "automation.linked_doc": "Document #{} lié au trajet #{}",
    "automation.preview_trip_format": "Trajet #{} — {} ({} → {})",
    "automation.err_matching": "Échec de la correspondance : {}",
    "automation.scanned_title": "Scanné — {}",
    "automation.run_label": "Exécution #{}",
    "automation.label_status": "Statut :",
    "automation.label_stage": "Étape :",
    "automation.label_matched_trip": "Trajet correspondant :",
    "automation.label_extracted_fields": "Champs extraits :",
    "automation.label_top_candidates": "Meilleurs candidats :",
    "automation.label_document": "Doc #{}",
    "automation.err_standalone_failed": "Échec de la création du document autonome. Vérifiez que le PDF traité existe sur le disque.",
    "automation.err_package_failed": "Échec de la construction du paquet. Veuillez réessayer.",
    "automation.simple_awaiting": "Document traité — choisissez une action ci-dessous.",
    "automation.simple_select_trip": "Sélectionnez éventuellement un trajet pour associer ce document :",

    # ---- client ----
    "client.billed": "Facturé",
    "client.paid": "Payé",
    "client.unpaid": "Impayé",
    "client.overdue": "En retard",
    "client.table_name": "Nom",
    "client.table_contact": "Personne de contact",
    "client.table_phone": "Téléphone",
    "client.table_email": "Email",
    "client.table_trips": "Trajets",
    "client.table_revenue": "Revenus",
    "client.table_outstanding": "Impayé",
    "client.table_inv_number": "Facture n°",
    "client.table_amount": "Montant",
    "client.table_due_date": "Date d'échéance",
    "client.table_inv_status": "Statut",
    "client.field_name": "Nom du client *",
    "client.field_contact": "Personne de contact",
    "client.field_phone": "Téléphone",
    "client.field_email": "Email",
    "client.field_address": "Adresse",
    "client.field_vat": "Numéro de TVA",
    "client.field_notes": "Notes",
    "client.title": "Clients",
    "client.new_button": "Nouveau client",
    "client.edit_button": "Modifier",
    "client.deactivate_button": "Désactiver",
    "client.deactivate_confirm": "Désactiver '{name}' ?",
    "client.deactivate_trips_warning": "\n({count} trajet(s) lié(s) — les trajets seront conservés)",
    "client.edit_title": "Modifier le client",
    "client.new_title": "Nouveau client",
    "client.save_button": "Enregistrer",
    "client.name_required": "Le nom est requis.",
    "client.already_exists": "Le client '{name}' existe déjà.",
    "client.select_hint": "Sélectionnez un client pour voir les détails",
    "client.filter_active": "Tout afficher",
    "client.section_trips": "Trajets récents",
    "client.section_invoices": "Factures impayées",
    "client.section_contacts": "Contacts",
    "client.section_tags": "Étiquettes",
    "client.section_chart": "Tendance des revenus",
    "client.section_timeline": "Chronologie d'activité",
    "client.section_payment": "Récapitulatif des paiements",
    "client.no_trips": "Aucun trajet trouvé pour ce client.",
    "client.no_invoices": "Aucune facture impayée pour ce client.",
    "client.kpi_total_revenue": "Revenu total",
    "client.kpi_total_trips": "Total trajets",
    "client.kpi_total_km": "Distance totale",
    "client.kpi_last_30d": "Trajets (30j)",
    "client.kpi_total_profit": "Bénéfice total",
    "client.kpi_avg_profit": "Bénéfice moyen/trajet",
    "client.kpi_outstanding": "Impayé",
    "client.kpi_last_trip": "Dernier trajet",
    "client.field_type": "Type de client",
    "client.field_payment_terms": "Conditions de paiement (jours)",
    "client.field_credit_limit": "Plafond de crédit (EUR)",
    "client.field_default_rate": "Tarif par défaut/km",
    "client.field_rating": "Évaluation (1-5)",
    "client.field_full_name": "Nom complet *",
    "client.field_title": "Titre du poste",
    "client.field_contact_type": "Type de contact",
    "client.tag_placeholder": "Ajouter une étiquette…",
    "client.no_tags": "Aucune étiquette attribuée.",
    "client.no_data_export": "Aucune donnée client à exporter.",
    "client.csv_saved": "Clients exportés avec succès.",
    "client.export_csv": "Export CSV",
    "client.merge_button": "Fusionner",
    "client.merge_title": "Fusionner les clients",
    "client.merge_source": "Fusionner depuis : {name}",
    "client.merge_target_label": "Vers le client cible :",
    "client.merge_warning": "Tous les trajets, factures, contacts et étiquettes seront déplacés vers le client cible. Le client source sera désactivé. Cette action est irréversible.",
    "client.merge_final_confirm": "Fusionner toutes les données de '{source}' vers '{target}' ?",
    "client.merge_execute": "Exécuter la fusion",
    "client.new_contact": "Nouveau contact",
    "client.edit_contact": "Modifier le contact",
    "client.confirm_delete_contact": "Supprimer ce contact ?",
    "client.add_contact": "Ajouter un contact",
    "client.section_kpis": "KPI",
    "client.tab_details": "Détails",
    "client.tab_trips": "Trajets",
    "client.tab_invoices": "Factures",
    "client.tab_revenue": "Revenus",
    "client.vat": "TVA :",
    "client.terms_days": "Conditions : {} jours",
    "client.limit_eur": "Plafond : {:,} €",
    "client.phone": "📞",
    "client.email_icon": "✉",
    "client.trip_timeline": "Trajet : {} — {} / {} — {} km",
    "client.invoice_timeline": "Facture : {} — {} — {} EUR ({})",

    # ---- cmr ----
    "cmr.place_of_loading": "Lieu de chargement",
    "cmr.destination": "Destination",
    "cmr.vehicle": "Véhicule",
    "cmr.goods_description": "Désignation des marchandises",
    "cmr.gross_weight": "Poids brut (kg)",
    "cmr.cmr_number": "Numéro CMR",
    "cmr.title": "Lettre de voiture CMR internationale",
    "cmr.subtitle": "Convention relative au contrat de transport international de marchandises par route (CMR)",
    "cmr.select_role": "Sélectionnez votre rôle pour préremplir le formulaire",
    "cmr.role_consignor": "Je suis l'expéditeur",
    "cmr.role_consignee": "Je suis le destinataire",
    "cmr.section_parties": "Parties au contrat",
    "cmr.consignor": "Expéditeur / Chargeur",
    "cmr.consignee": "Destinataire",
    "cmr.section_parties_sub": "Cases 1-2",
    "cmr.section_route": "Itinéraire et documents annexes",
    "cmr.section_route_sub": "Cases 3-5",
    "cmr.locality_country": "Localité / Pays",
    "cmr.date": "Date",
    "cmr.loading_country": "Pays de chargement",
    "cmr.delivery_country": "Pays de livraison",
    "cmr.documents": "Documents annexés",
    "cmr.section_vehicle": "Véhicule et conducteur",
    "cmr.section_vehicle_sub": "Cases 6-7",
    "cmr.truck_plate": "Plaque du camion",
    "cmr.trailer_plate": "Plaque de la remorque",
    "cmr.driver_name": "Nom du conducteur",
    "cmr.driver_license": "Permis de conduire",
    "cmr.section_cargo": "Description de la marchandise",
    "cmr.section_cargo_sub": "Cases 8-14",
    "cmr.adr_toggle": "Marchandises dangereuses ADR",
    "cmr.add_adr": "+ Ajouter une entrée ADR",
    "cmr.section_instructions": "Instructions et réserves",
    "cmr.section_instructions_sub": "Cases 13-17",
    "cmr.sender_instructions": "Instructions (transport, douane, assurance)",
    "cmr.carrier_reservations": "Réserves et observations du transporteur",
    "cmr.payment_instruction": "Instruction de paiement",
    "cmr.cod": "Remboursement (COD)",
    "cmr.amount_eur": "Montant (EUR)",
    "cmr.special_agreements": "Conventions spéciales",
    "cmr.distance": "Distance (km)",
    "cmr.distance_placeholder": "Distance totale du transport",
    "cmr.section_carrier": "Transporteur",
    "cmr.section_carrier_sub": "Cases 18-19",
    "cmr.carrier": "Transporteur",
    "cmr.successive_carriers": "Transporteurs successifs",
    "cmr.add_successive_carrier": "+ Ajouter un transporteur successif",
    "cmr.section_charges": "Frais (Case 20)",
    "cmr.section_charges_sub": "L'expéditeur paie / Le destinataire paie",
    "cmr.cost_type": "Type de coût",
    "cmr.sender": "Expéditeur",
    "cmr.consignee_short": "Destinataire",
    "cmr.section_issue": "Établissement et signatures",
    "cmr.section_issue_sub": "Cases 21-24",
    "cmr.established_in": "Établi à",
    "cmr.place": "Lieu",
    "cmr.city_country": "Ville / Pays",
    "cmr.sig_sender": "Signature — Expéditeur",
    "cmr.sig_carrier": "Signature — Transporteur",
    "cmr.sig_consignee": "Signature — Destinataire",
    "cmr.generate": "Générer le CMR",
    "cmr.print": "Imprimer",
    "cmr.save": "Enregistrer",
    "cmr.distance_km": "Distance (km)",
    "cmr.vat_cui": "TVA/CUI :",
    "cmr.vat": "TVA :",
    "cmr.eori": "EORI :",
    "cmr.tel": "Tél :",
    "cmr.contact": "Contact :",
    "cmr.email": "Email :",
    "cmr.reg_no": "N° d'enregistrement :",
    "cmr.consignor_placeholder": "Nom, adresse, pays",
    "cmr.consignee_placeholder": "Nom, adresse, pays",
    "cmr.documents_placeholder": "Listez les documents annexés",
    "cmr.label_name": "Nom",
    "cmr.label_address": "Adresse",
    "cmr.label_country": "Pays",
    "cmr.label_plate": "Plaque",
    "cmr.label_trailer": "Remorque",
    "cmr.label_driver": "Conducteur",
    "cmr.label_from": "De",
    "cmr.label_to": "À",

    # ---- common ----
    "common.no_data": "Aucune donnée",

    # ---- date_picker ----
    "date_picker.open_calendar": "Ouvrir le calendrier",
    "date_picker.select_date": "Sélectionner la date",

    # ---- dispatch_board ----
    "dispatch_board.col_cancelled": "Annulé",
    "dispatch_board.bulk_clear_selection": "Effacer",
    "dispatch_board.detail_trip_id": "ID du trajet",
    "dispatch_board.undo_nothing": "Rien à annuler",
    "dispatch_board.redo_nothing": "Rien à rétablir",
    "dispatch_board.no_results_subtitle": "Essayez d'ajuster vos critères de recherche ou de filtre",

    # ---- docs ----
    "docs.cat_all": "Tous",
    "docs.cat_maintenance": "Maintenance",
    "docs.cat_invoices": "Factures",
    "docs.cat_trips": "Trajets",
    "docs.cat_drivers": "Conducteurs",
    "docs.cat_vehicles": "Véhicules",
    "docs.cat_other": "Autre",
    "docs.tab_documents": "Documents",
    "docs.tab_proforma": "Proforma",
    "docs.cat_proformas": "Proformas",
    "docs.cat_receipts": "Reçus",
    "docs.entity_documents_title": "Documents — {title}",
    "docs.entity_documents_default": "Documents de l'entité",
    "docs.title": "CENTRE DE DOCUMENTS",
    "docs.upload": "UPLOADER",
    "docs.upload_title": "Sélectionnez les fichiers à uploader",
    "docs.view": "Voir",
    "docs.delete": "Supprimer",
    "docs.confirm_delete_title": "Supprimer le document",
    "docs.confirm_delete_msg": "Supprimer '{name}' ?\nCela supprimera le fichier et tous ses liens.",
    "docs.search_placeholder": "Rechercher des documents…",
    "docs.select_document": "Sélectionnez un document pour voir les détails",
    "docs.no_documents": "Aucun document trouvé",
    "docs.prev": "<",
    "docs.next": ">",
    "docs.sort_newest": "Plus récents d'abord",
    "docs.sort_oldest": "Plus anciens d'abord",
    "docs.sort_name_az": "Nom A-Z",
    "docs.sort_name_za": "Nom Z-A",
    "docs.sort_size_lg": "Plus grands d'abord",
    "docs.sort_size_sm": "Plus petits d'abord",
    "docs.filters": "Filtres",
    "docs.filter_apply": "Appliquer les filtres",
    "docs.filter_clear": "Effacer les filtres",
    "docs.filter_entity": "Type d'entité :",
    "docs.filter_date_from": "Date de début :",
    "docs.filter_date_to": "Date de fin :",
    "docs.filter_type": "Type de fichier :",
    "docs.details": "Détails",
    "docs.tags_label": "Étiquettes :",
    "docs.add_tag": "Ajouter une étiquette…",
    "docs.linked_to": "Lié à :",
    "docs.email": "Email",
    "docs.email_title": "Envoyer le document par email",
    "docs.email_prompt": "Adresse email du destinataire :",
    "docs.email_sent": "Email envoyé avec succès.",
    "docs.download_zip": "Télécharger en ZIP",
    "docs.archive": "Archiver",
    "docs.unlink": "Délier",
    "docs.batch_delete": "Supprimer la sélection",
    "docs.batch_select_all": "Tout sélectionner",
    "docs.expiry_label": "Date d'expiration :",
    "docs.set_expiry": "Définir",
    "docs.versions_label": "Versions :",
    "docs.restore": "Restaurer",
    "docs.upload_version": "Uploader une nouvelle version",
    "docs.confirm_restore": "Restaurer la version",
    "docs.confirm_restore_msg": "Restaurer la version {v} ? La version actuelle sera remplacée.",
    "docs.contract": "Créer un contrat",
    "docs.contract_type": "Type de contrat :",
    "docs.generate_cmr": "Générer un CMR",
    "docs.expiry_saved": "Date d'expiration enregistrée",
    "docs.version_comment": "Commentaire",
    "docs.version_error": "Erreur de version",
    "docs.version_uploaded": "Version uploadée",
    "docs.filter_date_range": "Plage de dates :",
    "docs.invalid_document_data": "Données de document invalides.",
    "docs.link_to_trip": "Lier à un trajet…",
    "docs.link_to_trip_done": "Document lié au trajet.",
    "docs.link_to_trip_exists": "Déjà lié.",
    "docs.ocr_fields": "Extrait",
    "docs.ocr_last_run": "Dernière exécution",
    "docs.ocr_not_run": "L'OCR n'a pas encore été exécuté sur ce document.",
    "docs.ocr_section": "OCR",
    "docs.pick_trip_empty": "Aucun trajet ne correspond à votre filtre.",
    "docs.pick_trip_placeholder": "Tapez pour filtrer…",
    "docs.pick_trip_search": "Rechercher :",
    "docs.pick_trip_title": "Choisir un trajet",
    "docs.rerun_ocr": "Relancer l'OCR",
    "docs.rerun_ocr_done": "OCR terminé",
    "docs.rerun_ocr_started": "OCR lancé…",
    "docs.select_trip": "Sélectionner",

    # ---- document ----
    "document.batch_deleted": "{n} documents supprimés",
    "document.deleted": "Document supprimé",
    "document.downloaded_zip": "Téléchargé en ZIP",
    "document.emailed": "Document envoyé par email",
    "document.version_added": "Nouvelle version ajoutée",
    "document.version_restored": "Version restaurée",

    # ---- driver_manager ----
    "driver_manager.export_success": "Conducteurs exportés",

    # ---- email_logs ----
    "email_logs.col_id": "ID",

    # ---- features ----
    "features.page_title": "Fonctionnalités - Operion ERP",
    "features.page_header": "Fonctionnalités puissantes pour la logistique moderne",
    "features.page_header_desc": "Tout ce dont vous avez besoin pour gérer votre flotte efficacement, de la planification d'itinéraires aux analyses.",
    "features.category_route_planning": "Planification et optimisation d'itinéraires",
    "features.route_planning_title": "Planification d'itinéraire intelligente",
    "features.route_planning_desc": "Des algorithmes avancés optimisent le temps, la distance, le carburant et les péages à travers l'Europe.",
    "features.multi_stop_title": "Optimisation multi-arrêts",
    "features.multi_stop_desc": "Planifiez des itinéraires complexes avec jusqu'à 50 points de passage et un séquencement automatisé.",
    "features.traffic_title": "Intégration trafic en temps réel",
    "features.traffic_desc": "Les itinéraires s'adaptent dynamiquement en fonction des conditions de trafic et des fermetures de routes.",
    "features.category_fleet": "Gestion de flotte",
    "features.gps_tracking_title": "Suivi GPS en temps réel",
    "features.gps_tracking_desc": "Surveillez la position, la vitesse et le statut de chaque véhicule sur une carte interactive.",
    "features.maintenance_title": "Suivi de maintenance véhicule",
    "features.maintenance_desc": "Planifiez et suivez la maintenance avec des alertes automatisées pour les inspections, assurances et services.",
    "features.geofencing_title": "Géorepérage et alertes",
    "features.geofencing_desc": "Définissez des zones géographiques et recevez des notifications instantanées lorsque les véhicules entrent ou sortent des zones.",
    "features.category_dispatch": "Répartition et opérations",
    "features.auto_assign_title": "Assignation automatisée des tâches",
    "features.auto_assign_desc": "Faites correspondre les tâches aux meilleurs conducteurs et camions disponibles selon la localisation, les compétences et la conformité.",
    "features.pod_title": "Preuve de livraison numérique",
    "features.pod_desc": "Capturez les signatures, photos et horodatages à la livraison pour une preuve de livraison complète.",
    "features.status_updates_title": "Mises à jour de statut en temps réel",
    "features.status_updates_desc": "Suivez chaque tâche de l'assignation à l'achèvement avec des mises à jour de statut en direct.",
    "features.category_documents": "Gestion des documents",
    "features.ocr_ai_title": "OCR alimenté par l'IA",
    "features.ocr_ai_desc": "Scannez et numérisez les factures, CMR, reçus et contrats avec OCR alimenté par l'IA.",
    "features.digital_archive_title": "Archive numérique",
    "features.digital_archive_desc": "Stockez et recherchez tous les documents avec historique des versions, étiquettes et recherche en texte intégral.",
    "features.auto_invoicing_title": "Facturation automatisée",
    "features.auto_invoicing_desc": "Générez automatiquement des factures à partir des données de livraison et envoyez-les par email aux clients.",
    "features.category_analytics": "Analytique et rapports",
    "features.dashboards_title": "Tableaux de bord personnalisés",
    "features.dashboards_desc": "Construisez des vues personnalisées avec des KPI, des graphiques et des données en temps réel.",
    "features.kpi_title": "Suivi des KPI",
    "features.kpi_desc": "Surveillez les indicateurs clés de performance incluant le bénéfice par km, l'efficacité carburant et la performance des conducteurs.",
    "features.export_title": "Export et intégration",
    "features.export_desc": "Exportez les rapports en plusieurs formats et intégrez-les avec votre ERP existant et votre logiciel comptable.",
    "features.category_drivers": "Gestion des conducteurs",
    "features.driver_profiles_title": "Profils des conducteurs",
    "features.driver_profiles_desc": "Base de données complète des conducteurs avec permis, certificats médicaux, contrats et documents.",
    "features.driver_performance_title": "Suivi des performances",
    "features.driver_performance_desc": "Surveillez l'efficacité des conducteurs, les scores de sécurité, la conformité tachygraphe et les heures de conduite.",
    "features.schedule_title": "Gestion des plannings",
    "features.schedule_desc": "Planifiez les quarts de travail des conducteurs, gérez la disponibilité et suivez les heures de travail.",

    # ---- file_filter ----
    "file_filter.all": "Tous les fichiers",
    "file_filter.images": "Images",

    # ---- generators ----
    "generators.tab_invoice": "Facture",
    "generators.tab_cmr": "CMR",
    "generators.doc_receipt_title": "Reçu",
    "generators.title": "Générateurs de documents",
    "generators.subtitle": "Créez des factures et des lettres de voiture CMR internationales pour vos trajets.",
    "generators.trip_label": "Trajet :",
    "generators.doc_invoice_title": "Facture",
    "generators.doc_invoice_desc": "Générez une facture PDF professionnelle pour le trajet sélectionné.",
    "generators.doc_cmr_title": "Lettre de voiture CMR",
    "generators.doc_cmr_desc": "Générez une lettre de voiture internationale (CMR) avec les 4 exemplaires.",
    "generators.cmr_title": "Générer la lettre de voiture CMR",
    "generators.cmr_subtitle": "Créez une lettre de voiture CMR internationale pour un trajet sélectionné.",
    "generators.cmr_trip_select": "1. Sélectionnez le trajet :",
    "generators.cmr_options": "2. Remplacements optionnels :",
    "generators.cmr_loading": "Adresse de chargement :",
    "generators.cmr_unloading": "Adresse de déchargement :",
    "generators.cmr_driver": "Nom du conducteur :",
    "generators.cmr_generate": "Générer le CMR",
    "generators.cmr_open": "Ouvrir le PDF",
    "generators.cmr_generated": "CMR généré : {path}",
    "generators.cmr_all_generated": "Tous les exemplaires générés : {path}",
    "generators.cmr_select_trip": "Veuillez d'abord sélectionner un trajet.",
    "generators.cmr_error": "Échec de la génération du CMR : {error}",
    "generators.cmr_primary_language": "Langue principale",
    "generators.cmr_secondary_language": "Langue secondaire",
    "generators.cmr_step_consignment": "Parties à l'expédition",
    "generators.cmr_step_transport": "Détails du transport",
    "generators.cmr_step_cargo": "Détails de la cargaison",
    "generators.cmr_step_instructions": "Instructions et réserves",
    "generators.cmr_step_adr": "Marchandises dangereuses ADR",
    "generators.cmr_step_successive": "Transporteurs successifs",
    "generators.cmr_step_signatures": "Signature et cachet",
    "generators.cmr_generate_all": "Générer les 4 exemplaires",
    "generators.cmr_generate_single": "Générer un seul exemplaire",
    "generators.cmr_copy_sender": "Exemplaire expéditeur",
    "generators.cmr_copy_consignee": "Exemplaire destinataire",
    "generators.cmr_copy_carrier": "Exemplaire transporteur",
    "generators.cmr_copy_admin": "Exemplaire administratif",
    "generators.cmr_not_generated": "non généré",
    "generators.cmr_copies_title": "Exemplaires générés",
    "generators.cmr_options_title": "Options",
    "generators.cmr_actions_title": "Actions",
    "generators.cmr_status_ready": "Prêt à générer.",
    "generators.cmr_status_generating": "Génération des 4 exemplaires…",
    "generators.open_pdf": "Ouvrir",
    "generators.cmr_generated_status": "généré",
    "generators.cmr_trip_title": "CMR Trajet #{}",
    "generators.cmr_copy_title": "CMR Trajet #{} - Exemplaire {}",
    "generators.doc_receipt_title": "Reçu",

    # ---- invoice_editor ----
    "invoice_editor.select_client": "Client :",
    "invoice_editor.select_trip": "Trajet :",
    "invoice_editor.auto_fill": "Remplissage automatique",
    "invoice_editor.from": "De",
    "invoice_editor.bill_to": "Facturer à",
    "invoice_editor.invoice_number": "Facture n°",
    "invoice_editor.issue_date": "Date d'émission",
    "invoice_editor.due_date": "Date d'échéance",
    "invoice_editor.payment_terms": "Conditions de paiement",
    "invoice_editor.description": "Description",
    "invoice_editor.amount": "Montant",
    "invoice_editor.quantity": "Qté",
    "invoice_editor.unit_price": "Prix unitaire",
    "invoice_editor.tax_rate": "Taux de TVA",
    "invoice_editor.tax_rate_short": "TVA%",
    "invoice_editor.total": "Total",
    "invoice_editor.add_row": "Ajouter une ligne",
    "invoice_editor.remove_row": "Supprimer",
    "invoice_editor.duplicate_row": "Dupliquer",
    "invoice_editor.move_up": "Monter",
    "invoice_editor.move_down": "Descendre",
    "invoice_editor.notes": "Notes",
    "invoice_editor.subtotal": "Sous-total",
    "invoice_editor.tax": "TVA",
    "invoice_editor.discount": "Remise",
    "invoice_editor.grand_total": "Total général",
    "invoice_editor.financial_controls": "Contrôles financiers",
    "invoice_editor.tax_preset": "Préréglage TVA",
    "invoice_editor.discount_type": "Type de remise",
    "invoice_editor.discount_value": "Valeur de la remise",
    "invoice_editor.currency": "Devise",
    "invoice_editor.branding": "Marque",
    "invoice_editor.logo": "Logo",
    "invoice_editor.company_color": "Couleur",
    "invoice_editor.signature": "Signature",
    "invoice_editor.stamp": "Cachet",
    "invoice_editor.upload": "Uploader",
    "invoice_editor.pick_color": "Choisir",
    "invoice_editor.pick_color_title": "Choisir la couleur de l'entreprise",
    "invoice_editor.preview_pdf": "Aperçu",
    "invoice_editor.generate_pdf": "Générer le PDF",
    "invoice_editor.print": "Imprimer",
    "invoice_editor.email": "Email",
    "invoice_editor.save_draft": "Sauvegarder le brouillon",
    "invoice_editor.load_draft": "Charger le brouillon",
    "invoice_editor.cancel": "Annuler",
    "invoice_editor.discount_percentage": "Pourcentage",
    "invoice_editor.discount_fixed": "Fixé",
    "invoice_editor.net_30": "Net 30",
    "invoice_editor.net_15": "Net 15",
    "invoice_editor.net_60": "Net 60",
    "invoice_editor.due_on_receipt": " payable à réception",
    "invoice_editor.select_logo": "Sélectionner l'image du logo",
    "invoice_editor.select_signature": "Sélectionner l'image de signature",
    "invoice_editor.select_stamp": "Sélectionner l'image du cachet",
    "invoice_editor.invoice_generated": "Facture générée : {}",
    "invoice_editor.draft_saved": "Brouillon sauvegardé",
    "invoice_editor.draft_saved_msg": "Brouillon '{}' sauvegardé avec succès.",
    "invoice_editor.draft_loaded": "Brouillon chargé",
    "invoice_editor.draft_loaded_msg": "Brouillon '{}' chargé avec succès.",
    "invoice_editor.no_drafts": "Aucun brouillon trouvé.",
    "invoice_editor.draft_name": "Entrez un nom pour ce brouillon :",
    "invoice_editor.default_service": "Services de transport",
    "invoice_editor.email_to": "Email du destinataire",
    "invoice_editor.enter_email": "Entrez l'adresse email du destinataire :",
    "invoice_editor.trip_details": "Détails du trajet",
    "invoice_editor.loading_stops": "Arrêts de chargement",
    "invoice_editor.unloading_stops": "Arrêts de déchargement",
    "invoice_editor.loading_label": "Chargement",
    "invoice_editor.unloading_label": "Déchargement",
    "invoice_editor.add_loading_stop": "Ajouter un arrêt de chargement",
    "invoice_editor.add_unloading_stop": "Ajouter un arrêt de déchargement",
    "invoice_editor.distance": "Distance",
    "invoice_editor.truck_plate": "Plaque du camion",
    "invoice_editor.driver": "Conducteur",
    "invoice_editor.browse": "Parcourir",
    "invoice_editor.title": "Éditeur de facture",
    "invoice_editor.totals": "Totaux",
    "invoice_editor.line_items": "Lignes d'articles",
    "invoice_editor.notes_section": "Notes",
    "invoice_editor.invoice_details": "Détails de la facture",
    "invoice_editor.invoice_metadata": "Métadonnées de la facture",
    "invoice_editor.client_info": "Infos client",
    "invoice_editor.subtitle": "Créez et modifiez des factures professionnelles",
    "invoice_editor.export_json": "Exporter JSON",
    "invoice_editor.branch": "Succursale / Bureau",
    "invoice_editor.number_format": "Format du numéro",

    # ---- login ----
    "login.email_placeholder": "admin@exemple.com",
    "login.password_placeholder": "············",

    # ---- maint ----
    "maint.control_panel_title": "Panneau de contrôle maintenance",
    "maint.schedule_next_due_km": "Prochaine échéance à {km} km",
    "maint.status_overdue": "Statut en retard",
    "maint.status_remaining": "{km} km restants",
    "maint.action_maint": "Action maintenance",
    "maint.action_remind": "Action rappel",
    "maint.action_resolve": "Action résoudre",
    "maint.action_trip": "Action trajet",
    "maint.action_truck": "Action camion",
    "maint.add_record": "Ajouter un enregistrement",
    "maint.alert_plural": "Alertes",
    "maint.alert_s": "Alerte",
    "maint.cancel": "Annuler",
    "maint.close": "Fermer",
    "maint.col_cost": "Coût",
    "maint.col_date": "Date",
    "maint.col_km": "KM",
    "maint.col_notes": "Notes",
    "maint.col_provider": "Fournisseur",
    "maint.col_type": "Type",
    "maint.confirm_delete_msg": "Confirmer la suppression",
    "maint.confirm_delete_title": "Confirmer la suppression",
    "maint.critical_count": "Nombre critique",
    "maint.critical_health": "Santé critique",
    "maint.days_left": "Jours restants",
    "maint.delete": "Supprimer",
    "maint.due_by_date": "À faire pour le",
    "maint.edit": "Modifier",
    "maint.error_generic": "Erreur générique",
    "maint.excellent": "Excellent",
    "maint.export": "Exporter",
    "maint.export_success": "Export réussi",
    "maint.export_title": "Titre d'export",
    "maint.fair": "Correct",
    "maint.filter_label": "Étiquette de filtre",
    "maint.flash_maint_scheduled": "Maintenance planifiée",
    "maint.flash_reminder": "Rappel",
    "maint.flash_trip_copied": "Trajet copié",
    "maint.flash_truck_copied": "Camion copié",
    "maint.form_cost": "Coût",
    "maint.form_date": "Date",
    "maint.form_km": "KM",
    "maint.form_notes": "Notes",
    "maint.form_provider": "Fournisseur de service",
    "maint.form_quick": "Sélection rapide :",
    "maint.form_title_add": "Ajouter un enregistrement",
    "maint.form_title_edit": "Modifier l'enregistrement",
    "maint.form_type": "Type :",
    "maint.form_attachment": "Pièce jointe :",
    "maint.form_no_attachment": "Aucun fichier sélectionné",
    "maint.form_choose_file": "Choisir un fichier",
    "maint.header": "En-tête",
    "maint.info_count": "Nombre d'infos",
    "maint.km_remaining": "KM restants",
    "maint.label_trip": "Trajet",
    "maint.label_truck": "Camion",
    "maint.metric_compliance": "Conformité",
    "maint.metric_downtime": "Temps d'arrêt",
    "maint.metric_overdue": "En retard",
    "maint.metric_recurring": "Récurrent",
    "maint.metric_score": "Score",
    "maint.next": "Suivant",
    "maint.no_alerts_filter": "Aucune alerte",
    "maint.no_records": "Aucun enregistrement",
    "maint.no_schedule": "Aucun planning",
    "maint.no_schedules": "Aucun planning",
    "maint.page_info": "Page {current} sur {total}",
    "maint.predictions": "Prédictions",
    "maint.predictions_header": "En-tête des prédictions",
    "maint.predictions_title": "Titre des prédictions",
    "maint.prev": "Précédent",
    "maint.refresh": "Actualiser",
    "maint.refresh_score": "Actualiser le score",
    "maint.save": "Enregistrer",
    "maint.schedule_add": "Ajouter un planning",
    "maint.schedule_delete_confirm": "Confirmer la suppression du planning",
    "maint.schedule_delete_prompt": "Supprimer le planning ?",
    "maint.schedule_delete_title": "Supprimer le planning",
    "maint.schedule_due_by": "Échéance du planning",
    "maint.schedule_every_km": "Tous les (km)",
    "maint.schedule_every_months": "Tous les (mois)",
    "maint.schedule_expires": "Expiration du planning",
    "maint.schedule_form_expiry": "Expiration du planning",
    "maint.schedule_form_interval_km": "Intervalle (km)",
    "maint.schedule_form_interval_months": "Intervalle (mois)",
    "maint.schedule_form_last_date": "Dernière date",
    "maint.schedule_form_last_km": "Dernier KM",
    "maint.schedule_form_title_add": "Ajouter un planning",
    "maint.schedule_form_title_edit": "Modifier le planning",
    "maint.schedule_last_date": "Dernière date",
    "maint.schedule_last_km": "Dernier KM",
    "maint.status_due_soon": "Bientôt due",
    "maint.status_ok": "Statut OK",
    "maint.tab_health": "Santé",
    "maint.tab_history": "Historique",
    "maint.tab_schedules": "Plannings",
    "maint.target_km": "KM cible",
    "maint.title": "Titre",
    "maint.updated": "Mis à jour",
    "maint.warning_count": "Nombre d'avertissements",
    "maint.filter_severity": "Filtrer par gravité",
    "maint.filter_trip": "Filtrer par trajet",
    "maint.filter_truck": "Filtrer par camion",
    "maint.filter_type": "Filtrer par type",
    "maint.show_resolved": "Afficher les résolus",
    "maint.avg_health": "Santé moyenne",
    "maint.due_service": "Service dû",
    "maint.overdue": "En retard",
    "maint.cost_30d": "Coût (30j)",
    "maint.total_cost_kpi": "Coût total",
    "maint.severity_critical": "Critique",
    "maint.severity_warning": "Avertissement",
    "maint.severity_info": "Info",
    "maint.due_by_km": "Dû par KM",
    "maint.section_status": "Statut",
    "maint.section_alerts": "Alertes",
    "maint.health_overall": "Santé globale",
    "maint.health_compliance": "Conformité",
    "maint.health_overdue": "En retard",
    "maint.health_recurring": "Problèmes récurrents",
    "maint.col_description": "Description",
    "maint.col_interval_days": "Intervalle (jours)",
    "maint.col_interval_km": "Intervalle (km)",
    "maint.col_mileage": "Kilométrage",
    "maint.col_next_date": "Prochaine date",
    "maint.col_next_mileage": "Prochain kilométrage",
    "maint.health_downtime": "Temps d'arrêt",
    "maint.health_no_data": "Aucune donnée de santé disponible",
    "maint.health_ok": "Tous les systèmes sont nominaux",
    "maint.control_panel_subtitle": "Plannings de maintenance et surveillance de la santé",
    "maint.filter_placeholder": "Filtrer…",
    "maint.unit_km": " km",
    "maint.unit_months": " mois",
    "maint.due_by_date": "À faire pour le",

    # ---- maint_analytics ----
    "maint_analytics.month_jan": "Jan",
    "maint_analytics.month_feb": "Fév",
    "maint_analytics.month_mar": "Mar",
    "maint_analytics.month_apr": "Avr",
    "maint_analytics.month_may": "Mai",
    "maint_analytics.month_jun": "Juin",
    "maint_analytics.month_jul": "Juil",
    "maint_analytics.month_aug": "Aoû",
    "maint_analytics.month_sep": "Sep",
    "maint_analytics.month_oct": "Oct",
    "maint_analytics.month_nov": "Nov",
    "maint_analytics.month_dec": "Déc",
    "maint_analytics.filter_all": "Tous",
    "maint_analytics.filter_truck": "Camion",
    "maint_analytics.type": "Type",
    "maint_analytics.subtitle": "Coûts et tendances de maintenance de la flotte",
    "maint_analytics.section_title": "Analytique de maintenance",
    "maint_analytics.cost_month": "Coût par mois",
    "maint_analytics.cost_year": "Coût par an",
    "maint_analytics.cost_total": "Coût total",

    # ---- maint_timeline ----
    "maint_timeline.add_entry": "Ajouter une entrée",
    "maint_timeline.date": "Date",
    "maint_timeline.km": "KM",
    "maint_timeline.type": "Type",
    "maint_timeline.cost": "Coût",
    "maint_timeline.description": "Description",
    "maint_timeline.no_entries": "Aucune entrée",
    "maint_timeline.title": "Chronologie maintenance",
    "maint_timeline.section_title": "Chronologie maintenance",
    "maint_timeline.detail_title": "Détail de l'entrée",
    "maint_timeline.field_cost": "Coût",
    "maint_timeline.field_date": "Date",
    "maint_timeline.field_km": "KM",
    "maint_timeline.field_notes": "Notes",
    "maint_timeline.field_provider": "Fournisseur",
    "maint_timeline.field_type": "Type",

    # ---- notification ----
    "notification.test_message": "Ceci est une notification de test du moteur d'opérations.",

    # ---- proforma ----
    "proforma.default_description": "Services de transport",

    # ---- proforma_editor ----
    "proforma_editor.title": "Éditeur de facture proforma",
    "proforma_editor.subtitle": "Créez et gérez des factures proforma",
    "proforma_editor.select_client": "Client :",
    "proforma_editor.mode_client": "Mode client",
    "proforma_editor.mode_internal": "Mode interne",
    "proforma_editor.proforma_details": "Détails de la proforma",
    "proforma_editor.proforma_number": "Proforma n°",
    "proforma_editor.issue_date": "Date d'émission",
    "proforma_editor.valid_until": "Valable jusqu'au",
    "proforma_editor.payment_terms": "Conditions de paiement",
    "proforma_editor.client_info": "Infos client",
    "proforma_editor.from": "De",
    "proforma_editor.bill_to": "Facturer à",
    "proforma_editor.description": "Description",
    "proforma_editor.line_items": "Lignes d'articles",
    "proforma_editor.add_row": "Ajouter une ligne",
    "proforma_editor.quantity": "Qté",
    "proforma_editor.unit_price": "Prix unitaire",
    "proforma_editor.total": "Total",
    "proforma_editor.tax_rate": "Taux de TVA",
    "proforma_editor.discount": "Remise",
    "proforma_editor.discount_percentage": "Pourcentage",
    "proforma_editor.discount_fixed": "Fixé",
    "proforma_editor.currency": "Devise",
    "proforma_editor.subtotal": "Sous-total",
    "proforma_editor.tax": "TVA",
    "proforma_editor.grand_total": "Total général",
    "proforma_editor.financial_controls": "Contrôles financiers",
    "proforma_editor.branding": "Marque",
    "proforma_editor.logo": "Logo",
    "proforma_editor.company_color": "Couleur",
    "proforma_editor.signature": "Signature",
    "proforma_editor.stamp": "Cachet",
    "proforma_editor.browse": "Parcourir",
    "proforma_editor.pick_color": "Choisir",
    "proforma_editor.pick_color_title": "Choisir la couleur de l'entreprise",
    "proforma_editor.notes": "Notes",
    "proforma_editor.linked_documents": "Documents liés",
    "proforma_editor.link_document": "Lier un document",
    "proforma_editor.unlink_document": "Délier",
    "proforma_editor.select_document": "Sélectionner un document",
    "proforma_editor.select": "Sélectionner",
    "proforma_editor.cancel": "Annuler",
    "proforma_editor.save": "Enregistrer",
    "proforma_editor.autofill_from_doc": "Remplissage auto. depuis le doc",
    "proforma_editor.autofill_empty": "Aucun texte extractible dans le document sélectionné.",
    "proforma_editor.autofill_done": "Champs remplis automatiquement depuis le document lié.",
    "proforma_editor.autofill_partial": "Le document lié contient du texte mais aucune donnée structurée. Saisie manuelle requise.",
    "proforma_editor.no_docs_available": "Aucun document disponible à lier.",
    "proforma_editor.no_items": "Veuillez ajouter au moins une ligne d'article.",
    "proforma_editor.preview_pdf": "Aperçu",
    "proforma_editor.generate_pdf": "Générer le PDF",
    "proforma_editor.print": "Imprimer",
    "proforma_editor.email": "Email",
    "proforma_editor.email_to": "Email du destinataire",
    "proforma_editor.enter_email": "Entrez l'adresse email du destinataire :",
    "proforma_editor.email_confirm": "Envoyer la proforma par email ?",
    "proforma_editor.include_linked_docs": "Inclure les CMR et factures liés",
    "proforma_editor.email_sent": "Email envoyé avec succès.",
    "proforma_editor.email_failed": "Échec de l'envoi de l'email.",
    "proforma_editor.save_draft": "Sauvegarder le brouillon",
    "proforma_editor.load_draft": "Charger le brouillon",
    "proforma_editor.draft_name": "Entrez un nom pour ce brouillon :",
    "proforma_editor.draft_saved": "Brouillon sauvegardé",
    "proforma_editor.draft_saved_msg": "Brouillon '{}' sauvegardé avec succès.",
    "proforma_editor.draft_save_failed": "Échec de la sauvegarde du brouillon.",
    "proforma_editor.no_drafts": "Aucun brouillon trouvé.",
    "proforma_editor.load": "Charger",
    "proforma_editor.success": "Succès",
    "proforma_editor.error": "Erreur",
    "proforma_editor.proforma_generated": "Proforma générée : {}",
    "proforma_editor.company_editor": "Modifier les infos entreprise",
    "proforma_editor.net_30": "Net 30",
    "proforma_editor.net_15": "Net 15",
    "proforma_editor.net_60": "Net 60",
    "proforma_editor.due_on_receipt": " payable à réception",
    "proforma_editor.select_logo": "Sélectionner l'image du logo",
    "proforma_editor.select_signature": "Sélectionner l'image de signature",
    "proforma_editor.select_stamp": "Sélectionner l'image du cachet",
    "proforma_editor.export_json": "Exporter JSON",
    "proforma_editor.number_format": "Format du numéro",

    # ---- receipt ----
    "receipt.title": "REÇU",
    "receipt.editor.title": "Générateur de reçus",
    "receipt.editor.subtitle": "Créez des reçus professionnels pour paiements, remboursements et dépenses",
    "receipt.editor.generate_pdf": "Générer le PDF",
    "receipt.editor.print": "Imprimer",
    "receipt.editor.save_draft": "Sauvegarder le brouillon",
    "receipt.editor.load_draft": "Charger le brouillon",
    "receipt.editor.duplicate": "Dupliquer",
    "receipt.editor.export_json": "Exporter JSON",
    "receipt.editor.email": "Email",
    "receipt.editor.browse": "Parcourir",
    "receipt.editor.attach_files": "Joindre des fichiers",
    "receipt.editor.select_file": "Sélectionner un fichier",
    "receipt.editor.validation_error": "Erreur de validation",
    "receipt.editor.pdf_generated": "Reçu généré",
    "receipt.editor.pdf_generated_msg": "PDF sauvegardé dans : {path}",
    "receipt.editor.error": "Erreur",
    "receipt.editor.print_no_number": "Aucun numéro de reçu. Générez d'abord.",
    "receipt.editor.print_no_file": "Aucun fichier PDF trouvé. Générez d'abord.",
    "receipt.editor.duplicated": "Reçu dupliqué",
    "receipt.editor.duplicated_msg": "Copie créée avec un nouveau numéro.",
    "receipt.editor.email_placeholder": "Fonctionnalité d'email à venir.",
    "receipt.editor.no_attachments": "Aucun fichier joint.",
    "receipt.editor.draft_name": "Nom du brouillon :",
    "receipt.editor.draft_saved": "Brouillon sauvegardé",
    "receipt.editor.draft_saved_msg": "Brouillon \"{name}\" sauvegardé.",
    "receipt.editor.draft_save_failed": "Échec de la sauvegarde du brouillon.",
    "receipt.editor.no_drafts": "Aucun brouillon sauvegardé.",
    "receipt.editor.load": "Charger",
    "receipt.editor.cancel": "Annuler",
    "receipt.section_type": "TYPE DE REÇU",
    "receipt.section_info": "INFORMATIONS DU REÇU",
    "receipt.section_parties": "PARTIES",
    "receipt.section_payment": "DÉTAILS DU PAIEMENT",
    "receipt.section_logistics": "LOGISTIQUE",
    "receipt.section_purpose": "OBJET",
    "receipt.section_financial": "FINANCIER",
    "receipt.section_employee": "DÉPENSES EMPLOYÉ",
    "receipt.section_attachments": "PIÈCES JOINTES",
    "receipt.section_notes": "NOTES",
    "receipt.section_branding": "MARQUE ET SIGNATURES",
    "receipt.type_customer_payment": "Paiement client",
    "receipt.type_cash_receipt": "Reçu d'encaissement",
    "receipt.type_driver_reimbursement": "Remboursement conducteur",
    "receipt.type_employee_expense": "Remboursement de frais employé",
    "receipt.type_fuel_reimbursement": "Remboursement carburant",
    "receipt.type_toll_reimbursement": "Remboursement péage",
    "receipt.type_miscellaneous": "Dépense diverse d'entreprise",
    "receipt.type_refund": "Remboursement",
    "receipt.type_deposit": "Acompte",
    "receipt.type_advance_payment": "Paiement anticipé",
    "receipt.type_other": "Autre",
    "receipt.number_label": "N° de reçu",
    "receipt.number_placeholder": "Auto-généré",
    "receipt.issue_date_label": "Date d'émission",
    "receipt.issue_date_placeholder": "AAAA-MM-JJ",
    "receipt.payment_date_label": "Date de paiement",
    "receipt.payment_date_placeholder": "AAAA-MM-JJ",
    "receipt.currency_label": "Devise",
    "receipt.language_label": "Langue",
    "receipt.received_from": "Reçu de",
    "receipt.received_by": "Reçu par",
    "receipt.payment_method_label": "Mode de paiement",
    "receipt.reference_number_label": "N° de référence",
    "receipt.transaction_id_label": "ID de transaction",
    "receipt.bank_reference_label": "Référence bancaire",
    "receipt.invoice_reference_label": "Référence facture",
    "receipt.related_trip_label": "Trajet lié",
    "receipt.trip_placeholder": "Trajet n°",
    "receipt.pickup_label": "Lieu d'enlèvement",
    "receipt.delivery_label": "Lieu de livraison",
    "receipt.route_label": "Itinéraire",
    "receipt.dispatcher_label": "Répartiteur",
    "receipt.purpose_label": "Objet",
    "receipt.amount_label": "Montant",
    "receipt.amount_placeholder": "0,00",
    "receipt.amount_helper": "Entrez le montant du paiement",
    "receipt.vat_rate_label": "Taux de TVA (%)",
    "receipt.vat_placeholder": "ex. 19",
    "receipt.vat_helper": "Optionnel",
    "receipt.vat_amount_label": "Montant TVA",
    "receipt.total_label": "Total",
    "receipt.amount_words_label": "Montant en lettres",
    "receipt.words_placeholder": "Auto-calculé",
    "receipt.employee_name_label": "Nom de l'employé",
    "receipt.department_label": "Service",
    "receipt.expense_category_label": "Catégorie de dépense",
    "receipt.mileage_label": "Kilométrage",
    "receipt.fuel_label": "Carburant",
    "receipt.accommodation_label": "Hébergement",
    "receipt.meals_label": "Repas",
    "receipt.parking_label": "Stationnement",
    "receipt.tolls_label": "Péages",
    "receipt.other_label": "Autre",
    "receipt.notes_label": "Notes",
    "receipt.logo_label": "Logo de l'entreprise",
    "receipt.logo_placeholder": "Chemin vers l'image du logo",
    "receipt.signature_label": "Signature",
    "receipt.signature_placeholder": "Chemin vers l'image de signature",
    "receipt.stamp_label": "Cachet de l'entreprise",
    "receipt.stamp_placeholder": "Chemin vers l'image du cachet",
    "receipt.company_signature_label": "Signature de l'entreprise",
    "receipt.recipient_signature_label": "Signature du destinataire",
    "receipt.company_stamp_label": "Cachet de l'entreprise",
    "receipt.generated_by": "Généré par Operion",
    "receipt.validation.amount_required": "Le montant est requis et doit être positif.",
    "receipt.validation.recipient_required": "Le bénéficiaire (Reçu de) est requis.",
    "receipt.validation.number_required": "Le numéro de reçu est requis.",
    "receipt.validation.date_required": "La date d'émission est requise.",
    "receipt.validation.vat_invalid": "Le taux de TVA doit être compris entre 0 et 100.",
    "receipt.validation.date_format": "{field} doit être au format AAAA-MM-JJ.",
    "receipt.customer_label": "Client",
    "receipt.vehicle_label": "Véhicule",
    "receipt.trailer_label": "Remorque",
    "receipt.branch_label": "Succursale / Bureau",
    "receipt.branch_placeholder": "ex. Siège Paris",
    "receipt.export_json": "Exporter JSON",
    "receipt.exported_msg": "Données exportées vers : {path}",
    "receipt.section_invoice_autofill": "REMPlISSAGE RAPIDE DEPUIS FACTURE",
    "receipt.invoice_autofill_label": "Sélectionner une facture",
    "receipt.invoice_autofill_helper": "Sélectionnez une facture pour remplir automatiquement les champs du reçu",
    "receipt.number_format_label": "Format du numéro",
    "receipt.attach_type_label": "Type de pièce jointe",
    "receipt.attach_type_photo": "Photo du reçu",
    "receipt.attach_type_fuel": "Reçu carburant",
    "receipt.attach_type_invoice": "Facture",
    "receipt.attach_type_cmr": "CMR",
    "receipt.attach_type_pod": "POD",
    "receipt.attach_type_document": "Document",
    "receipt.attach_type_image": "Image",
    "receipt.attach_type_other": "Autre",
    "receipt.received_from_placeholder": "Sera complété",
    "receipt.amount_hint": "Entrez un montant ci-dessus",

    # ---- signature ----
    "signature.no_signature": "Aucune signature",
    "signature.accepted": "Signature acceptée",
    "signature.cleaned_up": "Nettoyée",
    "signature.select_title": "Sélectionner l'image de signature",
    "signature.filter_images": "Fichiers image (*.png *.jpg *.jpeg *.bmp);;Tous les fichiers (*.*)",
    "signature.label_selected": "Sélectionné : {}",
    "signature.label_loaded": "Chargé : {}",

    # ---- tacho ----
    "tacho.avg_daily": "Moyenne quotidienne",
    "tacho.subtitle": "Sous-titre tachygraphe",
    "tacho.title": "Tachygraphe",
    "tacho.total_hours": "Heures totales",
    "tacho.type_driver": "Carte conducteur",
    "tacho.type_vehicle": "Unité véhicule",
    "tacho.violations": "Infractions",
    "tacho.unknown_error": "Erreur inconnue",
    "tacho.import_successful": "Import réussi",
    "tacho.result_label": "{label} : {value}",
    "tacho.violations_warning": "{count} infraction(s) détectée(s)",
    "tacho.result_driver": "Conducteur",
    "tacho.result_plate": "Plaque",
    "tacho.result_calibration": "Calibrage",
    "tacho.result_days": "Jours",
    "tacho.result_odometer": "Compteur kilométrique",
    "tacho.hdr_date": "Date",
    "tacho.hdr_file": "Fichier",
    "tacho.hdr_records": "Enregistrements",
    "tacho.hdr_status": "Statut",
    "tacho.hdr_type": "Type",
    "tacho.status_error": "Erreur",
    "tacho.status_ok": "OK",
    "tacho.status_partial": "Partiel",
    "tacho.drop_hint": "Déposez les fichiers ici ou cliquez pour sélectionner",
    "tacho.drop_supported": "DDD / TGD / autres fichiers tachygraphe",
    "tacho.select_file": "Sélectionner un fichier tachygraphe",
    "tacho.history_empty_title": "Aucun import pour l'instant",
    "tacho.history_empty_subtitle": "Importez un fichier tachygraphe pour voir l'historique",
    "tacho.calibration_date": "Date d'étalonnage",
    "tacho.driver_activity_title": "Activité tachygraphe",
    "tacho.expiry": "Expiration",
    "tacho.how_it_works": "1. Le conducteur insère la carte dans le lecteur USB\n2. Exportez le fichier .DDD avec le logiciel du lecteur\n3. Importez le fichier .DDD ici",
    "tacho.import_card_title": "Importer des fichiers",
    "tacho.import_driver_card": "Importer la carte conducteur",
    "tacho.import_history": "Historique d'importation",
    "tacho.import_now": "Importer maintenant",
    "tacho.import_vehicle_unit": "Importer l'unité véhicule",
    "tacho.importing": "Importation en cours",
    "tacho.last_14_days": "14 derniers jours",
    "tacho.last_import": "Dernière importation",
    "tacho.no_activity": "Aucune activité",
    "tacho.no_data": "Aucune donnée",
    "tacho.no_history": "Aucun historique",
    "tacho.no_trucks": "Aucun camion",
    "tacho.recent_violations": "Infractions récentes",
    "tacho.section_status_title": "Statut tachygraphe",
    "tacho.select_driver_card": "Sélectionner la carte conducteur (DDD)",
    "tacho.select_vehicle_unit": "Sélectionner l'unité véhicule (DDD)",
    "tacho.status_expired": "Expiré",
    "tacho.status_no_data": "Aucune donnée",
    "tacho.status_valid": "Valide",

    # ---- text_danger / text_success / text_warning ----
    "text_danger": "Danger",
    "text_success": "Succès",
    "text_warning": "Avertissement",

    # ---- trip ----
    "trip.speed_display": "{speed:.0f} km/h",

    # ---- upload ----
    "upload.title": "Upload et OCR",
    "upload.no_file": "Aucun fichier sélectionné",
    "upload.browse": "Parcourir…",
    "upload.start": "Uploader et lancer l'OCR",
    "upload.too_large_title": "Fichier trop volumineux",
    "upload.too_large_msg": "La taille maximale d'upload est de 50 Mo.",
    "upload.uploading": "Upload en cours…",
    "upload.done": "Upload terminé. Document #{id}",
    "upload.fetching_ocr": "Récupération des résultats OCR…",
    "upload.ocr_done": "OCR terminé.",
    "upload.error": "Erreur",
    "upload.error_title": "Erreur d'upload",
    "upload.extracted_fields": "Champs extraits",
    "upload.select_document": "Sélectionner un document",

    # ---- fleet_dashboard remaining ----
    "fleet_dashboard.activity_title": "Activité de la flotte",
    "fleet_dashboard.activity_view_all": "Voir tout",
    "fleet_dashboard.card_avg_profit": "Bénéfice moyen",
    "fleet_dashboard.card_best_driver": "Meilleur conducteur",
    "fleet_dashboard.card_best_truck": "Meilleur camion",
    "fleet_dashboard.card_consumption": "Consommation",
    "fleet_dashboard.card_fuel_cost": "Coût carburant",
    "fleet_dashboard.card_highest_fuel": "Plus haute consommation",
    "fleet_dashboard.card_revenue": "Revenus",
    "fleet_dashboard.card_trips": "Trajets",
    "fleet_dashboard.chart_fleet_status": "Statut de la flotte",
    "fleet_dashboard.chart_trip_activity": "Activité des trajets",
    "fleet_dashboard.charts_unavailable": "Graphiques indisponibles",
    "fleet_dashboard.date": "Date",
    "fleet_dashboard.error_msg": "Erreur lors du chargement des données.",
    "fleet_dashboard.error_title": "Erreur",
    "fleet_dashboard.last_refreshed": "Dernière actualisation",
    "fleet_dashboard.no_data": "Aucune donnée disponible",
    "fleet_dashboard.no_driver_data": "Aucune donnée conducteur",
    "fleet_dashboard.refresh": "Actualiser",
    "fleet_dashboard.status_active": "Actif",
    "fleet_dashboard.status_cancelled": "Annulé",
    "fleet_dashboard.status_completed": "Terminé",
    "fleet_dashboard.status_idle": "Inactif",
    "fleet_dashboard.status_in_progress": "En cours",
    "fleet_dashboard.status_inactive": "Inactif",
    "fleet_dashboard.status_maintenance": "En maintenance",
    "fleet_dashboard.title": "Tableau de bord de la flotte",
    "fleet_dashboard.trips": "Trajets",

    # ---- form ----
    "form.duration": "Durée",
    "form.start_date": "Date de début",
    "form.status": "Statut",
    "form.truck": "Camion",

    # ---- fuel ----
    "fuel.age_hours": "il y a {n}h",
    "fuel.age_minutes": "il y a {n}m",
    "fuel.age_seconds": "il y a {n}s",
    "fuel.section_title": "Prix du carburant",
    "fuel.updated_status": "Mis à jour : {ts} ({age})",
    "fuel.updated_tooltip": "Prix du carburant mis à jour il y a {minutes} minutes",
    "fuel.no_data": "Aucune donnée carburant",
    "fuel.not_fetched": "Pas encore récupéré",

    # ---- time ----
    "time.days_ago": "il y a {n}j",
    "time.hours_ago": "il y a {n}h",
    "time.just_now": "à l'instant",
    "time.minutes_ago": "il y a {n}m",

    # ---- email_logs ----
    "email_logs.col_recipient": "Destinataire",
    "email_logs.col_subject": "Sujet",
    "email_logs.col_sent": "Envoyé",
    "email_logs.col_status": "Statut",
    "email_logs.no_logs": "Aucun journal trouvé",
    "email_logs.col_id": "ID",

    # ---- alerts ----
    "alerts.severity_info": "Info",

    # ---- settings ----
    "settings.subtitle": "Paramètres de l'application",

    # ---- home ----
    "home.active_alerts": "Alertes actives",
    "home.active_trips": "Trajets actifs",
    "home.no_active_trips": "Aucun trajet actif",
    "home.no_alerts": "Aucune alerte active",
    "home.profit_chart_title": "Bénéfice (30 derniers jours)",
    "home.profit_data_source": "Importé automatiquement depuis Analytics",
    "home.profit_day_label": "Jour",
    "home.profit_no_data": "Aucune donnée de bénéfice disponible.",
    "home.profit_30_days": "30 derniers jours",
    "home.recent_activity": "Activité récente",
    "home.top_trucks": "Meilleurs camions",
    "home.more": "plus",
    "home.feature_route_planning_title": "Planification d'itinéraire intelligente",
    "home.feature_route_planning_desc": "Optimisez les itinéraires en quelques secondes grâce à des algorithmes avancés qui tiennent compte de la distance, du trafic, des coûts de carburant et des fenêtres de livraison.",
    "home.feature_tracking_title": "Suivi de flotte en temps réel",
    "home.feature_tracking_desc": "Surveillez chaque véhicule de votre flotte avec le suivi GPS en direct, le géorepérage et les alertes instantanées.",
    "home.feature_dispatch_title": "Répartition intelligente",
    "home.feature_dispatch_desc": "Assignez les tâches automatiquement en fonction de la disponibilité des conducteurs, du statut des camions et de la proximité.",
    "home.feature_ocr_title": "Traitement OCR de documents",
    "home.feature_ocr_desc": "Numérisez et digitalisez les factures, CMR et reçus avec l'OCR alimenté par IA.",
    "home.feature_analytics_title": "Analytique avancée",
    "home.feature_analytics_desc": "Obtenez des informations exploitables avec des tableaux de bord, des KPI et des rapports personnalisables.",
    "home.feature_driver_title": "Gestion des conducteurs",
    "home.feature_driver_desc": "Gérez les profils des conducteurs, les permis, les certificats médicaux et les performances.",
    "home.benefit_cost_title": "Réduisez les coûts opérationnels",
    "home.benefit_cost_desc": "Réduisez la consommation de carburant jusqu'à 20 % grâce à un routage optimisé, réduisez les temps d'inactivité et minimisez les coûts de maintenance.",
    "home.benefit_speed_title": "Augmentez la vitesse de livraison",
    "home.benefit_speed_desc": "Effectuez plus de livraisons par jour grâce à l'optimisation intelligente des itinéraires et à l'évitement du trafic en temps réel.",
    "home.benefit_paperwork_title": "Éliminez la paperasse",
    "home.benefit_paperwork_desc": "Numérisez tous les documents avec l'OCR, automatisez la facturation et devenez 100 % sans papier.",
    "home.benefit_scale_title": "Évoluez en toute confiance",
    "home.benefit_scale_desc": "De 5 à 500 véhicules, notre plateforme évolue avec votre entreprise sans perdre un rythme.",
    "home.testimonial_1": "Operion a transformé nos opérations. Nous avons réduit le temps de planification des itinéraires de 80 % et les coûts de carburant de 15 % dès le premier trimestre.",
    "home.testimonial_1_author": "Mihai Popescu",
    "home.testimonial_1_role": "Gestionnaire de flotte, TransLogistic",
    "home.testimonial_2": "Avoir une visibilité en temps réel sur notre flotte a changé la donne. Nos clients adorent les ETA précises.",
    "home.testimonial_2_author": "Sarah Müller",
    "home.testimonial_2_role": "Directrice des opérations, EuroFreight",
    "home.testimonial_3": "Nous sommes passés de 10 à 50 véhicules sans ajouter un seul répartiteur. L'automatisation d'Operion est incroyable.",
    "home.testimonial_3_author": "John Smith",
    "home.testimonial_3_role": "CEO, Smith Logistics",
    "home.page_title": "Operion ERP — Logistique d'entreprise, simplifiée",
    "home.hero_headline": "Logistique d'entreprise, simplifiée",
    "home.hero_description": "Operion ERP donne à votre flotte le pouvoir de planifier plus intelligemment, répartir plus rapidement et grandir davantage.",
    "home.cta_start_trial": "Essai gratuit",
    "home.cta_see_how": "Voir comment ça marche",
    "home.section_features": "Tout ce dont vous avez besoin pour gérer votre flotte",
    "home.section_features_desc": "Des outils puissants qui fonctionnent ensemble pour rationaliser chaque aspect de vos opérations logistiques.",
    "home.section_benefits": "Conçu pour des résultats logistiques réels",
    "home.section_benefits_desc": "Chaque fonctionnalité est conçue pour résoudre un vrai problème rencontré par nos clients.",
    "home.section_testimonials": "Approuvé par les leaders logistiques",
    "home.section_testimonials_desc": "Découvrez comment Operion aide les entreprises à transformer leurs opérations logistiques.",
    "home.section_mission": "Notre mission",
    "home.section_mission_desc": "Notre mission est de rendre les logiciels de logistique d'entreprise accessibles, puissants et faciles à utiliser.",
    "home.section_cta_title": "Prêt à transformer votre logistique ?",
    "home.section_cta_desc": "Rejoignez des centaines d'entreprises qui font confiance à Operion pour gérer leurs opérations de flotte.",
    "home.cta_talk_sales": "Parler aux ventes",

    # ---- REMAINING AFTER FIRST PASS (224 keys, handle leftovers) ----
    # Words that are the same in French - keep as-is
    "about.value_innovation_title": "Innovation",
    "admin.config_flags": "Configuration",
    "admin.diagnostics": "Diagnostics",
    "admin.email": "Email",
    "admin.latency_ms": "{value} ms",
    "admin.password_placeholder": "············",
    "admin.query_placeholder": "SELECT * FROM table LIMIT 100",
    "alerts.severity_info": "Info",
    "analytics.col_km": "KM",
    "analytics.distance_km": "Distance (km)",
    "analytics.distance_label": "Distance (km)",
    "analytics.group_clients": "Clients",
    "analytics.group_top3": "Top 3",
    "analytics.group_total": "Total",
    "analytics.kpi_revenue_concentration": "Concentration",
    "analytics.tab_client": "Clients",
    "analytics.tab_document": "Documents",
    "analytics.waterfall_net": "Net",
    "app.subtitle": "ERP",
    "auth.email_label": "Email",
    "auth.login_brand": "Operion",
    "auth.register_brand": "Operion",
    "automation.label_document": "Doc #{}",
    "automation.mode_simple": "Simple",
    "client.export_csv": "Exporter CSV",
    "client.field_email": "Email",
    "client.field_notes": "Notes",
    "client.section_contacts": "Contacts",
    "client.table_email": "Email",
    "client.title": "Clients",
    "common.currency_eur": "EUR",
    "common.id": "ID",
    "dispatch_board.detail_client": "Client",
    "dispatch_board.detail_distance": "Distance",
    "dispatch_board.detail_eta": "ETA",
    "dispatch_board.detail_notes": "Notes",
    "dispatch_board.driver_hours_weekly": "{hours:.1f}h/{max_h}h",
    "dispatch_board.export_csv": "CSV",
    "dispatch_board.export_pdf": "PDF",
    "dispatch_board.live": "LIVE",
    "dispatch_board.resource_eta": "ETA",
    "docs.cat_maintenance": "Maintenance",
    "docs.cat_proformas": "Proformas",
    "docs.email": "Email",
    "docs.next": ">",
    "docs.ocr_section": "OCR",
    "docs.prev": "<",
    "docs.tab_documents": "Documents",
    "docs.tab_proforma": "Proforma",
    "driver_manager.col_id": "ID",
    "driver_manager.documents_button": "Documents",
    "driver_manager.field_email": "Email",
    "driver_manager.import_csv": "Importer CSV",
    "email_logs.col_id": "ID",
    "file_filter.images": "Images",
    "fleet.documents_button": "Documents",
    "fleet.expenses_table_id": "ID",
    "fleet.maintenance_table_id": "ID",
    "fleet.maintenance_table_km": "KM",
    "fleet.table_consumption": "L/100km",
    "fleet.table_id": "ID",
    "fleet.table_km": "KM",
    "fleet.table_vin": "VIN",
    "fleet.unit_km": "km",
    "fleet_dashboard.date": "Date",
    "generators.cmr_actions_title": "Actions",
    "generators.cmr_options_title": "Options",
    "generators.tab_cmr": "CMR",
    "history.button_documents": "Documents",
    "history.button_email": "Email",
    "history.button_excel": "Excel",
    "history.button_pdf": "PDF",
    "history.col_client": "Client",
    "history.col_data": "Date",
    "history.col_id": "ID",
    "history.col_km": "Distance (km)",
    "history.table_id": "ID",
    "history.table_km": "KM",
    "invoice_editor.description": "Description",
    "invoice_editor.distance": "Distance",
    "invoice_editor.email": "Email",
    "invoice_editor.logo": "Logo",
    "invoice_editor.net_15": "Net 15",
    "invoice_editor.net_30": "Net 30",
    "invoice_editor.net_60": "Net 60",
    "invoice_editor.notes": "Notes",
    "invoice_editor.notes_section": "Notes",
    "invoice_editor.signature": "Signature",
    "invoice_editor.total": "Total",
    "invoice_pdf.desc_header": "Description",
    "invoice_pdf.distance": "Distance",
    "invoice_pdf.total_header": "Total (EUR)",
    "main.section_identify": "IDENTIFICATION",
    "maint.col_description": "Description",
    "maint.excellent": "Excellent",
    "maint.form_notes": "Notes",
    "maint.severity_info": "Info",
    "maint.unit_km": " km",
    "maint_analytics.col_count": "Services",
    "maint_analytics.type": "Type",
    "maint_timeline.description": "Description",
    "maint_timeline.field_notes": "Notes",
    "maint_timeline.field_type": "Type",
    "maint_timeline.km": "KM",
    "maint_timeline.type": "Type",
    "nav.clients": "Clients",
    "nav.group_administration": "Administration",
    "nav.maintenance": "Maintenance",
    "proforma_editor.description": "Description",
    "proforma_editor.email": "Email",
    "proforma_editor.logo": "Logo",
    "proforma_editor.net_15": "Net 15",
    "proforma_editor.net_30": "Net 30",
    "proforma_editor.net_60": "Net 60",
    "proforma_editor.notes": "Notes",
    "proforma_editor.signature": "Signature",
    "proforma_editor.total": "Total",
    "receipt.attach_type_cmr": "CMR",
    "receipt.attach_type_document": "Document",
    "receipt.attach_type_image": "Image",
    "receipt.attach_type_pod": "POD",
    "receipt.editor.attach_files": "Joindre des fichiers",
    "receipt.editor.browse": "Parcourir",
    "receipt.editor.cancel": "Annuler",
    "receipt.editor.draft_name": "Nom du brouillon :",
    "receipt.editor.draft_save_failed": "Échec de la sauvegarde du brouillon.",
    "receipt.editor.draft_saved": "Brouillon sauvegardé",
    "receipt.editor.draft_saved_msg": "Brouillon \"{name}\" sauvegardé.",
    "receipt.editor.duplicate": "Dupliquer",
    "receipt.editor.duplicated": "Reçu dupliqué",
    "receipt.editor.duplicated_msg": "Copie créée avec un nouveau numéro.",
    "receipt.editor.email": "Email",
    "receipt.editor.email_placeholder": "Fonctionnalité d'envoi par email à venir.",
    "receipt.editor.error": "Erreur",
    "receipt.editor.export_json": "Exporter JSON",
    "receipt.editor.generate_pdf": "Générer le PDF",
    "receipt.editor.load": "Charger",
    "receipt.editor.load_draft": "Charger le brouillon",
    "receipt.editor.no_attachments": "Aucun fichier joint.",
    "receipt.editor.no_drafts": "Aucun brouillon sauvegardé.",
    "receipt.editor.pdf_generated": "Reçu généré",
    "receipt.editor.pdf_generated_msg": "PDF sauvegardé dans : {path}",
    "receipt.editor.print": "Imprimer",
    "receipt.editor.print_no_file": "Aucun fichier PDF trouvé. Générez d'abord.",
    "receipt.editor.print_no_number": "Aucun numéro de reçu. Générez d'abord.",
    "receipt.editor.save_draft": "Sauvegarder le brouillon",
    "receipt.editor.select_file": "Sélectionner un fichier",
    "receipt.editor.subtitle": "Créez des reçus professionnels pour paiements, remboursements et dépenses",
    "receipt.editor.title": "Générateur de reçus",
    "receipt.editor.validation_error": "Erreur de validation",
    "receipt.notes_label": "Notes",
    "receipt.section_notes": "NOTES",
    "receipt.section_parties": "PARTIES",
    "receipt.signature_label": "Signature",
    "receipt.total_label": "Total",
    "receipt.validation.amount_required": "Le montant est requis et doit être positif.",
    "receipt.validation.date_format": "{field} doit être au format AAAA-MM-JJ.",
    "receipt.validation.date_required": "La date d'émission est requise.",
    "receipt.validation.number_required": "Le numéro de reçu est requis.",
    "receipt.validation.recipient_required": "Le bénéficiaire (Reçu de) est requis.",
    "receipt.validation.vat_invalid": "Le taux de TVA doit être compris entre 0 et 100.",
    "result.minute": "minute",
    "result.minutes": "minutes",
    "route.open_in_gmaps": "Google Maps",
    "route.result.distance": "Distance",
    "route.section.options": "OPTIONS",
    "route.stop_destination": "Destination",
    "route_history.table_destination": "Destination",
    "route_history.table_distance": "Distance",
    "settings.section_branding": "MARQUE",
    "settings.section_email": "EMAIL & SMTP",
    "team.col_actions": "Actions",
    "team.col_email": "Email",
    "team.email_label": "EMAIL",
    "team.validation_title": "Validation",
    "text_danger": "Danger",
    "trip.speed_display": "{speed:.0f} km/h",
    "tacho.hdr_date": "Date",
    "tacho.hdr_type": "Type",
    "tacho.status_ok": "OK",
    "login.password_placeholder": "············",
    "invoice_pdf.default_cui": "RO12345678",
    "invoice_pdf.default_email": "contact@firma.ro",
    "invoice_pdf.default_phone": "07xx xxx xxx",
    "invoice_pdf.default_reg": "J40/123/2023",
    "invoice.trip_list_format": "#{id} {truck_number} — {client_name} [{created_at}]",
    "history.col_camion": "Camion",
    "history.col_brut_km": "€/km",
    "fleet.add_maintenance": "Ajouter un entretien",
    "fleet.alert_format": "[{type}] {msg}",
    "main.separator": "───────────────────────────────────────────────────────────",
    "docs.entity_documents_title": "Documents — {title}",
    "route_history.comparison_result": "Route #{a} vs #{b}\nDelta distance : {d_dist:+.1f} km\nDelta durée : {d_dur}\nProfils : {p_a} / {p_b}",
    "route_history.page_info": "Page {current} sur {total} ({count} itinéraires)",
    "tacho.import_steps": "1. Le conducteur insère la carte dans le lecteur USB\n2. Exportez le fichier .DDD avec le logiciel du lecteur\n3. Importez le fichier .DDD ici",
    "home.testimonial_1_author": "Mihai Popescu",
    "home.testimonial_2_author": "Sarah Müller",
    "home.testimonial_3_author": "John Smith",
    "home.testimonial_3_role": "CEO, Smith Logistics",
    "cmr.carrier_reservations_ro": "REZERVARILE TRANSPORTATORULUI / RESERVES DU TRANSPORTEUR",
    "cmr.carrier_ro": "TRANSPORTATOR / TRANSPORTEUR",
    "cmr.cod_ro": "PLATA LA LIVRARE / REMBOURSEMENT",
    "cmr.consignee_ro": "DESTINATAR / CONSIGNATAIRE",
    "cmr.consignor_ro": "EXPEDITOR / EXPEDITEUR",
    "cmr.date": "Date",
    "cmr.destination": "Destination",
    "cmr.destination_ro": "LOCUL LIVRARII MARFII / LIEU DE LIVRAISON",
    "cmr.distance": "Distance (km)",
    "cmr.distance_km": "Distance (km)",
    "cmr.distance_ro": "DISTANTA / DISTANCE",
    "cmr.documents_ro": "DOCUMENTE ANEXATE / DOCUMENTS ANNEXES",
    "cmr.payment_instruction_ro": "MODALITATEA DE PLATA / INSTRUCTION DE PAIEMENT",
    "cmr.place_of_loading_ro": "LOCUL PREDARII MARFII / LIEU DE PRISE EN CHARGE",
    "cmr.sender_instructions_ro": "INSTRUCTIUNILE EXPEDITORULUI / INSTRUCTIONS DE L'EXPEDITEUR",
    "cmr.special_agreements_ro": "INTELEGERI SPECIALE / CONVENTIONS SPECIALES",
    "maint_analytics.month_jan": "Jan",
    "maint_analytics.month_mar": "Mar",
    "maint_analytics.month_nov": "Nov",
    "maint_analytics.month_oct": "Oct",
    "maint_analytics.month_sep": "Sep",
    "maint_timeline.date": "Date",
    "maint_timeline.field_date": "Date",
    "client.phone": "📞",
    "client.email_icon": "✉",
    "receipt.export_json": "Exporter JSON",
}

# Apply translations
applied = 0
for key, val in EXPLICIT.items():
    if key in untranslated:
        parts = key.split(".")
        set_nested(fr_data, parts, val)
        applied += 1

print(f"Explicitly translated: {applied} keys")

# Write final result FIRST
with open(FR_PATH, "w", encoding="utf-8") as f:
    json.dump(fr_data, f, ensure_ascii=False, indent=2)
    f.write("\n")
print(f"Written to {FR_PATH}")

# Check remaining untranslated
fr_flat2 = flatten(fr_data)
remaining = {k for k in en_flat if k in fr_flat2 and isinstance(fr_flat2[k], str) and fr_flat2[k] == en_flat[k]}
print(f"Still remaining: {len(remaining)}")

for k in sorted(remaining):
    val = en_flat[k]
    if isinstance(val, str) and any(ord(c) > 127 for c in val):
        continue
    print(f"  REMAINING: {k} = {val!r}")

# Log all remaining to file
with open("remaining_keys_final.txt", "w", encoding="utf-8") as out:
    for k in sorted(remaining):
        out.write(f"{k}={repr(en_flat[k])}\n")
print(f"Full remaining list written to remaining_keys_final.txt")
