#!/usr/bin/env python3
"""Translate ALL untranslated English values in bs.json, hr.json, sv.json, sl.json.

Uses value-based translation maps built from already-translated entries.
Falls back to word-by-word translation for any remaining untranslated values.

Usage: python scripts/translate_batch1.py
"""
from __future__ import annotations


import json
import os
import re
import sys
from copy import deepcopy

TRANSLATIONS_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "translations")

def load_json(path):
    with open(path, "r", encoding="utf-8-sig") as f:
        return json.load(f)

def flatten(d, prefix=""):
    items = {}
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            items.update(flatten(v, key))
        else:
            items[key] = v
    return items

def set_nested(d, key_parts, value):
    cur = d
    for p in key_parts[:-1]:
        cur = cur.setdefault(p, {})
    cur[key_parts[-1]] = value

def unflatten(flat):
    result = {}
    for key, value in sorted(flat.items()):
        parts = key.split(".")
        set_nested(result, parts, value)
    return result

def is_untranslatable(val):
    if not isinstance(val, str) or not val:
        return True
    if re.match(r'^[\d\.,\s%€\$£±\-─—=]+$', val):
        return True
    if val.startswith(('SELECT ', 'SELECT *', 'DROP ', 'INSERT ', 'UPDATE ', 'DELETE ')):
        return True
    if '@' in val and '.' in val:
        return True
    if val.startswith(('data/', '\\\\', '/', '*.', 'Image files')):
        return True
    if re.match(r'^[·.]+$', val):
        return True
    if val.upper() in {'ID', 'KM', 'VIN', 'EUR', 'N/A', 'CSV', 'PDF', 'OCR', 'GPS', 'API',
                       'CMR', 'KPI', 'SMTP', 'DSO', 'SLA', 'SOC', 'GDPR', 'CUI', 'VAT',
                       'ETA', 'SMS', 'GBP', 'USD', 'RON', 'JSON', 'BOM', 'UTF-8', 'MB',
                       'MB.', 'AI', 'R&D', 'HQ', 'POD', 'ADR', 'EORI', 'COD', 'YTD',
                       'DDD', 'TGD', 'ZIP', 'L/100KM', '€/KM'}:
        return True
    return False

# ─── WORD-LEVEL TRANSLATION DICTIONARIES ───
# Used as fallback for phrases not in the value maps

BS_WORDS = {
    "Active": "Aktivan", "Activity": "Aktivnost", "Add": "Dodaj",
    "Address": "Adresa", "Administration": "Administracija",
    "Advanced": "Napredno", "Aging": "Starenje", "Alert": "Upozorenje",
    "Alerts": "Upozorenja", "All": "Sve", "Amount": "Iznos",
    "Analysis": "Analiza", "Analytics": "Analitika", "And": "I",
    "Application": "Aplikacija", "Apply": "Primijeni", "Archive": "Arhiva",
    "Archived": "Arhivirano", "Assign": "Dodijeli", "Assignment": "Dodjela",
    "Attachment": "Prilog", "Attachments": "Prilozi", "Auto": "Auto",
    "Automated": "Automatski", "Automation": "Automatizacija",
    "Available": "Dostupno", "Average": "Prosjek", "Avg": "Prosjek",
    "Back": "Nazad", "Backup": "Sigurnosna kopija", "Best": "Najbolji",
    "Blocked": "Blokiran", "Board": "Tabla", "Body": "Tijelo",
    "Box": "Polje", "Branch": "Podružnica", "Branding": "Brendiranje",
    "Breakdown": "Pregled", "Browse": "Pretraži", "Bulk": "Skupno",
    "Business": "Poslovanje", "Button": "Dugme", "Cache": "Cache",
    "Calculate": "Izračunaj", "Calculation": "Kalkulacija",
    "Calendar": "Kalendar", "Cancel": "Otkaži", "Cancelled": "Otkazano",
    "Carrier": "Prijevoznik", "Category": "Kategorija", "Center": "Centar",
    "Change": "Promijeni", "Chart": "Grafikon", "Charts": "Grafikoni",
    "City": "Grad", "Clear": "Obriši", "Client": "Klijent",
    "Clients": "Klijenti", "Close": "Zatvori", "Code": "Kod",
    "Collection": "Naplata", "Color": "Boja", "Column": "Kolona",
    "Compare": "Uporedi", "Comparison": "Poređenje", "Completed": "Završeno",
    "Compliance": "Usklađenost", "Composition": "Sastav",
    "Concentration": "Koncentracija", "Config": "Konfiguracija",
    "Configuration": "Konfiguracija", "Confirm": "Potvrdi",
    "Conflict": "Konflikt", "Connection": "Veza", "Consignee": "Primalac",
    "Consignor": "Pošiljalac", "Contact": "Kontakt", "Contacts": "Kontakti",
    "Control": "Kontrola", "Copy": "Kopija", "Cost": "Trošak",
    "Costs": "Troškovi", "Country": "Država", "Countries": "Države",
    "Count": "Broj", "Coverage": "Pokrivenost", "Create": "Kreiraj",
    "Created": "Kreirano", "Critical": "Kritično", "Currency": "Valuta",
    "Current": "Trenutno", "Custom": "Prilagođeno", "Customer": "Kupac",
    "Daily": "Dnevno", "Danger": "Opasnost", "Dashboard": "Kontrolna ploča",
    "Data": "Podaci", "Database": "Baza podataka", "Date": "Datum",
    "Day": "Dan", "Days": "Dani", "Deactivate": "Deaktiviraj",
    "Default": "Podrazumijevano", "Delay": "Kašnjenje",
    "Delayed": "Zakašnjelo", "Delete": "Obriši", "Delivered": "Isporučeno",
    "Department": "Odjel", "Departure": "Polazak", "Description": "Opis",
    "Destination": "Odredište", "Detail": "Detalj", "Details": "Detalji",
    "Diagnostics": "Dijagnostika", "Digital": "Digitalno",
    "Director": "Direktor", "Discount": "Popust", "Dispatch": "Dispečer",
    "Dispatcher": "Dispečer", "Display": "Prikaz", "Distance": "Udaljenost",
    "Distribution": "Distribucija", "Document": "Dokument",
    "Documents": "Dokumenti", "Download": "Preuzmi", "Draft": "Nacrt",
    "Driver": "Vozač", "Drivers": "Vozači", "Due": "Dospjelo",
    "Duplicate": "Dupliraj", "Duration": "Trajanje", "Edit": "Uredi",
    "Efficiency": "Efikasnost", "Email": "Email", "Employee": "Zaposlenik",
    "Engine": "Motor", "Entry": "Unos", "Environment": "Okruženje",
    "Error": "Greška", "Excel": "Excel", "Execute": "Izvrši",
    "Expense": "Trošak", "Expenses": "Troškovi", "Expired": "Isteklo",
    "Expiring": "Ističe", "Expiry": "Istek", "Export": "Izvoz",
    "Extended": "Produženo", "Extra": "Dodatno", "Extracted": "Izdvojeno",
    "Failed": "Neuspjelo", "Failure": "Neuspjeh", "Fair": "Dobro",
    "Features": "Funkcionalnosti", "Field": "Polje", "Fields": "Polja",
    "File": "Datoteka", "Files": "Datoteke", "Filter": "Filter",
    "Filters": "Filteri", "Finance": "Finansije", "Financial": "Finansijski",
    "Find": "Pronađi", "First": "Prvi", "Fleet": "Flota",
    "Footer": "Podnožje", "Forecast": "Prognoza", "Form": "Obrazac",
    "Format": "Format", "Free": "Slobodno", "Frequency": "Učestalost",
    "From": "Od", "Fuel": "Gorivo", "Full": "Puno",
    "Generate": "Generiši", "Generated": "Generirano", "Generator": "Generator",
    "Generators": "Generatori", "Geographic": "Geografski",
    "Goods": "Roba", "Grand": "Ukupno", "Gross": "Bruto",
    "Group": "Grupa", "Growth": "Rast", "Header": "Zaglavlje",
    "Health": "Zdravlje", "Hide": "Sakrij", "History": "Historija",
    "Home": "Početna", "Host": "Host", "Hour": "Sat", "Hours": "Sati",
    "Icon": "Ikona", "Idle": "Miruje", "Image": "Slika",
    "Images": "Slike", "Import": "Uvoz", "Inactive": "Neaktivno",
    "Info": "Info", "Information": "Informacija", "Innovation": "Inovacija",
    "Inspection": "Inspekcija", "Insurance": "Osiguranje",
    "Integration": "Integracija", "Intelligence": "Inteligencija",
    "Interval": "Interval", "Invalid": "Neispravno", "Invoice": "Faktura",
    "Invoices": "Fakture", "Invoiced": "Fakturisano", "Invoicing": "Fakturisanje",
    "Item": "Stavka", "Key": "Ključ", "Keys": "Ključevi",
    "Label": "Oznaka", "Language": "Jezik", "Last": "Posljednji",
    "Latency": "Kašnjenje", "License": "Dozvola", "Limit": "Limit",
    "Line": "Linija", "Link": "Link", "Linked": "Povezano",
    "List": "Spisak", "Live": "Uživo", "Load": "Učitaj",
    "Loaded": "Učitano", "Loading": "Utovar", "Location": "Lokacija",
    "Log": "Dnevnik", "Login": "Prijava", "Logo": "Logo",
    "Logs": "Dnevnici", "Main": "Glavno", "Maintenance": "Održavanje",
    "Manage": "Upravljaj", "Management": "Upravljanje", "Manager": "Menadžer",
    "Manual": "Ručno", "Map": "Mapa", "Margin": "Marža",
    "Match": "Podudaranje", "Meals": "Obroci", "Medical": "Medicinski",
    "Member": "Član", "Members": "Članovi", "Memory": "Memorija",
    "Merge": "Spoji", "Message": "Poruka", "Metadata": "Metapodaci",
    "Metric": "Metrika", "Migration": "Migracija", "Mileage": "Kilometraža",
    "Minute": "Minut", "Minutes": "Minuti", "Mission": "Misija",
    "Mode": "Režim", "Model": "Model", "Modern": "Moderan",
    "Month": "Mjesec", "Monthly": "Mjesečno", "Months": "Mjeseci",
    "More": "Više", "Most": "Najviše", "Move": "Premjesti",
    "Multi": "Multi", "Name": "Ime", "Navigation": "Navigacija",
    "Net": "Neto", "New": "Novi", "Next": "Sljedeći",
    "No": "Ne", "None": "Nijedan", "Notes": "Napomene",
    "Notification": "Obavijest", "Notifications": "Obavijesti",
    "Number": "Broj", "OCR": "OCR", "Odometer": "Brojač km",
    "Office": "Kancelarija", "Offline": "Oflajn", "Online": "Onlajn",
    "Open": "Otvori", "Operation": "Operacija", "Operations": "Operacije",
    "Optimization": "Optimizacija", "Option": "Opcija", "Optional": "Opciono",
    "Options": "Opcije", "Origin": "Porijeklo", "Other": "Ostalo",
    "Others": "Ostali", "Outstanding": "Nenaplaćeno", "Overall": "Ukupno",
    "Overdue": "Dospjelo", "Overview": "Pregled", "Package": "Paket",
    "Page": "Stranica", "Paid": "Plaćeno", "Panel": "Panel",
    "Parking": "Parking", "Partial": "Djelomično", "Partner": "Partner",
    "Partnership": "Partnerstvo", "Password": "Lozinka", "Path": "Putanja",
    "Payment": "Plaćanje", "Percent": "Postotak", "Performance": "Performanse",
    "Period": "Period", "Phone": "Telefon", "Photo": "Fotografija",
    "Place": "Mjesto", "Plan": "Plan", "Planned": "Planirano",
    "Planning": "Planiranje", "Plate": "Tablica", "Platform": "Platforma",
    "Port": "Port", "Prediction": "Predviđanje", "Predictions": "Predviđanja",
    "Preferences": "Postavke", "Preview": "Pregled", "Previous": "Prethodni",
    "Price": "Cijena", "Print": "Štampaj", "Priority": "Prioritet",
    "Process": "Proces", "Processing": "Obrada", "Profit": "Profit",
    "Profitability": "Profitabilnost", "Profile": "Profil",
    "Proof": "Dokaz", "Provider": "Pružalac usluge", "Purpose": "Svrha",
    "Qty": "Količina", "Quarter": "Kvartal", "Quarterly": "Kvartalno",
    "Query": "Upit", "Quick": "Brzi", "Rate": "Stopa", "Rating": "Ocjena",
    "Ratio": "Odnos", "Receipt": "Račun", "Received": "Primljeno",
    "Recipient": "Primalac", "Recommended": "Preporučeno", "Record": "Zapis",
    "Records": "Zapisi", "Recurring": "Ponavljajuće", "Refresh": "Osveži",
    "Refund": "Povrat", "Register": "Registracija", "Reliability": "Pouzdanost",
    "Remaining": "Preostalo", "Reminder": "Podsjetnik", "Remove": "Ukloni",
    "Report": "Izvještaj", "Reports": "Izvještaji", "Required": "Obavezno",
    "Reset": "Poništi", "Resolve": "Riješi", "Resource": "Resurs",
    "Resources": "Resursi", "Rest": "Ostalo", "Restore": "Vrati",
    "Result": "Rezultat", "Results": "Rezultati", "Retention": "Zadržavanje",
    "Retry": "Pokušaj ponovo", "Return": "Povratak", "Revenue": "Prihod",
    "Role": "Uloga", "Route": "Ruta", "Routes": "Rute", "Run": "Pokreni",
    "Safety": "Sigurnost", "Salary": "Plata", "Save": "Spremi",
    "Saved": "Spremljeno", "Schedule": "Raspored", "Scheduled": "Zakazano",
    "Schedules": "Rasporedi", "Score": "Rezultat", "Search": "Pretraga",
    "Second": "Sekunda", "Seconds": "Sekunde", "Section": "Sekcija",
    "Security": "Sigurnost", "Select": "Odaberi", "Selected": "Odabrano",
    "Selection": "Odabir", "Sender": "Pošiljalac", "Send": "Pošalji",
    "Sent": "Poslano", "Server": "Server", "Service": "Servis",
    "Services": "Usluge", "Setting": "Postavka", "Settings": "Postavke",
    "Setup": "Podešavanje", "Severity": "Ozbiljnost", "Share": "Podijeli",
    "Show": "Prikaži", "Signature": "Potpis", "Simple": "Jednostavno",
    "Size": "Veličina", "Small": "Malo", "Smart": "Pametno",
    "Software": "Softver", "Sort": "Sortiranje", "Source": "Izvor",
    "Specific": "Specifično", "Speed": "Brzina", "Stamp": "Pečat",
    "Standalone": "Samostalno", "Start": "Početak", "Statistics": "Statistika",
    "Status": "Status", "Stop": "Stanica", "Stops": "Stanice",
    "Storage": "Pohrana", "Subtitle": "Podnaslov", "Subtotal": "Međuzbir",
    "Success": "Uspjeh", "Successful": "Uspješno", "Summary": "Sažetak",
    "System": "Sistem", "Table": "Tabela", "Tab": "Tab", "Tag": "Oznaka",
    "Tags": "Oznake", "Target": "Cilj", "Task": "Zadatak",
    "Tasks": "Zadaci", "Tax": "Porez", "Team": "Tim", "Template": "Šablon",
    "Terms": "Uslovi", "Test": "Test", "Theme": "Tema",
    "Threshold": "Prag", "Time": "Vrijeme", "Timeline": "Vremenska linija",
    "Title": "Naslov", "To": "Do", "Today": "Danas",
    "Token": "Token", "Toll": "Putarina", "Tolls": "Putarine",
    "Tool": "Alat", "Tools": "Alati", "Top": "Najbolji",
    "Total": "Ukupno", "Track": "Prati", "Tracking": "Praćenje",
    "Traffic": "Saobraćaj", "Trailer": "Prikolica", "Transaction": "Transakcija",
    "Transition": "Prijelaz", "Transparency": "Transparentnost",
    "Transport": "Transport", "Trend": "Trend", "Trends": "Trendovi",
    "Trip": "Putovanje", "Trips": "Putovanja", "Truck": "Kamion",
    "Trucks": "Kamioni", "Type": "Tip", "Unassigned": "Nedodijeljeno",
    "Unavailable": "Nedostupno", "Undo": "Poništi", "Unknown": "Nepoznato",
    "Unpaid": "Neplaćeno", "Update": "Ažuriraj", "Updated": "Ažurirano",
    "Upload": "Otpremi", "Uploading": "Otpremanje", "Usage": "Upotreba",
    "User": "Korisnik", "Users": "Korisnici", "Utilization": "Iskorištenost",
    "Validation": "Validacija", "Value": "Vrijednost", "Values": "Vrijednosti",
    "Vehicle": "Vozilo", "Vehicles": "Vozila", "Version": "Verzija",
    "View": "Pogled", "Views": "Pregledi", "Violation": "Prekršaj",
    "Violations": "Prekršaji", "Visibility": "Vidljivost", "Volume": "Volumen",
    "Warning": "Upozorenje", "Warnings": "Upozorenja", "Week": "Sedmica",
    "Weekly": "Sedmično", "Weight": "Težina", "Welcome": "Dobrodošli",
    "Year": "Godina", "Yearly": "Godišnje", "Years": "Godine",
    "Yes": "Da", "Yesterday": "Jučer",     "Zip": "Zip",
    # Additional phrases
    "About Operion": "O Operionu",
    "About - Operion ERP": "O - Operion ERP",
    "Our Story": "Naša priča",
    "Our Values": "Naše vrijednosti",
    "The principles that guide every decision we make.": "Principi koji vode svaku odluku koju donosimo.",
    "Our Team": "Naš tim",
    "Innovation": "Inovacija",
    "Reliability": "Pouzdanost",
    "Transparency": "Transparentnost",
    "Partnership": "Partnerstvo",
    "Customer First": "Kupac na prvom mjestu",
    "Cache cleared": "Cache je očišćen",
    "Celery Status": "Celery status",
    "Redis Status": "Redis status",
    "Connected:": "Povezano:",
    "Access denied": "Pristup odbijen",
    "Server unreachable": "Server nedostupan",
    "System Info": "Informacije o sistemu",
    "Admin Panel": "Admin panel",
    "Workers Online": "Radnici na mreži",
    "API Version:": "API verzija:",
    "Python Version": "Python verzija",
    "Profit": "Profit",
    "Period": "Period",
    "Relevant": "Relevantno",
    "Email": "Email",
    "Sign In — Operion ERP": "Prijava — Operion ERP",
    "Sign in": "Prijavi se",
    "Sign up": "Registruj se",
    "Sign In": "Prijava",
    "Sign Out": "Odjava",
    "Don't have an account?": "Nemate račun?",
    "Already have an account?": "Već imate račun?",
    "Full Name": "Puno ime",
    "Company Name (optional)": "Naziv kompanije (opciono)",
    "At least 8 characters": "Najmanje 8 znakova",
    "Password is required": "Lozinka je obavezna",
    "Forgot password?": "Zaboravili ste lozinku?",
    "Enter your password": "Unesite lozinku",
    "Hide password": "Sakrij lozinku",
    "Show password": "Prikaži lozinku",
    "Signing in…": "Prijavljivanje…",
    "Welcome back": "Dobrodošli nazad",
    "Back to home": "Nazad na početnu",
    "Create Account — Operion ERP": "Kreiraj račun — Operion ERP",
    "Create your account": "Kreirajte svoj račun",
    "Start your 14-day free trial": "Započnite besplatnu probu od 14 dana",
    "Creating account…": "Kreiranje računa…",
    "Create account": "Kreiraj račun",
    "Name must be at least 2 characters": "Ime mora imati najmanje 2 znaka",
    "Password must be at least 8 characters": "Lozinka mora imati najmanje 8 znakova",
    "Passwords don't match": "Lozinke se ne poklapaju",
    "Account created successfully!": "Račun uspješno kreiran!",
    "Failed to create account": "Kreiranje računa nije uspjelo",
    "Signed in successfully!": "Uspješno prijavljeni!",
    "Failed to sign in": "Prijava nije uspjela",
    "Please enter a valid email": "Molimo unesite ispravan email",
    "Please enter your email address.": "Molimo unesite vašu email adresu.",
    "Please enter your password.": "Molimo unesite vašu lozinku.",
    "Please enter a valid email address.": "Molimo unesite ispravnu email adresu.",
    "Please enter a valid email": "Molimo unesite ispravan email",
    "You don't have an account?": "Nemate račun?",
    "Confirm Password": "Potvrdi lozinku",
    "Repeat your password": "Ponovite lozinku",
    "Actual Uploads": "Stvarna otpremanja",
    "CMR Generation Trend": "Trend generiranja CMR-a",
    "Profit per KM": "Profit po KM",
    "CMRs": "CMR-ovi",
    "Expires": "Ističe",
    "KPI Tracking": "Praćenje KPI-ja",
    "Correlation & Distribution": "Korelacija i distribucija",
    "Distribution & Insights": "Distribucija i uvidi",
    "Profit/KM": "Profit/KM",
    "Cost per Truck": "Trošak po kamionu",
    "Cost per Month": "Trošak po mjesecu",
    "Cost per Year": "Trošak po godini",
    "No Data 12Mo": "Nema podataka 12Mj",
    "Truck Fallback": "Rezervni kamion",
    "Total Cost": "Ukupni trošak",
    "Avg. Cost": "Prosječan trošak",
    "Top Category": "Najbolja kategorija",
    "Services": "Usluge",
    "More": "Više",
    "No Active Trips": "Nema aktivnih putovanja",
    "No Alerts": "Nema upozorenja",
    "Profit (Past 30 Days)": "Profit (posljednjih 30 dana)",
    "Automatically imported from Analytics": "Automatski uvezeno iz analitike",
    "Day": "Dan",
    "No profit data available yet.": "Još nema podataka o profitu.",
    "Past 30 Days": "Posljednjih 30 dana",
    "Recent Activity": "Nedavna aktivnost",
    "Top Trucks": "Najbolji kamioni",
    "enterprise": "preduzeće",
    "simplified": "pojednostavljeno",
    "smarter": "pametnije",
    "faster": "brže",
    "bigger": "veće",
    "Intelligent Route Planning": "Inteligentno planiranje ruta",
    "Real-Time Fleet Tracking": "Praćenje flote u stvarnom vremenu",
    "Smart Dispatch": "Pametni dispečing",
    "OCR Document Processing": "OCR obrada dokumenata",
    "Advanced Analytics": "Napredna analitika",
    "Driver Management": "Upravljanje vozačima",
    "Reduce Operational Costs": "Smanjite operativne troškove",
    "Increase Delivery Speed": "Povećajte brzinu isporuke",
    "Eliminate Paperwork": "Eliminišite papirologiju",
    "Scale With Confidence": "Rastite s povjerenjem",
    "Enterprise Logistics, Simplified": "Poslovna logistika, pojednostavljena",
    "Start Free Trial": "Započnite besplatnu probu",
    "Talk to Sales": "Razgovarajte s prodajom",
    "Ready to Transform Your Logistics?": "Spremni za transformaciju vaše logistike?",
    "Everything you need to run your fleet": "Sve što vam treba za upravljanje flotom",
    "Built for real logistics results": "Napravljeno za stvarne logističke rezultate",
    "Trusted by logistics leaders": "Poverenje logističkih lidera",
    "Our Mission": "Naša misija",
    "Features - Operion ERP": "Funkcionalnosti - Operion ERP",
    "Powerful Features for Modern Logistics": "Moćne funkcionalnosti za modernu logistiku",
    "Route Planning & Optimization": "Planiranje i optimizacija ruta",
    "Multi-Stop Optimization": "Optimizacija više stanica",
    "Real-Time Traffic Integration": "Integracija saobraćaja u stvarnom vremenu",
    "Fleet Management": "Upravljanje flotom",
    "Real-Time GPS Tracking": "GPS praćenje u stvarnom vremenu",
    "Vehicle Maintenance Tracking": "Praćenje održavanja vozila",
    "Geofencing & Alerts": "Geofencing i upozorenja",
    "Dispatch & Operations": "Dispečing i operacije",
    "Automated Job Assignment": "Automatska dodjela poslova",
    "Digital Proof of Delivery": "Digitalni dokaz isporuke",
    "Real-Time Status Updates": "Ažuriranja statusa u stvarnom vremenu",
    "Document Management": "Upravljanje dokumentima",
    "AI-Powered OCR": "OCR pokretan umjetnom inteligencijom",
    "Digital Archive": "Digitalna arhiva",
    "Automated Invoicing": "Automatsko fakturisanje",
    "Analytics & Reporting": "Analitika i izvještavanje",
    "Custom Dashboards": "Prilagođene kontrolne ploče",
    "Export & Integration": "Izvoz i integracija",
    "Driver Profiles": "Profili vozača",
    "Performance Tracking": "Praćenje performansi",
    "Schedule Management": "Upravljanje rasporedom",
    "Click map to add stop": "Kliknite na mapu za dodavanje stanice",
    "Route loaded": "Ruta učitana",
    "Route Options": "Opcije rute",
    "Plan multi-stop routes with cost estimation": "Planirajte rute s više stanica s procjenom troškova",
    "Route Planner": "Planer ruta",
    "Share Route": "Podijeli rutu",
    "Share this route with others so they can load it in Operion.": "Podijelite ovu rutu s drugima kako bi je mogli učitati u Operionu.",
    "Share link": "Podijeli link",
    "Export File": "Izvezi datoteku",
    "Google Maps": "Google mape",
    "Save & Open Folder": "Spremi i otvori fasciklu",
    "Copied!": "Kopirano!",
    "Clipboard unavailable": "Međuspremnik nedostupan",
    "Calculate Route": "Izračunaj rutu",
    "Route History": "Historija ruta",
    "All history": "Cjelokupna historija",
    "Last week": "Prošla sedmica",
    "Current month": "Trenutni mjesec",
    "Specific year": "Određena godina",
    "Custom": "Prilagođeno",
    "No data": "Nema podataka",
    "Info": "Informacija",
    "No": "Ne",
    "Yes": "Da",
    "Cancel": "Otkaži",
    "OK": "U redu",
    "Confirm": "Potvrdi",
    "Warning": "Upozorenje",
    "Error": "Greška",
    "Success": "Uspjeh",
    "Danger": "Opasnost",
    "N/A": "N/A",
    "Search...": "Pretraži...",
    "Edit": "Uredi",
    "Save": "Spremi",
    "Reset": "Poništi",
    "Delete": "Obriši",
    "Print": "Štampaj",
    "Preview": "Pregled",
    "Close": "Zatvori",
    "Open": "Otvori",
    "Browse": "Pretraži",
    "Upload": "Otpremi",
    "Download": "Preuzmi",
    "Remove": "Ukloni",
    "Clear": "Obriši",
    "Select": "Odaberi",
    "Select All": "Odaberi sve",
    "Deselect All": "Poništi odabir",
    "Filter": "Filter",
    "Sort": "Sortiraj",
    "Group": "Grupa",
    "List": "Spisak",
    "Grid": "Mreža",
    "View": "Pogled",
    "Details": "Detalji",
    "Summary": "Sažetak",
    "Export": "Izvoz",
    "Import": "Uvoz",
    "Send": "Pošalji",
    "Receive": "Primi",
    "Share": "Podijeli",
    "Link": "Link",
    "Copy": "Kopiraj",
    "Paste": "Zalijepi",
    "Cut": "Izreži",
    "Undo": "Poništi",
    "Redo": "Ponovi",
    "Refresh": "Osveži",
    "Update": "Ažuriraj",
    "Upgrade": "Nadogradnja",
    "Install": "Instaliraj",
    "Uninstall": "Deinstaliraj",
    "Configure": "Konfiguriši",
    "Settings": "Postavke",
    "Preferences": "Postavke",
    "Options": "Opcije",
    "Tools": "Alati",
    "Help": "Pomoć",
    "About": "O programu",
    "Support": "Podrška",
    "Contact": "Kontakt",
    "Feedback": "Povratne informacije",
    "Report": "Izvještaj",
    "Bug": "Greška",
    "Feature": "Funkcionalnost",
    "Request": "Zahtjev",
    "Language": "Jezik",
    "Theme": "Tema",
    "Dark": "Tamno",
    "Light": "Svijetlo",
    "Auto": "Automatski",
    "Notification": "Obavijest",
    "Notifications": "Obavijesti",
    "Message": "Poruka",
    "Alert": "Upozorenje",
    "Reminder": "Podsjetnik",
    # Additional remaining translations
    "Cannot read input: {}": "Ne mogu pročitati ulaz: {}",
    "Imported {} ({} bytes)": "Uvezeno {} ({} bajtova)",
    "Doc #{}": "Dok #{}",
    "Stage:": "Faza:",
    "Status:": "Status:",
    "Subject:": "Predmet:",
    "Sending…": "Slanje…",
    "Scanned — {}": "Skenirano — {}",
    "Billed": "Fakturisano",
    "Credit Limit (EUR)": "Kreditni limit (EUR)",
    "↓ Down": "↓ Dolje",
    "Cleaned up": "Očišćeno",
    "Established in": "Osnovano u",
    "Instructions & Reservations": "Upute i rezervacije",
    "Issue & Signatures": "Izdavanje i potpisi",
    "Special agreements": "Posebni dogovori",
    "Successive carriers": "Uzastopni prijevoznici",
    "CMR International Consignment Note": "CMR međunarodni tovarni list",
    "Limit: €{:,}": "Limit: €{:,}",
    "Credit Limit": "Kreditni limit",
    "Payment Terms (days)": "Uvjeti plaćanja (dani)",
    "Default Rate/km": "Zadana stopa/km",
    "Full Name *": "Puno ime *",
    "Contact Type": "Tip kontakta",
    "Job Title": "Radno mjesto",
    "Client Type": "Tip klijenta",
    "Add Contact": "Dodaj kontakt",
    "Revenue Trend": "Trend prihoda",
    "Activity Timeline": "Vremenska linija aktivnosti",
    "Payment Summary": "Sažetak plaćanja",
    "Rating (1-5)": "Ocjena (1-5)",
    "No tags assigned.": "Nema dodijeljenih oznaka.",
    "New Contact": "Novi kontakt",
    "Edit Contact": "Uredi kontakt",
    "Delete this contact?": "Obrisati ovaj kontakt?",
    "Merge Clients": "Spoji klijente",
    "Merge from: {name}": "Spoji iz: {name}",
    "Into target client:": "U ciljnog klijenta:",
    "Execute Merge": "Izvrši spajanje",
    "Contact Person": "Kontakt osoba",
    "Invoice #": "Faktura #",
    "Outstanding Invoices": "Nenaplaćene fakture",
    "Total Distance": "Ukupna udaljenost",
    "Avg Profit/Trip": "Prosječan profit/putovanje",
    "Last Trip": "Posljednje putovanje",
    "Show All": "Prikaži sve",
    "Recent Trips": "Nedavna putovanja",
    "Upload new version": "Otpremi novu verziju",
    "Restore Version": "Vrati verziju",
    "Create Contract": "Kreiraj ugovor",
    "Generate CMR": "Generiši CMR",
    "Contract type:": "Tip ugovora:",
    "Pick a trip": "Odaberite putovanje",
    "Select Invoice": "Odaberite fakturu",
    "Quick Fill From": "Brzo popunjavanje iz",
    "QUICK FILL FROM INVOICE": "BRZO POPUNJAVANJE IZ FAKTURE",
    "Attachment Type": "Tip priloga",
    "Receipt Photo": "Fotografija računa",
    "Fuel Receipt": "Račun za gorivo",
    "Amount in Words": "Iznos slovima",
    "Employee Name": "Ime zaposlenika",
    "Expense Category": "Kategorija troška",
    "Path to logo image": "Putanja do logotipa",
    "Path to signature image": "Putanja do potpisa",
    "Path to stamp image": "Putanja do pečata",
    "Company Signature": "Potpis kompanije",
    "Recipient Signature": "Potpis primaoca",
    "Company Stamp": "Pečat kompanije",
    "Generated by Operion": "Generirano od Operion",
    "Receipt number is required.": "Broj računa je obavezan.",
    "Issue date is required.": "Datum izdavanja je obavezan.",
    "Will be completed": "Bit će popunjeno",
    "Enter an amount above": "Unesite iznos iznad",
    "Related Trip": "Povezano putovanje",
    "Pickup Location": "Mjesto utovara",
    "Delivery Location": "Mjesto istovara",
    "Trip #": "Putovanje #",
    "Reference No.": "Referentni broj",
    "Transaction ID": "ID transakcije",
    "Bank Reference": "Bankovna referenca",
    "Invoice Reference": "Referenca fakture",
    "Payment Method": "Način plaćanja",
    "Received From": "Primljeno od",
    "Received By": "Primio",
    "VAT Rate (%)": "PDV stopa (%)",
    "VAT Amount": "Iznos PDV-a",
    "Amount in Words": "Iznos slovima",
    "Auto-calculated": "Automatski izračunato",
    "Department": "Odjel",
    "Company Logo": "Logo kompanije",
    "Validation Error": "Greška validacije",
    "Receipt Generated": "Račun generiran",
    "Receipt Duplicated": "Račun dupliciran",
    "Attach Files": "Priloži datoteke",
    "No file selected": "Nije odabrana datoteka",
    "Max file size": "Maksimalna veličina",
    "e.g. 19": "npr. 19",
    "e.g. Bucharest HQ": "npr. Sjedište Bukurešt",
    "Upload & Run OCR": "Otpremi i pokreni OCR",
    "File too large": "Datoteka je prevelika",
    "Upload complete. Document #{id}": "Otpremanje završeno. Dokument #{id}",
    "Fetching OCR results...": "Dohvatanje OCR rezultata...",
    "OCR complete.": "OCR završen.",
    "Upload Error": "Greška pri otpremanju",
    "Extracted Fields": "Izdvojena polja",
    "Select Document": "Odaberi dokument",
    "From Date": "Od datuma",
    "To Date": "Do datuma",
    "CSV Filter": "CSV filter",
    "No Data": "Nema podataka",
    "Schedule": "Raspored",
    "Show alerts": "Prikaži upozorenja",
    "Open calendar": "Otvori kalendar",
    "Select date": "Odaberi datum",
    "Confirm": "Potvrdi",
    "Refresh": "Osveži",
    "Truck": "Kamion",
    "No revenue data yet": "Još nema podataka o prihodu",
    "Ops not available": "Operacije nisu dostupne",
    "No signature": "Nema potpisa",
    "Signature accepted": "Potpis prihvaćen",
    "Select Signature Image": "Odaberi sliku potpisa",
    "No activity recorded": "Nema zabilježene aktivnosti",
    "No": "Ne",
    "Yes": "Da",
    # More targeted BS translations
    "Fully Assigned": "Potpuno dodijeljeno",
    "Needs Attention": "Potrebna pažnja",
    "Today's Brief": "Današnji pregled",
    "Returning": "Povratak",
    "NOW": "SADA",
    "Re-run OCR": "Ponovo pokreni OCR",
    "Unlink": "Odveži",
    "Set": "Postavi",
    "Comment": "Komentar",
    "Versions:": "Verzije:",
    "Auto-Fill": "Automatsko popunjavanje",
    "Fixed": "Fiksno",
    "Percentage": "Postotak",
    "Pick": "Izaberi",
    "Totals": "Zbrojevi",
    "Unloading": "Istovar",
    "Cost/Month": "Trošak/Mjesec",
    "Actions": "Akcije",
    "Exported": "Izvoz",
    "Proformas": "Proforme",
    "Proforma": "Proforma",
    "Receipts": "Računi",
    "Consignment Parties": "Strane u pošiljci",
    "Successive Carriers": "Uzastopni prijevoznici",
    "CMR Waybill": "CMR tovarni list",
    "Generating 4 copies...": "Generiranje 4 kopije...",
    "Status Prompt": "Prompt statusa",
    "Email Subject": "Predmet emaila",
    "Smtp Not Configured": "SMTP nije konfiguriran",
    "Account / Subdomain": "Račun / Poddomena",
    "Server URL": "URL servera",
    "API Token": "API token",
    "Not Configured": "Nije konfigurirano",
    "Stopped": "Zaustavljeno",
    "Username": "Korisničko ime",
    "Calibration": "Kalibracija",
    "General": "Općenito",
    "Interval (km)": "Interval (km)",
    "Prev": "Prethodno",
    "Downtime": "Zastoj",
    "Excellent": "Odlično",
    "Filter...": "Filter...",
    "See How It Works": "Pogledajte kako radi",
    "CEO, Smith Logistics": "CEO, Smith Logistics",
    "Logo": "Logo",
    "Dark": "Tamno",
    "Light": "Svijetlo",
    "Tax%": "Porez%",
    "VAT %": "PDV %",
}

HR_WORDS = {
    "Active": "Aktivan", "Activity": "Aktivnost", "Add": "Dodaj",
    "Address": "Adresa", "Administration": "Administracija",
    "Advanced": "Napredno", "Aging": "Starenje", "Alert": "Upozorenje",
    "Alerts": "Upozorenja", "All": "Sve", "Amount": "Iznos",
    "Analysis": "Analiza", "Analytics": "Analitika", "And": "I",
    "Application": "Aplikacija", "Apply": "Primijeni", "Archive": "Arhiva",
    "Archived": "Arhivirano", "Assign": "Dodijeli", "Assignment": "Dodjela",
    "Attachment": "Privitak", "Attachments": "Privitci", "Auto": "Auto",
    "Automated": "Automatski", "Automation": "Automatizacija",
    "Available": "Dostupno", "Average": "Prosjek", "Avg": "Prosjek",
    "Back": "Natrag", "Backup": "Sigurnosna kopija", "Best": "Najbolji",
    "Blocked": "Blokiran", "Board": "Ploča", "Body": "Tijelo",
    "Box": "Polje", "Branch": "Podružnica", "Branding": "Brendiranje",
    "Breakdown": "Pregled", "Browse": "Pretraži", "Bulk": "Skupno",
    "Business": "Poslovanje", "Button": "Gumb", "Cache": "Cache",
    "Calculate": "Izračunaj", "Calculation": "Izračun",
    "Calendar": "Kalendar", "Cancel": "Odustani", "Cancelled": "Otkazano",
    "Carrier": "Prijevoznik", "Category": "Kategorija", "Center": "Centar",
    "Change": "Promijeni", "Chart": "Grafikon", "Charts": "Grafikoni",
    "City": "Grad", "Clear": "Očisti", "Client": "Klijent",
    "Clients": "Klijenti", "Close": "Zatvori", "Code": "Kôd",
    "Collection": "Naplata", "Color": "Boja", "Column": "Kolona",
    "Compare": "Usporedi", "Comparison": "Usporedba", "Completed": "Završeno",
    "Compliance": "Usklađenost", "Composition": "Sastav",
    "Concentration": "Koncentracija", "Config": "Konfiguracija",
    "Configuration": "Konfiguracija", "Confirm": "Potvrdi",
    "Conflict": "Sukob", "Connection": "Veza", "Consignee": "Primatelj",
    "Consignor": "Pošiljatelj", "Contact": "Kontakt", "Contacts": "Kontakti",
    "Control": "Kontrola", "Copy": "Kopija", "Cost": "Trošak",
    "Costs": "Troškovi", "Country": "Država", "Countries": "Države",
    "Count": "Broj", "Coverage": "Pokrivenost", "Create": "Kreiraj",
    "Created": "Kreirano", "Critical": "Kritično", "Currency": "Valuta",
    "Current": "Trenutno", "Custom": "Prilagođeno", "Customer": "Kupac",
    "Daily": "Dnevno", "Danger": "Opasnost", "Dashboard": "Nadzorna ploča",
    "Data": "Podaci", "Database": "Baza podataka", "Date": "Datum",
    "Day": "Dan", "Days": "Dani", "Deactivate": "Deaktiviraj",
    "Default": "Zadano", "Delay": "Kašnjenje", "Delayed": "Zakašnjelo",
    "Delete": "Izbriši", "Delivered": "Isporučeno", "Department": "Odjel",
    "Departure": "Polazak", "Description": "Opis", "Destination": "Odredište",
    "Detail": "Detalj", "Details": "Detalji", "Diagnostics": "Dijagnostika",
    "Digital": "Digitalno", "Director": "Direktor", "Discount": "Popust",
    "Dispatch": "Dispečer", "Dispatcher": "Dispečer", "Display": "Prikaz",
    "Distance": "Udaljenost", "Distribution": "Distribucija",
    "Document": "Dokument", "Documents": "Dokumenti", "Download": "Preuzmi",
    "Draft": "Nacrt", "Driver": "Vozač", "Drivers": "Vozači",
    "Due": "Dospjelo", "Duplicate": "Dupliciraj", "Duration": "Trajanje",
    "Edit": "Uredi", "Efficiency": "Učinkovitost", "Email": "Email",
    "Employee": "Zaposlenik", "Engine": "Motor", "Entry": "Unos",
    "Environment": "Okruženje", "Error": "Greška", "Excel": "Excel",
    "Execute": "Izvrši", "Expense": "Trošak", "Expenses": "Troškovi",
    "Expired": "Isteklo", "Expiring": "Ističe", "Expiry": "Istek",
    "Export": "Izvoz", "Extended": "Produženo", "Extra": "Dodatno",
    "Extracted": "Izdvojeno", "Failed": "Neuspjelo", "Failure": "Neuspjeh",
    "Fair": "Dobro", "Features": "Značajke", "Field": "Polje",
    "Fields": "Polja", "File": "Datoteka", "Files": "Datoteke",
    "Filter": "Filter", "Filters": "Filteri", "Finance": "Financije",
    "Financial": "Financijski", "Find": "Pronađi", "First": "Prvi",
    "Fleet": "Flota", "Footer": "Podnožje", "Forecast": "Prognoza",
    "Form": "Obrazac", "Format": "Format", "Free": "Slobodno",
    "Frequency": "Učestalost", "From": "Od", "Fuel": "Gorivo",
    "Full": "Puno", "Generate": "Generiraj", "Generated": "Generirano",
    "Generator": "Generator", "Generators": "Generatori",
    "Geographic": "Geografski", "Goods": "Roba", "Grand": "Ukupno",
    "Gross": "Bruto", "Group": "Grupa", "Growth": "Rast",
    "Header": "Zaglavlje", "Health": "Zdravlje", "Hide": "Sakrij",
    "History": "Povijest", "Home": "Početna", "Host": "Host",
    "Hour": "Sat", "Hours": "Sati", "Icon": "Ikona", "Idle": "Miruje",
    "Image": "Slika", "Images": "Slike", "Import": "Uvoz",
    "Inactive": "Neaktivno", "Info": "Info", "Information": "Informacija",
    "Innovation": "Inovacija", "Inspection": "Inspekcija",
    "Insurance": "Osiguranje", "Integration": "Integracija",
    "Intelligence": "Inteligencija", "Interval": "Interval",
    "Invalid": "Neispravno", "Invoice": "Faktura", "Invoices": "Fakture",
    "Invoiced": "Fakturirano", "Invoicing": "Fakturiranje", "Item": "Stavka",
    "Key": "Ključ", "Keys": "Ključevi", "Label": "Oznaka",
    "Language": "Jezik", "Last": "Posljednji", "Latency": "Kašnjenje",
    "License": "Dozvola", "Limit": "Limit", "Line": "Linija",
    "Link": "Veza", "Linked": "Povezano", "List": "Popis",
    "Live": "Uživo", "Load": "Učitaj", "Loaded": "Učitano",
    "Loading": "Utovar", "Location": "Lokacija", "Log": "Dnevnik",
    "Login": "Prijava", "Logo": "Logo", "Logs": "Dnevnici",
    "Main": "Glavno", "Maintenance": "Održavanje", "Manage": "Upravljaj",
    "Management": "Upravljanje", "Manager": "Menadžer", "Manual": "Ručno",
    "Map": "Karta", "Margin": "Marža", "Match": "Podudaranje",
    "Meals": "Obroci", "Medical": "Medicinski", "Member": "Član",
    "Members": "Članovi", "Memory": "Memorija", "Merge": "Spoji",
    "Message": "Poruka", "Metadata": "Metapodaci", "Metric": "Metrika",
    "Migration": "Migracija", "Mileage": "Kilometraža", "Minute": "Minuta",
    "Minutes": "Minute", "Mission": "Misija", "Mode": "Način",
    "Model": "Model", "Modern": "Moderan", "Month": "Mjesec",
    "Monthly": "Mjesečno", "Months": "Mjeseci", "More": "Više",
    "Most": "Najviše", "Move": "Premjesti", "Multi": "Multi",
    "Name": "Ime", "Navigation": "Navigacija", "Net": "Neto",
    "New": "Novi", "Next": "Sljedeći", "No": "Ne", "None": "Nijedan",
    "Notes": "Bilješke", "Notification": "Obavijest",
    "Notifications": "Obavijesti", "Number": "Broj", "OCR": "OCR",
    "Odometer": "Brojač km", "Office": "Ured", "Offline": "Izvanmrežno",
    "Online": "Na mreži", "Open": "Otvori", "Operation": "Operacija",
    "Operations": "Operacije", "Optimization": "Optimizacija",
    "Option": "Opcija", "Optional": "Opcionalno", "Options": "Opcije",
    "Origin": "Podrijetlo", "Other": "Ostalo", "Others": "Ostali",
    "Outstanding": "Nenaplaćeno", "Overall": "Ukupno", "Overdue": "Dospjelo",
    "Overview": "Pregled", "Package": "Paket", "Page": "Stranica",
    "Paid": "Plaćeno", "Panel": "Panel", "Parking": "Parkiranje",
    "Partial": "Djelomično", "Partner": "Partner", "Partnership": "Partnerstvo",
    "Password": "Lozinka", "Path": "Putanja", "Payment": "Plaćanje",
    "Percent": "Postotak", "Performance": "Performanse", "Period": "Razdoblje",
    "Phone": "Telefon", "Photo": "Fotografija", "Place": "Mjesto",
    "Plan": "Plan", "Planned": "Planirano", "Planning": "Planiranje",
    "Plate": "Registarska oznaka", "Platform": "Platforma", "Port": "Port",
    "Prediction": "Predviđanje", "Predictions": "Predviđanja",
    "Preferences": "Postavke", "Preview": "Pregled", "Previous": "Prethodni",
    "Price": "Cijena", "Print": "Ispis", "Priority": "Prioritet",
    "Process": "Proces", "Processing": "Obrada", "Profit": "Dobit",
    "Profitability": "Profitabilnost", "Profile": "Profil",
    "Proof": "Dokaz", "Provider": "Pružatelj usluge", "Purpose": "Svrha",
    "Qty": "Kol", "Quarter": "Kvartal", "Quarterly": "Kvartalno",
    "Query": "Upit", "Quick": "Brzi", "Rate": "Stopa", "Rating": "Ocjena",
    "Ratio": "Omjer", "Receipt": "Račun", "Received": "Primljeno",
    "Recipient": "Primatelj", "Recommended": "Preporučeno", "Record": "Zapis",
    "Records": "Zapisi", "Recurring": "Ponavljajuće", "Refresh": "Osvježi",
    "Refund": "Povrat", "Register": "Registracija", "Reliability": "Pouzdanost",
    "Remaining": "Preostalo", "Reminder": "Podsjetnik", "Remove": "Ukloni",
    "Report": "Izvještaj", "Reports": "Izvještaji", "Required": "Obavezno",
    "Reset": "Poništi", "Resolve": "Riješi", "Resource": "Resurs",
    "Resources": "Resursi", "Rest": "Ostalo", "Restore": "Vrati",
    "Result": "Rezultat", "Results": "Rezultati", "Retention": "Zadržavanje",
    "Retry": "Pokušaj ponovo", "Return": "Povratak", "Revenue": "Prihod",
    "Role": "Uloga", "Route": "Ruta", "Routes": "Rute", "Run": "Pokreni",
    "Safety": "Sigurnost", "Salary": "Plaća", "Save": "Spremi",
    "Saved": "Spremljeno", "Schedule": "Raspored", "Scheduled": "Zakazano",
    "Schedules": "Rasporedi", "Score": "Rezultat", "Search": "Pretraga",
    "Second": "Sekunda", "Seconds": "Sekunde", "Section": "Sekcija",
    "Security": "Sigurnost", "Select": "Odaberi", "Selected": "Odabrano",
    "Selection": "Odabir", "Sender": "Pošiljatelj", "Send": "Pošalji",
    "Sent": "Poslano", "Server": "Server", "Service": "Usluga",
    "Services": "Usluge", "Setting": "Postavka", "Settings": "Postavke",
    "Setup": "Postavljanje", "Severity": "Ozbiljnost", "Share": "Podijeli",
    "Show": "Prikaži", "Signature": "Potpis", "Simple": "Jednostavno",
    "Size": "Veličina", "Small": "Malo", "Smart": "Pametno",
    "Software": "Softver", "Sort": "Sortiranje", "Source": "Izvor",
    "Specific": "Specifično", "Speed": "Brzina", "Stamp": "Pečat",
    "Standalone": "Samostalno", "Start": "Početak", "Statistics": "Statistika",
    "Status": "Status", "Stop": "Stanica", "Stops": "Stanice",
    "Storage": "Pohrana", "Subtitle": "Podnaslov", "Subtotal": "Međuzbroj",
    "Success": "Uspjeh", "Successful": "Uspješno", "Summary": "Sažetak",
    "System": "Sustav", "Table": "Tablica", "Tab": "Tab", "Tag": "Oznaka",
    "Tags": "Oznake", "Target": "Cilj", "Task": "Zadatak",
    "Tasks": "Zadaci", "Tax": "Porez", "Team": "Tim", "Template": "Predložak",
    "Terms": "Uvjeti", "Test": "Test", "Theme": "Tema",
    "Threshold": "Prag", "Time": "Vrijeme", "Timeline": "Vremenska linija",
    "Title": "Naslov", "To": "Do", "Today": "Danas",
    "Token": "Token", "Toll": "Cestarina", "Tolls": "Cestarina",
    "Tool": "Alat", "Tools": "Alati", "Top": "Najbolji",
    "Total": "Ukupno", "Track": "Prati", "Tracking": "Praćenje",
    "Traffic": "Promet", "Trailer": "Prikolica", "Transaction": "Transakcija",
    "Transition": "Prijelaz", "Transparency": "Transparentnost",
    "Transport": "Transport", "Trend": "Trend", "Trends": "Trendovi",
    "Trip": "Putovanje", "Trips": "Putovanja", "Truck": "Kamion",
    "Trucks": "Kamioni", "Type": "Tip", "Unassigned": "Nedodijeljeno",
    "Unavailable": "Nedostupno", "Undo": "Poništi", "Unknown": "Nepoznato",
    "Unpaid": "Neplaćeno", "Update": "Ažuriraj", "Updated": "Ažurirano",
    "Upload": "Prenesi", "Uploading": "Prijenos", "Usage": "Korištenje",
    "User": "Korisnik", "Users": "Korisnici", "Utilization": "Iskorištenost",
    "Validation": "Validacija", "Value": "Vrijednost", "Values": "Vrijednosti",
    "Vehicle": "Vozilo", "Vehicles": "Vozila", "Version": "Verzija",
    "View": "Pogled", "Views": "Pregledi", "Violation": "Prekršaj",
    "Violations": "Prekršaji", "Visibility": "Vidljivost", "Volume": "Volumen",
    "Warning": "Upozorenje", "Warnings": "Upozorenja", "Week": "Tjedan",
    "Weekly": "Tjedno", "Weight": "Težina", "Welcome": "Dobrodošli",
    "Year": "Godina", "Yearly": "Godišnje", "Years": "Godine",
    "Yes": "Da", "Yesterday": "Jučer", "Zip": "Zip",
    # HR common phrases
    "About Operion": "O Operionu",
    "About - Operion ERP": "O - Operion ERP",
    "Our Story": "Naša priča",
    "Our Values": "Naše vrijednosti",
    "The principles that guide every decision we make.": "Načela koja vode svaku odluku koju donosimo.",
    "Our Team": "Naš tim",
    "Innovation": "Inovacija",
    "Reliability": "Pouzdanost",
    "Transparency": "Transparentnost",
    "Partnership": "Partnerstvo",
    "Customer First": "Kupac na prvom mjestu",
    "Cache cleared": "Cache je očišćen",
    "Celery Status": "Celery status",
    "Redis Status": "Redis status",
    "Connected:": "Spojeno:",
    "Access denied": "Pristup odbijen",
    "Server unreachable": "Server nedostupan",
    "System Info": "Informacije o sustavu",
    "Admin Panel": "Admin panel",
    "Workers Online": "Radnici online",
    "API Version:": "API verzija:",
    "Python Version": "Python verzija",
    "DB Engine:": "DB motor:",
    "Environment:": "Okruženje:",
    "Debug Mode:": "Debug način:",
    "DB Path": "DB putanja",
    "Platform": "Platforma",
    "Forgot password?": "Zaboravili ste lozinku?",
    "Enter your password": "Unesite lozinku",
    "Hide password": "Sakrij lozinku",
    "Show password": "Prikaži lozinku",
    "Signing in…": "Prijava…",
    "Welcome back": "Dobrodošli natrag",
    "Back to home": "Natrag na početnu",
    "Sign In — Operion ERP": "Prijava — Operion ERP",
    "Sign in": "Prijavi se",
    "Sign up": "Registriraj se",
    "Sign In": "Prijava",
    "Sign Out": "Odjava",
    "Don't have an account?": "Nemate račun?",
    "Already have an account?": "Već imate račun?",
    "Full Name": "Puno ime",
    "Company Name (optional)": "Naziv tvrtke (opcionalno)",
    "At least 8 characters": "Najmanje 8 znakova",
    "Password is required": "Lozinka je obavezna",
    "Create Account — Operion ERP": "Kreiraj račun — Operion ERP",
    "Create your account": "Kreirajte svoj račun",
    "Start your 14-day free trial": "Započnite besplatnu probu od 14 dana",
    "Creating account…": "Kreiranje računa…",
    "Create account": "Kreiraj račun",
    "Name must be at least 2 characters": "Ime mora imati najmanje 2 znaka",
    "Password must be at least 8 characters": "Lozinka mora imati najmanje 8 znakova",
    "Passwords don't match": "Lozinke se ne podudaraju",
    "Account created successfully!": "Račun uspješno kreiran!",
    "Failed to create account": "Kreiranje računa nije uspjelo",
    "Signed in successfully!": "Uspješno prijavljeni!",
    "Failed to sign in": "Prijava nije uspjela",
    "Please enter a valid email": "Molimo unesite ispravan email",
    "Please enter your email address.": "Molimo unesite vašu email adresu.",
    "Please enter your password.": "Molimo unesite vašu lozinku.",
    "Please enter a valid email address.": "Molimo unesite ispravnu email adresu.",
    "Confirm Password": "Potvrdi lozinku",
    "Repeat your password": "Ponovite lozinku",
    "Actual Uploads": "Stvarna prijenosa",
    "CMR Generation Trend": "Trend generiranja CMR-a",
    "Profit per KM": "Profit po KM",
    "CMRs": "CMR-ovi",
    "Expires": "Ističe",
    "KPI Tracking": "Praćenje KPI-ja",
    "Correlation & Distribution": "Korelacija i distribucija",
    "Distribution & Insights": "Distribucija i uvidi",
    "Profit/KM": "Profit/KM",
    "Cost per Truck": "Trošak po kamionu",
    "Cost per Month": "Trošak po mjesecu",
    "Cost per Year": "Trošak po godini",
    "No Data 12Mo": "Nema podataka 12Mj",
    "Truck Fallback": "Rezervni kamion",
    "Avg. Cost": "Prosječan trošak",
    "Top Category": "Najbolja kategorija",
    "More": "Više",
    "No Active Trips": "Nema aktivnih putovanja",
    "No Alerts": "Nema upozorenja",
    "Profit (Past 30 Days)": "Profit (posljednjih 30 dana)",
    "Intelligent Route Planning": "Inteligentno planiranje ruta",
    "Real-Time Fleet Tracking": "Praćenje flote u stvarnom vremenu",
    "Smart Dispatch": "Pametni dispečing",
    "OCR Document Processing": "OCR obrada dokumenata",
    "Advanced Analytics": "Napredna analitika",
    "Driver Management": "Upravljanje vozačima",
    "Reduce Operational Costs": "Smanjite operativne troškove",
    "Increase Delivery Speed": "Povećajte brzinu isporuke",
    "Eliminate Paperwork": "Eliminirajte papirologiju",
    "Scale With Confidence": "Rastite s povjerenjem",
    "Enterprise Logistics, Simplified": "Poslovna logistika, pojednostavljena",
    "Start Free Trial": "Započnite besplatnu probu",
    "Talk to Sales": "Razgovarajte s prodajom",
    "Features - Operion ERP": "Značajke - Operion ERP",
    "Powerful Features for Modern Logistics": "Moćne značajke za modernu logistiku",
    "Route Planning & Optimization": "Planiranje i optimizacija ruta",
    "Multi-Stop Optimization": "Optimizacija više stanica",
    "Real-Time Traffic Integration": "Integracija prometa u stvarnom vremenu",
    "Fleet Management": "Upravljanje flotom",
    "Real-Time GPS Tracking": "GPS praćenje u stvarnom vremenu",
    "Vehicle Maintenance Tracking": "Praćenje održavanja vozila",
    "Geofencing & Alerts": "Geofencing i upozorenja",
    "Dispatch & Operations": "Dispečing i operacije",
    "Automated Job Assignment": "Automatska dodjela poslova",
    "Digital Proof of Delivery": "Digitalni dokaz isporuke",
    "Real-Time Status Updates": "Ažuriranja statusa u stvarnom vremenu",
    "Document Management": "Upravljanje dokumentima",
    "AI-Powered OCR": "OCR pokretan umjetnom inteligencijom",
    "Digital Archive": "Digitalna arhiva",
    "Automated Invoicing": "Automatsko fakturiranje",
    "Analytics & Reporting": "Analitika i izvještavanje",
    "Custom Dashboards": "Prilagođene nadzorne ploče",
    "Export & Integration": "Izvoz i integracija",
    "Driver Profiles": "Profili vozača",
    "Performance Tracking": "Praćenje performansi",
    "Schedule Management": "Upravljanje rasporedom",
    "Click map to add stop": "Kliknite na kartu za dodavanje stanice",
    "Route loaded": "Ruta učitana",
    "Route Options": "Opcije rute",
    "Plan multi-stop routes with cost estimation": "Planirajte rute s više stanica s procjenom troškova",
    "Route Planner": "Planer ruta",
    "Share Route": "Podijeli rutu",
    "Share link": "Podijeli link",
    "Export File": "Izvezi datoteku",
    "Google Maps": "Google karte",
    "Save & Open Folder": "Spremi i otvori mapu",
    "Copied!": "Kopirano!",
    "Calculate Route": "Izračunaj rutu",
    "Route History": "Povijest ruta",
    "All history": "Sva povijest",
    "Last week": "Prošli tjedan",
    "Current month": "Trenutni mjesec",
    "Specific year": "Određena godina",
    "N/A": "N/A",
    "Search...": "Pretraži...",
    "OK": "U redu",
    "Info": "Informacija",
    # Additional HR remaining translations
    "Cannot read input: {}": "Ne mogu pročitati ulaz: {}",
    "Imported {} ({} bytes)": "Uvezeno {} ({} bajtova)",
    "Doc #{}": "Dok #{}",
    "Stage:": "Faza:",
    "Status:": "Status:",
    "Subject:": "Predmet:",
    "Sending…": "Slanje…",
    "Scanned — {}": "Skenirano — {}",
    "Billed": "Fakturirano",
    "Credit Limit (EUR)": "Kreditni limit (EUR)",
    "↓ Down": "↓ Dolje",
    "Cleaned up": "Očišćeno",
    "Established in": "Osnovano u",
    "Instructions & Reservations": "Upute i rezervacije",
    "Issue & Signatures": "Izdavanje i potpisi",
    "Special agreements": "Posebni dogovori",
    "Successive carriers": "Uzastopni prijevoznici",
    "CMR International Consignment Note": "CMR međunarodni tovarni list",
    "Limit: €{:,}": "Limit: €{:,}",
    "Payment Terms (days)": "Uvjeti plaćanja (dani)",
    "Full Name *": "Puno ime *",
    "Contact Type": "Tip kontakta",
    "Job Title": "Radno mjesto",
    "Client Type": "Tip klijenta",
    "Add Contact": "Dodaj kontakt",
    "Revenue Trend": "Trend prihoda",
    "Activity Timeline": "Vremenska linija aktivnosti",
    "Payment Summary": "Sažetak plaćanja",
    "Rating (1-5)": "Ocjena (1-5)",
    "No tags assigned.": "Nema dodijeljenih oznaka.",
    "Merge Clients": "Spoji klijente",
    "Execute Merge": "Izvrši spajanje",
    "Contact Person": "Kontakt osoba",
    "Invoice #": "Faktura #",
    "Outstanding Invoices": "Nenaplaćene fakture",
    "Total Distance": "Ukupna udaljenost",
    "Avg Profit/Trip": "Prosječna dobit/putovanje",
    "Last Trip": "Posljednje putovanje",
    "Show All": "Prikaži sve",
    "Recent Trips": "Nedavna putovanja",
    "Upload new version": "Prenesi novu verziju",
    "Restore Version": "Vrati verziju",
    "Create Contract": "Kreiraj ugovor",
    "Generate CMR": "Generiraj CMR",
    "Pick a trip": "Odaberi putovanje",
    "Select Invoice": "Odaberi fakturu",
    "QUICK FILL FROM INVOICE": "BRZO POPUNJAVANJE IZ FAKTURE",
    "Attachment Type": "Tip privitka",
    "Receipt Photo": "Fotografija računa",
    "Fuel Receipt": "Račun za gorivo",
    "Amount in Words": "Iznos slovima",
    "Employee Name": "Ime zaposlenika",
    "Expense Category": "Kategorija troška",
    "Path to logo image": "Putanja do logotipa",
    "Path to signature image": "Putanja do potpisa",
    "Path to stamp image": "Putanja do pečata",
    "Company Signature": "Potpis tvrtke",
    "Recipient Signature": "Potpis primatelja",
    "Company Stamp": "Pečat tvrtke",
    "Generated by Operion": "Generirano od Operion",
    "Receipt number is required.": "Broj računa je obavezan.",
    "Issue date is required.": "Datum izdavanja je obavezan.",
    "Will be completed": "Bit će popunjeno",
    "Enter an amount above": "Unesite iznos iznad",
    "Related Trip": "Povezano putovanje",
    "Pickup Location": "Mjesto utovara",
    "Delivery Location": "Mjesto istovara",
    "Trip #": "Putovanje #",
    "Reference No.": "Referentni broj",
    "Transaction ID": "ID transakcije",
    "Bank Reference": "Bankovna referenca",
    "Invoice Reference": "Referenca fakture",
    "Payment Method": "Način plaćanja",
    "Received From": "Primljeno od",
    "Received By": "Primio",
    "VAT Rate (%)": "Stopa PDV-a (%)",
    "VAT Amount": "Iznos PDV-a",
    "Auto-calculated": "Automatski izračunato",
    "Department": "Odjel",
    "Company Logo": "Logo tvrtke",
    "File too large": "Datoteka je prevelika",
    "Upload complete. Document #{id}": "Prijenos završen. Dokument #{id}",
    "Upload Error": "Greška pri prijenosu",
    "Extracted Fields": "Izdvojena polja",
    "Select Document": "Odaberi dokument",
    "From Date": "Od datuma",
    "To Date": "Do datuma",
    "CSV Filter": "CSV filter",
    "Show alerts": "Prikaži upozorenja",
    "Open calendar": "Otvori kalendar",
    "Select date": "Odaberi datum",
    "No revenue data yet": "Još nema podataka o prihodu",
    "No signature": "Nema potpisa",
    "Signature accepted": "Potpis prihvaćen",
    "Select Signature Image": "Odaberi sliku potpisa",
    "No activity recorded": "Nema zabilježene aktivnosti",
    "Truck": "Kamion",
    "Schedule": "Raspored",
    "Relevant": "Relevantno",
    "Email Subject": "Predmet e-pošte",
    "Emailed": "Poslano e-poštom",
    "Company Logo:": "Logo tvrtke:",
    "SMTP Port:": "SMTP priključak:",
    "SMTP Server:": "SMTP poslužitelj:",
    "Cloud OCR credentials:": "Cloud OCR vjerodajnice:",
    "Accommodation": "Smještaj",
    "Deposit": "Depozit",
    "Auto-generated": "Automatski generirano",
    "Valid Until": "Vrijedi do",
    "Proforma #": "Proforma #",
    "Actions": "Akcije",
    "Cost/Month": "Trošak/Mjesec",
    "Fully Assigned": "Potpuno dodijeljeno",
    "Needs Attention": "Potrebna pažnja",
    "Today's Brief": "Današnji pregled",
    "Returning": "Povratak",
    "See How It Works": "Pogledajte kako radi",
    "CEO, Smith Logistics": "CEO, Smith Logistics",
}

SV_WORDS = {
    # Common phrases
    "About Operion": "Om Operion",
    "About - Operion ERP": "Om - Operion ERP",
    "Our Story": "Vår historia",
    "Our Values": "Våra värderingar",
    "The principles that guide every decision we make.": "Principerna som vägleder varje beslut vi fattar.",
    "Our Team": "Vårt team",
    "Innovation": "Innovation",
    "Reliability": "Tillförlitlighet",
    "Transparency": "Transparens",
    "Partnership": "Partnerskap",
    "Customer First": "Kunden först",
    "Cache cleared": "Cache rensad",
    "Celery Status": "Celery-status",
    "Redis Status": "Redis-status",
    "Connected:": "Ansluten:",
    "Access denied": "Åtkomst nekad",
    "Server unreachable": "Servern nås inte",
    "System Info": "Systeminformation",
    "Admin Panel": "Adminpanel",
    "Workers Online": "Arbetare online",
    "API Version:": "API-version:",
    "Python Version": "Python-version",
    "DB Engine:": "DB-motor:",
    "Environment:": "Miljö:",
    "Debug Mode:": "Felsökningsläge:",
    "DB Path": "DB-sökväg",
    "Platform": "Plattform",
    "Forgot password?": "Glömt lösenord?",
    "Enter your password": "Ange ditt lösenord",
    "Hide password": "Dölj lösenord",
    "Show password": "Visa lösenord",
    "Signing in…": "Loggar in…",
    "Welcome back": "Välkommen tillbaka",
    "Back to home": "Tillbaka till startsidan",
    "Sign In — Operion ERP": "Logga in — Operion ERP",
    "Sign in": "Logga in",
    "Sign up": "Registrera dig",
    "Sign In": "Logga in",
    "Sign Out": "Logga ut",
    "Don't have an account?": "Har du inget konto?",
    "Already have an account?": "Har du redan ett konto?",
    "Full Name": "Fullständigt namn",
    "Company Name (optional)": "Företagsnamn (valfritt)",
    "At least 8 characters": "Minst 8 tecken",
    "Password is required": "Lösenord krävs",
    "Create Account — Operion ERP": "Skapa konto — Operion ERP",
    "Create your account": "Skapa ditt konto",
    "Start your 14-day free trial": "Starta din 14-dagars gratis provperiod",
    "Creating account…": "Skapar konto…",
    "Create account": "Skapa konto",
    "Name must be at least 2 characters": "Namnet måste vara minst 2 tecken",
    "Password must be at least 8 characters": "Lösenordet måste vara minst 8 tecken",
    "Passwords don't match": "Lösenorden matchar inte",
    "Account created successfully!": "Konto skapat!",
    "Failed to create account": "Misslyckades med att skapa konto",
    "Signed in successfully!": "Inloggad!",
    "Failed to sign in": "Inloggning misslyckades",
    "Please enter a valid email": "Ange en giltig e-postadress",
    "Please enter your email address.": "Ange din e-postadress.",
    "Please enter your password.": "Ange ditt lösenord.",
    "Please enter a valid email address.": "Ange en giltig e-postadress.",
    "Confirm Password": "Bekräfta lösenord",
    "Repeat your password": "Upprepa ditt lösenord",
    "You don't have an account?": "Har du inget konto?",
    "Actual Uploads": "Faktiska uppladdningar",
    "CMR Generation Trend": "CMR-generationstrend",
    "Profit per KM": "Vinst per KM",
    "CMRs": "CMR",
    "Expires": "Utgår",
    "KPI Tracking": "KPI-spårning",
    "Correlation & Distribution": "Korrelation och distribution",
    "Distribution & Insights": "Distribution och insikter",
    "Profit/KM": "Vinst/KM",
    "Cost per Truck": "Kostnad per lastbil",
    "Cost per Month": "Kostnad per månad",
    "Cost per Year": "Kostnad per år",
    "No Data 12Mo": "Ingen data 12 mån",
    "Truck Fallback": "Lastbilsreserv",
    "Avg. Cost": "Snittkostnad",
    "Top Category": "Toppkategori",
    "More": "Mer",
    "No Active Trips": "Inga aktiva resor",
    "No Alerts": "Inga varningar",
    "Profit (Past 30 Days)": "Vinst (senaste 30 dagarna)",
    "Automatically imported from Analytics": "Automatiskt importerad från analys",
    "No profit data available yet.": "Inga vinstdata tillgängliga än.",
    "Past 30 Days": "Senaste 30 dagarna",
    "Recent Activity": "Senaste aktivitet",
    "Top Trucks": "Topplastbilar",
    "Intelligent Route Planning": "Intelligent ruttplanering",
    "Real-Time Fleet Tracking": "Realtids spårning av flotta",
    "Smart Dispatch": "Smart dispatch",
    "OCR Document Processing": "OCR-dokumenthantering",
    "Advanced Analytics": "Avancerad analys",
    "Driver Management": "Förarhantering",
    "Reduce Operational Costs": "Minska driftskostnader",
    "Increase Delivery Speed": "Öka leveranshastighet",
    "Eliminate Paperwork": "Eliminera pappersarbete",
    "Scale With Confidence": "Väx med förtroende",
    "Enterprise Logistics, Simplified": "Företagslogistik, förenklad",
    "Start Free Trial": "Starta gratis provperiod",
    "Talk to Sales": "Prata med försäljning",
    "Ready to Transform Your Logistics?": "Redo att transformera din logistik?",
    "Everything you need to run your fleet": "Allt du behöver för din flotta",
    "Built for real logistics results": "Byggt för verkliga logistikresultat",
    "Trusted by logistics leaders": "Betrodd av logistikledare",
    "Our Mission": "Vårt uppdrag",
    "Features - Operion ERP": "Funktioner - Operion ERP",
    "Powerful Features for Modern Logistics": "Kraftfulla funktioner för modern logistik",
    "Route Planning & Optimization": "Ruttplanering och optimering",
    "Multi-Stop Optimization": "Optimering av flera stopp",
    "Real-Time Traffic Integration": "Realtids trafikintegration",
    "Fleet Management": "Flotthantering",
    "Real-Time GPS Tracking": "GPS-spårning i realtid",
    "Vehicle Maintenance Tracking": "Fordonsunderhållsspårning",
    "Geofencing & Alerts": "Geofencing och varningar",
    "Dispatch & Operations": "Dispatch och verksamhet",
    "Automated Job Assignment": "Automatisk jobbtilldelning",
    "Digital Proof of Delivery": "Digitalt leveransbevis",
    "Real-Time Status Updates": "Statusuppdateringar i realtid",
    "Document Management": "Dokumenthantering",
    "AI-Powered OCR": "AI-driven OCR",
    "Digital Archive": "Digitalt arkiv",
    "Automated Invoicing": "Automatisk fakturering",
    "Analytics & Reporting": "Analys och rapportering",
    "Custom Dashboards": "Anpassade instrumentpaneler",
    "Export & Integration": "Export och integration",
    "Driver Profiles": "Förarprofiler",
    "Performance Tracking": "Prestandaspårning",
    "Schedule Management": "Schema hantering",
    "Click map to add stop": "Klicka på kartan för att lägga till stopp",
    "Route loaded": "Rutt laddad",
    "Route Options": "Ruttalternativ",
    "Plan multi-stop routes with cost estimation": "Planera rutter med flera stopp och kostnadsuppskattning",
    "Route Planner": "Ruttplanerare",
    "Share Route": "Dela rutt",
    "Share this route with others so they can load it in Operion.": "Dela denna rutt så att andra kan ladda den i Operion.",
    "Share link": "Dela länk",
    "Export File": "Exportera fil",
    "Google Maps": "Google Maps",
    "Save & Open Folder": "Spara och öppna mapp",
    "Copied!": "Kopierad!",
    "Clipboard unavailable": "Urklipp ej tillgängligt",
    "Calculate Route": "Beräkna rutt",
    "Route History": "Rutthistorik",
    "All history": "All historik",
    "Last week": "Förra veckan",
    "Current month": "Aktuell månad",
    "Specific year": "Specifikt år",
    "No data": "Ingen data",
    "N/A": "N/A",
    "Search...": "Sök...",
    "OK": "OK",
    # Additional SV translations for placeholder-safe keys
    "Failed to add user: {error}": "Misslyckades att lägga till användare: {error}",
    "Failed to deactivate user: {error}": "Misslyckades att avaktivera användare: {error}",
    "Insight: {client} generates {rev_pct}% of revenue but only {profit_pct}% of profit.": "Insikt: {client} genererar {rev_pct}% av intäkten men bara {profit_pct}% av vinsten.",
    "[{type}] {msg}": "[{type}] {msg}",
    "Fully Assigned": "Fullt tilldelad",
    "Emailed": "E-postad",
    "Needs Attention": "Behöver uppmärksamhet",
    "Today's Brief": "Dagens sammanfattning",
    "Returning": "Återvänder",
    "NOW": "NU",
    "Re-run OCR": "Kör OCR igen",
    "Unlink": "Ta bort länk",
    "Set": "Ställ in",
    "Versions:": "Versioner:",
    "Auto-Fill": "Autofyll",
    "Fixed": "Fast",
    "Percentage": "Procent",
    "Pick": "Välj",
    "Totals": "Summor",
    "Unloading": "Lossning",
    "Consignment Parties": "Leveransparter",
    "Successive Carriers": "Successiva transportörer",
    "CMR Waybill": "CMR fraktsedel",
    "Generating 4 copies...": "Genererar 4 kopior...",
    "Status Prompt": "Statusprompt",
    "Smtp Not Configured": "SMTP inte konfigurerad",
    "Account / Subdomain": "Konto / underdomän",
    "Server URL": "Server-URL",
    "API Token": "API-token",
    "Not Configured": "Inte konfigurerad",
    "Stopped": "Stannad",
    "Username": "Användarnamn",
    "Calibration": "Kalibrering",
    "See How It Works": "Se hur det fungerar",
    "CEO, Smith Logistics": "VD, Smith Logistics",
    "Cloud OCR credentials:": "Cloud OCR-uppgifter:",
    "SMTP Port:": "SMTP-port:",
    "SMTP Server:": "SMTP-server:",
    "Dark": "Mörk",
    "Light": "Ljus",
    "Tax%": "Moms%",
    "VAT %": "Moms %",
    "Auto-generated": "Autogenererad",
    "Auto-calculated": "Automatiskt beräknad",
    "e.g. 19": "t.ex. 19",
    "e.g. Bucharest HQ": "t.ex. Bukarest HQ",
    "Deposit": "Deposition",
    "Accommodation": "Logi",
    "Bank Reference": "Bankreferens",
    "Valid Until": "Giltig till",
    "Proforma #": "Proforma #",
    "Unloading": "Lossning",
    "Google Maps": "Google Maps",
    "Start": "Start",
    "Destination": "Destination",
    "Actions": "Åtgärder",
    "Version uploaded": "Version uppladdad",
    "Version restored": "Version återställd",
    "Clean": "Rensa",
}

SL_WORDS = {
    "Active": "Aktiven", "Activity": "Aktivnost", "Add": "Dodaj",
    "Address": "Naslov", "Administration": "Administracija",
    "Advanced": "Napredno", "Aging": "Staranje", "Alert": "Opozorilo",
    "Alerts": "Opozorila", "All": "Vse", "Amount": "Znesek",
    "Analysis": "Analiza", "Analytics": "Analitika", "And": "In",
    "Application": "Aplikacija", "Apply": "Uporabi", "Archive": "Arhiv",
    "Archived": "Arhivirano", "Assign": "Dodeli", "Assignment": "Dodelitev",
    "Attachment": "Priloga", "Attachments": "Priloge", "Auto": "Samodejno",
    "Automated": "Avtomatizirano", "Automation": "Avtomatizacija",
    "Available": "Na voljo", "Average": "Povprečje", "Avg": "Povp",
    "Back": "Nazaj", "Backup": "Varnostna kopija", "Best": "Najboljši",
    "Blocked": "Blokiran", "Board": "Tabla", "Body": "Telo",
    "Box": "Polje", "Branch": "Podružnica", "Branding": "Oblikovanje",
    "Breakdown": "Razčlenitev", "Browse": "Prebrskaj", "Bulk": "Skupinsko",
    "Business": "Poslovanje", "Button": "Gumb", "Cache": "Predpomnilnik",
    "Calculate": "Izračunaj", "Calculation": "Izračun",
    "Calendar": "Koledar", "Cancel": "Prekliči", "Cancelled": "Preklicano",
    "Carrier": "Prevoznik", "Category": "Kategorija", "Center": "Center",
    "Change": "Spremeni", "Chart": "Grafikon", "Charts": "Grafikoni",
    "City": "Mesto", "Clear": "Počisti", "Client": "Stranka",
    "Clients": "Stranke", "Close": "Zapri", "Code": "Koda",
    "Collection": "Izterjava", "Color": "Barva", "Column": "Stolpec",
    "Compare": "Primerjaj", "Comparison": "Primerjava", "Completed": "Zaključeno",
    "Compliance": "Skladnost", "Composition": "Sestava",
    "Concentration": "Koncentracija", "Config": "Konfiguracija",
    "Configuration": "Konfiguracija", "Confirm": "Potrdi",
    "Conflict": "Konflikt", "Connection": "Povezava", "Consignee": "Prejemnik",
    "Consignor": "Pošiljatelj", "Contact": "Kontakt", "Contacts": "Kontakti",
    "Control": "Nadzor", "Copy": "Kopija", "Cost": "Strošek",
    "Costs": "Stroški", "Country": "Država", "Countries": "Države",
    "Count": "Število", "Coverage": "Pokritost", "Create": "Ustvari",
    "Created": "Ustvarjeno", "Critical": "Kritično", "Currency": "Valuta",
    "Current": "Trenutno", "Custom": "Po meri", "Customer": "Stranka",
    "Daily": "Dnevno", "Danger": "Nevarnost", "Dashboard": "Nadzorna plošča",
    "Data": "Podatki", "Database": "Podatkovna baza", "Date": "Datum",
    "Day": "Dan", "Days": "Dnevi", "Deactivate": "Deaktiviraj",
    "Default": "Privzeto", "Delay": "Zamuda", "Delayed": "Zamujeno",
    "Delete": "Izbriši", "Delivered": "Dostavljeno", "Department": "Oddelek",
    "Departure": "Odhod", "Description": "Opis", "Destination": "Destinacija",
    "Detail": "Podrobnost", "Details": "Podrobnosti", "Diagnostics": "Diagnostika",
    "Digital": "Digitalno", "Director": "Direktor", "Discount": "Popust",
    "Dispatch": "Dispečer", "Dispatcher": "Dispečer", "Display": "Prikaz",
    "Distance": "Razdalja", "Distribution": "Distribucija",
    "Document": "Dokument", "Documents": "Dokumenti", "Download": "Prenesi",
    "Draft": "Osnutek", "Driver": "Voznik", "Drivers": "Vozniki",
    "Due": "Zapadlo", "Duplicate": "Podvoji", "Duration": "Trajanje",
    "Edit": "Uredi", "Efficiency": "Učinkovitost", "Email": "E-pošta",
    "Employee": "Zaposleni", "Engine": "Motor", "Entry": "Vnos",
    "Environment": "Okolje", "Error": "Napaka", "Excel": "Excel",
    "Execute": "Izvedi", "Expense": "Strošek", "Expenses": "Stroški",
    "Expired": "Poteklo", "Expiring": "Poteče", "Expiry": "Potek",
    "Export": "Izvozi", "Extended": "Podaljšano", "Extra": "Dodatno",
    "Extracted": "Izvlečeno", "Failed": "Neuspelo", "Failure": "Neuspeh",
    "Fair": "Dobro", "Features": "Funkcije", "Field": "Polje",
    "Fields": "Polja", "File": "Datoteka", "Files": "Datoteke",
    "Filter": "Filter", "Filters": "Filtri", "Finance": "Finance",
    "Financial": "Finančni", "Find": "Najdi", "First": "Prvi",
    "Fleet": "Flota", "Footer": "Noga", "Forecast": "Napoved",
    "Form": "Obrazec", "Format": "Format", "Free": "Prosto",
    "Frequency": "Pogostost", "From": "Od", "Fuel": "Gorivo",
    "Full": "Polno", "Generate": "Ustvari", "Generated": "Ustvarjeno",
    "Generator": "Generator", "Generators": "Generatorji",
    "Geographic": "Geografski", "Goods": "Blago", "Grand": "Skupaj",
    "Gross": "Bruto", "Group": "Skupina", "Growth": "Rast",
    "Header": "Glava", "Health": "Zdravje", "Hide": "Skrij",
    "History": "Zgodovina", "Home": "Domov", "Host": "Gostitelj",
    "Hour": "Ura", "Hours": "Ure", "Icon": "Ikona", "Idle": "Nedejaven",
    "Image": "Slika", "Images": "Slike", "Import": "Uvozi",
    "Inactive": "Neaktivno", "Info": "Info", "Information": "Informacija",
    "Innovation": "Inovacija", "Inspection": "Pregled",
    "Insurance": "Zavarovanje", "Integration": "Integracija",
    "Intelligence": "Inteligenca", "Interval": "Interval",
    "Invalid": "Neveljavno", "Invoice": "Račun", "Invoices": "Računi",
    "Invoiced": "Fakturirano", "Invoicing": "Fakturiranje", "Item": "Postavka",
    "Key": "Ključ", "Keys": "Ključi", "Label": "Oznaka",
    "Language": "Jezik", "Last": "Zadnji", "Latency": "Zakasnitev",
    "License": "Licenca", "Limit": "Omejitev", "Line": "Vrstica",
    "Link": "Povezava", "Linked": "Povezano", "List": "Seznam",
    "Live": "V živo", "Load": "Naloži", "Loaded": "Naloženo",
    "Loading": "Nalaganje", "Location": "Lokacija", "Log": "Dnevnik",
    "Login": "Prijava", "Logo": "Logotip", "Logs": "Dnevniki",
    "Main": "Glavno", "Maintenance": "Vzdrževanje", "Manage": "Upravljaj",
    "Management": "Upravljanje", "Manager": "Vodja", "Manual": "Ročno",
    "Map": "Zemljevid", "Margin": "Marža", "Match": "Ujemanje",
    "Meals": "Obroke", "Medical": "Medicinski", "Member": "Član",
    "Members": "Člani", "Memory": "Pomnilnik", "Merge": "Združi",
    "Message": "Sporočilo", "Metadata": "Metapodatki", "Metric": "Metrika",
    "Migration": "Migracija", "Mileage": "Kilometrina", "Minute": "Minuta",
    "Minutes": "Minute", "Mission": "Misija", "Mode": "Način",
    "Model": "Model", "Modern": "Sodoben", "Month": "Mesec",
    "Monthly": "Mesečno", "Months": "Meseci", "More": "Več",
    "Most": "Največ", "Move": "Premakni", "Multi": "Multi",
    "Name": "Ime", "Navigation": "Navigacija", "Net": "Neto",
    "New": "Nov", "Next": "Naslednji", "No": "Ne", "None": "Noben",
    "Notes": "Opombe", "Notification": "Obvestilo",
    "Notifications": "Obvestila", "Number": "Številka", "OCR": "OCR",
    "Odometer": "Števec km", "Office": "Pisarna", "Offline": "Brez povezave",
    "Online": "Na spletu", "Open": "Odpri", "Operation": "Operacija",
    "Operations": "Operacije", "Optimization": "Optimizacija",
    "Option": "Možnost", "Optional": "Izbirno", "Options": "Možnosti",
    "Origin": "Izvor", "Other": "Drugo", "Others": "Drugi",
    "Outstanding": "Neporavnano", "Overall": "Skupno", "Overdue": "Zapadlo",
    "Overview": "Pregled", "Package": "Paket", "Page": "Stran",
    "Paid": "Plačano", "Panel": "Panel", "Parking": "Parkirišče",
    "Partial": "Delno", "Partner": "Partner", "Partnership": "Partnerstvo",
    "Password": "Geslo", "Path": "Pot", "Payment": "Plačilo",
    "Percent": "Odstotek", "Performance": "Uspešnost", "Period": "Obdobje",
    "Phone": "Telefon", "Photo": "Fotografija", "Place": "Kraj",
    "Plan": "Načrt", "Planned": "Načrtovano", "Planning": "Načrtovanje",
    "Plate": "Registrska oznaka", "Platform": "Platforma", "Port": "Vrata",
    "Prediction": "Napoved", "Predictions": "Napovedi",
    "Preferences": "Nastavitve", "Preview": "Predogled", "Previous": "Prejšnji",
    "Price": "Cena", "Print": "Natisni", "Priority": "Prioriteta",
    "Process": "Proces", "Processing": "Obdelava", "Profit": "Dobiček",
    "Profitability": "Dobičkonosnost", "Profile": "Profil",
    "Proof": "Dokaz", "Provider": "Ponudnik", "Purpose": "Namen",
    "Qty": "Količina", "Quarter": "Četrtletje", "Quarterly": "Četrtletno",
    "Query": "Poizvedba", "Quick": "Hitro", "Rate": "Stopnja", "Rating": "Ocena",
    "Ratio": "Razmerje", "Receipt": "Potrdilo", "Received": "Prejeto",
    "Recipient": "Prejemnik", "Recommended": "Priporočeno", "Record": "Zapis",
    "Records": "Zapisi", "Recurring": "Ponavljajoče", "Refresh": "Osveži",
    "Refund": "Povračilo", "Register": "Registracija", "Reliability": "Zanesljivost",
    "Remaining": "Preostalo", "Reminder": "Opomnik", "Remove": "Odstrani",
    "Report": "Poročilo", "Reports": "Poročila", "Required": "Obvezno",
    "Reset": "Ponastavi", "Resolve": "Reši", "Resource": "Vir",
    "Resources": "Viri", "Rest": "Ostalo", "Restore": "Obnovi",
    "Result": "Rezultat", "Results": "Rezultati", "Retention": "Ohranjanje",
    "Retry": "Poskusi znova", "Return": "Vrnitev", "Revenue": "Prihodek",
    "Role": "Vloga", "Route": "Pot", "Routes": "Poti", "Run": "Zaženi",
    "Safety": "Varnost", "Salary": "Plača", "Save": "Shrani",
    "Saved": "Shranjeno", "Schedule": "Urnik", "Scheduled": "Načrtovano",
    "Schedules": "Urniki", "Score": "Rezultat", "Search": "Iskanje",
    "Second": "Sekunda", "Seconds": "Sekunde", "Section": "Odsek",
    "Security": "Varnost", "Select": "Izberi", "Selected": "Izbrano",
    "Selection": "Izbira", "Sender": "Pošiljatelj", "Send": "Pošlji",
    "Sent": "Poslano", "Server": "Strežnik", "Service": "Storitev",
    "Services": "Storitve", "Setting": "Nastavitev", "Settings": "Nastavitve",
    "Setup": "Nastavitev", "Severity": "Resnost", "Share": "Deli",
    "Show": "Pokaži", "Signature": "Podpis", "Simple": "Enostavno",
    "Size": "Velikost", "Small": "Majhno", "Smart": "Pametno",
    "Software": "Programska oprema", "Sort": "Razvrsti", "Source": "Vir",
    "Specific": "Specifično", "Speed": "Hitrost", "Stamp": "Žig",
    "Standalone": "Samostojno", "Start": "Začetek", "Statistics": "Statistika",
    "Status": "Status", "Stop": "Postanek", "Stops": "Postanki",
    "Storage": "Shramba", "Subtitle": "Podnaslov", "Subtotal": "Vmesni seštevek",
    "Success": "Uspeh", "Successful": "Uspešno", "Summary": "Povzetek",
    "System": "Sistem", "Table": "Tabela", "Tab": "Zavihek", "Tag": "Oznaka",
    "Tags": "Oznake", "Target": "Cilj", "Task": "Naloga",
    "Tasks": "Naloge", "Tax": "Davek", "Team": "Ekipa", "Template": "Predloga",
    "Terms": "Pogoji", "Test": "Test", "Theme": "Tema",
    "Threshold": "Prag", "Time": "Čas", "Timeline": "Časovnica",
    "Title": "Naslov", "To": "Do", "Today": "Danes",
    "Token": "Žeton", "Toll": "Cestnina", "Tolls": "Cestnine",
    "Tool": "Orodje", "Tools": "Orodja", "Top": "Najboljši",
    "Total": "Skupaj", "Track": "Sledi", "Tracking": "Sledenje",
    "Traffic": "Promet", "Trailer": "Priklopnik", "Transaction": "Transakcija",
    "Transition": "Prehod", "Transparency": "Transparentnost",
    "Transport": "Transport", "Trend": "Trend", "Trends": "Trendi",
    "Trip": "Vožnja", "Trips": "Vožnje", "Truck": "Tovornjak",
    "Trucks": "Tovornjaki", "Type": "Tip", "Unassigned": "Nedodeljeno",
    "Unavailable": "Nedosegljiv", "Undo": "Razveljavi", "Unknown": "Neznano",
    "Unpaid": "Neplačano", "Update": "Posodobi", "Updated": "Posodobljeno",
    "Upload": "Naloži", "Uploading": "Nalaganje", "Usage": "Uporaba",
    "User": "Uporabnik", "Users": "Uporabniki", "Utilization": "Izkoriščenost",
    "Validation": "Validacija", "Value": "Vrednost", "Values": "Vrednosti",
    "Vehicle": "Vozilo", "Vehicles": "Vozila", "Version": "Različica",
    "View": "Pogled", "Views": "Pogledi", "Violation": "Kršitev",
    "Violations": "Kršitve", "Visibility": "Vidnost", "Volume": "Obseg",
    "Warning": "Opozorilo", "Warnings": "Opozorila", "Week": "Teden",
    "Weekly": "Tedensko", "Weight": "Teža", "Welcome": "Dobrodošli",
    "Year": "Leto", "Yearly": "Letno", "Years": "Leta",
    "Yes": "Da", "Yesterday": "Včeraj", "Zip": "Zip",
    # SL common phrases
    "About Operion": "O Operionu",
    "About - Operion ERP": "O - Operion ERP",
    "Our Story": "Naša zgodba",
    "Our Values": "Naše vrednote",
    "The principles that guide every decision we make.": "Načela, ki vodijo vsako našo odločitev.",
    "Our Team": "Naša ekipa",
    "Cache cleared": "Predpomnilnik počiščen",
    "Celery Status": "Celery status",
    "Redis Status": "Redis status",
    "Connected:": "Povezano:",
    "Access denied": "Dostop zavrnjen",
    "Server unreachable": "Strežnik nedosegljiv",
    "System Info": "Sistemske informacije",
    "Admin Panel": "Admin plošča",
    "Workers Online": "Delavci na spletu",
    "Forgot password?": "Ste pozabili geslo?",
    "Enter your password": "Vnesite geslo",
    "Hide password": "Skrij geslo",
    "Show password": "Pokaži geslo",
    "Signing in…": "Prijava…",
    "Welcome back": "Dobrodošli nazaj",
    "Back to home": "Nazaj na domov",
    "Sign In — Operion ERP": "Prijava — Operion ERP",
    "Sign in": "Prijavi se",
    "Sign up": "Registriraj se",
    "Don't have an account?": "Nimate računa?",
    "Already have an account?": "Že imate račun?",
    "Full Name": "Polno ime",
    "Company Name (optional)": "Ime podjetja (izbirno)",
    "At least 8 characters": "Vsaj 8 znakov",
    "Password is required": "Geslo je obvezno",
    "Create Account — Operion ERP": "Ustvari račun — Operion ERP",
    "Create your account": "Ustvarite svoj račun",
    "Start your 14-day free trial": "Začnite 14-dnevno brezplačno preizkušnjo",
    "Creating account…": "Ustvarjanje računa…",
    "Create account": "Ustvari račun",
    "Name must be at least 2 characters": "Ime mora imeti vsaj 2 znaka",
    "Password must be at least 8 characters": "Geslo mora imeti vsaj 8 znakov",
    "Passwords don't match": "Gesli se ne ujemata",
    "Account created successfully!": "Račun uspešno ustvarjen!",
    "Failed to create account": "Ustvarjanje računa ni uspelo",
    "Signed in successfully!": "Uspešno prijavljeni!",
    "Failed to sign in": "Prijava ni uspela",
    "Please enter a valid email": "Prosimo, vnesite veljaven e-poštni naslov",
    "Please enter your email address.": "Prosimo, vnesite vaš e-poštni naslov.",
    "Please enter your password.": "Prosimo, vnesite vaše geslo.",
    "Confirm Password": "Potrdi geslo",
    "Repeat your password": "Ponovite geslo",
    "Actual Uploads": "Dejanske nalaganja",
    "CMR Generation Trend": "Trend generiranja CMR",
    "Profit per KM": "Dobiček na KM",
    "CMRs": "CMR",
    "Expires": "Poteče",
    "Correlation & Distribution": "Korelacija in distribucija",
    "Distribution & Insights": "Distribucija in vpogledi",
    "Profit/KM": "Dobiček/KM",
    "Cost per Truck": "Strošek na tovornjak",
    "Cost per Month": "Strošek na mesec",
    "Cost per Year": "Strošek na leto",
    "Truck Fallback": "Rezervni tovornjak",
    "Avg. Cost": "Povp. strošek",
    "Top Category": "Najboljša kategorija",
    "More": "Več",
    "No Active Trips": "Ni aktivnih voženj",
    "No Alerts": "Ni opozoril",
    "Profit (Past 30 Days)": "Dobiček (zadnjih 30 dni)",
    "Intelligent Route Planning": "Inteligentno načrtovanje poti",
    "Real-Time Fleet Tracking": "Sledenje floti v realnem času",
    "Smart Dispatch": "Pametni dispečing",
    "OCR Document Processing": "OCR obdelava dokumentov",
    "Advanced Analytics": "Napredna analitika",
    "Driver Management": "Upravljanje voznikov",
    "Reduce Operational Costs": "Zmanjšajte operativne stroške",
    "Increase Delivery Speed": "Povečajte hitrost dostave",
    "Eliminate Paperwork": "Odpravite papirologijo",
    "Scale With Confidence": "Rastite z zaupanjem",
    "Enterprise Logistics, Simplified": "Poslovna logistika, poenostavljena",
    "Start Free Trial": "Začnite brezplačno preizkušnjo",
    "Talk to Sales": "Pogovorite se s prodajo",
    "Features - Operion ERP": "Funkcije - Operion ERP",
    "Powerful Features for Modern Logistics": "Močne funkcije za moderno logistiko",
    "Route Planning & Optimization": "Načrtovanje in optimizacija poti",
    "Multi-Stop Optimization": "Optimizacija več postankov",
    "Real-Time Traffic Integration": "Integracija prometa v realnem času",
    "Fleet Management": "Upravljanje flote",
    "Real-Time GPS Tracking": "GPS sledenje v realnem času",
    "Vehicle Maintenance Tracking": "Sledenje vzdrževanju vozil",
    "Geofencing & Alerts": "Geofencing in opozorila",
    "Dispatch & Operations": "Dispečing in operacije",
    "Automated Job Assignment": "Avtomatska dodelitev nalog",
    "Digital Proof of Delivery": "Digitalni dokaz dostave",
    "Real-Time Status Updates": "Posodobitve statusa v realnem času",
    "Document Management": "Upravljanje dokumentov",
    "AI-Powered OCR": "OCR na podlagi umetne inteligence",
    "Digital Archive": "Digitalni arhiv",
    "Automated Invoicing": "Avtomatsko fakturiranje",
    "Analytics & Reporting": "Analitika in poročanje",
    "Custom Dashboards": "Prilagojene nadzorne plošče",
    "Export & Integration": "Izvoz in integracija",
    "Driver Profiles": "Profili voznikov",
    "Performance Tracking": "Sledenje uspešnosti",
    "Schedule Management": "Upravljanje urnika",
    "Route Planner": "Načrtovalec poti",
    "All history": "Vsa zgodovina",
    "Last week": "Prejšnji teden",
    "Current month": "Trenutni mesec",
    "Specific year": "Določeno leto",
    "OK": "V redu",
    # Additional SL translations
    "Cannot read input: {}": "Ni mogoče brati vhoda: {}",
    "Imported {} ({} bytes)": "Uvoženo {} ({} bajtov)",
    "Doc #{}": "Dok #{}",
    "Stage:": "Faza:",
    "Status:": "Status:",
    "Subject:": "Zadeva:",
    "Sending…": "Pošiljanje…",
    "Scanned — {}": "Skenirano — {}",
    "Billed": "Fakturirano",
    "Credit Limit (EUR)": "Kreditni limit (EUR)",
    "↓ Down": "↓ Dol",
    "Cleaned up": "Počiščeno",
    "Established in": "Ustanovljeno v",
    "Instructions & Reservations": "Navodila in rezervacije",
    "Issue & Signatures": "Izdaja in podpisi",
    "Special agreements": "Posebni dogovori",
    "Successive carriers": "Zaporedni prevozniki",
    "CMR International Consignment Note": "CMR mednarodni tovorni list",
    "Limit: €{:,}": "Limit: €{:,}",
    "Payment Terms (days)": "Plačilni pogoji (dni)",
    "Full Name *": "Polno ime *",
    "Contact Type": "Tip kontakta",
    "Job Title": "Naziv delovnega mesta",
    "Client Type": "Tip stranke",
    "Add Contact": "Dodaj kontakt",
    "Revenue Trend": "Trend prihodkov",
    "Activity Timeline": "Časovnica aktivnosti",
    "Payment Summary": "Povzetek plačila",
    "Merge Clients": "Združi stranke",
    "Execute Merge": "Izvedi združitev",
    "Contact Person": "Kontaktna oseba",
    "Invoice #": "Račun #",
    "Outstanding Invoices": "Neporavnani računi",
    "Total Distance": "Skupna razdalja",
    "Avg Profit/Trip": "Povp. dobiček/vožnja",
    "Last Trip": "Zadnja vožnja",
    "Show All": "Pokaži vse",
    "Recent Trips": "Nedavne vožnje",
    "Upload new version": "Naloži novo različico",
    "Restore Version": "Obnovi različico",
    "Create Contract": "Ustvari pogodbo",
    "Generate CMR": "Ustvari CMR",
    "Pick a trip": "Izberite vožnjo",
    "Select Invoice": "Izberite račun",
    "QUICK FILL FROM INVOICE": "HITRO POLNJENJE IZ RAČUNA",
    "Attachment Type": "Tip priloge",
    "Receipt Photo": "Fotografija potrdila",
    "Fuel Receipt": "Račun za gorivo",
    "Amount in Words": "Znesek z besedami",
    "Employee Name": "Ime zaposlenega",
    "Expense Category": "Kategorija stroška",
    "Path to logo image": "Pot do logotipa",
    "Path to signature image": "Pot do podpisa",
    "Path to stamp image": "Pot do žiga",
    "Company Signature": "Podpis podjetja",
    "Recipient Signature": "Podpis prejemnika",
    "Company Stamp": "Žig podjetja",
    "Generated by Operion": "Ustvaril Operion",
    "Receipt number is required.": "Številka potrdila je obvezna.",
    "Issue date is required.": "Datum izdaje je obvezen.",
    "Related Trip": "Povezana vožnja",
    "Pickup Location": "Kraj nakladanja",
    "Delivery Location": "Kraj dostave",
    "Trip #": "Vožnja #",
    "Reference No.": "Referenčna št.",
    "Transaction ID": "ID transakcije",
    "Payment Method": "Način plačila",
    "Received From": "Prejeto od",
    "Received By": "Prejel",
    "VAT Rate (%)": "Stopnja DDV (%)",
    "VAT Amount": "Znesek DDV",
    "Auto-calculated": "Samodejno izračunano",
    "Department": "Oddelek",
    "Company Logo": "Logotip podjetja",
    "File too large": "Datoteka je prevelika",
    "Upload Error": "Napaka pri nalaganju",
    "Extracted Fields": "Izvlečena polja",
    "Select Document": "Izberi dokument",
    "From Date": "Od datuma",
    "To Date": "Do datuma",
    "CSV Filter": "CSV filter",
    "Show alerts": "Pokaži opozorila",
    "Open calendar": "Odpri koledar",
    "Select date": "Izberi datum",
    "No revenue data yet": "Ni še podatkov o prihodkih",
    "No signature": "Ni podpisa",
    "Signature accepted": "Podpis sprejet",
    "Select Signature Image": "Izberi sliko podpisa",
    "No activity recorded": "Ni zabeležene aktivnosti",
    "Schedule": "Urnik",
}


def translate_word_by_word(text, word_map):
    """Translate text by replacing individual words using the word map.
    Preserves {} placeholders and other special patterns."""
    if not isinstance(text, str):
        return text
    
    # Check if entire phrase is in word_map as key
    if text in word_map:
        return word_map[text]
    
    # Handle special characters
    words = text.split()
    translated_words = []
    for w in words:
        # Skip words that contain { or } (placeholders)
        if "{" in w or "}" in w:
            translated_words.append(w)
            continue
        
        # Check with punctuation
        clean = w.strip(".,;:!?()[]\"'")
        punct_before = w[:len(w)-len(w.lstrip(".,;:!?()[]\"'"))]
        punct_after = w[len(w.rstrip(".,;:!?()[]\"'")):]
        
        if clean in word_map:
            translated_words.append(punct_before + word_map[clean] + punct_after)
        elif clean.capitalize() in word_map:
            translated_words.append(punct_before + word_map[clean.capitalize()] + punct_after)
        elif clean.lower() in word_map:
            translated_words.append(punct_before + word_map[clean.lower()] + punct_after)
        else:
            translated_words.append(w)
    
    result = " ".join(translated_words)
    
    # If nothing changed, return None
    if result == text:
        return None
    return result


# ─── MAIN ───

def translate_all(en_flat, lang_code, word_map):
    """Translate all English values in a language file using word_map."""
    path = os.path.join(TRANSLATIONS_DIR, f"{lang_code}.json")
    lang_data = load_json(path)
    lang_flat = flatten(lang_data)
    changes = 0
    for key, en_val in sorted(en_flat.items()):
        if key not in lang_flat:
            continue
        if not isinstance(en_val, str) or not isinstance(lang_flat[key], str):
            continue
        if en_val == "":
            continue
        lang_val = lang_flat[key]
        if lang_val != en_val:
            continue
        if is_untranslatable(en_val):
            continue
        translated = translate_word_by_word(en_val, word_map)
        if translated is not None and translated != en_val:
            lang_flat[key] = translated
            changes += 1
    nested = unflatten(lang_flat)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nested, f, ensure_ascii=False, indent=2)
        f.write("\n")
    return changes


if __name__ == "__main__":
    # Load en.json reference
    en_data = load_json(os.path.join(TRANSLATIONS_DIR, "en.json"))
    en_flat = flatten(en_data)
    
    print("=" * 60)
    print("  Batch Translation v1 — 4 worst languages")
    print("=" * 60)
    
    targets = [
        ("bs", BS_WORDS, "Bosnian"),
        ("hr", HR_WORDS, "Croatian"),
        ("sv", SV_WORDS, "Swedish"),
        ("sl", SL_WORDS, "Slovenian"),
    ]
    
    total_changes = 0
    for code, words, name in targets:
        print(f"\n  Translating {name} ({code}.json)...", end=" ")
        try:
            n = translate_all(en_flat, code, words)
            total_changes += n
            print(f"{n} values translated")
        except Exception as e:
            import traceback
            print(f"ERROR: {e}")
            traceback.print_exc()
    
    print(f"\n{'='*60}")
    print(f"  Total translations made: {total_changes}")
    print(f"{'='*60}")
    
    # Print coverage
    print("\n  Final coverage:")
    for code, _, name in targets:
        path = os.path.join(TRANSLATIONS_DIR, f"{code}.json")
        try:
            data = load_json(path)
            flat = flatten(data)
            total = len(en_flat)
            untrans = sum(1 for k, v in flat.items() if k in en_flat and isinstance(v, str) and isinstance(en_flat[k], str) and v == en_flat[k] and en_flat[k] != "")
            trans = total - untrans
            pct = 100 * trans / total
            print(f"    {code}.json: {trans}/{total} ({pct:.1f}%)")
        except Exception as e:
            print(f"    {code}.json: ERROR {e}")
    
    print(f"{'='*60}")
